### ISSUE TITLE
Include an unminified version of braintree.js

### ISSUE THREAD

**Issue by jeffcarp** [braintree/braintree-web#1]
As discussed in [this thread](https://github.com/braintree/braintree-encryption.js/issues/28), people would find it useful if we included an unminified version of braintree.js in this repo.

**Comment by pdg137** [comment]
Please do!  Not having the source makes it really hard to incorporate this into a larger project.  Patching / debugging / change-tracking / auditing are all basically impossible with the minified version.

**Comment by keshavkaul** [comment]
+1 for this. Any updates on when we will see this?

**Comment by pdg137** [comment]
For reference from the other thread, you can find something that appears to be the source code at

https://js.braintreegateway.com/js/braintree-2.3.3.js

Hopefully there we be a more official copy included with the update that is coming next week.

**Comment by michelem09** [comment]
Any chance to get the unminified version here?

**Comment by kyledetella** [comment]
We hope to include unminified source in a future version, but as of now there are no plans to include an unminified version here. You can grab unminified versions using this schema: [https://js.braintreegateway.com/js/braintree-2.5.2.js](https://js.braintreegateway.com/js/braintree-2.5.2.js).

**Comment by ConAntonakos** [comment]
Any progress on this yet? Is there a way to link the latest build from, let's say, the source URL (https://js.braintreegateway.com/js/braintree-2.17.5.js) to npm's package.json file?

**Comment by connor4312** [comment]
Any luck? It'd be really nice to be able to submit our fixes and improvements here rather than having to keep our downstream patched and up to date...

**Comment by MCProhosting-Matt** [comment]
+1 would like to see this

**Comment by githoober** [comment]
@ConAntonakos: there cannot be any progress on a closed issue.

**Comment by jackmcpickle** [comment]
For those interested you can use bower to install from a file
`bower install -S https://js.braintreegateway.com/js/braintree-2.x.x.js`

See [bower](http://bower.io/#install-packages)

**Comment by mrak** [comment]
We've released a beta of our next major version. Starting with the beta of v3 we additionally provide unminified files for debugging purposes. The files ending in `debug.js` are the uniminified counterparts to their `.js` files.

```javascript
// minified
var hostedFields = require('braintree-web/hosted-fields');
// unminified
var hostedFields = require('braintree-web/hosted-fields.debug');
```

One caveat to using the `debug` forms of the includes is that ___files served within our iframes will also be unminified___. For instance, by using the debug file of the hosted-fields component all assets served within our iframes for each field will also be unminified. Though this is useful for debugging.

```javascript
// iframe assets (outside of your control) will also become unminified
var hostedFields = require('braintree-web/hosted-fields.debug');
```

For this reason we only recommend using the `debug` counterparts for debugging purposes.

Here are some links to our official documentation:

[Setup for v3](https://developers.braintreepayments.com/guides/client-sdk/setup/javascript/v3)
[Migrating from v2 to v3](https://developers.braintreepayments.com/guides/client-sdk/migration/javascript/v3)

Please send any beta feedback to js-sdk-beta@braintreepayments.com
