### ISSUE TITLE
Pasting a credit card number in from a clipboard manager fails

### ISSUE THREAD

**Issue by tednaleid** [braintree/braintree-web#10]
If you paste a value into the credit card input, but the field doesn't have focus when the paste happens (such as when you're using a clipboard manager like Alfred for OSX), the form doesn't properly notice that the value has been updated and doesn't think it's a credit card number.  It lets the user then press the submit button, but the submission doesn't include a credit card number and it fails with "there was an error processing your request".

You can see the behavior in the video attached to this tweet: https://twitter.com/tednaleid/status/551114969144496128/photo/1

This was on chrome 39.0.2171.95 on OSX Mavericks.

**Comment by kyledetella** [comment]
@tednaleid the latest version of `braintree.js` has fixed this issue. Please try it out and let me know if that works.
