### ISSUE TITLE
Formless coinbase integration

### ISSUE THREAD

**Issue by osener** [braintree/braintree-web#100]
When using custom integration it's possible to grab nonce using [this workaround](https://github.com/braintree/braintree-web/issues/58#issuecomment-118852093) but I can't see an option other than scanning the form periodically since coinbase integration doesn't support `onSuccess` callback.

**Comment by rturumella** [comment]
@osener 

Although Coinbase does not support the `onSuccess` callback, you can try the following with our onPaymentMethodReceived callback:

```javascript
braintree.setup(TOKEN, "custom", {
  coinbase: { container: "coinbase-container-id" }
   onPaymentMethodReceived: function (obj) {
      doSomethingWithTheNonce(obj.nonce);
    }
});
```

**Comment by osener** [comment]
@rturumella I believe onPaymentMethodReceived gets called after the form is submitted so it doesn't fit our use case. We're using it to process credit card info but for PayPal and Coinbase we'd like to store the payment method in the vault as soon as users successfully authenticate to those services.

**Comment by mrak** [comment]
There is no equivalent to PayPal's `onSuccess` for Coinbase integrations.

If you are using Coinbase or PayPal in a custom integration that includes a hosted-fields or credit card form, we only support receiving the nonces at submit time.

It is a known limitation with our current SDK that we are aware of and intend to fix in future versions.
