### ISSUE TITLE
Coinbase button user experience and branding is subpar to PayPal on custom integration

### ISSUE THREAD

**Issue by osener** [braintree/braintree-web#102]
Compare drop-in UI to buttons embedded by custom integration:

![image](https://cloud.githubusercontent.com/assets/111265/11276389/962813fa-8eea-11e5-8ad0-baf3cbf48e39.png)
![image](https://cloud.githubusercontent.com/assets/111265/11276604/6b7035ce-8eeb-11e5-9f7b-3145740a2a99.png)

I was excited to see headless option for PayPal since it would allow us to integrate it into our design but it's not supported for Coinbase (#101).

PayPal integration also shows an overlay like this one when user starts the authentication flow but there is no indication of this for Coinbase.

![image](https://cloud.githubusercontent.com/assets/111265/11276785/2043f47c-8eec-11e5-93bd-e25c3ab6ab45.png)

**Comment by rturumella** [comment]
Thanks for the feedback @osener. I totally understand the desire to customize your experience for Coinbase to fit in with your site. We may take a look at improving this in future versions of braintree.js, we'll keep you posted.
