### ISSUE TITLE
This is a Pre-Built Javascript File. Try to Require the Original Source...

### ISSUE THREAD

**Issue by ppiekarczyk** [braintree/braintree-web#103]
Hey guys,

Installing `braintree-web 2.17.1` via npm yields the following error:

```error
./~/braintree-web/dist/braintree.js
Critical dependencies:
3:420-427 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/braintree-web/dist/braintree.js 3:420-427
```

I went went through `node_modules` and no source files are included, only the dist. 

Any suggestions? 

Thanks,
Peter

**Comment by kyledetella** [comment]
@ppiekarczyk are you seeing this error when installing via `npm` or trying to compile with Webpack?

If it is the latter, it seems like this is a duplicate of #52.

**Comment by ppiekarczyk** [comment]
Ah yeah. Same issue. Thanks
