### ISSUE TITLE
Support padding inner style in Hosted Fields

### ISSUE THREAD

**Issue by csm123** [braintree/braintree-web#104]
It would be great if `padding` were a supported style for hosted field inputs. This would make it easier for users to click into fields.

Please see [this example on CodePen](http://codepen.io/csm123/pen/EVByeG).

Right now, to have a border around a hosted field box, you must apply a border and a padding to the container element. This is the case on [Braintree's official example](https://www.braintreepayments.com/features/hosted-fields). The input box is smaller than the container element, so clicking some areas within the container will not focus the input. If we could apply `padding` to the input element itself, we could get the same visual with a better click target.

**Comment by EvanHahn** [comment]
In Hosted Fields, we wanted to allow as few CSS properties as possible. If it couldn't be done without setting a CSS property in the iframe, we didn't do it. This was both for security and for product simplicity.

We felt that `padding` was one of these things that could be left out of Hosted Fields.

You can accomplish what you want using `<label>` elements to wrap your fields and then applying padding to that label.

For example:

```html
<style>
.braintree-field-wrapper {
  display: block;
  padding: 1em;
  border: 1px solid #000;
}
</style>

<!-- ... -->

<label class="braintree-field-wrapper" for="braintree-credit-card-field">
  <!-- This text is totally optional. -->
  <span>Credit Card</span>

  <div id="braintree-credit-card-field"></div>
</label>
```

Hope that helps!

**Comment by csm123** [comment]
Definitely helps! Thanks

**Comment by EvanHahn** [comment]
Fantastic! Let us know if you have any other issues.

**Comment by richardudovich** [comment]
This does not work if you using the drop down option
![image](https://user-images.githubusercontent.com/828730/32875095-37f38998-caea-11e7-85c2-d0b2a4d4e854.png)

**Comment by pietersharefaith** [comment]
I am having a similar issue with using a dropdown.
The dropdown becomes smaller that the field when I add the padding to the outside of the iframe.

**Comment by crookedneighbor** [comment]
@pietersharefaith You're right that the work around does not work for dropdowns, because dropdowns cannot be opened programmatically in all browsers. 

We'll go ahead and add `padding` as a white listed style in the next release. I'll update here when it's ready.

In order for padding to work with selects, you will also need to set the appearance properties:

```
styles: {
  'input, select': {
    padding: '10px'
  }, 
  select: {
    '-webkit-appearance': 'none',
    '-moz-appearance': 'none',
    appearance: 'none'
  }
}
```

This will have the side effect of removing the Dropdown caret on the right in most browsers.

**Comment by pietersharefaith** [comment]
Thanks for that. I will integrate the proposed code when it is ready in my project. Thanks for the quick reply and the willingness to meet your customers needs.

**Comment by crookedneighbor** [comment]
Padding has been added in v3.30.0
