### ISSUE TITLE
PayPal auth flow broken for Android <= 4.4 WebViews

### ISSUE THREAD

**Issue by obiwarn** [braintree/braintree-web#106]
On some clients the PayPal Auth Flow popup iFrame is blank.

Can I force the Auth Flow into a div on my page?

**Comment by kyledetella** [comment]
@obiwarn would you be able to provide some more details on what you are seeing?

- Which clients are you referring to?
- Which version of braintree.js are you using?

Could you also provide a snippet of your integration code.

**Comment by obiwarn** [comment]
I use Meteor.js. I also provide my Website as a "native" app for Android (via Cordova)

package is:
"braintree": "1.32.0"

My code is the classic drop-in code. Nearly the same as here:
http://www.slideshare.net/DemianBorba1/making-money-with-phonegap-and-angular-apps

Everything works fine on the Website. But when I compile the app with cordova on half of my testing devices there is this small but annoying bug:
The blue PayPal Button appears as always. When the user presses it, a fullscreen popup opens. Usually it shows the PayPal authentication flow (Login Email & Password...). but sometimes it is blank / completely white. (The user has to press the back button tor eturn to the app).

The problematic devices are:
HUAWEI Ascent Y330-U01 with Android 4.2.2
Lenovo Yoga 8 B600-F with Android 4.4.2

On a Samsung galaxy Young with Android 4.4.2 it works fine.
Also on a Samsung Galaxy S4 with Android 5.0.1 also.

Maybe it has to do with the older (but popular) Android versions.

My code:

HTML:
    <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
    <div id="paypal-container" class="{{payPalClass}}"></div>

Coffescript:
    container = "paypal-container"
    braintree.setup(Login.braintreeToken, "paypal", {
            container: container
            singleUse: singleUse
            locale: preferredLanguage()
            onSuccess: (nonce, email, address) ->
                console.log("PayPal initialized.")
                Session.set('missingPayPalLogin', false)
                return
            onCancelled: ->
                console.log("Error on PayPal init.")
                Session.set('missingPayPalLogin', true)
                return
        }
    )

**Comment by EvanHahn** [comment]
We've had some bug reports with WebViews on older Android devices, and we suspect this is related. We haven't pinned down the problem yet, but we'll let you know as soon as we do.

**Comment by obiwarn** [comment]
According to Google stats 70% of Android users use an old version (<= 4.4) where this bug appears.

So I hope this has some higher priority for you guys?   ;-)

**Comment by ponelat** [comment]
Not sure if this is related, but on a SPA app the PayPal popup is black, the console logs of the window have this error....
```js
Uncaught TypeError: Cannot read property 'locale' of undefinedi.extend.initialize 
@ braintree-paypal-internal.min.js:7t.Model 
@ braintree-paypal-internal.min.js:1r 
@ braintree-paypal-internal.min.js:1r 
@ braintree-paypal-internal.min.js:1i 
@ braintree-paypal-internal.min.js:8n 
@ braintree-paypal-internal.min.js:2d 
@ braintree-paypal-internal.min.js:2p 
@ braintree-paypal-internal.min.js:2
```

**Comment by EvanHahn** [comment]
@ponelat We encountered that error last week and believe we fixed it in `2.17.4`. Are you using that version? If not, could you try upgrading and seeing if that fixes your problem?

**Comment by ponelat** [comment]
Thanks for the reply! I'm on 2.17.1... will upgrade and post back here.

**Comment by ponelat** [comment]
Thanks... that seems to have solved it! Will wait to test over https, but its working in development.

**Comment by mrak** [comment]
This is a known issue with past Android versions.

## Technical Reasons

WebViews have communication quirks between iframes and popups. Generally we can differentiate WebViews and WebView-based browsers (such as Chrome for iOS) and have fallback plans in place.

User-Agent strings are the means of separating these environments, and some platforms report _identical_ UA strings for both WebViews and the default internet browser. In these cases we are unable to properly determine a working codepath.

## Problematic Environments

WebViews in Android versions prior to `4.4`.

## Suggestions

* Do not rely on our JavaScript SDK WebView-based app environments (i.e. Cordova and PhoneGap).
* Do not rely on our JavaScript SDK within WebViews.
* Instead, utilize our specialized [Android](https://developers.braintreepayments.com/guides/client-sdk/android/v2) and [iOS](https://developers.braintreepayments.com/guides/client-sdk/ios/v4) SDKs.

There are known issues both with the handling of iframes/popups in these environments (on which we depend heavily) as well as the WebView problems mentioned in this thread.

We are working on making these caveats more apparent and well documented in our official documentation channels.

**Comment by obiwarn** [comment]
For me his would imply to recode my complete webapp two times in iOS and Android natively, right?
Or is there some official Cordova plugin?
I fear in this case it is simpler for us to change the payment provider to a Cordova compatible one.

**Comment by obiwarn** [comment]
And on the other hand why does Braintree publish slides like this:
http://www.slideshare.net/DemianBorba1/making-money-with-phonegap-and-angular-apps

This clearly suggest to use JavaScript SDK with Cordova, or did I get this wrong?

**Comment by obiwarn** [comment]
@mrak Could it be a workaround to change the UA string in cordova?

**Comment by mrak** [comment]
@obiwarn unfortunately, PayPal will not work properly in WebViews on Android versions below 4.4.

Our documentation falls short in specifying compatibility. We are working on a clear, official list of supported and tested browsers and environments that our SDK is known to work (or not work) in. 

The slides you referenced were created by developer evangelists, and unfortunately they lack key caveats about version support. While it is currently possible to use our JS SDK in environments like Cordova on Android 4.4+, Cordova is not one of our officially supported JS SDK integrations, and we do not test Cordova compatibility when we release.

We use multiple variables to determine PayPal presentation. Changing the User Agent string for your WebViews is not an approach we support or test, and we expect it won't offer the behavior you're looking for.

**Comment by obiwarn** [comment]
Thanks for the info.

Unfortunately I stepped into another problem: It seems that in a production app the PayPal button does not appear at all on Android (see #108).

**Comment by bhagyasri** [comment]
Since Android Brain tree SDK also using web view internally, we are getting a crash in Lenovo A6000(version 4.4.4) and Samsung galaxy series (Version <=4.4). Could you please help us to resolve this.

Error Log from Android device:
java.lang.VerifyError: com/braintreepayments/api/BraintreeFragment
at com.braintreepayments.api.BraintreePaymentActivity.getBraintreeFragment(BraintreePaymentActivity.java:298)
at com.braintreepayments.api.BraintreePaymentActivity.onCreate(BraintreePaymentActivity.java:114)
at android.app.Activity.performCreate(Activity.java:5541)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2368)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2464)
at android.app.ActivityThread.access$900(ActivityThread.java:172)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5653)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
at dalvik.system.NativeStart.main(Native Method)

**Comment by lkorth** [comment]
@bhagyasri: The Android SDK in no way uses a webview.

**Comment by bhagyasri** [comment]
From Brain Tree Android SDK, we have seen this "class ThreeDSecureWebView extends WebView". So I thought of using web view inside Brain tree.

**Comment by lkorth** [comment]
That is a specific case for 3D Secure verifications, but no webview is used for PayPal or tokenization.

**Comment by bhagyasri** [comment]
Thanks for the info.
