### ISSUE TITLE
Is it possible to lazy load braintree.js on a web page?

### ISSUE THREAD

**Issue by michaelherold** [braintree/braintree-web#107]
I want to only load `braintree.js` when it is needed, not on page load. I have tried using jQuery's `$.getScript` like so:

```js
$.getScript('https://js.braintreegateway.com/v2/braintree.js')
  .done(function () {
    client = new braintree.api.Client({
      clientToken: config.clientToken
    });
  });
```

However, loading it this way does not propagate the `braintree` object onto `window`, so `braintree` does not resolve. I read the documentation and came across this statement:

> If you include braintree.js in a `<script>` tag, the `braintree` object will be available on the global namespace.

As such, I have tried dynamically creating a script element and adding it to the page, like so:

```js
var script = document.createElement('script');
script.type = 'text/javascript';
script.src = 'https://js.braintreegateway.com/v2/braintree.js';
document.getElementsByTagName('head')[0].appendChild(script);
// I've also tried: document.body.appendChild(script)
```

The script is fetched and shows up in my loaded scripts, but the `braintree` object still is not added to `window`.

Is there any way to lazy load braintree.js? I really do not want to load a 50kb (gzipped) script unless the user actually needs it, which isn't always the case.

**Comment by EvanHahn** [comment]
I tested the first snippet you posted with jQuery 1.11.2 and it worked for me; `window.braintree` was defined after running that. What version of jQuery are you using?

The second snippet you posted should also work so long as you wait for the script to load before you start using `braintree`:

```js
var script = document.createElement('script');
script.type = 'text/javascript';
script.src = 'https://js.braintreegateway.com/v2/braintree.js';
script.onload = function () {
  client = new braintree.api.Client({
    clientToken: config.clientToken
  });
};
document.getElementsByTagName('head')[0].appendChild(script);
```

Hope this helps!

**Comment by michaelherold** [comment]
Thanks for the reply @EvanHahn. I checked out what you said and you're right - on JSBin both methods work. However, it still does not work in our application. That leads me to believe that it could be the fact that we're using a we're using an iframe. Is there anything that would prevent lazy-loading braintree.js in an iframe? I notice that there's a check of whether `window.self === window.top`, so I thought maybe that was the case. I hope not, because we have a need to use it in an iframe.

If braintree.js cannot be used in an iframe, is there a stable, supported way of tokenizing a card on the client other than braintree.js?

**Comment by EvanHahn** [comment]
I spun up a tiny iframe demo app and everything seemed to work when lazy-loading.

Are you using a sandboxed iframe? That shouldn't cause the issues you're seeing, but it might. If not, could we see more of your integration? If you don't feel comfortable posting it here, feel free to send it to <support@braintreepayments.com> and we'll take a look.

**Comment by EvanHahn** [comment]
@michaelherold Any updates? Would love to know if we can help further.

**Comment by michaelherold** [comment]
Thanks for following up @EvanHahn. I contacted the support email and am waiting for a reply through that channel.

**Comment by EvanHahn** [comment]
@michaelherold Sounds good! Is it alright if we close this issue?

**Comment by michaelherold** [comment]
Sure - I thought I'd update it if there's a shareable tidbit that I get from support, but I can do that equally well with a closed issue.

**Comment by EvanHahn** [comment]
Let us know if you have more problems!
