### ISSUE TITLE
PayPal button not showing. Error: unsupported protocol detected (Cordova)

### ISSUE THREAD

**Issue by obiwarn** [braintree/braintree-web#108]
I use Meteor.js and compile my app via Cordova. 

The PayPal button does not show up. It throws: "Error: unsupported protocol detected". I guess it has something to do with your helper function  `_isBrowserSecure() ` since it checks for https: ?

I wrote this on Stackoverflow:

Braintree expects `window.location.protocol` to be "https:". However, when I compile with cordova the location is:  http://meteor.local/ and so the protocol "http:".

Is there any way to fake `window.location.protocol` locally to be "https:"?

**Comment by kyledetella** [comment]
There is not a supported way to fake the `location.protocol` value. In order for the PayPal  flows to properly communicate with the braintree code executing on your checkout page, the protocol must be `https` in webviews.

This seems to be a familiar problem with Meteor and Cordova. A quick google search of _"meteor.local https"_ yields several discussions on the topic. It may be worth reading through those threads to see what options are available.

While I have by no means vetted this package, it seems like it could be something for you to look into: https://github.com/nourharidy/meteor-ssl.
