### ISSUE TITLE
Retrieve Creditcard details using Payment Method Nonce

### ISSUE THREAD

**Issue by abinayakannazhagan** [braintree/braintree-web#109]
I want to retrieve CreditCard details (including Billing Address) using Payment Method Nonce before creating the customer profile (with payment method nonce) in Braintree.

From your documents, I found there is a method "fromNonce" in https://github.com/braintree/braintree_java/blob/master/src/main/java/com/braintreegateway/CreditCardGateway.java to fetch the card details. But I got the below error while calling that method:
**Payment method with nonce <payment-method-nonce-here> locked, consumed or not found**

Please help me to fix this issue.

Thanks in Advance,
Abinaya

**Comment by kyledetella** [comment]
@abinayakannazhagan this sounds like an issue with your server-side integration. I would suggest opening an issue on the [`braintree_java`](https://github.com/braintree/braintree_java) library or reaching out to our support team (support@braintreepayments.com) directly.
