### ISSUE TITLE
fieldStateChange events do not always fire when they should

### ISSUE THREAD

**Issue by roughearth** [braintree/braintree-web#110]
I am implementing Hosted Fields on a client page. In using the validation provided by fieldStateChange events, I have found that the transition between "isEmpty" and "isPotentiallyValid" is not picked up on all fields.

I have found this on expirationDate, expirationYear and cvv. 

The field starts empty and the first "focus" event returns the validation state expected. If the user then type an invalid character (eg an "x"), a fieldStateChange event fires as expected.

The bug is when the user starts to type valid characters (ie numbers) in to the empty field. No fieldStateChange event is fired until the field becomes definitely valid or invalid. Similarly, if the user types a valid value, then starts to delete characters, an event is fired when the field becomes invalid, but no further events are fired, even when the field becomes empty. 

In both cases, blurring the field (eg by clicking out of it) fires an event with the expected validation data.

The side effect of this for my app is that I can't reliably tell the difference between a field that is invalid because it's empty and one that is invalid because the user has filled in in incorrectly.

As a work around I have carefully worded the validation messages, but it's be better not to have to.

**Comment by mrak** [comment]
@roughearth which browsers are you able to reproduce this behavior in?

**Comment by roughearth** [comment]
@mrak Current versions of all major browsers (FF, Chrome, IE, Edge).

**Comment by EvanHahn** [comment]
We'll look into this while we look into #111. Thanks for reporting!

**Comment by crookedneighbor** [comment]
This is fixed in the newly released version 2.17.6.

https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#2176
