### ISSUE TITLE
The cvv field incorrectly marks 3 digit AMEX CIDs as valid.

### ISSUE THREAD

**Issue by roughearth** [braintree/braintree-web#111]
I am implementing Hosted Fields on a client page. I have found a bug in CVV validation.

If the user types an American Express card number in the number field, the field events that follow all pass event.card.code.size with a correct value of 4, but if the user types a 3 digit number in the cvv field, it is incorrectly marked as valid. 

As a workaround, I am relying on the card details throwing an error at the 3DSecure stage, but I'd rather not mislead the user.

**Comment by roughearth** [comment]
BTW this is reproducible in current versions of all major browsers (FF, Chrome, IE, Edge).

**Comment by EvanHahn** [comment]
You're right—this is a bug! We will get to fixing this and update you as soon as it's patched.

**Comment by crookedneighbor** [comment]
This is fixed in the newly released version 2.17.6.

https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#2176
