### ISSUE TITLE
Tab between credit card fields

### ISSUE THREAD

**Issue by NealJMD** [braintree/braintree-web#112]
Hey guys!

I've recently implemented the hosted fields on our site and things are going quite well. However, one thing I've noticed that detracts from the user experience is that to go from the credit card to cvv to expiration date without the mouse, you have to hit the tab key twice between each field. I assume this is because of the iframe. Is there any way that you guys have found to allow a user to move between form fields with the tab key?

Thanks!

**Comment by mrak** [comment]
Hey @NealJMD, due to the limitations in some browsers it is very difficult or impossible to control the focus behavior on <TAB> between iframes.

We've had success in some browsers (Chrome and Firefox) where we could get forward-tabbing working as expected, but back-tabbing still takes two hits.

For other browsers (i.e. IE) the attempts have been less fruitful.

**Comment by NealJMD** [comment]
That's encouraging! most of our base is on Chrome and Firefox. Did you get that to work just by fiddling with the DOM structure, or were you actually capturing the tab in javascript?

**Comment by EvanHahn** [comment]
Some browsers let you tab between fields across iframes, so we took advantage of that.

We tried a bunch of stuff with the `tabindex` property and capturing tab keys like you mentioned, but we couldn't get it to work perfectly on all browsers. We also did our best to avoid making any assumptions about the merchant's page, which meant that things weren't as easy as "if the customer tabs while on the credit card number field, transition to the CVV field".

This is something that's on our list to take another look at, but I don't want to promise that we'll have better luck wrangling things the next time around!

**Comment by EvanHahn** [comment]
We're going to close this issue for now, but we'll let you know if we make any further progress. Feel free to continue discussion here or to open new issues for any other issues you find!

**Comment by wtimme** [comment]
Hey @EvanHahn, we're using hosted fields in our iOS application. The page is embedded into a `WKWebView`.

In the Simulator, using `<TAB>` to switch between the fields is working, but only until the field for the expiry date. I am not able to tab into the CVV field. This is minor, of course, as it doesn't concern our customers. Still, it's a bit more effort for our developers when testing the Braintree integration in the Simulator. Just adding this to the list.

Have you tried using the hosted fields with `<TAB>` in the Simulator? Might be a starting point for further debugging, if your devs could have a look. Again, this isn't a major issue, as it doesn't affect customers. Just a fellow developer reaching out.

**Comment by EvanHahn** [comment]
@wtimme Thanks for the report! As you mentioned, this isn't a major issue, but we'll let you know if we make progress on this.
