### ISSUE TITLE
HostedFields Paypal callback/event

### ISSUE THREAD

**Issue by bradleybeddoes** [braintree/braintree-web#113]
Is there any callback/event available for when Paypal login has completed successfully? (I've crawled over the docs and can't find anything)

Specific use case: Generic error message is shown to the user when no payment details are entered but payment form submit is triggered. I need to clear that error message when either valid credit card details are entered or a Paypal login occurs.

Using `onError` I can detect when no payment method (Paypal/CreditCard) is present and using `hostedFields` > `onFieldEvent` I can determine when credit card details are entered correctly and clear the afore mentioned generic error. Unfortunately on successful Paypal login I can't seem to achieve the same, leaving the error in place when in reality everything is now fine.

**Comment by crookedneighbor** [comment]
When v.zero was originally introduced, PayPal integrations were documented with an `onSuccess` method. We later decided to move to a root level callback (onPaymentMethodReceived) to better accommodate the orchestration of multiple payment methods in a single integration (PayPal, credit cards, Coinbase, etc). 

This `onSuccess` method is still supported but no longer updated and could prove useful in your case as it will fire as soon as the user completed the PayPal flow and a nonce is generated. Here is how you can use it:

```js
braintree.setup(yourClientToken, "custom", {
  hostedFields: { /* hosted fields options */ },
  paypal: {
    container: 'id-of-elment-for-paypal-button',
    onSuccess: function () {
      // User has logged in with PayPal
      // Remove error message if it exists
    }
  }
});
```
