### ISSUE TITLE
deviceData is undefined

### ISSUE THREAD

**Issue by michelem09** [braintree/braintree-web#114]
Hello,
I was trying to enable advanced fraud tools in our SANDBOX account following this doc https://developers.braintreepayments.com/guides/advanced-fraud-tools/client-side/javascript/v2, but as soon as I place the `dataCollector` property to the `braintree.setup` I receive this error from the braintree library:

> Uncaught TypeError: Cannot set property 'deviceData' of undefined

I use the latest one.

My client code is:

```
$window.braintree.setup(data.token, 'dropin', {
    container: 'dropin',
    dataCollector: {
        kount: {
            environment: 'sandbox'
        },
        paypal: true
    },
    paypal: {
        enableShippingAddress: false,
        locale: $rootScope._layout.lang
    },
    paymentMethodNonceReceived: function(event, nonce) {
        // Do something
    },
    onReady: function(braintreeInstance) {
                // This won't work due to the error
        console.log(braintreeInstance);
        braintreeInstance.deviceData;
    }
});
```

Did I miss something? Of course I have enabled the tools under our sandbox control panel.

**Comment by kyledetella** [comment]
@michelem09 which version of `braintree.js` are you using? The "hotlink" is currently at `2.15.4` and this implementation of Advanced Fraud Tools require version `2.16.0+`. Try upgrading to the latest version of [`braintree.js`](https://js.braintreegateway.com/js/braintree-2.17.5.min.js):

```html
<script src="https://js.braintreegateway.com/js/braintree-2.17.5.min.js"></script>
```

**Note:** We are aware that there is some ambiguity around versioning and we are working on solutions to clarify these issues.

**Comment by michelem09** [comment]
I think I have latest:

```
cat public/lib/braintree-web/bower.json 
{
  "name": "braintree-web",
  "version": "2.17.5",
  "authors": [
    "braintree <code@getbraintree.com>"
  ],
  "description": "A suite of tools for integrating Braintree in the browser",
  "main": "dist/braintree.js",
  "moduleType": [
    "amd",
    "globals",
    "node"
  ],
  "repository": {
    "type": "git",
    "url": "git@github.com:braintree/braintree-web"
  },
  "keywords": [
    "braintree",
    "payments"
  ],
  "license": "MIT",
  "homepage": "https://github.com/braintree/braintree-web",
  "ignore": [
    "*",
    "!dist/braintree.js"
  ]
}
```

**Comment by michelem09** [comment]
This is where it fails with the error:

> Uncaught TypeError: Cannot set property 'deviceData' of undefined

`t.deviceData=e.deviceData)}}`

**Comment by kyledetella** [comment]
@michelem09 thanks for that info. We are looking into this and will let you know when we have something.

**Comment by michelem09** [comment]
For the record I tried also with previous versions and they did the same. I tried `2.16.1`, `2.17.1` and `2.17.5`.
Thanks

**Comment by imran-a** [comment]
Hey - I am getting the same error. I am currently using the js in the docs

```javascript
<script src="https://js.braintreegateway.com/v2/braintree.js"></script>
```

Incidentally, what is the exact version of v2/braintree.js ?

I also tried 

```javascript
<script src="https://js.braintreegateway.com/js/braintree-2.17.5.min.js"></script
```

I have all my code wired up to use device data and its enabled in my account. We are looking to code live in the next couple of days. If this isn't resolved by then, I assume I can disable advanced fraud tools and release to live and then enable when this is fixed?

Thanks

**Comment by kyledetella** [comment]
@michelem09 you are correct, there is indeed a bug where `deviceData` will report as `undefined` in Drop-in. We will apply a fix with the next release (which should be in the next day or two).

**Comment by michelem09** [comment]
Glad I found it :) Thanks waiting for it.

**Comment by rsnipes** [comment]
I'm also seeing this.  Looking forward to the next release.

**Comment by crookedneighbor** [comment]
This is fixed in the newly released version 2.17.6. Thanks for your patience everyone!

https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#2176

**Comment by YeisonMelo** [comment]
I'm having the same issue if I use version 2.17.6 I get the device data but with version 2.27.0 is undefined!

` var client_token = [[${clientToken}]];
    braintree.setup(client_token, "dropin", {
        container: "bt-dropin",
        dataCollector: {
            kount: {environment: 'sandbox'}
        },
        onReady: function (braintreeInstance) {
            var field = document.getElementById('deviceData');
            field.value = braintreeInstance.deviceData;
        }
    });`

**Comment by skunkworks** [comment]
@YeisonMelo Can you double-check that your integration is loading the right version of the SDK? In the browser dev console, check `braintree.VERSION`. You can also check `braintree.data` to see if the Data Collector component is available as well.

If those items look good, it's also worthwhile to double check that you have [enabled this in the Braintree Control Panel](https://articles.braintreepayments.com/support/guides/fraud-tools/advanced/overview#enabling-advanced-fraud-tools).

**Comment by crookedneighbor** [comment]
@YeisonMelo We haven't heard from you about this issue, so we're going to assume you've resolved it. I'll close this issue now, but comment or open a new issue if your problem persists.

**Comment by justanne** [comment]
Same problem here. Although weird thing is, on my local dev, the code is working right, but on the server (and on my colleagues' computer), deviceData is undefined.

My Local Dev | Server
--------------| -------------
![screen shot 2017-05-08 at 1 07 38 pm](https://cloud.githubusercontent.com/assets/1003597/25791003/de798ab6-33ef-11e7-8314-72fd3cb8b3ff.png) | ![screen shot 2017-05-08 at 1 09 42 pm](https://cloud.githubusercontent.com/assets/1003597/25791008/ea7bd5e4-33ef-11e7-958d-c7bc1dc2cf0b.png)


I'm using 2.27.0

**Comment by crookedneighbor** [comment]
@justanne Is your local dev environment and your server both using the same Braintree environment? IE, are both sandbox or both production? Or are you using sandbox for local development and production on your server?

**Comment by justanne** [comment]
Both are in sandbox environment

**Comment by crookedneighbor** [comment]
@justanne Do you have a staging site we can look at? If you don't feel comfortable posting it here, you can email it to support@braintreepayments.com and reference this issue.

**Comment by justanne** [comment]
Email sent!

**Comment by crookedneighbor** [comment]
@justanne I took a look at your staging site and it looks like you call `braintree.setup` when the page loads, but `onReady` does not fire until you proceed to the section of the page where you input your card information. This is because `onReady` gets called when the drop-in form is visible on the page (usually when the animation completes). Since you are hiding the form, the `onReady` call is delayed, and something about that seems to be interfering with the `deviceData` being populated on the instance. 

If I set up a fresh version of the drop-in on your page in a div that is not hidden, the deviceData populates normally.

Could you try delaying calling `braintree.setup` until the div that it will populate in is visible? I'm curious to see if that fixes your inconsistent `deviceData` issues.

**Comment by justanne** [comment]
Perfect, it works now. I've just set it up so `braintree.setup` will be called once an event occurred, in this case, when a payment mode is selected. Thanks!

**Comment by crookedneighbor** [comment]
Awesome!

**Comment by taishi06** [comment]
Hi,

I'm having this issue at the moment with my setup. It was working okay before but seem to just suddenly not work and not getting the "deviceData" from the onReady callback of braintree.setup.

I am using version 2.32.

Let me know if you'll require any details for this.

**Comment by crookedneighbor** [comment]
@taishi06 contact our support team for assistance: https://help.braintreepayments.com/
