### ISSUE TITLE
Processing errors with `tokenizeCard()`

### ISSUE THREAD

**Issue by henri-hulski** [braintree/braintree-web#115]
Is there a possibility to process errors thrown by `braintree.js` when using `tokenizeCard()`?

I try something like this:
``` javascript
client.tokenizeCard({
    number:  $('#id_card_number').val(),
    expirationMonth:  $('#id_card_expiry_month').val(),
    expirationYear: $('#id_card_expiry_year').val(),
    cvv: $('#id_card_ccv').val(),
}, function (err, nonce) {
    // Set the nonce and errors in the form
    $("#id_card_token").val(nonce);
    if (err) {
        $("#id_braintree_errors").val(JSON.stringify(err));
    }

    // Resubmit the form to the server
    // The card_number and card_ccv will not be submitted to the server,
    // as the form inputs have no 'name' attribute.
    // Instead the nonce and error messages are submitted to the server.
    form.get(0).submit();
});
```
But `err` is always `null`, even if credit card number and CCV are empty, so no way to process it.

Actually there should be some documentation which format `err` uses and what errors it can contain.

Regards, 
Henri

**Comment by crookedneighbor** [comment]
A nonce will be created even if there are input validation issues like empty fields or invalid input (see this info on [client-side validation](https://developers.braintreepayments.com/guides/credit-cards/client-side/javascript/v2#client-side-validation)).

An error in the form of the string "Unable to tokenize card." will be returned if the `tokenizeCard` call does not return a nonce. This may happen if the Braintree gateway is unreachable at the time of the call.

You are correct that the information about the kind of error that is returned is not documented. We're updating the documentation and it should be available soon. Thanks for bringing it to our attention!
