### ISSUE TITLE
Possible conflict with existing require.js script?

### ISSUE THREAD

**Issue by pivotal-vanguard** [braintree/braintree-web#116]
I've added the braintree.js to our site and we are getting the following client side error when the page loads. Is this a sign of a possible conflict with the existing require.js version on our site? When I put that html snippet with the correct client token in it's own isolated page, the form fields load fine. The requirejs npm version we are on is 2.1.

Uncaught Error: Mismatched anonymous define() module: function (){var t;return function e(t,n,i){function o(s,a){if(!n[s]){if(!t[s]){var c="function"==typeof require&&require;if(!a&&c)return c(s,!0);if(r)return r(s,!0);var u=new Error("Cannot find module '"+s+"'");throw u.code="MODULE_NOT_FOUND",u}var l=n[s]={exports:{}};t[s][0].call(l.exports,function(e){var n=t[s][1][e];return o(n?n:e)},l,l.exports,e,t,n,i)}return n[s].exports}for(var r="function"==typeof require&&require,s=0;s<i.length;s++)o(i[s]);return o}({1:[function(t,e,n){(function(n){"use strict";function i(t){var e=t.analyticsConfiguration||{},i=n.braintree?

**Comment by kyledetella** [comment]
@pivotal-vanguard at this point, there are no known issues with `requirejs`. Could you provide some more details on your integration? Perhaps a sample of how you are setting up `braintree` in your JS file.

**Comment by kyledetella** [comment]
I am going to go ahead and close this. Feel free to re-open if you run into more issues.
