### ISSUE TITLE
Usage with angular2

### ISSUE THREAD

**Issue by ekarlso** [braintree/braintree-web#117]
Hi, I'm trying to make this work with angular2 but when I change routes to the route with the payment form then to another one and then back again I suddenly end up with multiple payment forms on the same page, any ideas? Example code is here:

https://github.com/ekarlso/angular2-seed

**Comment by bolten00** [comment]
<img width="1440" alt="skjermbilde 2015-12-26 kl 01 35 09" src="https://cloud.githubusercontent.com/assets/15720141/12004716/56bc2fe6-ab71-11e5-9d63-83aad548ca70.png">

**Comment by kyledetella** [comment]
@ekarlso @bolten00 my first thought is the Drop-in is not being torn down before navigating away from the view. Are you calling [`teardown`](https://developers.braintreepayments.com/guides/client-sdk/javascript/v2#teardown) prior to your route change?

If you are calling `teardown` then the problem lies elsewhere and we can keep digging.

**Comment by bolten00** [comment]
@kyledetella https://gitlab.com/creator-makerspace/members-ui

**Comment by crookedneighbor** [comment]
I ran `git grep braintree` in the repo @bolten00 provided, and I couldn't find any instance where `teardown` was being called.

**Comment by ekarlso** [comment]
So, I updated the https://github.com/ekarlso/angular2-seed fork that I have with a teardown that's called upon the Component ngOnDestroy event method, it doesn't seem to help anything with this?

**Comment by crookedneighbor** [comment]
@ekarlso and @bolten00 thanks for the links. It looks like something Angular 2 is doing with `ngOnDestroy` is interfering with the teardown function. When called inside `ngOnDestroy`, the teardown process starts, but never finishes.

We're looking into this further, but you could do something like this as temporary workaround until it's fixed:

```js
import {Component} from 'angular2/core';

declare var braintree:any;

var braintreeHasBeenSetup = false;

@Component({
 // component stuff here
})
export class Home {
  ngOnInit() {
    var clientToken = "<YOUR_CLIENT_TOKEN>";

    if (!braintreeHasBeenSetup) {
      braintree.setup(clientToken, "dropin", {
        container: "payment-form",
        onReady: function(int) {
          braintreeHasBeenSetup = true
        }
      })
    }
  }
}
```

We'll report back here when we have a better fix.

**Comment by crookedneighbor** [comment]
An alternative solution, using `CanDeactivate` and promises:

```
import {Component} from 'angular2/core';
import {CanDeactivate} from 'angular2/router';

declare var braintree:any;

@Component({
 // component stuff
})
export class Home implements CanDeactivate {
  integration: any

  ngOnInit() {
    var c = this;

    var clientToken = "<client_token>";

    braintree.setup(clientToken, "dropin", {
      container: "payment-form",
      onReady: function(int) {
        c.integration = int
      }
    })
  }

  routerCanDeactivate() {
    var c = this;

    return new Promise(function(resolve, reject) {
      c.integration.teardown(function () {
        c.integration = null
        resolve()
      })
    })
  }
}
```
