### ISSUE TITLE
device_data on the server

### ISSUE THREAD

**Issue by imran-a** [braintree/braintree-web#118]
Hey

I am following the documentation on Advanced Fraud tools here:

```html
https://developers.braintreepayments.com/guides/advanced-fraud-tools/overview
```

The client-side integration seems fine with deviceData having some data when I log it:

```javascript
braintree.setup(TOKEN, 'custom', {
  dataCollector: {
    kount: {environment: 'sandbox'}
  },
  onReady: function (braintreeInstance) {
    braintreeInstance.deviceData;
  }
  /* ... */
});
```

My server is .Net and when I do Request.Form["device_data"] it's always null/empty.

1) Is there a possibility that sometimes device_data can be empty? Or should it always have a value?
2) If it should always have a value, any ideas why that data isn't getting posted to the server?

We are looking to go live in the next few days. If this doesn't get resolved by then, it is a simple of disabling Advanced fraud tools in the settings?

Thanks

**Comment by mrak** [comment]
You will need to inject `braintreeInstance.deviceData` into your form as a `device_data` field yourself. Something like this:

```javascript
onReady: function (braintreeInstance) {
  var form = document.getElementById('my-form-id');
  var deviceDataInput = form['device_data'];

  if (deviceDataInput == null) {
    deviceDataInput = document.createElement('input');
    deviceDataInput.name = 'device_data';
    deviceDataInput.hidden = true;
    form.appendChild(deviceDataInput);
  }

  deviceDataInput.value = braintreeInstance.deviceData;  
}
```

We have not done this for you, as merchants may be using methods other than form submission to get values to their server.

If you supply the `dataCollector` options, then `deviceData` should always be present on the instance returned in `onReady`.

**Comment by jordanlewiz** [comment]
@mrak this is exactly what I was looking for! Perhaps this scenario could be added to the documentation as it's not obvious at all what to do with `deviceData`. Thanks in advance

**Comment by kyledetella** [comment]
@jordanlewiz glad that worked out. We will make sure to clarify this better in our [documentation](https://developers.braintreepayments.com/guides/advanced-fraud-tools/client-side/javascript/v2). Thanks for the feedback!

**Comment by kyledetella** [comment]
I may have been a bit hasty in closing this issue. @imran-a did @mrak's comment help out?

**Comment by imran-a** [comment]
The comment makes perfect sense. I haven't tested just yet. As you mentioned, definitely worth updating the documentation.

Please feel free to close the issue. I'll try and implement tomorrow.

Many thanks guys.

**Comment by kyledetella** [comment]
Thanks @imran-a. Will do.

**Comment by kyledetella** [comment]
@imran-a @jordanlewiz the docs have been updated. 

https://developers.braintreepayments.com/guides/advanced-fraud-tools/client-side/javascript/v2#collecting-device-data

**Comment by imran-a** [comment]
@kyledetella Many thanks for this, I noticed earlier this morning when I re-implemented the fix. All works great. 

One thing would be great, is how users can link to the specific versions of braintree.js minified/cdn'ed as the docs in this instance refer to v.2.16

Thanks for the help!

**Comment by kyledetella** [comment]
> One thing would be great, is how users can link to the specific versions of braintree.js minified/cdn'ed as the docs in this instance refer to v.2.16

@imran-a I totally agree. We are in the process of improving that documentation because it is ambiguous at best right now. To clarify for now, specific versions are released following this pattern: `https://js.braintreegateway.com/js/braintree-<VERSION>{.min}.js`

So as of today, the [latest release](https://github.com/braintree/braintree-web/tree/2.17.6) is available via:

https://js.braintreegateway.com/js/braintree-2.17.6.js
https://js.braintreegateway.com/js/braintree-2.17.6.minjs

**Comment by jordanlewiz** [comment]
@kyledetella thank you very much for updating the docs. One other suggestion I made via a support email was that the following example in the docs is very misleading.
```
onReady: function (braintreeInstance) {
  braintreeInstance.deviceData;
}
```

Line 2 `braintreeInstance.deviceData;` is not really valid as far as I can see. It's just a value not assigned to anything?

Initially I thought this was some magic function and didn't give it much thought and actually used this in my code expecting to do the job.

Perhaps a quick fix for this example would be:
```
onReady: function (braintreeInstance) {
  var deviceData = braintreeInstance.deviceData;
  /* send deviceData to server */
}
```
