### ISSUE TITLE
PayPal shippingAddressOverride

### ISSUE THREAD

**Issue by illia94ua** [braintree/braintree-web#119]
Hi! I am currently using braintree's sandbox. When I try to setup braintree, I use shippingAddressOverride to set the test shipping address. However, I've been getting the default shipping address returned back to me. I have tried to use an older version of braintree.js, and in version 2.7.1 it worked correctly.

**Comment by danielwu426** [comment]
Hi @illia94ua - just for some more context, are you using our mocked Sandbox flow? Also, are you using Checkout with PayPal or our Vault flow?

**Comment by illia94ua** [comment]
Hi @danielwu426, yes I'm using mocked Sandbox flow and this applies to both of flow.

**Comment by danielwu426** [comment]
@illia94ua - our team is digging into the issue and will update here once we figure out the root cause. Stay tuned!

**Comment by intelliot** [comment]
At this time, our mocked Sandbox flow does not support the `shippingAddressOverride` feature. As a workaround, you may want to test this feature in production.

Meanwhile, we're looking into adding a passthrough to our mocked Sandbox flow so that the behavior is more similar to production. Thanks for your patience :)

**Comment by braintreeps** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;feTsZUBe&#x2F;459-allow-shippingaddressoverride-to-work-in-sandbox"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Allow shippingAddressOverride to work in sandbox</a>

**Comment by lilaconlee** [comment]
@illia94ua As of version 2.21.0, this issue has been fixed. Thanks for bringing it to our attention!
