### ISSUE TITLE
PayPal button displays in dropin

### ISSUE THREAD

**Issue by jeffhoye** [braintree/braintree-web#12]
When I use the dropin for a new user who doesn't yet have any payment options, it also displays the PayPal button even though I've not selected PayPal as one of my options in setup().

braintree.setup(client_token, "dropin", {
    container: container,
    paymentMethodNonceReceived: function (event, nonce) {
        ...
    }
});

Note that I've only seen this behavior in the sandbox. 
![bt_web_gray_bg](https://cloud.githubusercontent.com/assets/1181397/5669475/d34cd038-9745-11e4-830d-e0f71ad3f4de.png)

**Comment by kyledetella** [comment]
@jeffhoye the decision to display the PayPal button in Drop-in is determined by settings in your Control Panel. If you contact support@getbraintree.com and mention this issue, they can help you get that disabled.

**Comment by jeffhoye** [comment]
Ok, apparently it can't be disabled in the sandbox.  This is what it says about PayPal in the sandbox Processing Options (Support | Processing):

Accept PayPal
PayPal is enabled by default in the Sandbox.

**Comment by kyledetella** [comment]
That is correct, however if you contact support@getbraintree.com, they should be able to disable the PayPal button on your behalf.

**Comment by baisani** [comment]
How can i disable paypal option in BTDropInViewController,Please give me any suggestion. i am using sandbox account, paypal disable option is available in android not  IOS.

**Comment by intelliot** [comment]
@baisani This issue is for the JavaScript (web) SDK. `BTDropInViewController` is part of the [Braintree iOS SDK](https://github.com/braintree/braintree_ios). If you still need help, you can [contact Braintree Support](https://www.braintreepayments.com/contact).

**Comment by baisani** [comment]
How can i disable paypal option in IOS.

**Comment by matthewarkin** [comment]
@baisani as @intelliot mentioned before, this repo is and this issue are for the web SDK, for iOS there is a separate repository. 

However since you're not asking about a bug in the library, the most appropriate venue for your question would be to contact support: https://www.braintreepayments.com/contact
