### ISSUE TITLE
braintree requirejs config issue

### ISSUE THREAD

**Issue by muhammad-ammar** [braintree/braintree-web#120]
Below is my `require-config.js`

```javascript
require.config({
    waitSeconds: 60,
    paths: {
        "jquery": "js/vendor/jquery",
        "text": 'js/vendor/text',
        "underscore": "js/vendor/underscore",
        "backbone": "js/vendor/backbone",
        "babysitter" : "js/vendor/backbone.babysitter",
        "wreqr" : "js/vendor/backbone.wreqr",
        "marionette": "js/vendor/backbone.marionette.min",
        "braintree": "https://js.braintreegateway.com/v2/braintree",
    },
    shim: {
        "underscore": {
            exports: "_"
        },
        "backbone": {
            deps: ["underscore", "jquery"],
            exports: "Backbone"
        },
        "marionette": {
            deps: ["backbone", "babysitter", "wreqr"],
            exports: "Marionette"
        },
        deps: [ 'jquery', 'underscore']
    }
});
```

My backbone view:
```javascript
define([
    'jquery',
    'backbone',
    'underscore',
    'braintree',
    'text!subscription/templates/upgrade.underscore'
    ],
    function ($, Backbone, _, braintree, upgradeTemplate) {
        return Backbone.View.extend({

            el: '.tab-content',

            events: {
            },

            initialize: function(options) {
                this.sample_newsletter_url = options.sample_newsletter_url;
            },

            render: function() {
                $('.status-message').hide();

                this.$el.html(
                    _.template(upgradeTemplate)({sample_newsletter_url: this.sample_newsletter_url})
                );
                return this;
            },
    });
});
```

With this configuration when try to access `braintree` object in render or any other function, i am getting
`Uncaught ReferenceError: braintree is not defined`

Please guide how can i resolve this issue?

**Comment by EvanHahn** [comment]
@muhammad-ammar I'm investigating this now.

**Comment by EvanHahn** [comment]
@muhammad-ammar I couldn't reproduce your error. Could you take a look at the test app I made and see how it differs from yours? It's at [github.com/EvanHahn/braintree-web-issue-120](https://github.com/EvanHahn/braintree-web-issue-120).

**Comment by muhammad-ammar** [comment]
@EvanHahn Thanks a lot for your help. Test app works perfectly on my side. I am not using `data-main` attribute and my require-config and backbone modules in separate files. To me it looks like that my requirejs config/setup is not good as it should be. Here are more details.

I am using Django.

In my main django template(base.html):
```HTML
<script type="text/javascript" src="{% static 'js/vendor/require.js' %}"></script>
<script type="text/javascript" src="{% static 'js/require-config.js' %}"></script>
```

In my another django template(manage.html), here i can access the braintree object so i passed it to main backbone app to be used by other backbone views.
```JS
<script type="text/javascript">
    (function (require) {
         require(['manager/js/app', 'braintree'], function (ManageApp, braintree) {
             new ManageApp({{ info|safe }}, braintree);
         });
    }).call(this, require || RequireJS.require);
</script>
```
Now with this configuration i can use the `braintree` object in my backbone views.

**Comment by EvanHahn** [comment]
@muhammad-ammar I've updated [the test app](https://github.com/EvanHahn/braintree-web-issue-120) to use Django and it seems to work for me. Could you change your require.js `<script>` tag to something like this?

```django
<script type="text/javascript" data-main="{% static 'checkout/js/main' %}" src="{% static 'js/vendor/require.js' %}"></script>
```

**Comment by muhammad-ammar** [comment]
@EvanHahn I have already tried this but no success :(

**Comment by EvanHahn** [comment]
Do you get any errors in the console saying that braintree.js fails to load? Or do you only see `braintree is not defined`?

**Comment by muhammad-ammar** [comment]
ah..its working now. i have downloaded the braintree.js and i changed my require-config.js to
`"braintree": "js/vendor/braintree"`

i don't know how this is an issue but issue is resolved and i can define and use braintree like backbone, underscore etc in my backbone views

**Comment by EvanHahn** [comment]
Perfect! Is it alright if we close this issue?

**Comment by muhammad-ammar** [comment]
@EvanHahn Yes, we can close the issue. Thanks for all of your help.

**Comment by EvanHahn** [comment]
No problem! Feel free to open up a new issue if anything comes up.
