### ISSUE TITLE
Provide a way to stay informed of breaking changes, even in test

### ISSUE THREAD

**Issue by csm123** [braintree/braintree-web#123]
I have some feature tests that go through the PayPal sandbox flow and make sure the page responds properly. Recently there was a change to the PayPal sandbox flow where instead of asking for a login it shows a button to simulate a log in. It broke our tests, which is fine but I would have liked to have gotten notice. How can developers stay informed of changes like this? I'd recommend the docs address this directly and provide a way to subscribe to API updates.

**Comment by EvanHahn** [comment]
We understand that this isn't ideal. We have a suggestion that might not be exactly what you're looking for but we do have an [announcement list for SDK releases](https://groups.google.com/forum/#!forum/braintree-sdk-announce).

Luckily, it sounds like you have at least some way to check for breaking changes when your tests fail.

P.S. I noticed your username includes `123` and this issue number is `123`. Congratulations!
