### ISSUE TITLE
Change the 'close' link on the 3DS overlay to 'cancel'

### ISSUE THREAD

**Issue by skiddle** [braintree/braintree-web#124]
We've experienced that some banks don't have a very clear message, when passive 3DS is taking place

As such there is no indication that anything is occuring, for example HSBC says "We dont need your password for this transaction." There's no  'please wait', or 'loading...' etc/

As the only link visible is the 'close' button on the bottom of the overlay. We've had a few customers call explaining that they get stuck at this point (they close the window then have to start again)

I'd propose that the 'close' link is instead labelled 'cancel' - as that's what it does and it will discourage casual clicking

**Comment by mrak** [comment]
This is one of the limitations to 3DS - we have no way of knowing what is happening within the bank-hosted iframe.

Most banks have an "Exit" or "Cancel" button within their 3DS page that will forego the additional security checks and return us a non-3DSed nonce. Using the "cancel" terminology for our modal here would be even more confusing to the user, as the link "cancel" to close the modal would not do the same thing as the bank's "cancel".
![verified_by_visa_screen_shot](https://cloud.githubusercontent.com/assets/491140/13228353/5e490bfa-d950-11e5-904b-508d6e153e7a.jpg)
Closing the modal with the "close" link will remove the iframe from the page in case the user wanted to look at something else (such as shipping or cart items) and wasn't prepared to sign in to their bank. But we won't receive anything from the bank if they close the modal -- we won't have a nonce (3DS or no) to give you.

Overall it can be a kludgy experience as each bank has a different UI and different degrees of UX ergonomics. It a shame that some banks don't communicate that something is happening behind the scenes and for the user to "hang tight" while it happens.

**Comment by skiddle** [comment]
Completely understand. However, you guys do control the lightbox that appears (from which the 3DS iframe is contained).

If you look at the VbV implemenation guidelines[1], they say:

7.5 Merchants must provide a brief communication to customers outside of the frame for the
authentication page. The recommended text is:

_**Processing, please wait. Do not click the refresh or back button or this transaction may be
interrupted. **_

Visa also recommends that merchants implement a “processing” indicator with simple movement,
outside of the frame for the authentication page, to provide a visual cue to customers that the
purchase process is continuing in the background. Simple dots or arrows moving from left to right
are sufficient for this purpose. It is important that the status indicator have some kind of simple
movement.**_ Static processing screens confuse users because they cannot tell if the system is
working or frozen._**


It's the lack of implemention of this which is the main issue here I'd say.  We've been speaking to your guys are now implementing a workaround for this, but this may help other users?


[1] https://usa.visa.com/dam/VCOM/download/merchants/verified-by-visa-acquirer-merchant-implementation-guide.pdf

**Comment by crookedneighbor** [comment]
Just a note that we're exploring ways to improve control over the 3DS flow in the next major version of the SDK. We'll update this issue when the v3.0.0 beta is out.

**Comment by crookedneighbor** [comment]
We've released [beta 10 of version 3 of braintree-web](https://github.com/braintree/braintree-web/releases/tag/3.0.0-beta.10) which includes 3D Secure support. 

In version 3 you have full control over how the bank's iframe is presented. Here is [some documentation on using it](https://developers.braintreepayments.com/guides/3d-secure/client-side/javascript/v3).

We won't be changing the behavior in version 2 of braintree-web, so I'm going to close this issue. Let us know if you have questions!
