### ISSUE TITLE
Braintree JS SDK in sandbox iframe

### ISSUE THREAD

**Issue by crookedneighbor** [braintree/braintree-web#125]
Originally posted by @jart in https://github.com/braintree/braintree_java/issues/35

> Forgive me if this is not the proper place to file this bug.

> If I try to embed the 'dropin' Braintree JS SDK v2 in an iframe with the HTML5 sandbox attribute (for bidirectional security), then the browser will raise an error saying that the script is accessing document.cookie to write a value named 'venmo' or something. Even though I'm not using Venmo.

> A workaround exists, which is to host the iframe on a separate domain, so cross-origin browser security policies kick in. But it would simplify production systems management if the braintree iframe were able to be hosted inside a sandbox.

**Comment by quinnjn** [comment]
@jart We do not support using Drop-in with sandboxed iframes. Although, currently it looks like using `allow-scripts allow-same-origin` allows Drop-in to work in a sandboxed iframe but we can’t guarantee it will in the future.

**Comment by jart** [comment]
Using `allow-scripts allow-same-origin` disables the sandbox entirely.

Do you guys support drop-in within a cross-origin iframe? Because I was planning on using that in production. Having bidirectional security is kind of important for where this is being embedded.

**Comment by EvanHahn** [comment]
Yes, we support Drop-in within a cross-origin iframe.
