### ISSUE TITLE
Allow CVV and 3DS for vaulted cards

### ISSUE THREAD

**Issue by skiddle** [braintree/braintree-web#126]
Hi

We are implementing vaulted cards to allow our customers a faster checkout

3DS is mandatory for us due to fraud prevention and the lower IC+ rates. 

However when using 3DS with vaulted cards it's not possible to also collect the CVV code

The main reason for requiring both is the CVV check is a convenient way to verify the customer is genuine and an extra check against account takeover and someone else ordering products using saved cards. 

We can get around this by introducing an sms verification code but it's a lot of work when we should just be able to recapture the CVV value as documented. 

Would be great to see this feature

**Comment by lilaconlee** [comment]
Hi @skiddle, we understand your use case, but have no plans to support CVV checks with 3DS at the moment. That being said, we will keep this in mind as we work on 3DS in the future.
