### ISSUE TITLE
Localize credit card form

### ISSUE THREAD

**Issue by fjg** [braintree/braintree-web#127]
Offer the possibility to pass a locale (not only for Paypal) but also for the credit card form: placeholder, error messages...

**Comment by EvanHahn** [comment]
We are actively looking into this for the next version of Drop-in. We don't have anything to show yet, but we'll let you know if we have any updates.

If you're using any of our other integrations (like Hosted Fields), you can already do this localization yourself by setting the placeholders based on locale.

**Comment by Gtoffo** [comment]
+1 this is crucial for us

**Comment by kyledetella** [comment]
@Gtoffo just to reiterate what @EvanHahn said, if you find yourself in critical need for localization of your card form, take a look at [Hosted Fields](https://developers.braintreepayments.com/guides/hosted-fields/overview) as that will provide you the flexibility you need.

**Comment by lilaconlee** [comment]
The [new version of Drop-in](https://developers.braintreepayments.com/guides/drop-in/javascript/v3) is localized in 23 languages. Check out our [developer docs](https://developers.braintreepayments.com/guides/drop-in/javascript/v3#availability) or the [braintree-web-drop-in repo](https://github.com/braintree/braintree-web-drop-in/tree/release#localization) for more details!
