### ISSUE TITLE
Dropin Transparency

### ISSUE THREAD

**Issue by jeffhoye** [braintree/braintree-web#13]
After a user has a payment method in the vault, the Dropin iframe is transparent, and it looks fine over our black background:
![bt_web_transparent](https://cloud.githubusercontent.com/assets/1181397/5669528/27cf889e-9746-11e4-8b99-0a431fa7a9a3.png)

However, the first time, it's white/opaque and looks poor on our black background:
![bt_web_gray_bg](https://cloud.githubusercontent.com/assets/1181397/5669544/44f39e38-9746-11e4-93a8-0ff6e3e5a3ea.png)

The dropin does a lot for us, so I prefer to use it rather than write the customized forms.  Is there any chance that you will make the initial screen also transparent or else give us some minor customization options such as background color?

**Comment by kyledetella** [comment]
@jeffhoye, we have noted this feature request and have had a lot of discussion on the matter. As it stands today the background colors of the Drop-In UI are not customizable. In your case, when using a black background, we suggest styling your container `div` (maybe giving it a white background color) to help the Drop-In UI integrate a bit more seamlessly.

**Comment by MichaelWilkens** [comment]
On the parent container div, the one which houses the braintree drop-in iframe, you can put some css like this:

`iframe {
  background-color: white !important;
}`

That seemed to work for me. Obviously insert your background color of choice.
