### ISSUE TITLE
onReady never fire

### ISSUE THREAD

**Issue by valcamonica** [braintree/braintree-web#132]
hello, 
I'm trying to get the client device data to use with the advanced fraud tool, but the **onReady** callback never fire.
I'm using braintree-2.20.0.min.js

```
<form>
	<div id="braintree-container"></div>
	<input type='submit' value='Pay'/>
</form>

<script>
	braintree.setup(clientToken,"dropin", {
		container: 'braintree-container',
		dataCollector: {
			kount: {
				environment: 'sandbox'
			},
			paypal: true
		},
		paymentMethodNonceReceived: function(event, nonce) {
			console.log("paymentMethodNonceReceived");
			console.log(event);
			console.log(nonce);
		},
		onReady: function(braintreeInstance) {
			console.log("onReady");
			console.log(braintreeInstance);
			console.log(braintreeInstance.deviceData);
		},
	});
</script>
```

**Comment by lilaconlee** [comment]
Hi @valcamonica, it sounds like you might be experiencing the issue described in https://github.com/braintree/braintree-web/issues/121 where `onReady` does not fire when your container is hidden. 

If this is not the case, let us know and we can investigate further.

**Comment by valcamonica** [comment]
Hi, 

my container is not hidden. My code is as shown in my previous post.

In the code you referenced, there is a display none:
```
<form style="display:none;">
```

**Comment by mrak** [comment]
Your setup looks correct. Are you receiving any errors in the console?

Also, `paymentMethodNonceReceived` has been deprecated in favor of `onPaymentMethodReceived`.

**Comment by valcamonica** [comment]
Hello,

onPaymentMethodReceived don't work either. Here is a better example, showing what happens:

```
<script src="https://js.braintreegateway.com/js/braintree-2.20.0.min.js"></script>
<form>
	<div id="braintree-container"></div>
	<input type='submit' value='Pay'/>
</form>

<script>
	braintree.setup(clientToken,"dropin", {
		container: 'braintree-container',
		dataCollector: {
			kount: {
				environment: 'sandbox'
			},
			paypal: true
		},		
		paymentMethodNonceReceived: function(event, nonce) {
			console.log("paymentMethodNonceReceived");
			console.log(event);
			console.log(nonce);
		},
		onReady: function(braintreeInstance) {
			console.log("never called");
		},
		onSuccess: function (nonce, email) {
			console.log("never called");
		},
		onPaymentMethodReceived: function(event, nonce) {
			console.log("never called");
		},		
		onError: function (type, message) {
			console.log("never called");
		},
	});
</script>
```

console output:

```
paymentMethodNonceReceived
Event {isTrusted: true}
******-******-******-*****-******
```

**Comment by lilaconlee** [comment]
It looks like this issue might be more fitting for our support team. You can email them at support@braintreepayments.com with a link to this issue and they can help figure out what's going on. We'll follow up with them directly as well.

**Comment by beaurepair** [comment]
Have found that the following css is preventing the onready and onerror events from firing.

iframe{
	height: auto;
}

**Comment by valcamonica** [comment]
Tried with iframe{height: auto;}, and  iframe{height: 200px !important;}.

onReady, onSuccess, onPaymentMethodReceived, onError are never called.

paymentMethodNonceReceived is called.

Maybe the problem is that I'm executing from Italy?

On Tue, Mar 15, 2016 at 12:25 AM, Beau Gibson <notifications@github.com>
wrote:

> Have found that the following css is preventing the onready and onerror
> events from firing.
>
> iframe{
> height: auto;
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/braintree/braintree-web/issues/132#issuecomment-196563165>
> .
>



-- 

*Cordiali Saluti / Best Regards,*



*Norberto Valcamonica*



*JavaEE Developer*



Open Gate S.r.l.  *( build 2.0 )*
*Via Milano, 37/C - 20064 - Gorgonzola (MI) - ITALY*


*Office  +39 *
*  02 8719 8839*
*Fax      +39 *
*  02*
*8718 3941*

*E-mail: n.valcamonica@opengate.biz <n.valcamonica@opengate.biz>*

*Internet: http://www.opengate.biz <http://www.opengate.biz/>*


------------------------------

*P Before printing, watch if it is really necessary*

*Le informazioni contenute in questo messaggio sono riservate e
confidenziali ed è vietata la diffusione in qualunque modo eseguita.
Qualora Lei non fosse la persona a cui il presente messaggio è destinato,
La invitiamo ad eliminarlo e a non leggerlo, dandocene gentilmente
comunicazione. Per qualsiasi informazione si prega di
contattare n.valcamonica@opengate.biz <n.valcamonica@opengate.biz>
Rif.D.Lgs.196/2003*



*This e-mail (including attachments) is intended only for the recipient(s)
named above. It may contain confidential or privileged information and
should not be read, copied or otherwise used by any other person. If you
are not the named recipient, pleasecontact n.valcamonica@opengate.biz
<n.valcamonica@opengate.biz> immediately and delete the e-mail from your
system. Rif.D.Lgs.196/2003*
------------------------------

**Comment by EvanHahn** [comment]
We tested out your integration. The `onReady` callback never fired when serving your checkout from the file system (using the `file:///` protocol). Everything worked fine when running an HTTP server.

Could you try running your checkout in an HTTP server to see if that fixes things?

We do not think that being in Italy is your problem.

**Comment by valcamonica** [comment]
that's it!

I have put the page inside a locally hosted Wordpress and now it works!


   - onReady function was called, with it's parameter valorized
   - onPaymentMethodReceived function was called, with it's parameter
   valorized


Thank you for all your time and support!

Norb.




On Tue, Mar 15, 2016 at 4:46 PM, Evan Hahn <notifications@github.com> wrote:

> We tested out your integration. The onReady callback never fired when
> serving your checkout from the file system (using the file:/// protocol).
> Everything worked fine when running an HTTP server.
>
> Could you try running your checkout in an HTTP server to see if that fixes
> things?
>
> We do not think that being in Italy is your problem.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
>
> https://github.com/braintree/braintree-web/issues/132#issuecomment-196889135
>



-- 

*Cordiali Saluti / Best Regards,*



*Norberto Valcamonica*



*JavaEE Developer*



Open Gate S.r.l.  *( build 2.0 )*
*Via Milano, 37/C - 20064 - Gorgonzola (MI) - ITALY*


*Office  +39 *
*  02 8719 8839*
*Fax      +39 *
*  02*
*8718 3941*

*E-mail: n.valcamonica@opengate.biz <n.valcamonica@opengate.biz>*

*Internet: http://www.opengate.biz <http://www.opengate.biz/>*


------------------------------

*P Before printing, watch if it is really necessary*

*Le informazioni contenute in questo messaggio sono riservate e
confidenziali ed è vietata la diffusione in qualunque modo eseguita.
Qualora Lei non fosse la persona a cui il presente messaggio è destinato,
La invitiamo ad eliminarlo e a non leggerlo, dandocene gentilmente
comunicazione. Per qualsiasi informazione si prega di
contattare n.valcamonica@opengate.biz <n.valcamonica@opengate.biz>
Rif.D.Lgs.196/2003*



*This e-mail (including attachments) is intended only for the recipient(s)
named above. It may contain confidential or privileged information and
should not be read, copied or otherwise used by any other person. If you
are not the named recipient, pleasecontact n.valcamonica@opengate.biz
<n.valcamonica@opengate.biz> immediately and delete the e-mail from your
system. Rif.D.Lgs.196/2003*
------------------------------
