### ISSUE TITLE
Some valid addresses used with the shippingAddressOverride cause PayPal to fail to load

### ISSUE THREAD

**Issue by mattgrosse** [braintree/braintree-web#135]
It seems that if the postalCode or region properties are excluded (or set null) on the shippingAddressOverride object, the connection to PayPal fails. The container seems to get setup correctly, but when you click the PayPal button the popup window shows a message like:

"Sorry we cannot connect to PayPal. Please try again in a few minutes."

This is problematic for international addresses that do not require or have a region (state) or postal code. We noticed the issue when a customer was trying to checkout using a German shipping address. We also reproduced the error using UK addresses. The proper alpha2 country code was provided in all cases. By putting a value in the region property, everything seemed to load as normal. 

To reproduce this, create the shippingAddressOverride object and omit the region or postal code. This was only reproducible in the production environment, since the dev sandbox doesn't simulate the address flow or shippingAddressOverride the same way as in production.

As of right now, we got around this by not sending the address into the PayPal config if the region/postalcode are not provided - but we'd like to do this whenever a shipping address is required.

Thanks for any assistance, and hopefully this will be helpful!

**Comment by danielwu426** [comment]
Hi @mattgrosse thanks for reaching out! The level of detail is helpful.

To your specific use case, postal code is required for German and UK addresses. I believe as long as you're passing that you won't need to pass a region (state). 

There's some work we can do here to pass back validation and configuration errors when required fields aren't passed. In addition, we should make sure there's parity with our Sandbox integration. I don't have a timeline for when you can expect this, but do know this is on our backlog.

**Comment by mattgrosse** [comment]
Hi Dan. I look forward to the updated validation/config errors and updates to the sandbox.

As for the German address, we definitely passed in the postal code without a region and it was failing to load. I only mentioned the postal code because in further testing I noticed that if you left that out, it would also fail. So I think there may be an issue with the validation of international addresses.

**Comment by danielwu426** [comment]
@mattgrosse - We're continuing to gather information on which address fields are required for specific countries.  We'll keep you updated once we have more information here.

**Comment by intelliot** [comment]
Hi @mattgrosse -

At this time, PayPal's shipping address validation is probably too strict for your use case. You may wish to avoid setting a shipping address override; handle shipping addresses within your own checkout code, as it sounds like you're already doing. Note that this may void Seller Protection for PayPal transactions.

Also, if you want to reproduce this issue in the sandbox environment, it's possible to link a PayPal Sandbox account with your Braintree Sandbox account. Contact Braintree Support for more info on how to do this.

Thanks for bringing this issue to our attention.
