### ISSUE TITLE
client.tokenizeCard using GET request

### ISSUE THREAD

**Issue by oblogic7** [braintree/braintree-web#136]
When using direct tokenization, the request is being sent as GET with all parameters in the URL.  Shouldn't it be sending the data as a POST?

**Comment by mrak** [comment]
Our library defaults to using JSONP (GET based) for backward-compatibility reasons. If you would like to use CORS with AJAX (POST based) instead you can use our `enableCORS: true` option for `braintree.setup`.

Link to docs: https://developers.braintreepayments.com/reference/client-reference/javascript/v2/configuration#setup-method-options

**Comment by oblogic7** [comment]
Thanks for the reply.
