### ISSUE TITLE
Driving Braintree's hosted fields through integration tests

### ISSUE THREAD

**Issue by mfrost** [braintree/braintree-web#139]
We're using [Cypress](https://www.cypress.io/) to drive some tests on a new application that will be using Hosted Fields. Cypress runs tests using JS, and is unable to enter information into the hosted fields because they belong to a different frame. The maintainer of Cypress is looking at a possible solution.

I was curious if there was the possibility of using something like `postMessage` to allow access to the values of those inputs. For example, something like:
```js
ccField.postMessage('4111111111111111', 'https://assets.braintreegateway.com');
cvvField.postMessage('123', 'https://assets.braintreegateway.com')
exprField.postMessage('12/20', 'https://assets.braintreegateway.com')
```
This would allow us to programmatically set the test values for full end-to-end testing. Hopefully I'm not missing an obvious security concern...

**Comment by EvanHahn** [comment]
In general, we avoid sending any sensitive card data over `postMessage` for security and compliance reasons.

We may allow you to set example values in a future version of the SDK—this is something we're exploring—we'll let you know if we have something to know. No promises, though.

**Comment by mfrost** [comment]
Right, makes sense. Was mostly hoping to programmatically set the value via something like `postMessage` but I think we'll be switching our integration test driver to something more capable.

Thanks for the reply.
