### ISSUE TITLE
Javascript crashes if form is submitted before the iframe fully loads.

### ISSUE THREAD

**Issue by pdg137** [braintree/braintree-web#14]
There seem to be a few different errors that occur if a form button is clicked while the iframe is still spinning its loading icon.  For example, using rspec/rails/phantomjs to try to proceed quickly through a form, I get this:

    TypeError: 'undefined' is not an object (evaluating 'this.views[this.currentView].handleRequestNonce')
           at https://assets.braintreegateway.com/dropin/1.1.9/braintree-dropin-internal.min.js:6
           ...

And a loading icon is visible in the saved screenshot.  Clicking quickly around in Chromium, I was able to get this:

    Uncaught TypeError: Cannot read property 'handleRequestNonce' of undefined braintree-dropin-internal.min.js:6
    ...

I can work around it to some extent, but it seems dangerous to not handle this situation.

**Comment by jeffcarp** [comment]
Good catch. We should definitely guard against this.

**Comment by idl3** [comment]
Could be solved with either a callback function to allow the form to be submitted only upon completed the loading of the iframe (same suggestion as #19) or append a class or attribute to the drop-in container to show that it has completed so we can do a on-submit check to verify if the iframe loaded completely.

**Comment by kyledetella** [comment]
Closing in favor of #19.

**Comment by pdg137** [comment]
So instead of the "few lines of code" advertised in your docs, we have to disable submit and write our own handler just to make sure braintree.js doesn't crash in some unforseen way?  Why can't your code handle its own errors?
