### ISSUE TITLE
Trouble Triggering onReady Callback 

### ISSUE THREAD

**Issue by auzmartist** [braintree/braintree-web#140]
Hello, I'm having some trouble triggering the onReady callback (or onError for that matter) and looking for a second pair of eyes. Hopefully my mistake is really trivial. My JS code is pretty vanilla; I'm using hosted fields and I can trigger the onFieldEvent callback in there successfully.

```
var options = {
	id: "my-sample-form",
	onReady: function(integration){
		console.log("Ready");
	},
	onError: function(type, message){
		alert(type);
	},
	hostedFields: {
		number: {
			selector: "#card-number"
		},
		cvv: {
			selector: "#cvv"
		},
		expirationDate: {
			selector: "#expiration-date"
		},
		onFieldEvent: function(e){
			if(e.type === "fieldStateChange"){
				console.log(e);
			}
		}
	}
};
braintree.setup(token, "custom", options);
```

I'm using braintree-2.21.0.min.js and have tried against 2.20.0 as well with no luck.

**Comment by lilaconlee** [comment]
That setup looks like it should work! Our support team is a little better suited to handle these type of questions. Feel free to email support@braintreepayments.com with this issue and they can take a more in depth look at your integration.

**Comment by auzmartist** [comment]
Thanks @lilaconlee. Unfortunately, I have had no luck since posting. I'll send a support email and get the ball rolling there.

**Comment by beaurepair** [comment]
Have found that the following css is preventing the onready and onerror events from firing.

`iframe{
	height: auto;
}`
