### ISSUE TITLE
Braintree dropin modal does not remove overflow: hidden; from body tag

### ISSUE THREAD

**Issue by beedaan** [braintree/braintree-web#142]
To reproduce:

1. Select "Change Payment Method"
2. Notice `braintree-dropin-modal-frame` opens and `style="overflow: hidden; height: 100%;` is applied to the `<body>`

![screen shot 2016-03-17 at 4 20 02 pm](https://cloud.githubusercontent.com/assets/884240/13859905/351d4696-ec5c-11e5-9057-99a920ff49c7.png)
3. Select "Cancel" from the modal
4. Notice `style="overflow:hidden;` is still applied to the `<body>`
![screen shot 2016-03-17 at 4 21 16 pm](https://cloud.githubusercontent.com/assets/884240/13859952/64621cd8-ec5c-11e5-9621-080fa83cc350.png)

This breaks my page and requires a refresh to get rid of the style.

**Comment by EvanHahn** [comment]
The `modal-open` class on your `<body>` tag makes it look like you're using Bootstrap modals _and_ Braintree's Drop-in modal.

If that's the case, unfortunately, this isn't supported by Bootstrap. To quote [their documentation](http://getbootstrap.com/javascript/#modals):

> **Multiple open modals not supported**
>
> Be sure not to open a modal while another is still visible. Showing more than one modal at a time requires custom code.

If you're using Bootstrap modals, you'll have to write some custom code that removes the `overflow` property. (We're happy to give you a push in the right direction here, if you need help!)

If you're not using Bootstrap modals, we'll look into this further.

**Comment by beedaan** [comment]
@EvanHahn I am using Bootstrap.  Thank you for the clarification!
