### ISSUE TITLE
Drop In Paypal window on iOS Chrome

### ISSUE THREAD

**Issue by xuaninbox** [braintree/braintree-web#143]
When select Paypal in the dropin on iOS Chrome it doesn't open a new tab like in safari and other browser, but it will overlay the view above the current page.

This may cause a problem as the drop in may be at the bottom of the page and the paypal will be on the very top of the page and produce a blank page that user have to scroll to the very top to find the paypal login

**- The url is not changed**

![img_0238](https://cloud.githubusercontent.com/assets/5108256/13926934/8b091dde-ef5c-11e5-8107-8c3404a0904a.PNG)

**- The page can be scrolled **

![img_0239](https://cloud.githubusercontent.com/assets/5108256/13927014/d36e7970-ef5c-11e5-9016-235587c359b9.PNG)

Thanks

**Comment by EvanHahn** [comment]
You're right, this is a bug. We're actively working on it and we'll update you when this is fixed!

**Comment by EvanHahn** [comment]
This was fixed in `braintree-web@2.22.2`. You can grab it from Bower, npm, or just link to the file at `https://js.braintreegateway.com/js/braintree-2.22.2.min.js`.

Hope this helps!
