### ISSUE TITLE
Can`t open window with PayPal in facebook iOS WebView

### ISSUE THREAD

**Issue by HZ-labs** [braintree/braintree-web#144]
After clicking on PayPal button, the window becomes white and nothing happens

**Comment by mrak** [comment]
We have an outstanding issue where paypal modals open at the top of the page instead of at the current scroll position.

Could you try scrolling to the top of the page to verify that the paypal flow has opened there?

**Comment by HZ-labs** [comment]
The page is not scrolling
![ezgif-3691150497](https://cloud.githubusercontent.com/assets/1663933/13979258/2b1724b0-f0e8-11e5-84fb-f573116f0300.gif)

**Comment by mrak** [comment]
We'll need more specifics and perhaps this forum isn't the best place to debug the issue.

I recommend emailing our support team at support@braintreepayments.com

They will help you sort out this issue in depth and I'll follow up with them.

**Comment by HZ-labs** [comment]
Thank you,I will send them an email
