### ISSUE TITLE
Cannot use a payment_method_nonce more than once.

### ISSUE THREAD

**Issue by Andrii-D** [braintree/braintree-web#148]
Hey guys, 
For the last few months we've been struggling with finding out why do we receive an error:
`Cannot use a payment_method_nonce more than once.` with code 91564.

Here is what we found:
When you click on "Pay" button on the braintree popup window it will show you an intermediate window with the information of you card and with link to change payment methods. But the "Pay" button is still exist and if you will click it again it will show you this error. If you don't click, after few seconds it will act like it should. 
Here is a [screencast ](https://www.dropbox.com/s/0tgvrkwtfunsjh0/braintree_web_bug.mov?dl=0) of reproducing this flow. 

Some of our users are getting a bad user experience because they click on button "Pay" two times and receive an error. 

We are using this version of braintree frontend:
https://js.braintreegateway.com/v2/braintree.js

Could you please help us to figure out if this behavior is normal or we have some troubles?

Many thanks!

**Comment by mrak** [comment]
Are you using `onPaymentMethodReceived` to get the nonce value from Drop-in?

**Comment by Andrii-D** [comment]
Yes, we use `onPaymentMethodReceived`.

**Comment by mrak** [comment]
If you are using `onPaymentMethodReceived` then Drop-in should not be submitting the form for you.

Are you sending the nonce to your sever to transact within your `onPaymentMethodReceived` handler?

**Comment by Andrii-D** [comment]
Yes, we do make ajax request to our server to charge a payment with nonce received from Braintree form. The problem can be that we cannot hide Drop-In UI as it is in iframe but on the other hand it is still possible to press Pay button one more time while ajax request reloads page on success.

**Comment by mrak** [comment]
Once you receive the nonce in the callback you can disable the Pay button and navigate the page for the user. That should prevent them from double-clicking by accident.

**Comment by Andrii-D** [comment]
Thank you @mrak, it sounds reasonable. We were confused because other fields are under the `iframe` and we can't access them from our script. But the button "Pay" is outside.

**Comment by mrak** [comment]
@Andrii-D did you find a solution?

**Comment by Andrii-D** [comment]
Yes @mrak , we just disabling this button in the callback. Thanks, you can close this issue!
