### ISSUE TITLE
Native submit not being prevented

### ISSUE THREAD

**Issue by JesusisFreedom** [braintree/braintree-web#149]
Hi braintree team. Thanks for your excellent hosted fields solution. What I running into is that Im manually submitting the form with the hosted field containers via 
```javascript
document.getElementById(this.ccFormId).submit();
```
But the native submit handler is running. In your docs you say to bypass the braintree submission handler you can do the following
```javascript
var form = document.getElementById('my-form');
HTMLFormElement.prototype.submit.call(form);
```
I'm not using that exact call, and I do have the ```OnPaymentMethodRecived``` callback in place but the form is still submitting natively instead of providing the nonce or validation errors.
Here is the form(in jade)
```
form(action="", method="POST").grid-block#cc-input-form
    .grid-content.small-6
      #card-number.hosted-input
    .grid-content.small-3
      #expiration-date.hosted-input
    .grid-content.small-3
      #cvv.hosted-input
```
The reason I have no submit input is that I'm using Angular and this form is actually a part of a larger and modular ```ngForm```(Which is not a form at all, but a construct that sort of acts like one, therefore this is NOT a `<form>` inside a `<form>` which is invalid html)

I'm wondering if you could provide some feedback. 

UPDATE: For kicks I tried putting in a submit input, but the same result. 
Do we actually need a click event to that submit button to get the braintree nonce goodness?

UPDATE: I overcame this with a hidden submit input that I then had to run .click() on.

See #151

**Comment by mrak** [comment]
Using `.submit()` directly on a form element will bypass all javascript submit handlers. This may be why you are not seeing `onPaymentMethodReceived` being fired.

If you want to programmatically dispatch a `submit` event on a form that has no button to click, you can do this:

```javascript
var form = document.getElementById('my-form');
var e = document.createEvent('Event');

e.initEvent('submit', true, true);
form.dispatchEvent(e);
```

See MDN's [Creating and triggering events](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events#The_old-fashioned_way)

**Comment by JesusisFreedom** [comment]
@mrak Thanks so much. I didn't think about doing it that way.
Thanks I think we can close this.

**Comment by JesusisFreedom** [comment]
@mrak perhaps what you said would be a helpful addition to the docs.
