### ISSUE TITLE
Allow access to some card information prior to using the nonce

### ISSUE THREAD

**Issue by pdg137** [braintree/braintree-web#15]
Many checkout systems show a preview page with a summary of what is about to happen, like "$44 will be charged to your Visa ending in 1234".  That's not possible with the Drop-In UI, since the only thing we have access to at preview time is a nonce, and (if you care about the CVV) the nonce can only be used to create a transaction.

So, here is a simple feature request: the Drop-In UI should submit the credit card type and last four digits in some additional parameters to our form, along with the nonce.  Presumably something similar would apply to PayPal transactions.

**Comment by jeffcarp** [comment]
Cool idea. Something you could do right now is:

1. [Intercept nonce](https://developers.braintreepayments.com/javascript+node/sdk/client/drop-in#paymentmethodnoncereceived) on Drop-in submit
2. Send nonce to your server
3. [Create a payment method](https://developers.braintreepayments.com/javascript+node/reference/request/payment-method/create) with that nonce
4. Send [`creditCard.last4`](https://developers.braintreepayments.com/javascript+node/reference/response/credit-card) and `creditCard.cardType` to your front-end for display

**Comment by pdg137** [comment]
You can do that to display a preview, but then if you create a transaction you won't get CVV verification at all, right?

**Comment by jeffcarp** [comment]
If you have CVV rules enabled in the control panel, Drop-in will validate the CVV and won't produce a nonce unless the credit card info is valid.

**Comment by pdg137** [comment]
Really?  What would it do instead, display some error to the user?  I just tried a few times in the sandbox with CVV 200, and the iframe generated nonces as usual.

**Comment by pdg137** [comment]
It would be surprising if there were some way to casually check CVVs without explicitly requesting a sale or verification.  Braintree support has indicated to me by email that there isn't a good way to do what I want yet.

**Comment by jeffcarp** [comment]
@pdg137 totally my bad, you're right - that would be opening a huge avenue for fraud. I'm going to add the enhancement tag.

**Comment by pdg137** [comment]
Thanks.  For comparison, [Stripe includes CC info with their nonce](https://stripe.com/docs/api#token_object).  It would be great to have a feature like that here!

**Comment by kyledetella** [comment]
@pdg137 we have recently released `braintree.js v2.5.0` which introduces a new callback schema. It is backwards compatible and what you are currently using will work, however with this new callback you can get some credit card details back.

We have not yet added it to our documentation (coming soon) but I am happy to help here to see if this addresses your issue.

```js
braintree.setup('TOKEN', 'dropin', {
  container: 'my-container',
  onPaymentMethodReceived: function (payload) {
    // payload.nonce
  }
});
```

The `payload` of `onPaymentMethodReceived` will look like this (for a credit card):

```js
{
  nonce: 'A nonce',
  type: 'CreditCard',
  details: {
    lastTwo: '44',
    type: 'Visa'
  }
}
```

Go ahead and try this out and let me know if that solves your problem. You can get the latest version of `braintree.js` on `npm` or `bower` or by using the "hotlinked" version at [https://assets.braintreegateway.com/v2/braintree.js](https://assets.braintreegateway.com/v2/braintree.js).

**Comment by pdg137** [comment]
Is it really only going to be the last two digits?  Will the information be available in the Ruby interface to the nonce, or do we have to use Javascript to see it?

**Comment by jeffcarp** [comment]
@pdg137 you can grab the last four [using the Ruby client library](https://developers.braintreepayments.com/javascript+ruby/reference/response/credit-card#last_4). Unfortunately for security reasons our client API only returns the last 2 digits of a card.

**Comment by pdg137** [comment]
So it is only available in Ruby after you make a transaction; you can't get it from the nonce in Ruby?

**Comment by jeffcarp** [comment]
@pdg137 that's correct - the nonce doesn't contain any information within itself, it just points to a payment method in the gateway.

**Comment by jeffcarp** [comment]
Closing - let me know if you have any other questions :smile:

**Comment by avidas** [comment]
Was looking for this exact feature :+1:

**Comment by pvaibhav1510** [comment]
Looking for same feature in Java. I want to retrieve the billing address using the Braintree nonce, validate it, & then create a customer profile.

Is it possible to get the credit cards details (expiry info, billing address ect.) using the nonce (before creating a customer)?

**Comment by kyledetella** [comment]
@pvaibhav1510 I just commented on #109 with this:

> ...this sounds like an issue with your server-side integration. I would suggest opening an issue on the braintree_java library or reaching out to our support team (support@braintreepayments.com) directly.
