### ISSUE TITLE
set type for PayPal cancel button

### ISSUE THREAD

**Issue by HZ-labs** [braintree/braintree-web#150]
if PayPal is used inside `<form>` then for `<button id="bt-pp-cancel">`  it is necessary to use  `type="button"` in order to prevent the situation when a user taps `Enter` inside  `<input>` of this form.

**Comment by EvanHahn** [comment]
Good catch! This is a bug; we'll let you know when it's fixed.

**Comment by intelliot** [comment]
@HZ-labs This was fixed in `braintree-web@2.23.0`. You can grab it from Bower, npm, or just link to the file at `https://js.braintreegateway.com/js/braintree-2.23.0.min.js`.

Thanks for the report!
