### ISSUE TITLE
Weird Cross Frame errors

### ISSUE THREAD

**Issue by JesusisFreedom** [braintree/braintree-web#152]
See screenshot. This is only happening in Safari.

![safaricors](https://cloud.githubusercontent.com/assets/4331331/14293012/752bb700-fb1f-11e5-9a72-a227def5e514.png)

Facebook and Braintree are fighting for some reason.

**Comment by intelliot** [comment]
@JesusisFreedom Thanks for the report. To clarify - does Safari exhibit any problems on the page, aside from showing these error messages in the console?

In other words, ignoring the errors, do Facebook and Braintree still work on the page?

Also - would it be possible to share an example page that demonstrates this problem?

**Comment by mrak** [comment]
Closing this issue as there has been no follow-up. Please comment back here if you have more information for us.
