### ISSUE TITLE
Input Masking

### ISSUE THREAD

**Issue by JesusisFreedom** [braintree/braintree-web#153]
Before the PCI 3 introduced the SAQ-A compliance level which necessitated the use of hosted fields our forms looked like the following. We used input masks to give the user a little better feedback on what was being asked of them.

![20160406screencast -454mx](https://cloud.githubusercontent.com/assets/4331331/14337297/5ff33a9a-fc21-11e5-8407-4da8adb523dd.gif)

I am requesting a similar functionality with hosted fields. Many users and our QA team were confused by the expiration date input because they didnt know right off the bat if they could do "2/18", "02/2018", "02/18".
Essentially they were confused on what to put in that input along with losing their place with the credit card due to lack of visual feedback.

It could look something like 
```
 hostedFields: {
    styles: {
      'input': {
        'font-size': '12px',
        'font-weight': '100',
        'color': 'rgba(0,0,0,.75)',
        'font-family': 'sans-serif'
      }
    }
    number: {
      selector: "#card-number",
      placeholder: 'Card Number'
    },
    cvv: {
      selector: "#cvv",
      placeholder: 'CVV'
    },
    expirationDate: {
      selector: "#expiration-date",
      format: '99/99' <----------------------- or '99/9999' 
      placeholder: 'MMYYYY'
    }
  }
```

**Comment by mrak** [comment]
Thanks for requesting this feature, @JesusisFreedom.

We're tracking the request for input formatting in #77. See @lilaconlee's [comment in that issue](https://github.com/braintree/braintree-web/issues/77#issuecomment-196917711) for more.

Formatting is coming...
