### ISSUE TITLE
Configuration of undefined error

### ISSUE THREAD

**Issue by bluejamesbond** [braintree/braintree-web#154]
When using Uglify, I get the following error:
```
Uncaught TypeError: Cannot set property 'configuration' of undefined'`
```

Without Uglify, it works fine.

v2.21.1

**Comment by intelliot** [comment]
@bluejamesbond We're not able to reproduce this error. Could you provide steps for how to trigger it?

Also, which version of braintree.js are you using? (We don't have a v2.21.1.)

Thanks!

**Comment by mrak** [comment]
Closing from lack of follow-up. Feel free to reopen this issue if you are still experiencing it and have more information for us.
