### ISSUE TITLE
Disabling submit with hosted fields

### ISSUE THREAD

**Issue by rickhall** [braintree/braintree-web#155]
I had contacted support with this question, but I'll re-enter it here to capture it.

I am using custom integration with hosted fields and I would like to disable the submit button while waiting to get the payment nonce. My current approach is to:

1. Add a submit listener on the form which always disables the submit UI button upon seeing a submit event.
2. In braintree onError callback, I re-enable submit button in case of any validation errors.
3. In onPaymentMethodReceived callback, I then send the payment nonce to my server.

This basically works ok and prevents duplicate submits if and only if the user clicks on the “submit” button.

Unfortunately, if the user uses the "return" key to submit the form, then the native submit event isn’t fired. This makes it so I cannot give my user any visual feedback that something is going on, increasing the likelihood that they may try to resubmit if it takes a long time.

Perhaps I’m missing something, but I’ve searched the web a bit and it seems that a lot of people want to do this flow, but it is more difficult than it seems it should be. It seems like adding some sort of “beforeSubmit” callback after everything is validated, but just before submitting to braintree server would make this flow a lot more intuitive.

Thanks.

**Comment by lilaconlee** [comment]
Unfortunately, the behavior you've described is not something we currently support. That being said, we totally understand this use case and are including this functionality in the next major version of our SDK. We'll update you here when it is available!

**Comment by rickhall** [comment]
Thanks for the response and, yes, definitely report back and close this issue when you have something available.

**Comment by ds00424** [comment]
Hmmm.  I have a click event where I disable the Submit button and that seems to work when <CR> is hit.
JS/Jquery code (which is probably obvious :-)
$("#myForm button[type=submit]").click(function() {
	$(this).prop('disabled', true);	// Disable the Submit button so it can't be clicked again
	$("#ErrorSummary").html("")
});

Not sure if the declaration order matters, but the click event is defined early on.

HTH

**Comment by rickhall** [comment]
Yes, if you disable the submit button, then the user is not able to click it. However, if the user presses "return" to submit the form, then there is no click on the submit button, but the form is still submitted. Further, if you disable the submit button, the user is still able to press "return" to submit the form again...at least for me.

**Comment by mrak** [comment]
@rickhall you are correct. Upon hitting enter within one of Hosted Fields' inputs we attempt to tokenize the card data and submit the form, bypassing any JavaScript handlers, including disabled buttons. Not the friendliest way to do things if you need to get some code inbetween the lifecycle stages of user interaction, tokenization, and submission.

One of our goals for the next major version of our SDK is to eliminate any dependency on forms and their submit events. We are actively working on this next release and will update this issue when it is available.

**Comment by rickhall** [comment]
@mrak Yes, that was my understanding from the previous discussion, so I look forward to it. I was just responding to @ds00424 . Thanks again.

**Comment by ds00424** [comment]
@rickhall - Ah, what I was missing was if the return is hit **when within one of the hosted fields**.  I have other fields in the form and if the return is hit when within one of *those* fields - the click event fires.  Thx.

**Comment by godza** [comment]
@mrak Any way you can provide event callback in setup options that will be triggered when tokenizing card data and submitting form, so we can hook up to that callback (something like onPaymentMethodRequested or something like that)?

**Comment by mrak** [comment]
If you use `onPaymentMethodReceived` we will call it instead of submitting the form.

**Comment by godza** [comment]
I know, i meant in context of this issue, you can use new event that will be triggered when you start submitting data to braintree servers. That way, we can use that new event to disable the button, hide the form or do whatever until we receive the response with onPaymentMethodReceived. That new event need to be triggered either by user submitting the form, or pressing enter key in hosted fields. That would solve the problem OP (and me) has

**Comment by mrak** [comment]
Ah, sorry for the misinterpretation.

While we likely will not add more lifecycle hooks to our current SDK version, our current work on the next major version directly addresses this issue.

**Comment by godza** [comment]
Great. Until then :)

**Comment by godza** [comment]
Not trying to be pain in the ass but, is there ETA for 3.0.0?

Thanks

**Comment by mrak** [comment]
We don't have a hard ETA yet, but we are planning to release a beta soon.

**Comment by collizo4sky** [comment]
Glad someone filed this issue. Having similar prob.

**Comment by mrak** [comment]
We've released a beta of our next major version. A new feature is a separate `inputSubmitRequest` event in Hosted Fields that you can bind to a form submit if you choose to do so. It does not have the default action of submitting a form as it does in v2.

Here are some links to our official documentation:

[Setup for v3](https://developers.braintreepayments.com/guides/client-sdk/setup/javascript/v3)
[Migrating from v2 to v3](https://developers.braintreepayments.com/guides/client-sdk/migration/javascript/v3)
[Events in Hosted Fields](https://developers.braintreepayments.com/guides/hosted-fields/events/javascript/v3)

**Comment by allella** [comment]
If you're using the onPaymentMethodReceived callback with Hosted Fields version 2 (I'm using 2.8) then a simple solution would be to check if the nonce has already been received.  I do this by saving the nonce to a hidden input field and only allowing the custom form submit.call() the first time a nonce has been seen. I'm already sending that hidden input field as part of the POST so it was already part of the form.

~~~~
....
onPaymentMethodReceived: function (details) {
  if ($("#nonce").val() === '')
  {
    $("#nonce").val(details.nonce);
    var form = document.getElementById('credit-card-info');
    HTMLFormElement.prototype.submit.call(form);
  }
 },
....
~~~~

**Comment by kilvroch** [comment]
I'm using js.braintreegateway.com/web/3.0.0-beta.9/js/hosted-fields and had the problem with users being able to submit form multiple times. I did something similar to allella, adding a counter field and only allowing the form to submit if the value of the counter === 1:
`<input type="hidden" name="counter" id="counter" value="1"/>

    submit.addEventListener('click', function(event) {
      event.preventDefault();

      hostedFieldsInstance.tokenize(function(err, payload) {
        if (err) {
          console.log(err);
			alert(err);
          return;
        }

        // This is where you would submit payload.nonce to your server
        //alert('Submit your nonce to your server here!');
		// Put `payload.nonce` into the `payment-method-nonce` input, and then
        // submit the form. Alternatively, you could send the nonce to your server
        // with AJAX.
		 counter = parseInt(document.querySelector('input[id="counter"]').value);
		 console.log("counter = " + counter);
		 if (counter === 1)
		 {
			document.querySelector('input[name="payment_method_nonce"]').value = payload.nonce;
			document.querySelector('input[id="button-pay"]').value = "Please wait...";	
			document.querySelector('input[id="button-pay"]').disabled = true;
			document.querySelector('#loading').style.display = 'block';
			form.submit();		
			counter++;
			document.querySelector('input[id="counter"]').value = counter;
			form.style.display = 'none';
		 }
      });
`

**Comment by allella** [comment]
@kilvroch does that method account for if there's a validation failure? The reason I checked for the nonce is it only gets returned if/when validation has been passed.
