### ISSUE TITLE
Help differentiating between custom ui and hosted fields

### ISSUE THREAD

**Issue by collizo4sky** [braintree/braintree-web#156]
AFAIK, hosted field is the same as custom UI or is there any difference? 

Confusion stem from 

https://www.braintreepayments.com/products-and-features/custom-ui

https://www.braintreepayments.com/products-and-features/custom-ui/hosted-fields

**Comment by mrak** [comment]
Our main two integration options are `dropin` and `custom`. Hosted Fields is a sub-feature for `custom` integrations.

Within custom, you can accept credit cards one of two ways. I've added links to our developer documentation, as it may be clearer than our marketing site.

1. Use your own form fields for the credit card inputs (_not_ SAQ-A)
  * [Traditional custom integration documentation](https://developers.braintreepayments.com/guides/credit-cards/client-side/javascript/v2)
2. Use Hosted Fields for the credit card inputs (SAQ-A)
  * [Hosted Fields documentation](https://developers.braintreepayments.com/guides/hosted-fields/overview/javascript/v2)

**Comment by collizo4sky** [comment]
Thank you.
