### ISSUE TITLE
Drop-in UI not showing default payment

### ISSUE THREAD

**Issue by p4sh4** [braintree/braintree-web#157]
This has been [identified as an issue and fixed](https://github.com/braintree/braintree_android/issues/23) in the Android SDK. Any updates on when it is going to be fixed in the JavaScript Drop-In UI?

**Comment by JoshuaGRubin** [comment]
+1

**Comment by mrak** [comment]
This fix is planned to go out with the next JS SDK release.

**Comment by crookedneighbor** [comment]
This feature has been added in [version 2.24.0](https://github.com/braintree/braintree-web/releases/tag/2.24.0)

The docs will be released shortly, but in the meantime, here's how you would configure it:

```js
var clientToken = "client_token_from_server"; // this client token must have the customer id parameter configured
braintree.setup(clientToken, 'dropin', {
  defaultFirst: true
});
```

**Comment by aashidham** [comment]
How would I use defaultFirst for v3 drop-in?

**Comment by crookedneighbor** [comment]
`defaultFirst` is the only way payment methods are shown: https://github.com/braintree/braintree-web-drop-in/blob/39ca485487ea4107288e32b8a0b1fb368474d138/src/dropin-model.js#L286

**Comment by aashidham** [comment]
Is this true for https://js.braintreegateway.com/web/dropin/1.11.0/js/dropin.min.js as well?

As a side note, why are the dropin files versioned seperately from the whole client SDK? Does 1.11 of the dropin correlate to the most recent v3 Client SDK?

**Comment by aashidham** [comment]
Here is what I am doing to set the dropin up:

<pre>
braintree.dropin.create({
                authorization: client_token_server,
                container: '#dropin-container', 
                defaultFirst: "true",
                vaultManager: true, 
                venmo: {}, paypal: {flow: 'vault'}, paypalCredit: {flow: 'vault'},
              }, function (createErr, instance) { [...] })
</pre>

**Comment by crookedneighbor** [comment]
Please open a new issue on Drop-in's repo and we'll dig into it: https://github.com/braintree/braintree-web-drop-in

Drop-in uses version 3 of braintree-web, but is itself it's own product. Which is why it has a separate repo and version.

**Comment by tenshis** [comment]
> @crookedneighbor
> 
> Here is what I am doing to set the dropin up:
> 
> braintree.dropin.create({
>                 authorization: client_token_server,
>                 container: '#dropin-container', 
>                 venmo: {}, paypal: {flow: 'vault'}, paypalCredit: {flow: 'vault'},
>               }, function (createErr, instance) { [...] })
> Is there something I'm missing in the setup?

Did you manage to solve this?

**Comment by crookedneighbor** [comment]
I've been out of office. It's been added as a feature on master, but has not been released yet. Hoping to get a release out next week or so. 

https://github.com/braintree/braintree-web-drop-in/pull/675
