### ISSUE TITLE
Drop-in UI onError callback is not triggered with server-side validations

### ISSUE THREAD

**Issue by p4sh4** [braintree/braintree-web#159]
Although this has been raised a few times already (for example, https://github.com/braintree/braintree-web/issues/59), those issues have been closed without a resolution even though a lot of people confirmed that this is a serious problem.

Additionally, the lack of this functionality is quite surprising because it is described in the [documentation](https://developers.braintreepayments.com/guides/drop-in/javascript/v2#server-related-errors), giving false hope to developers and causing confusion when a documented feature doesn't work: 
> When a server-related error occurs, onError will fire with a SERVER type. For example, this occurs when the customer's browser cannot connect to Braintree or **when a card number fails server-side validation**.

**Comment by crookedneighbor** [comment]
@p4sh4 Can you confirm which version of the library you are using? The documentation says:

> Server-related errors are provided to onError in version 2.23.0+ of our JavaScript SDK.

So if you're using an earlier version, you will not see those server errors in the onError callback. If you are using version 2.23.0 or higher, can you give us a particular reproducible case?

**Comment by p4sh4** [comment]
Thanks for the fast reply @crookedneighbor, I was using 2.22.2 and didn't know this got fixed in the new version because it wasn't reflected in the #59 issue. Just tried 2.23.0, and and it does seem to work correctly at this point. Perfect timing of the release, thanks!

I think this issue can be closed now?

**Comment by crookedneighbor** [comment]
Yep, this can be closed. 

We've included a note in #59. Thanks for pointing that out!
