### ISSUE TITLE
Drop-in EXP field doesn't add / on android(chrome) and WP(8 and 10)

### ISSUE THREAD

**Issue by xuaninbox** [braintree/braintree-web#161]
**Update** for android we found out it's because of the custom keyboard we are using, we're wondering  if there's a way around this. The keyboard we are using during our test is called sogou, don't know why it's related to it but you can download if from the play store if you want to test it

**Update 2** we have invested further and found out that only certain 3rd party we cause this problem, example are sogou and baidu, swiftkey and some other keyboard works just fine. However on WP it's the stock keyboard

Drop-in EXP field doesn't add / on android(chrome) and WP(8 and 10). We have just noticed this problem during our test, It works fine on safari(iOS).

Also for the card no. and exp on both android and WP u can type beyond 16 or 6 digits.

![img_0265](https://cloud.githubusercontent.com/assets/5108256/14977138/42724d4c-10d7-11e6-900a-c869a50b2543.JPG)
![img_0266](https://cloud.githubusercontent.com/assets/5108256/14977139/428109f4-10d7-11e6-913f-57efa5659afd.PNG)

**Comment by mrak** [comment]
Thank you for the updates. We'll take a look.

We've historically disabled formatting for certain mobile browsers (Android FireFox) and not all keyboards report key events in the same way to the browser.

**Comment by xuaninbox** [comment]
Thanks a lot !

Do you think switch to hosted fields can avoid this problem or that may also depend on the keyboard.

Also any timeline on 3.0?

**Comment by mrak** [comment]
Hosted Fields does not currently have input formatting like Drop-in does, although you can specify separate fields for month and year inputs and avoid the mismanagement of the `/` character.

3.0 is a work in progress, and we don't have a definite ETA at this time.

**Comment by mrak** [comment]
We've released a beta of our next major version. Though we do not have Drop-in ready for the beta of v3, Hosted Fields now has field formatting.

Here are some links to our official documentation:

[Setup for v3](https://developers.braintreepayments.com/guides/client-sdk/setup/javascript/v3)
[Migrating from v2 to v3](https://developers.braintreepayments.com/guides/client-sdk/migration/javascript/v3)
[Hosted Fields demo in v3](https://developers.braintreepayments.com/guides/hosted-fields/overview/javascript/v3#demo)

**Comment by crookedneighbor** [comment]
Closing this now. Re-open if you have more questions.
