### ISSUE TITLE
Show clearer error message instead of "There was an error processing your request" 

### ISSUE THREAD

**Issue by maloneyp** [braintree/braintree-web#163]
When you enter a creditcard number which fails to pass credit card verification, then the drop-in ui shows an error which displays very little helpful information as to what the user did wrong: 

"There was an error processing your request."

I think it should give some details why it failed to process the request. Now it is unclear that we couldn't perform a transaction with the credit card the user specified, instead of for example an internal server error. It is now also unclear for the user how to proceed and resolve this issue.

Since the UI is full screen when adding a new payment method, there isn't really a good way for us to add such a description ourselves.It makes users feel like it is an issue with the merchants site rather than their own card or an issue Braintree's side.

**Comment by mrak** [comment]
Thanks for the feedback!

As of version `2.23.0` the `onError` callback should report server errors during tokenization such as these.

Unfortunately, this still won't help for the scenario you describe when they are adding another payment method in the full-screen modal. I'll pass it along to our design team.

Have you taken a look at our Hosted Fields solution? It is an SAQ A qualified alternative that will give you greater customizability.

**Comment by EvanHahn** [comment]
@maloneyp Do those changes to `onError` help?

**Comment by EvanHahn** [comment]
We're going to close this issue. Feel free to open a new issue or follow up here!

**Comment by thalesrm** [comment]
any updates here?

**Comment by crookedneighbor** [comment]
@thalesrm This issue is for an old version of the web SDK that is no longer receiving updates. Please upgrade to the latest version.
