### ISSUE TITLE
How to intercept event when PayPal popup was closed?

### ISSUE THREAD

**Issue by bocharsky-bw** [braintree/braintree-web#164]
I use [Custom UI](https://developers.braintreepayments.com/reference/client-reference/javascript/v2/best-practices#custom-ui) integration to make a custom button for pop-up window, which is disabled when PayPal popup is opened.

How can I intercept event when PayPal popup was closed by user (i.e. purchase is canceled) in order to enable my custom button?

**Comment by sornon1** [comment]
You can use the `onAuthorizationDismissed` callback documented [here](https://developers.braintreepayments.com/reference/client-reference/javascript/v2/paypal) to listen for that event.

**Comment by bocharsky-bw** [comment]
@sornon1 Thank you! I definitely missed it

**Comment by mrak** [comment]
Additionally, we've released a beta of our next major version. The popup flow of the PayPal component of this new version is invoked through a `.tokenize(callback)` method. The `callback` is executed with nonce details when the user completes the popup auth flow.

Here are some links to our official documentation:

[Setup for v3](https://developers.braintreepayments.com/guides/client-sdk/setup/javascript/v3)
[Migrating from v2 to v3](https://developers.braintreepayments.com/guides/client-sdk/migration/javascript/v3)
[Using PayPal in v3](https://developers.braintreepayments.com/guides/paypal/client-side/javascript/v3)
