### ISSUE TITLE
how to write the test code for setup function in jasmine framework.Plz help me

### ISSUE THREAD

**Issue by mac066** [braintree/braintree-web#165]

**Comment by mrak** [comment]
Could you provide some details about what you are trying to accomplish or what scenario you are testing?

**Comment by mac066** [comment]
i've integrated you braintree in angular now i want to test it. i've no idea of testing the onPaymentMethodReceived function. how can we test the complete flow of the braintree in jasmine?
i've made a service to integrate the braintree in angularjs framework

**Comment by mrak** [comment]
Closing as this does not seem to be an issue with this library, but a question of how to do testing with jasmine.

You most likely will not want to test the complete flow of braintree in unit testing. You can do behavioral-level tests and assert that you are calling `braintree.setup` with the proper options.

As an example, assume `app.start()` at some point calls `braintree.setup` with `myPaymentMethodReceivedCallback` as the function handler for `onPaymentMethodReceived`:

```javascript
describe('app.start', function () {
  it('calls braintree.setup with my payment method received handler', function () {
    spyOn(braintree, 'setup');

    app.start();

    expect(braintree.setup).toHaveBeenCalledWith(
      jasmine.any(String),
      jasmine.any(String),
      jasmine.objectContaining({
        onPaymentMethodReceived: myPaymentMethodReceivedCallback
      })
    );
  });
});
```

You would potentially test the functionality of `myPaymentMethodReceived` in it's own test cases.

If you are doing functional-level testing you will want to be using something like [webdriver.io](http://webdriver.io/) or [nightwatch.js](http://nightwatchjs.org/) (or [Capybara](http://jnicklas.github.io/capybara/), if you are inclined to use ruby) to test complete user flows.

**Comment by mac066** [comment]
thanks Eric, i've already done the behaviour level testing. i was just in
dilemma where to test the complete process or not.
once again thank you
Regard Sagar Shrestha
