### ISSUE TITLE
onCancelled not firing when calling closeAuthFlow in custom integration

### ISSUE THREAD

**Issue by paulozoom** [braintree/braintree-web#167]
Hi!

I’m rolling out my own UI on a payment form, with both Credit Card and PayPal options.

To let people opt to use PayPal, I have a button which, when clicked, brings up the auth flow, with `integration.paypal.initAuthFlow()`, and I take care of business in the `paypal.onSuccess` config. That’s all working fine.

However, I’m also trying to recreate the "Cancel" behaviour, if the user changes their minds. So, for that, I have another button, which, when clicked, calls `integration.paypal.closeAuthFlow()`, and I was hoping it to automatically remove the nonce that was automatically added, and then I could execute some code in `onCancelled` that would show the credit card field again.

However, `onCancelled` never fires is this circumstance.

Why is that? Am I misunderstanding what the `closeAuthFlow` method is for?

**Comment by paulozoom** [comment]
Here’s my code, if that helps in any case.

```js
$('form.js-payments').each(function () {
  
  var $form = $(this);
      
  braintree.setup($form.data('braintree-client-token'), 'custom', {
    id: $form.attr('id'),
    onReady: function (integration) {
      // Save the integration
      window.App.braintreeCheckout = integration;
    },
    paypal: {
      headless: true,
      onSuccess: function (nonce, email) {
        // Hide Credit Card fields
        $form.find('.js-payments-cc').hide().find(':input').attr('disabled', 'disabled');
        // Show PayPal Fields
        $form.find('.js-payments-paypal').show();
        // Add the email to readonly field
        $form.find('.js-payments-paypal-email').val(email);
        // Hide the “Use PayPal” button
        $form.find('.js-payments-auth-paypal').hide();
      },
      onCancelled: function() {
        // THIS NEVER GETS TO RUN
        $form.find('.js-payments-paypal').show();
        $form.find('.js-payments-cc').hide();
        $form.find('.js-payments-cancel-paypal').show();
      }
    }    
  });

}).on('click', '.js-payments-auth-paypal', function (event) {
  // Show the PayPal auth flow
  if (window.App.braintreeCheckout) {
    event.preventDefault();
    window.App.braintreeCheckout.paypal.initAuthFlow();
  }
}).on('click', '.js-payments-cancel-paypal', function (event) {
  // Close the PayPal auth flow
  if (window.App.braintreeCheckout) {
    event.preventDefault();
    window.App.braintreeCheckout.paypal.closeAuthFlow();
  }
})
```

**Comment by lilaconlee** [comment]
@paulozoom, `closeAuthFlow()` is intended to give you a handle on the PayPal flow itself, allowing you to programmatically end the flow. The `onCancelled` callback is only called when the `Cancel` button is actually clicked, which is not rendered when in `headless` mode. 

It sounds like you want to use the `onAuthorizationDismissed` callback, which is called whenever the PayPal flow is closed before successful completion, including `closeAuthFlow()`. This should allow you to show your credit card fields whenever a PayPal flow is cancelled, regardless of the method of cancellation.

**Comment by paulozoom** [comment]
@lilaconlee: I don’t want to do that. I want to, after a *successful* completion of the PayPal flow, let users go back to the Credit Card option. Basically, replicate the functionality available in the drop-in. I can show them the fields again myself, but as the PayPal flow was successful, the `integration`’s internal state will let users go ahead with the payment, because a payment method was received.

Is there any method I can call on the integration to "reset" it, so that I can let users go back to credit card after completing the paypal auth?

**Comment by lilaconlee** [comment]
Gotcha, thanks for the clarification! If you call `window.App.braintreeCheckout.teardown()` when the cancel button is pressed, you will teardown your integration and it will no longer exist on your page. You should then be able to setup your integration again as if the initial flow never occurred. 

Checkout the [teardown docs](https://developers.braintreepayments.com/reference/client-reference/javascript/v2/best-practices#teardown) for more details. 

The latest version of our JS SDK (which is still in beta) would make the behavior you're looking for much easier. Your PayPal button and credit card form would be completely separate entities, meaning you would not have to teardown your entire integration to get your desired result. If you're interested, you should check out the new [PayPal guide](https://developers.braintreepayments.com/guides/paypal/client-side/javascript/v3) and our [documentation of direct credit card tokenization](https://braintree.github.io/braintree-web/3.0.0-beta.7/Client.html#request).

**Comment by paulozoom** [comment]
@lilaconlee Thanks!
