### ISSUE TITLE
Try Again button for drop-in UI is hard to click

### ISSUE THREAD

**Issue by waleedasif322** [braintree/braintree-web#172]
If a person enters a second payment method with invalid info, a popup appears. The popup shows an error with a 'try again' button which is hard to tap (I'm using this in a web-view/cordova project). 

Solution is to make it an actual button instead of just text?
EDIT:
This actually goes for all text-only links, I think they should be changed to buttons styles. Especially since you guys won't support cordova/phonegap, this is the least you can do.

**Comment by lilaconlee** [comment]
@waleedasif322 While we definitely understand your use case, we have largely stopped development on the current version of Drop-in in JS SDK. We will definitely keep ease of use for native mobile apps in mind while working on the next version of Drop-in.

For a more customizable experience (which might be preferable for you considering Drop-in is not optimized for native mobile apps), we recommend using [Hosted Fields](https://developers.braintreepayments.com/guides/hosted-fields/overview/javascript/v2) with [PayPal](https://developers.braintreepayments.com/guides/paypal/client-side/javascript/v2).
