### ISSUE TITLE
Popups not supported

### ISSUE THREAD

**Issue by zwarmapapa** [braintree/braintree-web#173]
Hi, I'm using the JS dropin in a Unreal Engine 4 web browser widget. 

The credit card option works fine, but the Paypal option creates a popup which can't be rendered in the engine. 

Is there a way to use something else, like an iframe, instead?

**Comment by lilaconlee** [comment]
@zwarmapapa For security reasons, the PayPal flow is rendered in a popup in desktop browsers.

Sorry for any inconvenience that may cause.
