### ISSUE TITLE
Un-minified version?

### ISSUE THREAD

**Issue by marcucio** [braintree/braintree-web#174]
Where can I find the un-minified version? My build scripts are having trouble with this version and I would like to minify and uglify myself.

**Comment by lilaconlee** [comment]
For v2, you can find an unminified version of `braintree.js` at `https://js.braintreegateway.com/js/braintree-<VERSION>.js`, such as https://js.braintreegateway.com/js/braintree-2.25.0.js. 

For v3, you can find unminified versions of components at `https://js.braintreegateway.com/web/<VERSION>/js/<COMPONENT>.js` such as https://js.braintreegateway.com/web/3.0.0-beta.9/js/client.js. Just as a warning, using unminified code in v3 means all assets we host in iframes or popups will also be unminified.

**Comment by marcucio** [comment]
thanks!
