### ISSUE TITLE
Expiration Date validation is no longer correct in beta 10

### ISSUE THREAD

**Issue by FutureGUIs** [braintree/braintree-web#178]
The expiration validation is no longer catching dates in the current year prior to the current month as invalid dates.  For example this month is July, so entering 04/2016 should be invalid, but isn't.

**Comment by lilaconlee** [comment]
Thanks for catching this! We'll update you here when we've deployed a fix.

**Comment by FutureGUIs** [comment]
Looks good in Beta 11 now.

**Comment by crookedneighbor** [comment]
Great, thanks for following up!
