### ISSUE TITLE
setup() with different user

### ISSUE THREAD

**Issue by jeffhoye** [braintree/braintree-web#18]
If you call this a 2nd time, with a different user's token, it still keeps the first user: 
```
braintree.setup(token, "dropin", { ... });
```

In our scenario, a user is about to pay, but realizes that they are logged in as the wrong account (such as another family member's account who uses the same browser).
The user re-authorizes the alternate account and gets a new token, but a 2nd call to braintree.setup() with a different user's token still keeps the first payer's cards active!  Worse, the transaction succeeds!!!  In other words, "Account B" is able to pay with "Account A's" card even though the token is from a "Account B" .

Is there any way to reset braintree?  I'm willing to try something outside the box such as reloading braintree.js.  

Interestingly, we can pay twice with the same user using different tokens w/o reloading.  It's just the user info that doesn't seem to update after calling setup().

Notes:
I can only verify that this is a problem with the dropin and in the sandbox.
This is within a Cordova app, so it's not convenient to just reload the whole page.

**Comment by jeffcarp** [comment]
@jeffhoye thanks for bringing this up - as you discovered, the behavior of `braintree.setup` after the first call is unspecified (which means we could do a better job by making it idempotent, or at least guarding against the scenario you described).

I'm not sure what exactly is causing this, but I don't think it's a good idea to call `braintree.setup` twice even if there is a way to get it working. We don't test for this scenario and a future release could break it.

As for a resolution to your problem, other than doing an entire page reload, you could try your suggestion of reloading braintree.js after `delete window.braintree` and clearing the cookies set by Drop-In.

Other than that, I'm out of ideas. Some kinks might need to be ironed out before braintree.js can play nicely in a single-page-app paradigm.

**Comment by tnunes** [comment]
We found a way to do it that I described here: https://github.com/braintree/braintree-web/issues/29#issuecomment-103986438

I hope that braintree will eventually support this internally, but at the moment you can try to cleanup its scripts, variables and event handlers in order to reload the widget and call `setup()` again with different parameters.

**Comment by kyledetella** [comment]
@jeffhoye @tnunes as per #43 and #29, you can now call `braintree.setup` more than once during a page load by using the new `teardown` feature. This functionality is officially supported as of the [latest release](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#2140). Let us know if you run into any issues.
