### ISSUE TITLE
CVV format

### ISSUE THREAD

**Issue by zambrevishal** [braintree/braintree-web#181]
Hello,

I'm using ```<script src="https://js.braintreegateway.com/web/3.0.0-beta.10/js/hosted-fields.min.js"></script>``` this client sdk.

Current cvv is visible and can copy and paste, I want to disable cut, copy and paste and also want to change cvv format like password(***). 

Can anyone please help me in this.

**Comment by zambrevishal** [comment]
@mrak Is there any way to bind copy and paste events to that fields so that I can disable it.

**Comment by mrak** [comment]
No, there is not a way to bind copy/paste events to the inputs within hosted fields.

**Comment by crookedneighbor** [comment]
@zambrevishal v3.2.0 allows you to specify type for Hosted Fields inputs. So to mark your CVV as a password input, you'd do:

```js
braintree.hostedFields.create({
  client: clientInstance,
  styles: {
     // your styles
  },
  fields: {
    cvv: {
      selector: '#cvv',
      placeholder: '•••',
      type: 'password'
    },
    // other fields
  }
}, callback);
```

**Comment by zambrevishal** [comment]
@crookedneighbor  Thanks
