### ISSUE TITLE
Paypal button href attribute

### ISSUE THREAD

**Issue by defra91** [braintree/braintree-web#183]
Hello guys!

I am facing a problem from few hours. Basically I am using `braintree-web` to implement payments on my **angular** app. Here is the code that I'm using:

```
braintree.setup(clientToken, 'custom', {
  paypal: {
    container: 'paypal-container-subscription',
    billingAgreementDescription: 'Lorem ipsum',
    singleUse: false,
  },
  dataCollector: {
    paypal: true,
  },
  onPaymentMethodReceived: onPaymentMethodReceivedForSubscription,
});
```
Once braintree is setup paypal button is something like:

```
<a id="braintree-paypal-button" href="#" style="display: block; width: 115px; height: 44px; overflow: hidden;">
<img src="https://checkout.paypal.com/pwpp/2.26.0/images/pay-with-paypal.png" alt="Pay with PayPal" style="max-width: 100%; display: block; width: 100%; height: 100%; outline: none; border: 0px;"></a>
```

The probem is the `href` attribute, which will redirect me to my home page. Could you help me to figure out how to solve it?

**Comment by crookedneighbor** [comment]
My best guess here is that you have some kind of Angular router that is automatically converting any `href` attributes. To get around this, you can specify your [own PayPal button](https://developers.braintreepayments.com/reference/client-reference/javascript/v2/best-practices#custom-ui).

Something like this should work:

```html
<div id="paypal-container-subscription">
  <button id="paypal-button" class="special-class-to-style-button">PayPal</button>
</div>
```

```js
var btIntegration;

braintree.setup(clientToken, 'custom', {
  paypal: {
    headless: true,
    billingAgreementDescription: 'Lorem ipsum',
    singleUse: false,
  },
  onReady: function (integration) {
    btIntegration = integration;
  },
  dataCollector: {
    paypal: true,
  },
  onPaymentMethodReceived: onPaymentMethodReceivedForSubscription,
});

// Add a click event listener to your own PayPal button
// Note: cross-browser compatibility for click handlers and events are up to you
document.querySelector('#paypal-button').addEventListener('click', function (event) {
  event.preventDefault();
  btIntegration.paypal.initAuthFlow();
}, false);

**Comment by legendac** [comment]
Hi there. I am having the same issue with Ember.js, and got redirected to the home page as well.

I am using the JS V3 of Hosted Fields this time round.  Could you help to point me in the right direction for my case?

Appreciate lots! Thank you in advance!

**Comment by crookedneighbor** [comment]
@legendac Seems unlikely to me that it is the same issue. Please open up a new issue and include a code sample so we can reproduce it.
