### ISSUE TITLE
onChangePaymentMethod

### ISSUE THREAD

**Issue by Josenzo** [braintree/braintree-web#184]
Why is not implemented onChangePlan that is dispatched when an user change the plan on drop-in payment UI. Would be useful to avoid the extra click for the user to confirm/update the payment method.

**Comment by crookedneighbor** [comment]
Could you provide more information about what you are asking for? What do you mean by `onChangePlan`? Are you referring to when a user clicks the "Change Payment Method" link?

**Comment by Josenzo** [comment]
I'm sorry in my comment when I say Plan I wanted to say Payment Method. Let me explain myself better.

In this case, by default I have selected PayPal:
<img width="393" alt="screen shot 2016-07-22 at 10 56 02" src="https://cloud.githubusercontent.com/assets/1819888/17045317/fda2def8-4ffa-11e6-95c6-409093417e07.png">

If I click on MasterCard for example, there is no event that tells developers another Payment Method it's been selected.

It would be great something like `onChangePaymentMethod` or `onSelectedPaymentMethod`.
Why is so useful? It tell us when we have to show the `Update Payment Method` button
<img width="606" alt="screen shot 2016-07-22 at 11 05 10" src="https://cloud.githubusercontent.com/assets/1819888/17045520/8019474a-4ffc-11e6-985a-b3f18e7e86d2.png">

I only would show `Use this payment method` button when the event `onChangePaymentMethod` is triggered.

And event better. I don't need to show that button if the event pass `payload.nonce` as argument. And then we avoid and extra click from the user.

**Comment by crookedneighbor** [comment]
Thanks for the explanation.

At this time we're not planning to add any new lifecycle hooks to the current version of Drop-In. However, we're currently working on Drop-In for [version 3 (currently in beta) of braintree-web](https://github.com/braintree/braintree-web/tree/3.x-beta) and we'll consider this suggestion while we work on it.

**Comment by dpolivy** [comment]
:+1: I agree, it would be helpful to have something like `onChangePaymentMethod` for the drop-in UI that could signal the nonce needs to be re-generated.

Any timeframe for the existing drop-in to be added to v3?

**Comment by lilaconlee** [comment]
At the moment, there is no timeline for a full Drop-in UI to be available. It is actively in development and will have a beta available relatively soon.

However, it should be noted that we are doing a refresh of the Drop-in UI, which means it will have a new UI with revised features. The existing version of Drop-in will not be part of v3.

**Comment by lilaconlee** [comment]
An update on this issue: with the [new version of Drop-in](https://developers.braintreepayments.com/guides/drop-in/javascript/v3), there are `paymentMethodRequestable` events fired when you can request a payment method and receive a new nonce. Check out the [events section of our developer docs](https://developers.braintreepayments.com/guides/drop-in/javascript/v3#events) for more information.

**Comment by pootzko** [comment]
I would argue that having an additional event for "payment method changed" would still be useful. Please see the [issue](https://github.com/braintree/braintree-web-drop-in/issues/211) I opened in the drop-in repo.
