### ISSUE TITLE
when will braintree be supporting apple pay for web?

### ISSUE THREAD

**Issue by owen26** [braintree/braintree-web#185]
Apple pay for web is still in beta at the moment, just wondering if braintree has plan to support it in future.

**Comment by crookedneighbor** [comment]
We're working on supporting Apple Pay for Web in [version 3](https://github.com/braintree/braintree-web/tree/3.x-beta) of braintree-web (currently in beta).

We'll add a comment here when the Apple Pay for Web component is released and ready to beta test.

**Comment by intelliot** [comment]
Although Apple Pay on the Web is not yet available, we have included support for it in version 3.0.0-beta.12 of our JS SDK. To plan for your integration, you can have a look at the Apple Pay component in this beta release: https://groups.google.com/forum/#!topic/braintree-sdk-announce/1qDlkkB3G-Q

For more information, and to join the pre-launch list for this new payment experience, please contact service-applepay@getbraintree.com

Thanks for your interest!

**Comment by crookedneighbor** [comment]
Version 3 of braintree.js is now on master and it includes an [ApplePay component in beta](http://braintree.github.io/braintree-web/current/module-braintree-web_apple-pay.html).
