### ISSUE TITLE
As a developer, I would like to be able to read a comprehensive API reference, so that I can learn about the API on a single page

### ISSUE THREAD

**Issue by messageagency** [braintree/braintree-web#186]
As a developer, I would like to be able to reference a comprehensive spec for the JS API, so that I don't have to read through narratives and tutorials, and navigate to a handful of different pages to learn Braintree's API.

I've been searching for a single, comprehensive reference for the Braintree javascript API and as far as I can tell it simply doesn't exist. Documentation for various methods and options are scattered across at least a dozen different pages.

[Google Maps' API documentation](https://developers.google.com/maps/documentation/javascript/reference) provides a stellar example of a comprehensive reference spec.

**Comment by crookedneighbor** [comment]
Thanks for your feedback. We have a collection for reference docs for version 2 of the JS API [here](https://developers.braintreepayments.com/reference/client-reference/javascript/v2/best-practices).

For version 3 (currently in beta), we have more of what you are looking for. You can [view it here](http://braintree.github.io/braintree-web/current/).

We have no plans to change how we present the documentation for version 2, so I'm going to close this now.

If you'd like to join the public beta for version 3, you can [go here for instructions](https://developers.braintreepayments.com/guides/client-sdk/setup/javascript/v3).
