### ISSUE TITLE
DropIn accepts credit cards payments that are not enable in our merchant account

### ISSUE THREAD

**Issue by gertjvr** [braintree/braintree-web#187]
We had a issue over the weekend where someone tried using there amex rather than visa the DropIn-UI accepted / validated there card but it only failed server side. Is there away to configure the dropin ui to not accept specific cards?

**Comment by mrak** [comment]
Unfortunately, Drop-in does not have the ability to reject specific card networks.

If you use the `onPaymentMethodReceived` callback, you can see the card network entered by the user under `details.cardType` and advise the user to enter a different payment method.

```javascript
braintree.setup(TOKEN, 'dropin', {
  onPaymentMethodReceived: function (payload) {
    if (payload.details.cardType === 'American Express') {
      showAmexNotAccepted();
    }
  }
});
```

**Comment by brett-mildwaters** [comment]
Hi Eric, thank you for your response - would you please add this capability ASAP?  It has caused a very poor customer experience where the customer is only informed that the card type they tried is not accepted AFTER going through the full payment process - it would be a significantly better customer experience for the Drop-In to advise the customer as soon as the customer starts to enter their card based on the first 4 numbers being entered - before the customer attempts to process the payment.

**Comment by mrak** [comment]
While we won't be adding this feature to the current iteration of Drop-in, this is an oft-requested feature that we're considering for the next version.

**Comment by skunkworks** [comment]
Hi, we are planning on adding this feature to Drop-in. We will keep this GitHub issue updated when we can commit to a specific release date.

**Comment by lilaconlee** [comment]
Quick update on this issue, the [new version of Drop-in](https://developers.braintreepayments.com/guides/drop-in/javascript/v3) shows your accepted card type icons in the UI and will not accept numbers of card types not enabled in your merchant account.
