### ISSUE TITLE
Processor declined test cards are successful with beta 3 js

### ISSUE THREAD

**Issue by msencenb** [braintree/braintree-web#188]
I've just finished up integrating the beta 3 version 11 javascript SDK, and want to test against processor declined credit cards.

Using [these credit cards](https://developers.braintreepayments.com/reference/general/testing/php) returns both a valid token, and ends up being successful when I charge it on the backend with the PHP sdk. Are there new invalid cards to be used for testing with the beta 3 version 11 SDK?

**Comment by crookedneighbor** [comment]
Those test cards ([direct link](https://developers.braintreepayments.com/reference/general/testing/php#unsuccessful-credit-card-verification)) are for testing [unsuccessful card verification responses](https://developers.braintreepayments.com/guides/credit-cards/server-side/php#verification-results), not unsuccessful transaction.

> The following credit card numbers will simulate an unsuccessful card verification response. Verifying a card is different than creating a transaction. To trigger an unsuccessful transaction, adjust the amount of the transaction.

Here are the [test amounts for unsuccessful transactions](https://developers.braintreepayments.com/reference/general/testing/php#test-amounts).

**Comment by msencenb** [comment]
Sorry about that. 

Dumb question on my part, and thank you for the links.

**Comment by crookedneighbor** [comment]
No worries, I have done the exact same thing in the past! We're working on improving the documentation around the test cards to make them less confusing.
