### ISSUE TITLE
Validate not allowed with tokenization key

### ISSUE THREAD

**Issue by dshiells** [braintree/braintree-web#193]
When I use the JS SDK v3.0.0 to get PayPal credentials we call `tokenize` with `flow: 'vault'` (as per the docs - https://developers.braintreepayments.com/guides/paypal/vault/javascript/v3).  However this adds an options key with `validate: true` caused by src/paypal/external/paypal.js line 253.

I believe this is just for cards, and should not be included for PayPal (which should already be validated by default, right?). As a result, I get the error back `Validate not allowed with tokenization key`.

Resorting back to v3 beta 11 fixed my issue, but it would be good to be fixed in the stable release.

**Comment by crookedneighbor** [comment]
Thanks @dshiells, we're aware of the issue and will be deploying a fix today. I'll update this issue once the deploy is complete.

**Comment by dshiells** [comment]
@crookedneighbor Thanks for getting back so quickly.

Possible one for the future, in your package.json you listed a beta release as the latest version. This meant when we installed via npm (`npm install braintree-web`) it installed a non-stable release by default, which is obviously susceptible to changes like you made in your beta, and hence break things in later deploys for developers (which happened to us).

Just thought as we had the issue others might also so would mention it.

**Comment by crookedneighbor** [comment]
This is fixed in `v3.0.1`.
