### ISSUE TITLE
Chrome: 'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M54.

### ISSUE THREAD

**Issue by milesich** [braintree/braintree-web#195]
While using hosted fields in v3.0.1 I am getting this warning in the console:

> 'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M54, around October 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.

Google Chrome Version 53.0.2785.46 beta (64-bit)

**Comment by crookedneighbor** [comment]
Thanks for reporting this. The place that uses this property is actually our restricted input module. I've opened an issue there: https://github.com/braintree/restricted-input/issues/6

You can follow the issue by pressing the subscribe button.
