### ISSUE TITLE
paymentMethodNonceReceived callback doesn't get a new nonce after submitting and re-entering number

### ISSUE THREAD

**Issue by aripollak** [braintree/braintree-web#20]
I'm using the following coffeescript setup code for the drop-in UI:
```coffee
      braintree.setup client_token, 'dropin',
        container: 'braintree-dropin',
        paymentMethodNonceReceived: (event, nonce) ->
          console.log event, nonce
```

`client_token` is a valid Braintree client token that's not associated with a Braintree customer. In the sandbox, if I enter in valid credit card information and submit the form with the `braintree-dropin`, then enter a different credit card and submit the same form, the same nonce gets used both times, which would then be rejected when submitting it to the Braintree server the second time during a customer create/update.
Is there a way of making this work? We do duplicate card checking on our side, which means that a user then might need to enter in a different card on the same form after being rejected.

**Comment by jeffcarp** [comment]
Hi @aripollak, since Drop-In was generally designed to be used once during the checkout / payment method update flow, I'm not sure if there's a way to use it twice. Would it be possible in your architecture to solve the problem by doing a full page reload? 

Something hacky that might also work would be removing the `#braintree-dropin` element from your DOM, re-adding it, and calling `braintree.setup` again. I'd highly recommend the full page reload route, though.

**Comment by aripollak** [comment]
We might end up needing to do a full page reload if this becomes a real problem, but currently we can't do that without more changes since reloading would lose the state of the current page.
I tried removing the dropin element and calling `setup` again, but the old event handlers still seem to be kept around, so submitting the form again ends up running the callback multiple times.

**Comment by jeffcarp** [comment]
Ok :/ sorry for leading you down the wrong path. I've replicated this and I'll try to see if there is a way to run with it.

**Comment by djhojd** [comment]
I'm experiencing the same problem, I would like to display success or error messages from payment process without reloading page, currently I receive "Cannot use a payment_method_nonce more than once." when trying to pay second time.

What we've end up doing is creating the form element and all children with JS and if payment was unsuccessful dumping it and recreating new one and start all over with braintree.setup. Maybe this helps you @aripollak.

**Comment by bkirkbri** [comment]
We experienced the same problem and found that reloading the page was our only recourse.

**Comment by cubicova17** [comment]
Same problem.

**Comment by imgntn** [comment]
definitely a problem... sigh

**Comment by jeffcarp** [comment]
Thanks everyone for chiming in! We're currently working on allowing Drop-in to support being submitted more than once per initialization. We will update this thread when the fix is deployed.

**Comment by ebaizel** [comment]
+1

**Comment by markadrianagbuya** [comment]
Same issue here.

**Comment by cwilkenloh** [comment]
Same issue. Is there a time frame for a fix?

Regarding the full page reload, is there a way to pre-populate the drop-in form with previously entered values?

**Comment by baillyje** [comment]
Quite same issue. 

I'm using the Drop-in UI.
If I use the 4000111111111115 visa card for sandbox test problem, I am unable to get another nonce if I enter directly another valid credit card code (like 4111111111111111) in a second time. The same nonce is always returned until I reload the page. 

I'm working on a Single page application, so reloading it's not a solution for me.

I confirm that removing the dropin element does not remove the old event handler.

Do you know how can I manage a user credit card problem without reloading the page ? 
Is there some kind of dropin reset process availlable somewhere ?

**Comment by tnunes** [comment]
@baillyje, until Braintree offers this out of the box, you can try to reset the widget by following the steps described in this comment https://github.com/braintree/braintree-web/issues/29#issuecomment-103986438

**Comment by baillyje** [comment]
@tnunes Thanks!

**Comment by kyledetella** [comment]
As of the recent [`2.7.4` release](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#274) you will receive a new nonce each time the user submits the form. This version has not been hotlinked yet but is available now via this repo, [bower](http://bower.io/search/?q=braintree-web), and [npm](https://www.npmjs.com/package/braintree-web).

**Comment by bkirkbri** [comment]
> you will receive a new nonce each time the user submits the form

That's great. How does this interact with `onPaymentMethodReceived` callbacks? Will our submission of the form from the callback be affected?

**Comment by kyledetella** [comment]
@bkirkbri if you are subscribe to `onPaymentMethodReceived` the form will [not be force-submitted](https://developers.braintreepayments.com/javascript+node/guides/drop-in#onpaymentmethodreceived) by `braintree.js` after a nonce has been generated.

> Will our submission of the form from the callback be affected?

Your submission should not be affected. Are you doing something like the following?

```javascript
braintree.setup(TOKEN, 'dropin', {
  container: 'my-container',
  onPaymentMethodReceived: function (payload) {
    // Manually submit your form with payload.nonce
  }
});
```

**Comment by bkirkbri** [comment]
> Are you doing something like the following? ...

Yes, we add `payload.nonce` to a form field, confirm with the user and then call `form.submit()`.

**Comment by kyledetella** [comment]
Ok, then yes, this will not affect that behavior. Let me know if you run into any issues.

**Comment by talofo** [comment]
Will this same thing work with hosted fields?

**Comment by kyledetella** [comment]
@talofo yes it will work the same way with Hosted Fields

**Comment by RikdeBoer** [comment]
I believe this problem has resurfaced or was not fixed in 3.3 ?
Using version 3.3 and the drop-in, a second submit on the form that holds the drop-in returns the previous nonce, even when payment details are different on second submit.
Shouldn't a new nonce be created automatically every time?

**Comment by RikdeBoer** [comment]
Same issue with the nonce used in 3D Secure:

```javascript
        function threeDResponseReceived(error, response)
        {
            if (error) {
                alert(error.message);
            }
            else 
            {
                insertNonceOnCheckoutForm(response.nonce);
            }
        }   
                 
        client.verify3DS(      
              { amount: 100, creditCard: nonce },
              threeDResponseReceived
        );
```

Also says that nonce cannot be used twice

**Comment by burnto** [comment]
@RikdeBoer thanks. The "re-tokenization" of a card form seems valid in the scenario you describe. As with other advanced use cases, it is supported with Hosted Fields. 

In the interest of maintaining API compatibility with current integrations, we do not intend to update Drop-in's behavior to support this card form re-tokenization use case.

**Comment by RikdeBoer** [comment]
Fair enough @burnto. Will take a closer look at Hosted Fields.
