### ISSUE TITLE
UnionPay IE9 error

### ISSUE THREAD

**Issue by bob2021** [braintree/braintree-web#200]
Hi, the Braintree EU Solutions team asked me to raise an issue here.

While testing the union pay integration in IE9 (9.0.8112.16421, update versions: 9.0.33), I received this error:

`Unable to get value of the property 'creditCards': object is null or undefined  unionpay-hosted-fields-internal.js, line 2292 character 7`

I am using version 3.0.1 of the sdk, my test script is below.  The error appears to occur when a tokenize attempt fails, in the example below I am forcing that to happen by using the sms code 999999, but I've also seen it happen due to invalid fields.

```html
<!DOCTYPE html>
<html>
<head>
    <script src="https://js.braintreegateway.com/web/3.0.1/js/client.min.js"></script>
    <script src="https://js.braintreegateway.com/web/3.0.1/js/unionpay.min.js"></script>
</head>
<body>

<div>Expected: "SMS verification code is incorrect. Please try again"</div>
<div>Got: <span id="result"></span></div>
<div id="error" style="font-family: monospace; white-space: pre;"></div>

<script>
    window.onerror = function(error){
        document.getElementById('error').innerHTML = 'An error occurred: ' + error;
    };

    var clientToken = 'CLIENT_AUTHORIZATION';

    braintree.client.create({
        authorization: clientToken
    }, function(err, clientInstance){
        braintree.unionpay.create({
            client: clientInstance
        }, function(err, unionpayInstance){
            unionpayInstance.enroll({
                card: {
                    number: '6212345678901232',
                    expirationMonth: '12',
                    expirationYear: '2038'
                },
                mobile: {
                    countryCode: '62',
                    number: '11111111111'
                }
            }, function(err, enrollPayload){
                unionpayInstance.tokenize({
                    card: {
                        number: '6212345678901232',
                        expirationMonth: '12',
                        expirationYear: '2038',
                        cvv: '123'
                    },
                    smsCode: '999999',
                    enrollmentId: enrollPayload.enrollmentId,
                    vault: true
                }, function(err, tokenizePayload){
                    document.getElementById('result').innerHTML = err.details.originalError.details.originalError.fieldErrors[0].fieldErrors[0].message;
                });
            });
        });
    });
</script>

</body>
</html>
```

**Comment by mrak** [comment]
Are you only seeing this happen in IE9?

**Comment by bob2021** [comment]
Yes, only IE9

**Comment by bob2021** [comment]
I just re-tested with version 3.0.2, the error is no longer thrown and the tokenize callback fires, but the error object in the callback is a generic network error:

```json
{
	"name": "BraintreeError",
	"code": "UNIONPAY_TOKENIZATION_NETWORK_ERROR",
	"message": "A tokenization network error occurred.",
	"type": "NETWORK",
	"details": {
		"originalError": {
			"name": "BraintreeError",
			"code": "CLIENT_GATEWAY_NETWORK",
			"message": "Cannot contact the gateway at this time.",
			"type": "NETWORK"
		}
	}
}
```

I think the change in 3.0.2 is related to this line: https://github.com/braintree/braintree-web/commit/a10a25db6d74f8e0846bf5b770190a2b10bd0fe6#diff-06631b7ce8673fe0daa016d69bcb4ca3L45 - there is a comment there that says `XDomainRequest does not report a body or status for errors` which seems to suggests that its not possible to get a full error response in IE9 if the server responds with a 4xx error - is that true?

**Comment by mrak** [comment]
@bob2021 Unfortunately it is impossible to get the response body or status code from error responses in IE9.

From Microsoft's documentation on the [onerror event](https://msdn.microsoft.com/en-us/library/ms536930(v=vs.85).aspx):

> ### Remarks
> The document can respond to the error, but there is no way to determine the cause or nature of the error.

Does the same request and scenario return full error details in newer browsers?

**Comment by bob2021** [comment]
From the browsers listed here: https://braintree.github.io/braintree-web/3.0.2/index.html only IE9 and IE10 support XDomainRequest, but IE10 uses XHR so it isn't affected.  

Full error details are returned in all the other browsers - only IE9 is affected.

This means that in IE9 it is not possible to show the customer specific error messages such as:

* The UnionPay Online Payment service hasn't been activated on your card. Please contact the card issuing bank to activate this service or use a different card
* SMS verification code is incorrect. Please try again

Though a generic error is generated so its still possible to ask the customer to retry.

I'll close this issue now as version 3.0.2 fixes the original error I was seeing, and there doesn't appear to be a simple workaround to get a full error response in IE9.

Thanks
