### ISSUE TITLE
ApplePay for web error

### ISSUE THREAD

**Issue by owen26** [braintree/braintree-web#201]
When I do `applePay.performValidation()` , the browser throw exception as below:

> Failed to load resource: the server responded with a status of 422
> https://api.sandbox.braintreegateway.com/merchants/stdg7bpqdhwdk2v6/client_api/v1/apple_pay_web/sessions

**Request**
```
{
    "_meta": {
        "merchantAppId": "192.168.1.10:3000",
        "platform": "web",
        "sdkVersion": "3.0.1",
        "source": "apple-pay",
        "integration": "custom",
        "integrationType": "custom",
        "sessionId": "322d18cb-9300-4ce0-abcf-5cef71608932"
    },
    "applePayWebSession": {
        "validationUrl": "https://cn-apple-pay-gateway.apple.com/paymentservices/startSession",
        "domainName": "192.168.1.10",
        "merchantIdentifier": "merchant.com.mycompany.iphone.sandbox",
        "displayName": "my display name"
    },
    "braintreeLibraryVersion": "braintree/web/3.0.1",
    "authorizationFingerprint": "***|created_at=2016-08-31T02:51:21.909332121+0000&merchant_id=***&public_key=***"
}

```

**Response**
```
{
    "error": {
        "message": "Unexpected validation URL"
    },
    "fieldErrors": []
}
```

I suspect it has something to do with the incompatibility for ApplePay China gateway, but I have no further ideas.

Braintree documentation for apple-pay-web is too simple to do further investigation.

**Update**

Just tried with a different sandbox account that pointing to:
> https://apple-pay-gateway-cert.apple.com/paymentservices/startSession

Response following:
```
{
    "error": {
        "message": "Apple Pay Web is not enabled for this merchant"
    },
    "fieldErrors": []
}
```

Does it have something to do with `"merchantAppId": "192.168.1.10:3000"` ?

**Comment by intelliot** [comment]
Hi @owen26 -

The error with a status of 422 is caused by the unexpected validation URL. We'll look into whether this is due to the China gateway.

The second error is likely due to your Braintree merchant not being enabled for Apple Pay on the Web. Apple Pay on the Web is currently in beta, and we are working directly with select merchants to ensure a smooth integration.

Please contact service-applepay@getbraintree.com with your Braintree merchant ID, and we'll help from there.

**Comment by owen26** [comment]
@intelliot 

Thank you for your assistant. I will make contact with service-applepay@getbraintree.com see if I can be SELECTED MERCHANT to make my project integration successful.

**Comment by estellehuang** [comment]
I have the same 422 issue. Do you resolve it successfully?

**Comment by estellehuang** [comment]
@owen26 

I have the same 422 issue. Do you resolve it successfully?

**Comment by crookedneighbor** [comment]
@estellehuang Please reach out to our support team for assistance with the details of the error you are seeing. https://developers.braintreepayments.com/forms/contact
