### ISSUE TITLE
PayPal authentication window freezes

### ISSUE THREAD

**Issue by Tyrdall** [braintree/braintree-web#202]
This issue occurs using the old Vault flow and js v2.27.0.
After adding the credentials and clicking on "Agree", the loading animation appears, but the window never closes. The PayPal account is added to the dropdown though.
I "fixed" it by downgrading the js file to 2.24.1.

**Comment by intelliot** [comment]
Hi @Tyrdall -

This bug should be fixed in version 2.28.0. For details, see https://groups.google.com/forum/#!topic/braintree-sdk-announce/yIY1teacxlc

Please let us know if the issue persists.

Thank you!
