### ISSUE TITLE
Typescript Type Definition

### ISSUE THREAD

**Issue by chlela** [braintree/braintree-web#206]
Please create Typescript type definition and host it on https://github.com/DefinitelyTyped/DefinitelyTyped

You can also learn more about Definitely typed here http://definitelytyped.org/

It would tremendously help Typescript developers using Braintree.

**Comment by EvanHahn** [comment]
This isn't something that's on our roadmap but we'll happily endorse an unofficial TypeScript definition!

Because we document everything with JSDoc, you might be able to use a tool like [jsdoc2tsd](https://github.com/englercj/tsd-jsdoc) to transform our JSDocs into `.d.ts` files, at least as a starting point.

**Comment by chlela** [comment]
Sounds good. Thank you for pointing out the tool, I'll check it out and will respond to this thread when I have something hosted

**Comment by chlela** [comment]
@EvanHahn I've created the typescript type definitions for v3.0.2. Feel free to review them https://github.com/chlela/DefinitelyTyped/blob/master/braintree-web/braintree-web.d.ts

I also took the examples from the documentation to test; you can view them
https://github.com/chlela/DefinitelyTyped/blob/master/braintree-web/braintree-web-tests.ts

**Comment by EvanHahn** [comment]
Looks cool. Feel free to open a PR on DefinitelyTyped and have them take a look.

**Comment by chlela** [comment]
Pull request merged.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/braintree-web/braintree-web.d.ts

Nuget package
https://www.nuget.org/packages/braintree-web.TypeScript.DefinitelyTyped/

NPM through typings
https://github.com/typings/typings

**Comment by maxisam** [comment]
probably should publish to npm @types with [https://github.com/Microsoft/types-publisher](https://github.com/Microsoft/types-publisher)

**Comment by simeyla** [comment]
Needs updating!

Missing lots of things now such as:
*  `authorization` in `HostedFieldFieldOptions`
* New PayPal client
* Vault manager (fetchPaymentMethods etc).
