### ISSUE TITLE
3.X paypal backdrop

### ISSUE THREAD

**Issue by maxisam** [braintree/braintree-web#208]
In 2.X, when Paypal window pops up, there is a backdrop for original window, so the whole thing looks like a modal popup. 

But in 3.X, this is gone. 

Any plan to get it back ? 

Thanks

**Comment by crookedneighbor** [comment]
With v3, we decided to remove as much pre-generated ui as possible. This means that you can add the backdrop yourself and make it look any way you want!

In v3.1.0, the [PayPal tokenize method](http://braintree.github.io/braintree-web/current/PayPal.html#tokenize) returns an object with two methods, `close` and `focus`. Calling `close` will close the popup and calling `focus` will bring it to the forefront.

Two caveats: 
  * iOS does not support the focus method.
  * Firefox requires the focus call to be done as the direct result of a user action (such as clicking a button).

Here's an example:

```js
var focusBtn = document.getElementById('focus-btn');
var paypalHandle = paypalInstance.tokenize({
    flow: 'vault' // Required
    // Any other tokenization options
  }, function (tokenizeErr, payload) {
  // your tokenize logic
});

focusBtn.addEventListener('click', function () {
  paypalHandle.focus();
});
```

**Comment by clintonb** [comment]
@crookedneighbor how can we replicate the old behavior? My primary motivation for using Braintree is to interface with Paypal in a clean manner. Presently, in Chrome, the Paypal login window appears _behind_ my checkout window (although it works for Firefox and iOS). This is a non-starter for me.

**Comment by crookedneighbor** [comment]
Why does it appear behind your checkout window? It should open a new window in front. Can you provide a repo that reproduces the behavior?

**Comment by crookedneighbor** [comment]
@clintonb You may also be interested in using the `paypal-checkout` component instead, which is built to be used with PayPal's checkout.js library to handle all the UI. http://braintree.github.io/braintree-web/current/module-braintree-web_paypal-checkout.html

**Comment by clintonb** [comment]
@crookedneighbor thanks for the _speedy_ reply! Our payment form was being too "smart". Despite not using a credit card, clicking the Paypal button kicked off form validation, screwing up focus. I'm all set. Thanks!
