### ISSUE TITLE
Callback function of tokenizeCard it's not called 

### ISSUE THREAD

**Issue by OscarRPR** [braintree/braintree-web#21]
I been integrating Braintree with my application and I found a problem. I need to use the method tokenizeCard but it seems the callback it's not called and I don't understand why.

    function buyNow() {
    	var token = getSessionVarFromView('client_token_braintree');
    	console.error(token);
        var client = new braintree.api.Client({clientToken: token});
        client.tokenizeCard({number: "4111111111111111", expirationDate: "10/20"}, function (err, nonce) {
    	    console.error("On tokenize card");
    	});
    }

The method buyNow it's called after the user presses buy. The method to generate my client token in the server is:

	Braintree_Configuration::environment('sandbox');
	Braintree_Configuration::merchantId('merchantId');
	Braintree_Configuration::publicKey('publicKey');
	Braintree_Configuration::privateKey('privateKey');	

	$clientToken = Braintree_ClientToken::generate();
	return $clientToken;

After this, the callback function of tokenizeCard never gets called.

I hope you can help me

Thank you

**Comment by kyledetella** [comment]
@OscarRPR it looks like you got an answer on [StackOverflow](http://stackoverflow.com/questions/28526584/callback-function-of-tokenizecard-its-not-called-on-braintree) from a Braintree developer. I am going to close this, but let me know if you run into anything else.
