### ISSUE TITLE
Feature request: support gulp-inject

### ISSUE THREAD

**Issue by lbehnke** [braintree/braintree-web#211]
As a follow-up of #210 and #194 I'd like to request a better bower / gulp-inject integration. 
Currently, the following JHipster workflow does not work:

    $ bower install braintree-web --save
    $ gulp inject

The injected `index.js` breaks the build.

*UPDATE* Please refer to #210 for details about the gulpfile.js file.

**Comment by crookedneighbor** [comment]
Thanks for the request, we're looking into it.

**Comment by mrak** [comment]
We have released version `3.3.0`, where the `index.js` file is a full UMD bundle of all of the components, ready to use in the browser.

Thanks for reporting!

**Comment by lbehnke** [comment]
Thanks for resolving the issue!
