### ISSUE TITLE
Braintree Javascript v3 SDK documentation missing DataCollector information

### ISSUE THREAD

**Issue by reidcooper** [braintree/braintree-web#214]
https://developers.braintreepayments.com/guides/advanced-fraud-tools/client-side/javascript/v3

Due to the upgrade from v2 to v3, the documentation in v3 (in the link above) does not state that the user has to provide a gatewayConfiguration configuration in the client creation as such (an example given): 

```
gatewayConfiguration: {
        environment: this.bt_preferred_server,
        kount: {
          kountMerchantId: this.bt_preferred_kount_merchant_id
        }
      }
```

You can find this out that it is required by reading the source code of the data-collectior (https://braintree.github.io/braintree-web/3.2.0/data-collector_index.js.html) on line 108.

Request to update the Javascript v3 SDK documentation for future reference.

**Comment by crookedneighbor** [comment]
That configuration is not provided when creating the client. That information is pulled directly from the Braintree gateway, which means your Kount id has to be configured in the Braintree gateway by one of our support team members. 

V2 allowed you to pass in the kount id yourself, but V3 requires you to have it enabled by Braintree support. (as a security precaution to make sure everything is set up correctly for use with Braintree)

We'll update the documentation link you provided to make this more clear.

**Comment by lilaconlee** [comment]
Closing this issue, as we've updated our [DataCollector documentation](http://braintree.github.io/braintree-web/current/DataCollector.html). Hope this helps!
