### ISSUE TITLE
2.5.0 broke us in the wild

### ISSUE THREAD

**Issue by robertmeta** [braintree/braintree-web#22]
We haven't yet tracked down the cause, we instantly rolled back to tag 2.3.3 because it was stopping our customers from placing non-CC orders.  I will update once I have more details on the specifics.  This ticket is mostly as a note to others who might hit breakage.   

For anyone else looking for a quick fix, 2.3.3 can referenced at https://js.braintreegateway.com/js/braintree-2.3.3.min.js (thanks @jeffcarp)

**Comment by jeffcarp** [comment]
If you're going to pin a hotlinked script, use this link (not the raw github one or you'll be rate limited): https://js.braintreegateway.com/js/braintree-2.3.3.min.js

@robertmeta do you have any more details about what is breaking?

**Comment by robertmeta** [comment]
@jeffcarp Not yet (first time I have ever looked at this code), it appears some work was done to avoid sending the requests to BT when it was either "Cash" or "Pay In Person" (which could be CC in person at location).  When we updated to 2.5.0 -- the form was always being submitted to BT, but obviously when cash or pay in person, all the fields were blank.  BT would sensibly return an error and we would ungracefully just stare at our users blankly.

**Comment by robertmeta** [comment]
@jeffcarp Paypal.

**Comment by jeffcarp** [comment]
Thanks for the info. Let me know if you find out more. Were you using the nonce received callback?

**Comment by kyledetella** [comment]
@robertmeta are you using a 'custom' integration or 'paypal'?

**Comment by robertmeta** [comment]
Simple custom integration.

**Comment by kyledetella** [comment]
Sorry, I am having trouble understanding what the exact issue is. What I think you are saying is before upgrading to 2.5.0 the form did not submit when the fields were empty and that was desired behavior on your end. Is that correct?

**Comment by kyledetella** [comment]
Ok, could you maybe share a snippet of your integration code (braintree.setup)?

**Comment by robertmeta** [comment]
Basically, as simple as can be: braintree.setup("{CLIENT_TOKEN}", "custom", {id: "formCheckout"});

**Comment by mirago** [comment]
Hi, we are having the same issue. Same simple custom integration as @robertmeta . We are getting braintree error When there are empty CC field.  something as "Payment cannot be processed at this time" can not really recall exactly.  And the form will not submit with that error.  I can see it is a json response with errors, however I can't seem to find a way how to show them to the user.
Had to rollback to 2.3.3 as well.

**Comment by geniiweb** [comment]
Same here, I already contacted the support and they requested the form and merchant id to test

**Comment by kyledetella** [comment]
@robertmeta @mirago @geniiweb We have deployed a fix as version `2.5.1` that will allow you to submit the form with empty credit card fields in a custom integration. Let me know if you run into any further issues.

**Comment by robertmeta** [comment]
@kyledetella thanks!

**Comment by jeffcarp** [comment]
Looks like this can be closed. Please yell if you're still experiencing issues related to this.
