### ISSUE TITLE
How to implement in cordova android app

### ISSUE THREAD

**Issue by subhash8108** [braintree/braintree-web#220]
Hello,

How to implement brainree-web in cordova android app, Please give me a suggetion, this plugin suitable? for cordova payment gateway.

Thank & Regards
Subhash Patel

**Comment by mrak** [comment]
Our JavaScript SDK is neither tested nor developed for hybrid runtimes such as Cordova, PhoneGap, Ionic, React Native, and Electron. While some success may be had in such environments, our SDK is optimized for the browser and its security policies and may not function correctly outside of them.
