### ISSUE TITLE
Allow typing slash when entering dates

### ISSUE THREAD

**Issue by armandn** [braintree/braintree-web#221]
Currently it's not possible to enter dates like 1/2018 - the slash is ignored and the result comes as 12/018.
_Of course_ users should type the leading zero so the date is 01/2018, but can they be expected to? I see there were other issues with people not realizing this behavior.

My proposal is simple - allow users to enter slashes (at least on desktops, if "tel" input doesn't allow slashes on mobile), so if someone enters "1/", this is automatically converted to "01/"

Thank you.

**Comment by mrak** [comment]
It would be a nice enhancement to intelligently prefix a zero for when `1/` is typed.

In the meantime, we have found in our UX testing that using placeholders or other visual cues like 

`MM / YYYY` or `MM / YY`

greatly reduced user input errors and seemed to set expectations properly for the formatting of the month.

**Comment by lilaconlee** [comment]
We've added this behavior as part of [3.16.0](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#3160). Thanks for the feedback!
