### ISSUE TITLE
Error in 3DSecure

### ISSUE THREAD

**Issue by ElenaMelashchenko** [braintree/braintree-web#222]
Hi guys,
I updated braintree library to 3.3.0 version ( to latest one ) and I faced with the next problem, maybe you can advice what better to do ?
We have protocol "file:" in phonegap application and when we are making query to 3DSecure - we are receiving next error code : THREEDS_HTTPS_REQUIRED. Is it possible somehow get round this problem?

**Comment by crookedneighbor** [comment]
Phonegap is not a supported platform for the SDK. From our [documentation](http://braintree.github.io/braintree-web/current/): 

> `braintree.js` is neither tested nor developed for hybrid runtimes such as Cordova, PhoneGap, Ionic, React Native, and Electron. While some success may be had in such environments, our SDK is optimized for the browser and its security policies and may not function correctly outside of them.
