### ISSUE TITLE
Handling `Destructor is already tearing down` in application

### ISSUE THREAD

**Issue by zemlanin** [braintree/braintree-web#224]
Can application code depend on [`'Destructor is already tearing down'`](https://github.com/braintree/braintree-web/blob/801c3fbebdf0f401965426980db4a72cceb81e95/src/lib/destructor.js#L19) message or its text can be changed in future?

Right now, to avoid duplicating `hostedFields.teardown` calls, we use our own `_isTearingDown`-like variable. But it'll be better to just catch lib's error

**Comment by skunkworks** [comment]
Hi @zemlanin,

Although it's highly unlikely, it's possible that the error message may change in the future, so I would not rely on it to catch teardown exceptions. Your current approach of using your own `isTearingDown` state variable is a good approach, or you could wrap the call to teardown in a try/catch and ignore it (although -- personal opinion! -- I like that approach less).

**Comment by skunkworks** [comment]
@zemlanin To follow up on this issue, we have added a work item to change the teardown method to throw a `BraintreeError` rather than a plain `Error` object. Thanks for opening this issue.

**Comment by zemlanin** [comment]
Yeah, ignoring all possible errors is no good… Ok, thanks for quick response
