### ISSUE TITLE
Server return 404 when tokenize for Apple Pay

### ISSUE THREAD

**Issue by xuaninbox** [braintree/braintree-web#225]
When we're implementing Apply Pay, we got a 404 on **applePayInstance.tokenize** 

<img width="560" alt="1" src="https://cloud.githubusercontent.com/assets/5108256/19670705/0834a558-9a2f-11e6-9ed1-2f48a8d7332b.png">

here's the endpoint that return the 404:

**https://api.braintreegateway.com/merchants/MERCHANT_ID/client_api/v1/payment_methods/apple_payment_tokens**

We have no issue with the **onvalidatemerchant** and **ApplePaySession**
We have print out the request as well and it seems correct, I can provide them if needed.

Thanks!

**Comment by crookedneighbor** [comment]
What version of braintree-web are you using? If you're not using the latest version, can you try upgrading to the latest version (v3.5.0)?

**Comment by xuaninbox** [comment]
Yes, we're using the latest v3.5, and its in production env.

Live demo: https://www.tixora.com/checkout?event_id=E160214&tickets=%7B%22T00001%22:0,%22T00002%22:1%7D

You can try to check out with Apple Pay and see if it present the same error. Even though it's in production, the payment nonce currently is not being submitted in any way (for apply pay only) so it's safe to pay around with.

One thing to note is for legacy reasons, we're using v3.5 in an iframe and v2.x in the main site so we don't have to change our current implementation, but I don't think this is the cause as we have tried to checkout with the iframe page alone and it still give back the same error.

**Comment by crookedneighbor** [comment]
I'm still trying to figure out why this isn't working. To confirm, you've gone through the entire setup process here outlined here? https://developers.braintreepayments.com/guides/apple-pay/overview

**Comment by xuaninbox** [comment]
Yeah we did, except the submitting csr to apple which I believe is for iOS only.

**Comment by crookedneighbor** [comment]
We’ve found the source of the bug. We’ll update here when the fix is out.

**Comment by xuaninbox** [comment]
Awesome! Thank you so much!

**Comment by xuaninbox** [comment]
Seem to be working now! I'll close it. Thanks!
