### ISSUE TITLE
Confusing on using the payment_method_token

### ISSUE THREAD

**Issue by justqyx** [braintree/braintree-web#229]
Hi, I want to use a `payment method token` to do a new transaction, but I got errors as follow.

```ruby
[{
  code: '91564',
  attribute: 'payment_method_nonce',
  message: 'Cannot use a payment_method_nonce more than once.'
}]
```

Steps for a reproducing.

1. server side: use the payment_method_token to create a nonce
2. client side: use the nonce to do 3D verification and then got a `new nonce`
3. server side: use the `new nonce` to create a sale transaction

![image](https://cloud.githubusercontent.com/assets/1448539/19849952/e682699c-9f90-11e6-93f3-183578d88be9.png)

Is there anything that I have missed?

**Comment by skunkworks** [comment]
Hi @justqyx,

The overall process as you've described it is correct.

I'm looking through the logs for the second payment method nonce, and I'm seeing a `GET` request that seems to be fetching the payment method nonce details. This is consuming the payment method nonce before the transaction is created.

Do you have any code on the client or server that might be causing this?

**Comment by justqyx** [comment]
Hi @skunkworks Thanks for your reply. 

**I forgot to declare that all of my code is running in the Braintree sandbox environment. And the JS SDK is v3.5.0**

The server side code is work with a simple front-end demo in the past few weeks. But now I'm developing a production UI, and getting the error I've got above. So I use the simple front-end demo which I've used to test before and unfortunately I got the some error in splite of the credit card part is work.

Here is some simple code of my front-end demo.

```js
function invokeWithSavedToken(clientInstance, paymentToken) {
    console.debug("Request a nonce from backend");
    $.post(nonceUrl, { token: paymentToken }, function(data) {
        console.debug(`Got: ${data.nonce}`);
        start3DVerify(clientInstance, data.nonce);
    }, 'json');
};

function invokeWithUsingNewCreditCard(clientInstance) {
    $('#new-credit-card-wrapper').removeClass('hidden');

    braintree.hostedFields.create({
        client: clientInstance,
        styles: window.creditCardStyles,
        fields: window.creditCardFields
    }, function(hostedFieldsErr, hostedFieldsInstance) {
        if (hostedFieldsErr) {
            console.dir(hostedFieldsErr);
            return;
        }

        console.debug('Loading Braintree iframe success');

        $submit.removeAttr('disabled');

        form.addEventListener('submit', function(event) {
            event.preventDefault();
            invoke3DFlowByNewCreditCard(hostedFieldsInstance, clientInstance);
        });
    });
};


function start3DVerify(clientInstance, paymentTokenNonce) {
    braintree.threeDSecure.create({ client: clientInstance }, function(_, threeDSecure) {
        var $container = $('#three-d-iframe');
        console.log('before 3d: ', paymentTokenNonce);

        threeDSecure.verifyCard({
            nonce: paymentTokenNonce,
            amount: parseFloat(amount),
            addFrame: function(err, iframe) {
                $container.append(iframe);
            },
            removeFrame: function() {
                $container.empty();
            }
        }, function(err, payload) {
            if (!err) {
                console.log('after 3d: ', payload.nonce);
                $('input[name="payment_method_nonce"]').val(payload.nonce);
                form.submit();
            } else {
                console.error(err);
            }
        });
    });
};
```

**Comment by skunkworks** [comment]
Hi,

Your client-side code looks correct, so it's likely that the issue is in the server code that occurs after the form is submitted.

Can you check whether your server code calls `CreditCard#from_nonce` before creating the transaction? This method consumes the nonce before you can transact with it.

**Comment by justqyx** [comment]
@skunkworks  Hi,

I found that there are another two steps using the `new nonce` before I use the new nonce to create a new transaction from Braintree.

1. get the 3d secure info by the `new_nonce`
2. get the token by the `new_nonce`

The first one is the common flow for the online business. And the second step is used to checked token which can be fetched by the `new nonce` whether belongs to the customer.

```ruby
def check_nonce_owner
  return true if paypal_nonce?(@payment_method_nonce_type)

  # Try to get the token by the `new nonce`
  @credit_card = @braintree_gateway.credit_card.from_nonce(params[:payment_method_nonce])
  
  # I have store the user's token into db, so I could confirm whether the new nonce is belongs to
  # the current customer or not.
  if current_platform_customer.tokens.braintree_platform.exists?(token: @credit_card.token)
    @ignore_three_d_secure = false
  else
    render_code_422('order.transaction.void_payment_token_nonce')
    return false
  end
rescue Braintree::NotFoundError
  # the nonce is not created by token, so skip
  return true
end
```

Will the `new nonce` be consumed if I call the `from_nonce` interface which provided by the CreditCardGateway instance?

**Comment by justqyx** [comment]
Hi @skunkworks 

After a debugger, the line code as follow will cause the `new nonce` to be consumed.

```ruby
@credit_card = @braintree_gateway.credit_card.from_nonce(params[:payment_method_nonce])
```

So I may have to found an another way to check the nonce owner. Thanks for your reply and time.
