### ISSUE TITLE
paymentMethodNonceReceived callback is unlocking Drop-in form fields

### ISSUE THREAD

**Issue by djhojd** [braintree/braintree-web#23]
Hi guys,

It would be nice to have more control on the locking and unlocking of Drop-in integration form fields.
Currently, if you use the paymentMethodNonceReceived callback, when you click the submit button the form fields are being locked and when the nonce code is received the form fields are being unlocked but the payment process is not yet complete, we just received a nonce code.

Thanks

**Comment by jeffcarp** [comment]
@djhojd ideally would you need exact control over when the fields are locked or unlocked? Or would it solve the problem simply to keep the fields locked once a nonce is generated (and maybe have a 'cancel' button to delete the generated nonce)?

**Comment by djhojd** [comment]
You are right! by leaving the fields locked after nonce is generated, until a "cancel" action is triggered and if canceled delete the old nonce and be ready for generating new one.

**Comment by lilaconlee** [comment]
@djhojd We're going to close this issue, but feel free to reopen the issue or email support@braintreepayments.com if you have further questions.
