### ISSUE TITLE
Apple Pay on web, merchant unauthorised

### ISSUE THREAD

**Issue by developius** [braintree/braintree-web#231]
Hi,

I've integrated Apple Pay into my code using your examples for the Braintree JS library. (Fantastic job by the way - very easy to use!).
However, I'm having trouble getting Apple Pay to work on my iPhone running iOS 10.1. It brings up the AP palette but the merchant validation is failing. This is using Braintree Sandbox with the correct domain added in the settings for AP.

```js
session.onvalidatemerchant = function (event) {
    applePayInstance.performValidation({
        validationURL: event.validationURL,
        displayName: 'My Name'
    }, function (validationErr, merchantSession) {
        if (validationErr) {
            alert('Error validating merchant:', validationErr);
            session.abort();
            return;
        }
        session.completeMerchantValidation(merchantSession);
    });
};
```

In the console, I can see
```
Failed to load resource: the server responded with a status of 417 (Expectation Failed) https://api.sandbox.braintreegateway.com/merchants/long-string/client_api/v1/apple_pay_web/sessions
```

I can see that the requested URL responded with
```
{
    "error": {
        "message": "Payment Services Exception merchantId=very-long-string unauthorized to service on behalf of merchantId=another-long-string reason=\"The latter is not registered for Apple Pay on the web\""
    },
    "fieldErrors": []
}
```

I'm unsure how to proceed, I was wondering if you could point me in the right direction?

Many thanks

**Comment by crookedneighbor** [comment]
Sounds like something went wrong with the registration process with Apple. Could you email your Braintree merchant ID to support@getbraintree.com and link to this Github Issue?

**Comment by skunkworks** [comment]
@developius Can you confirm that you are logged into an iCloud Sandbox account? We suspect that the error message indicates that `event.validationURL` is an Apple Pay production endpoint, which happens if your iCloud account is not a sandbox user.

**Comment by developius** [comment]
Thanks for your swift responses.
@skunkworks, ah! I am not logged into an iCloud sandbox account, I hadn't realised that this was something I needed to do - sorry.
For reference, `event.validationURL` is https://apple-pay-gateway.apple.com/paymentservices/startSession.

**Comment by skunkworks** [comment]
No worries, glad that fixed your issue!
