### ISSUE TITLE
Unable to supply postal code outside of Hosted Fields for tokenisation

### ISSUE THREAD

**Issue by DaveMacaulay** [braintree/braintree-web#235]
With v2 of the SDK we were able to provide the postal code separate to the Hosted Fields request. With the v3 SDK we are required to display the postal code as a hosted field and we're unable to manually pass this through to the tokenizeCard command.

This is less than desirable as many websites will already have or be capturing the billing postal code for the transaction. 

I believe in production mode this causes the tokenisation request to fail due to the postal code being required. This doesn't seem to be replicable in a sandbox environment, sadly I don't have a spare production account to test and report back this functionality on.

**Comment by crookedneighbor** [comment]
We're looking into a solution for this. Stand by!

**Comment by danakatz** [comment]
@DaveMacaulay As of version 3.9.0, released today, you can now pass a postal code in Hosted Fields options. See the [documentation](http://braintree.github.io/braintree-web/current/HostedFields.html#tokenize) for more details and an example.

Thanks for the request, and let us know if you run into any more issues!
