### ISSUE TITLE
AMD 2.5.1 version not working

### ISSUE THREAD

**Issue by djhojd** [braintree/braintree-web#24]
Hi guys,

I've just updated from 2.3.3 to 2.5.1 and the same drop-in code that I've used before is not working anymore. Maybe something has changed that needs to be reflected in the docs, I didn't find anything.

Thanks

**Comment by kyledetella** [comment]
@djhojd we have not encountered any issues with the `2.5.1` release regarding an AMD integration. Are you using RequireJS?

Here is a [RequireJS example on JSBin](http://jsbin.com/vumoyezoli/2/edit) I made using `2.5.1`. I recommend not relying on the included client token (it is from our marketing site and will go stale), but I wanted to share the setup we have made work.

It is likely that your setup may be different, so just let me know and we can help figure it out. In the meantime, if you are in production and can roll back to `2.3.3` [(linked here)](https://js.braintreegateway.com/js/braintree-2.3.3.min.js), I would recommend doing that until this is sorted out.

**Comment by djhojd** [comment]
I see that this example is working and yes, I'm using requireJS, the difference is that my setup includes a gulp build process where braintree.js is added and, without any code changes, this error is displayed in DevTools: Uncaught TypeError: undefined is not a function. Until DevTools becomes a little smarter (I saw that in the next few updates it will get rid of "undefined") ... I will do some digging into this and get to the bottom of this.
Thanks

**Comment by kyledetella** [comment]
@djhojd you can download [Chrome Canary](https://www.google.com/chrome/browser/canary.html) and try it out, that should give you a more specific error (instead of `undefined`).

**Comment by djhojd** [comment]
Thanks @kyledetella.
This is what the Canary whispered: braintree.js:4 Uncaught TypeError: d.on is not a function. Do you guys have any suggestions?

**Comment by kyledetella** [comment]
Ah, that makes sense. I assume you are building agains the minified version, correct? Could you try building it against [this unminified file](https://js.braintreegateway.com/js/braintree-2.5.3.js) and let me know what you get.

Also, could you provide the relevant code snippet from your `gulp` file? I would like to take a look at that and see if we can get to the bottom of this.

**Comment by djhojd** [comment]
Thanks for the unminified file, I really needed that. Why is that file not made public? :)
So, the error message is: `Uncaught TypeError: bus.on is not a function` and line from braintree.js is `bus.on(bus.events.ERROR, _rootErrorCallback);`
My gulp file is a bit complicated and large, if you think that that may help you I will make a simplified version and post it here.

**Comment by kyledetella** [comment]
@djhojd it could be helpful since we have not been able to replicate this ourselves just yet.

**Comment by djhojd** [comment]
@kyledetella just managed to find out the problem, it seems that when using a namespace in requirejs config file braintree stops working, if I comment out the namespace line everything is working just fine.

**Comment by mrak** [comment]
Could you elaborate on your setup and answer the following:

* Are you using the require.js optimizer (either directly or through something like `gulp-requirejs`)?
* Could you post your require.js config or main file describing your use of namespaces that caused the error?

Thanks!

**Comment by djhojd** [comment]
A short version of my rjs config file looks like this
```javascript
var gulp = require('gulp');
var rjs = require('requirejs');

// RequireJS configs
var rjsConf = {
  // namespace: 'requireJSBraintree',
  name: 'Braintree',
  create: true,
  optimize: 'none',
  generateSourceMaps: false,
  preserveLicenseComments: true,

  baseUrl: './static',
  paths: {
    requireLib: 'lib/require',
    'socket.io': 'lib/socket.io',
    jquery: 'lib/jquery.min',
    braintree: 'lib/braintree',
  },
  include: ['requireLib', 'main', 'jquery', 'braintree'],
  out: './public/js/mod-braintree.js',
};
gulp.task('rjs-braintree', function(cb){
  return rjs.optimize(rjsConf, function(buildResponse){
    cb();
  }, cb);
});

gulp.task('default', ['rjs-braintree']);
```

**Comment by mrak** [comment]
Thank you, this led to an actual bug in one of our libraries. For future reference and documentation here the issue arises from use of a UMD prelude that checks for AMD environments _first_ instead of _second_:

```javascript
// bad
if (typeof define === 'function' && define.amd) {
  ...
} else if (typeof exports === 'object' && typeof module !== 'undefined') {
  ...
} else {
  ...
}
```

```javascript
// good
if (typeof exports === 'object' && typeof module !== 'undefined') {
  ...
} else if (typeof define === 'function' && define.amd) {
  ...
} else {
  ...
}
```

We will resolve this issue once the fix is released

**Comment by kyledetella** [comment]
@djhojd this issue has been fixed with the latest `2.7.0` release. Can you try it out and let us know?

**Comment by djhojd** [comment]
@kyledetella yes, working with 2.7.0!

**Comment by kyledetella** [comment]
Awesome! Sorry for the mixup!
