### ISSUE TITLE
Braintree-web 2.30.0 and Webpack UglifyJS plugin 

### ISSUE THREAD

**Issue by albv** [braintree/braintree-web#240]
I have a problem bundling my application with braintree-web script in production. Specifically when using 
```
new UglifyJsPlugin({
  ...
  mangle: {screw_ie8: true, keep_fnames: true},
  ...
})
```
in webpack config, resulted bundle throw `a.getUserAgent is not a function` error after loading in a browser (maybe it's the same issue as https://github.com/braintree/braintree-web/issues/170).
With 
```
new UglifyJsPlugin({
  ...
  mangle: false,
  ...
})
```
all works as expected.

I also did a quick check and replaced `node_modules/braintree-web/dist/braintree.js` with `https://js.braintreegateway.com/js/braintree-2.30.0.js` (non-minified version). It's works fine with my initial webpack setup with enabled mangling.
I think it's considered a best practice to put to npm package non-minified version of your code. So client bundler (webpack or anything  else) could take care of concatenation and minification.

**Comment by intelliot** [comment]
Hi @albv -

Thanks for reporting this issue. We're glad that you found a workaround.

Note that v3 (the current version) of braintree-web doesn't have this problem. A non-minified version of the code is available on npm.
