### ISSUE TITLE
With formatInput: false, Javascript validation is done incorrectly

### ISSUE THREAD

**Issue by pdg137** [braintree/braintree-web#241]
When using the `formatInput: false` option with hosted fields, Braintree doesn't validate inputs correctly: entering "4111-1111-1111-1111", for example, generates an unusable nonce with card type "Unknown".

Example: http://codepen.io/anon/pen/rWKoMQ

**Comment by crookedneighbor** [comment]
Thanks for reporting this. I'm working on a fix for this.

**Comment by crookedneighbor** [comment]
This has been fixed in v3.6.2 which we've just released.

**Comment by pdg137** [comment]
This bug seems to be back in recent releases of braintree.js.  Can you get it fixed again?

Updated example for 3.32.1: https://codepen.io/anon/pen/jxrXMW

**Comment by crookedneighbor** [comment]
I'm not able to reproduce in the codepen you provided.

Typing in `4111-1111-1111-1111` tokenizes just fine.

**Comment by crookedneighbor** [comment]
Never mind, I misread it. Looking into it.

**Comment by crookedneighbor** [comment]
Looks like this regression happened way back in 3.8.0. Looks like a PR that was in progress didn't handle the merge conflicts correctly. We'll get this fixed.

**Comment by pdg137** [comment]
Thanks. By the way, in case anyone else comes here looking for a workaround, I noticed that despite the card type being "Unknown", the nonce can actually be processed, and the credit card appears normal in the vault.

**Comment by crookedneighbor** [comment]
This has been fixed in 3.33.0
