### ISSUE TITLE
Issue with Braintree Pyapal

### ISSUE THREAD

**Issue by avanish512** [braintree/braintree-web#243]
Hi,

I'm Migrating Braintree with My Magento 2 store after putting all credentials getting this issue for more you please check attached file.

Please suggest me what the issue.
![braintree-error](https://cloud.githubusercontent.com/assets/24352902/21287127/ae26ae2c-c48a-11e6-8825-bb60f157bd2e.PNG)

**Comment by crookedneighbor** [comment]
@avanish512 Looks to me like there's something wrong with how the Magento plugin is calling the JavaScript SDK. The line that is erroring is here: https://github.com/magento/magento2/blob/1ade3b769a937f19682bbbe4e51b6c956147952f/app/code/Magento/Braintree/view/frontend/web/js/paypal/button.js#L108

I'd open an issue on the magento2 repository to get help with Magento. It is not something that Braintree maintains.
