### ISSUE TITLE
Expiry date bug on mobile android chrome

### ISSUE THREAD

**Issue by yavuzg2** [braintree/braintree-web#246]
We have found a bug in the expiry date field from braintree.
When the customer tries to write the credit card expiry date on mobile android chrome browser, the cursor doesn't act the way it is supposed to and the user struggles to write the right number in the fields.
The user may end up writing "1222 /" instead of "12 / 22",
 
You can replicate this from the following url;
https://www.tuckerfox.com.au/takeaway-delivery/pizzabros-dromana
 
Just add an item and proceed to guest checkout on mobile android chrome browser

I am attaching a screenshot for reference.

Thank you

![screenshot_20170105-034049](https://cloud.githubusercontent.com/assets/13781075/21922794/6f14bd9e-d981-11e6-80c7-451ff0856ffd.png)

**Comment by crookedneighbor** [comment]
I'm going to close this issue, but re-open it if updating to v3.6.3 does not solve the problem.
