### ISSUE TITLE
Paypal Popup open fails on IE

### ISSUE THREAD

**Issue by Mocha--** [braintree/braintree-web#247]
Hi,

I have an issue about Paypal Popup only happening on IE. The paypal instance can be created successfully. However, when I call the function, paypal.tokenize, I got an Error with the code "PAYPAL_POPUP_OPEN_FAILED" and the page is just a spinner in the middle.

JS-SDK Version: 3.6.3
IE Version: 11.576.14393.0

Thanks,

**Comment by crookedneighbor** [comment]
I am unable to reproduce this. Can you share a staging site and/or your code for calling `paypal.tokenize`?

Are you able to reproduce it on this demo site I made? https://crookedneighbor.github.io/paypal-logged-in-demo/

**Comment by Mocha--** [comment]
Hi @crookedneighbor ,

Thanks for help. I figured this out. The code has no problems.

When I am developing my website, I use 'localhost' to access it. However, IE blocks something inside which I cannot see. Thus, the paypal popup cannot show up.

After I tried deploying the website, I found it works. So I think this is because of IE's security mechanism.

**Comment by crookedneighbor** [comment]
Thanks for posting your findings!
