### ISSUE TITLE
Manually trigger PayPal pop up

### ISSUE THREAD

**Issue by robrichard** [braintree/braintree-web#25]
I'd rather build my own UI instead of using the included paypal button. Is there a way I can manually trigger the paypal pop up in my own event listener callback?

**Comment by jeffcarp** [comment]
Hey @robrichard, I know there's a way to do this on iOS and Android. Let me dig in and see if it's possible on web. Worst case scenario, could you keep the button somewhere hidden in the DOM and manually trigger a click event on it when your custom button is pressed?

**Comment by robrichard** [comment]
I was considering that but wanted to make sure there isn't a cleaner solution.

**Comment by jeffcarp** [comment]
Ok so I have some bad news, due to the way popup blockers work (click events can't be fabricated), the hacky approach won't work. It looks like there's no easy way to use the PayPal pop-up without using the PayPal button :confused:
