### ISSUE TITLE
Paypal Button Href redirect

### ISSUE THREAD

**Issue by legendac** [braintree/braintree-web#251]
Hi guys,

I am facing this problem for some time. Basically when I try to click on the PayPal button, I could detect that a create_payment_resource is being sent to my server-side. It is only when receiving the response and during redirection where I would encounter the error. 

Error on Chrome Developer console

> index.js:2 Uncaught TypeError: Cannot set property 'href' of undefined
>     at o.redirect (index.js:2)
>     at i.<anonymous> (index.js:3)
>     at index.js:1
>     at index.js:3
>     at XMLHttpRequest.E.onreadystatechange (index.js:1)
> o.redirect @ index.js:2
> (anonymous) @ index.js:3
> (anonymous) @ index.js:1
> (anonymous) @ index.js:3
> E.onreadystatechange @ index.js:1

I am using `braintree-web` to implement payments for my **Ember.js** application. I am using the JS V3 of Hosted Fields. 

Here is my code
```js
braintree.paypal.create({
        client: clientInstance
      }, function (paypalErr, paypalInstance) {

        if (paypalErr) {
          console.error('Error creating PayPal:', paypalErr);
          return;
        }
        paypalButton.removeAttribute('disabled');
        paypalButton.addEventListener('click', function (event) {
          event.preventDefault();
          paypalInstance.tokenize({
            flow: 'checkout',
            amount: 100.00, // Required
            currency: 'SGD', // Required
          }, function (tokenizeErr, payload) {
            payload.focus();
          
            if (tokenizeErr) {
              if (tokenizeErr.type !== 'CUSTOMER') {
                console.error('Error tokenizing:', tokenizeErr);
              }
              return;
            }

            paypalButton.setAttribute('disabled', true);
            console.log('Got a nonce! You should submit this to your server.');
            console.log(payload.nonce);

          });

        }, false);
      });
    }
```

The button that I have for paypal is 
`<button id="paypal" class="ui button primary">PayPal</button>`

create_payment_resource 201 response

```
{"paymentResource":{"paymentToken":"token","intent":"authorize","redirectUrl":"https://checkout.paypal.com/one-touch-login-sandbox/index.html?action=create_payment_resource\u0026amount=100\u0026authorization_fingerprint=9295ad65cc7f582e773b6f67168c72e98b897094dc7542fa7b82b6ea577a5942%7Ccreated_at%3D2017-01-23T07%3A01%3A35.637359776%2B0000%26merchant_id%3Dg863h3kc2xg5fqzr%26public_key%3D2n84m7jtyn5q6hsm\u0026braintree_library_version=braintree%2Fweb%2F3.6.3\u0026cancel_url=https%3A%2F%2Fcheckout.paypal.com%2Fweb%2F3.6.3%2Fhtml%2Fpaypal-cancel-frame.min.html%3Fchannel%3D7ce9636ac73b42bb9041ba3afeee7739\u0026city=Chicago\u0026controller=client_api%2Fpaypal_hermes\u0026correlation_id=7ce9636ac73b42bb9041ba3afeee7739\u0026country_code=US\u0026currency_iso_code=SGD\u0026experience_profile%5Baddress_override%5D=true\u0026experience_profile%5Bbrand_name%5D=OTR+CORP\u0026experience_profile%5Blocale_code%5D=en_US\u0026experience_profile%5Bno_shipping%5D=false\u0026line1=1234+Main+St.\u0026line2=Unit+1\u0026merchant_id=g863h3kc2xg5fqzr\u0026offer_paypal_credit=false\u0026phone=123.456.7890\u0026postal_code=60652\u0026recipient_name=Scruff+McGruff\u0026return_url=https%3A%2F%2Fcheckout.paypal.com%2Fweb%2F3.6.3%2Fhtml%2Fpaypal-redirect-frame.min.html%3Fchannel%3D7ce9636ac73b42bb9041ba3afeee7739\u0026state=IL\u0026token=EC-HERMES-SANDBOX-EC-TOKEN\u0026version=1"}}
```

Appreciate lots! Thank you in advance!

**Comment by skunkworks** [comment]
@legendac Does the PayPal popup appear when you click the button? I believe the `href` that's being set is the PayPal popup window being redirected to show the authorization page, so I suspect that the popup window is failing to open.

**Comment by legendac** [comment]
@skunkworks Yes you are right, the PayPal popup window did not appear.  Apologies for the unclear description of the issue.

**Comment by skunkworks** [comment]
@legendac Do you have a code sample or a GitHub repo you can share with us that replicates this issue? It'll save us some time :)

**Comment by crookedneighbor** [comment]
I was able to make an ember app with PayPal without issue by forking https://github.com/EmberPittsburgh/ember-2-example and adding braintree-web.

You can see it here: https://github.com/crookedneighbor/ember-2-example

Here's the commit where I added braintree-web: https://github.com/crookedneighbor/ember-2-example/commit/54fb40143f86d393bb30ec0458a0b54e267b534d

I assume some plugin or addon you have installed with Ember is causing your issue. I'm going to close this now, but if you'd like us to help you troubleshoot some more, feel free to create a Github repo that illustrates the problem and re-open this issue when you post a link to it here.
