### ISSUE TITLE
PayPal Popup not opening in Chrome 43

### ISSUE THREAD

**Issue by eschie** [braintree/braintree-web#252]
I get a `PAYPAL_FLOW_FAILED` BraintreeError every time I request the PayPal popup on:

iPad Air 2; iOS 8.2(12D508)
Chrome 43.0.2357.56
UA: `Mozila/5.0 (iPAd; CPU OS 8_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) CriOS/43.0.2357.56 Mobile/12D508 Safari/600.1.4`

![ipadpopup](https://cloud.githubusercontent.com/assets/1564750/22228767/1a55bde4-e188-11e6-8699-848036fa95c7.gif)

**Comment by intelliot** [comment]
@eschie As indicated in our [browser support documentation](http://braintree.github.io/braintree-web/3.6.3/#browser-support), this requires Chrome 48+ (iOS 9+).

We'll take a look at whether we can improve the error returned in this case.

**Comment by crookedneighbor** [comment]
Version 3.8.0 will now return a browser unsupported error. Thanks for your reporting this!
