### ISSUE TITLE
Issue in braintree on Samsung devices

### ISSUE THREAD

**Issue by surabhishuklansi** [braintree/braintree-web#253]
Hello,

When we enter credit card number in Samsung the card number is not entered correctly, We are using Braintree PHP SDK Version 3.17.0

We are  facing the issue on following Samsung devices and browser
Samsung galaxy S6 chrome version 55
Samsung galaxy S4 default browser
Samsung galaxy A8, chrome version 55

You can check the website www.uniforms4healthcare.com/skinny-fit-trousers-black , 
add any product to cart, go to checkout, In the third step of checkout you can see the tab "Payment Method" Click on "Credit or Debit Card" Give any card number

Enter the card number 3530111333300000
The card number will not take the spaces manually
Press delete (backspace), and the auto formatting suddenly activates, but it deletes every 5th character and the last two, resulting in: 3530 1133 3000
If you will not delete and just submit the form you will get the errorr as 
"There are a number of errors present with the credit form: Card Number is invalid"
Even though we are giving correct card number and that number is working fine on all other devices and browsers.

**Comment by crookedneighbor** [comment]
I assume this is the same thing that you commented about on this issue: https://github.com/braintree/braintree-web/issues/234#issuecomment-275035757

Looks like it's resolved for you by updating your version of braintree-web, so I'm going to close this issue. Re-open it if you are still having issues.
