### ISSUE TITLE
Subscription id in the transaction gets changed to latest subscription ID

### ISSUE THREAD

**Issue by ashanbh** [braintree/braintree-web#254]
See https://www.braintreegateway.com/merchants/mspb8dyh8p5ydtxj/transactions/7hq2y8k5
![screen shot 2017-01-31 at 1 21 11 pm](https://cloud.githubusercontent.com/assets/537598/22484871/2a0524ba-e7b8-11e6-9fdf-f11c1b95500a.png)

When we changed this user's active subscription to a new plan, the plan

 on this (older) transaction changed to the new plan.
i.e this is showing the plan name "silver -202" which is a $99 plan. However this particular transaction is for $49.

**Comment by ashanbh** [comment]
@rocketreach

**Comment by crookedneighbor** [comment]
I don't think this has anything to do with the Braintree JavaScript SDK. Please contact support@braintreepayments.com for assistance. 

If I'm wrong about it's relation to this repo, please re-open the issue.

**Comment by ashanbh** [comment]
This same information is also returned by the API.
