### ISSUE TITLE
3D Secure requires HTTPS

### ISSUE THREAD

**Issue by sashakru** [braintree/braintree-web#255]
Hi guys,

I started braintree 3.7.0 integration in our payment system and faced with the next problem:

I'm trying to test 3DS flow on my local and get error from `threeDSecure.create`:

`{
code:"THREEDS_HTTPS_REQUIRED"
details:undefined
message:"3D Secure requires HTTPS."
name:"BraintreeError"
type:"MERCHANT"
}`

Am I missing some properties that allow 3DS flow on local machine without HTTPS?

**Comment by skunkworks** [comment]
Hi @sashakru, we will work on adding an option flag to disable the HTTPS requirement.

**Comment by sashakru** [comment]
Hi @skunkworks,
Thanks for your response,

Any suggestions/best practices how can we test on local machine without HTTPS?

**Comment by crookedneighbor** [comment]
@sashakru The next release of braintree-web will allow you to use 3D Secure without HTTPS when using a client token or tokenization key from the Braintree sandbox. In production, HTTPS will be required.

In the meantime, you can self sign a certificate on your machine to allow you to run a local server on https.

**Comment by sashakru** [comment]
@crookedneighbor thanks for your advice, meanwhile we have resolved it with [ngrock](https://ngrok.com/)

when do you about to release next version?

**Comment by crookedneighbor** [comment]
We're planning on a release some time in the next week.

**Comment by crookedneighbor** [comment]
3.8.0 is out now and will not require https when not in production.
