### ISSUE TITLE
Issue in braintree on Samsung devices

### ISSUE THREAD

**Issue by clovnrian** [braintree/braintree-web#256]
Hi,
we still have issues on Samsung devices.

Samsung Galaxy S7, default browser, on same phone in chrome everything works fine
Samsung Galaxy Grand prime, android 5.1.1, default browse.

We can write only first 4 digits in credit card field, after that all fields stop working.
We have 3.6.3 version on our website.

Thanks.

**Comment by intelliot** [comment]
@clovnrian We have addressed this issue in [version 3.7.0](https://github.com/braintree/braintree-web/releases/tag/3.7.0) ([changelog](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md)), which disables input formatting for the Samsung Internet browser. Please let us know if you continue having issues after updating. Thanks!

**Comment by clovnrian** [comment]
It helps, thanks.
