### ISSUE TITLE
Release v2.30.0 ?

### ISSUE THREAD

**Issue by ayb** [braintree/braintree-web#257]
The `dist/` folder of the v2.0 branch has v2.27.0 as the latest version of the javascript available in the repo

However your v2 guide located here:
https://developers.braintreepayments.com/start/hello-client/javascript/v2

includes the following reference to Braintree.js v2.30.0:
```
<script src="https://js.braintreegateway.com/js/braintree-2.30.0.min.js"></script>
```

Why is the v2.0 branch not showing a newer version?

**Comment by ayb** [comment]
Never mind!

Found it here -> https://github.com/braintree/braintree-web-bower/tree/2.x

**Comment by crookedneighbor** [comment]
:+1:
