### ISSUE TITLE
Issue in braintree on Huawei devices

### ISSUE THREAD

**Issue by clovnrian** [braintree/braintree-web#258]
Hi,
we found problem on device Huawei Y3 II, unfortunately we don't have any other information. Our customer just report it to us.

We had the same issue on Samsung devices, but version 3.7 fix it. Problem is that we can write only first 4 letters in credit card field, after that nothing works.

**Comment by crookedneighbor** [comment]
Thanks for the report @clovnrian. Do you know what browser this is occurring on? (IE, Chrome, the default browser, or some other browser)

Until we get more details about the issue, you can turn off input formatting for Huawei devices like so:

```js
// user agent for Huawei devices will look something like:
// Mozilla/5.0 (Linux; U; Android 4.2.2; nl-nl; HUAWEI P6-U06 Build/HuaweiP6-U06) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30

var isHuawei = navigator.userAgent.match(/HUAWEI/i)

braintree.hostedFields.create({
  client: clientInstance,
  fields: {
    number: {
      selector: '#card-number',
      formatInput: !isHuawei
    },
    cvv: {
      selector: '#cvv',
      formatInput: !isHuawei
    },
    // etc
  }
}, callback);

**Comment by clovnrian** [comment]
Hi,
unfortunately we don't know what browser was used. But we found other device.
Sony Xperia M2, android 4.4.4, it works in chrome, but in application webview (native browser) it doesn't.

**Comment by danakatz** [comment]
Hi @clovnrian, we haven’t been able to reproduce this behavior in a webview on an Android 4.4.4 device. It seems like the best solution at this point is to turn off input formatting, as @crookedneighbor suggested, for any browsers where this is an issue. 

Closing this for now, but feel free to update here if you gather any more information that might help debug this.
