### ISSUE TITLE
Hosted Field issue on IE 11

### ISSUE THREAD

**Issue by maxetime** [braintree/braintree-web#259]
I've found an issue when making a hosted field payment on IE 11 with v3.7.0 (also had the issue with 3.6.3)
Installed via npm

When you try to send the payment you get an exception : 
`'postMessage' of undefined or null reference`

The reference should be the `window.top` which returns undefined.
I've tried changing this to `(win.top || win.self)` which seems to have fixed the issue, but I have not fully tested to make sure it didn't have impact on anything else.
https://github.com/braintree/framebus/blob/09eeb98ee6a8496705b02f76ab4b7cd160b5f47b/lib/framebus.js#L52

**Comment by crookedneighbor** [comment]
Thanks for narrowing this down. We had gotten intermittent reports about this, but nothing we could reproduce. We've updated our `framebus` lib and this fix will go out in the next release of `braintree-web`.

I'll comment here when it is out.

**Comment by maxetime** [comment]
Great! Thanks

**Comment by crookedneighbor** [comment]
We've just released v3.9.0 which includes this fix. Thanks for your investigation on this!

**Comment by paresh-2016** [comment]
@crookedneighbor  Where can we find v3.9.0? In the release it says latest v3.28.0.

**Comment by bluk** [comment]
@paresh-2016 If you need to use an older version, you can replace the latest version number (in this case `3.28.0`) with the version number you want in the [Client SDK Setup guide](https://developers.braintreepayments.com/guides/client-sdk/setup/javascript/v3). For instance, `https://js.braintreegateway.com/web/3.9.0/js/client.min.js`.

v3.28.0 has the latest fixes, and I would recommend using the latest version unless there's a known issue.
