### ISSUE TITLE
Drop-In "Card Number" field does not reevaluate onChange

### ISSUE THREAD

**Issue by djhojd** [braintree/braintree-web#26]
Hi guys,

If you enter CC "4111 1111 1111 1112" you will get an error, now select last digit and type 1, that resulting CC is a valid one but you will still see it as being invalid. If you do the same for "4111 1111 1111 1111" and changing last digit to 2 you will see an error, only from 2 to 1 the CC field does not get reevaluated.

Thanks

**Comment by kyledetella** [comment]
@djhojd which browser/device are you experiencing this on? So far I am unable to replicate.

**Comment by djhojd** [comment]
Chrome Version 40.0.2214.115 (64-bit) & FireFox 36.
Also tried [here](http://jsbin.com/vumoyezoli/2/edit) and same case. Keep in mind that you need to replace a digit by selecting it not by hitting the delete or backspace key.

**Comment by kyledetella** [comment]
Ok, I see this happen when selecting. We will take a look at it.

**Comment by rturumella** [comment]
Just wanted to give you an update on this - we did take a look into this. It is an aesthetic issue and we'll let you know when it's fixed.

**Comment by EvanHahn** [comment]
@djhojd We took a look at this and fixed it. You'll be able to find this fix in an upcoming version of braintree.js—we'll keep you updated.

Thanks for catching it!

**Comment by EvanHahn** [comment]
@djhojd This is fixed in the latest version of braintree.js, 2.14.3. Thanks again for reporting!
