### ISSUE TITLE
AuthorizationError: 422 Unprocessable Entity

### ISSUE THREAD

**Issue by m-kumaran** [braintree/braintree-web#261]
Hi, 

Recently I integrated Braintree v-zero in one of my web applications.
It was working fine in Sandbox. But when I replaced the production token,
I am getting an error in the browser as Authorization Error with a debugId
(eg)
```
{"error":{"errorName":"AUTHORIZATION_ERROR","errorMessage":"Authorization error","debugId":"284bd8802c322"
,"paypalHttpStatus":403}}

```
I verified the access token and it is valid. There are no issues in logging in to Paypal Business account, and could not see any warning/notification related to authorization.

Any help would be highly appreciated.

Cheers
Kumaran

**Comment by crookedneighbor** [comment]
What version of braintree-web are you using? Can you share your frontend code or provide a staging site where we can reproduce the issue?

**Comment by crookedneighbor** [comment]
Going to close this now, but feel free to re-open with more details about your integration.
