### ISSUE TITLE
Aborting a create process

### ISSUE THREAD

**Issue by PatrickWatzlawik** [braintree/braintree-web#263]
Hey guys,

Is there a way to abort the `braintree.hostedFields.create` or `braintree.paypal.create` process?

Our payment site offers both methods and if an user clicks on, lets say, PayPal when the CreditCard-Form is still loading, an error is thrown `Selector does not reference a valid DOM node.` which is totally legit (SPA and DOM manipulations and stuff).

Of course, we could catch this error and handle it somehow. I was just wondering if there may exist a cleaner way :) 

Cheers,
Watte

**Comment by okovpashko** [comment]
@PatrickWatzlawik are you sure that this issue is not related to your own async code? 
We also have SPA with the payment form contained two tabs: Card and PayPal. Without any additional error catching, we don't have any error if changing tab during firm loading.

**Comment by PatrickWatzlawik** [comment]
@okovpashko Well, I dont want to blame anybody before I'm not completely sure it's not my fault :P 

The problem is, that the DOM containing the `<div id="credit-card-number">` elements for the hosted fields is removed due the tab change (`ng-if` from angular, if you're familiar with it). Basically the DOM is replaced with other elements (for example, the DOM for PayPal). 
Do you keep the hosted-fields elements and just hide them or are they really removed from the DOM?

**Comment by okovpashko** [comment]
@PatrickWatzlawik we have a React app and we remove tab content on another tab selecting.
As you can see [here](https://github.com/braintree/braintree-web/blob/6a854d64c8c7e0b57058c161abe1df4df3e6f46a/src/hosted-fields/external/hosted-fields.js#L335) your error is thrown in HostedFields constructor in synchronous code so it does not seem to be thrown after the successful create() call.
Maybe you are trying to initialize Braintree component before Angular updates the template?

**Comment by crookedneighbor** [comment]
@PatrickWatzlawik There is no method to cancel the create call while in progress. 

If I recall, `ng-show` should just hide the element. So you could try switching to that directive. Going this route would also allow you to load both components at once so when your user switches from one tab to the other, there is no delay in the setup.

**Comment by PatrickWatzlawik** [comment]
@okovpashko No, it's called, when the DOM is ready but will throw, when the DOM changes (selecting another tab). This is actually on purpose to get rid of any old partial context.

@crookedneighbor Yes, `ng-show` would be the workaround. 

Thanks to both of you! We'll probably catch the case :)
