### ISSUE TITLE
Question on upgrading from 3.2.0 into 3.8.0 ...

### ISSUE THREAD

**Issue by georgesunil81** [braintree/braintree-web#266]
This is more of a question and not an issue.

Here are the components I was using from braintree-web 3.2.0 (npm package)

      "braintreeClient": "node_modules/braintree-web/client.js",
      "braintreeHostedFields": "node_modules/braintree-web/hosted-fields.js"

1) Could you let me know which components should I use from 3.8.0 that will be equivalent?

2) Also, I see that the directory structure of library (npm package) for 3.8.0 is so different from 3.2.0. Could we get a bundled version also for 3.8.0?

**Comment by crookedneighbor** [comment]
We recently made the change to not publish pre-built files to NPM, which is why you're suddenly having issues. If you're looking for bundled files, you will not find them on NPM. You have a couple of options:

* Use a build tool (browserify, webpack, etc)
* Download the files and vendor them into your app (You can find them [here](https://github.com/braintree/braintree-web-bower))
* Use [bower](https://bower.io/) to manage your frontend dependencies.

**Comment by georgesunil81** [comment]
Ah! That is a strange decision though, since now with 3.2.8 all of your code is exposed. 

By the way, I am using StealJS as my build tool, but getting 404s left and right, due to the npm library structure change with 3.8.0!!

**Comment by crookedneighbor** [comment]
I'm not sure what you mean by "all of your code is exposed" is exposed. It's an open source repo. All the code is available to be perused.

You must be doing something non-standard with your steal configuration. The following configuration worked for me both with braintree-web@3.2.0 and braintree-web@3.8.0

```json
// package.json
{
  "name": "steal-demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "steal-tools"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "braintree-web": "3.8.0",
    "steal-tools": "^1.1.2"
  }
}
```

```js
// index.js
import btClient from 'braintree-web/client'
import btHostedFields from 'braintree-web/hosted-fields'

btClient.create({
  authorization: 'sandbox_g42y39zw_348pk9cgf3bgyw2b'
}, function (err, clientInstance) {
  if (err) {
    console.error(err);
    return;
  }

  btHostedFields.create({
    client: clientInstance,
    // rest of setup code
  })
})
```

**Comment by georgesunil81** [comment]
Ah! Did not know that Braintree went open-source. Its good. Thanks for your attempt at the solution for me. Actually, I am using Steal for module loading. Steal-tools is for building. I am good with both of them alongwith braintree-web v3.8.0. 

Thanks for your help.
