### ISSUE TITLE
Detecting PayPal support

### ISSUE THREAD

**Issue by okovpashko** [braintree/braintree-web#267]
Hello.
I've faced an issue with PayPal support in the Facebook browser on mobile devices.
It would be great to have a helper method in PayPal module for detecting PayPal support in the current environment.
I think it's mutch better not to show PayPal among available payment methods in unsupported browsers instead of showing error when the user is trying to use it.

**Comment by crookedneighbor** [comment]
If you look at the example for the PayPal create call here, you'll see that there is a check for the error with the code `PAYPAL_BROWSER_NOT_SUPPORTED`. http://braintree.github.io/braintree-web/current/module-braintree-web_paypal.html#.create

That should let you update your UI appropriately. Going to close this now, but feel free to re-open it if this does not help you.

**Comment by okovpashko** [comment]
@crookedneighbor thank you. I saw that example and I have already implemented error handling. But I think that it would be better to have the ability to hide PayPal payment method at all if the PayPal integration is not supported in the current browser.
Why should we let the user click on PayPal button and then immediately display an error about the unsupported browser?
Especially for SPA, when the logic is encapsulated inside separated components it's not convenient to create braintree-client and paypal instance outside paypal component just for checking if we should display PayPal payment method.
Also, it looks like easy to expose the function for checking browser support as a static method of paypal module.

**Comment by crookedneighbor** [comment]
That sounds reasonable to me. Probably a synchronous method on `braintree.paypal.isSupported` that returns true or false.

We'll put this in our backlog, but if you'd like to PR it, feel free.

**Comment by crookedneighbor** [comment]
We've added a helper method for detecting this. It'll go out in the next release of braintree-web.

**Comment by okovpashko** [comment]
@crookedneighbor great news. Thanks a lot!

**Comment by lilaconlee** [comment]
We've released 3.10.0 of `braintree-web` which includes [`paypal.isSupported()`](http://braintree.github.io/braintree-web/current/module-braintree-web_paypal.html#.isSupported). Thanks for your feedback!

**Comment by okovpashko** [comment]
@lilaconlee great news! Thank you!

**Comment by alainrostain** [comment]
Hello. Is paypal.isSupported() true for iOS 10.3.2 on iPhones 7 and 7 Plus? It's working for me on older iPhones, but not the 7 and 7 plus I'm testing. Thanks!

**Comment by alainrostain** [comment]
Update from braintree: "Thanks for contacting Braintree support. I've been able to replicate this issue within a Facebook webview. I'm looping in our API support team, who will investigate this issue further and reach back out to you once they have more information.

Thanks,
Subi"
