### ISSUE TITLE
Is there a repo and bower install for the braintree-data library?

### ISSUE THREAD

**Issue by trainerbill** [braintree/braintree-web#27]
I see that bower install is available for braintree-web.

**Comment by jeffcarp** [comment]
Not yet. We should do that. Thank you for bringing this up.

**Comment by trainerbill** [comment]
Thanks Jeff!  Do you have a timeframe on when it could happen?

**Comment by trainerbill** [comment]
Also with the data.js the setup documentation states:

BraintreeData.setup("yourMerchantId", 'yourFormDOMId', BraintreeData.environments.production);

But I am using angularJS and setting paymentMethodNonceRecieved.  It would be much better fit the BraintreeData.setup would return the data value or a callback function was created that returned the data so that I can use it in my scope how I see fit.  Instead of rendering a hidden field.

**Comment by kyledetella** [comment]
We do not plan to release the `braintree-data` library as a separate repo or module as of right now. However you can continue to use it as a supported feature of Braintree.

**Comment by tim-massey** [comment]
I'm thinking the same thing right now.

> It would be much better fit the BraintreeData.setup would return the data value or a callback function was created that returned the data so that I can use it in my scope how I see fit. Instead of rendering a hidden field.

**Comment by rturumella** [comment]
Thank you for the feedback - we currently don't support this and it's not planned at the moment but we will keep your feedback in mind for future versions!

Let me know if you have any other questions.

**Comment by liefl** [comment]
@tim-massey @trainerbill ... undocumented and obviously has no guarantees of being supported in the future, but running BraintreeData._getDeviceData() will return the device data in JSON-string format

**Comment by trainerbill** [comment]
@rturumella Can this feature be added to the roadmap?  You are requiring BTData info on paypal payments, but the only way to get that data is to use a JS library that appends it to a form?  Now I have to do a setTimeout and wait for hopefully enough time for your JS to do its work and then query the form for an input that you append.  This is definitely not a good practice.  I mean the functionality exists to get the information and create the input, how hard would it be to create a function to return the data instead of injecting an input field?

@liefl That is great for demos and such but I would be hesitant to use that in a production system. _ is usually private methods so I am not even sure how this is exposed globally.

**Comment by lilaconlee** [comment]
@tim-massey @liefl @trainerbill We have added a formless braintree-data setup to our roadmap and will keep you updated on our progress here.

**Comment by trainerbill** [comment]
Nice!  thanks for the heads up.  Looking forward to this functionality.

**Comment by trainerbill** [comment]
Last question.  Will the next release have a github repo with semver and a bower package?

**Comment by lilaconlee** [comment]
@trainerbill At the moment, that is not in our plans.

**Comment by charlieridley** [comment]
@lilaconlee any update on the formless braintree-data setup?

**Comment by kyledetella** [comment]
@charlieridley we have a new integration for `braintree-data` in our latest release. The official docs will be out in the next day or so. I would keep an eye on #80 as that is where we will be making updates.
