### ISSUE TITLE
422 (Unprocessable Entity)

### ISSUE THREAD

**Issue by sashakru** [braintree/braintree-web#272]
Hello there,

we have upgraded  BT SDK  to  version `3.9.0`,
on **staging** environment everything works great, but after deploying to **production** we are encountered with error: 
```
{  
   "error":{  
      "errorName":"BUSINESS_ERROR",
      "errorMessage":"Business error --- ZIP_MANDATORY_FIELD:Field mandatory for this country",
      "debugId":"97d99267f96f",
      "paypalHttpStatus":400
   }
}
```

We are getting this error when we are trying to tokenize paypal, like this:
```
addPayPalAccount = () => {
    return new Promise((resolve, reject) => {
      const configStore = getConfigStore();
      const marketId = configStore.getCurrentMarketId();
      const subMarketId = configStore.getSubMarketId();
      const marketLanguage = getMarketLanguage(subMarketId);
      const currency = getCurrencyCode(marketId);
      const locale = marketLanguage && marketLanguage.replace('-', '_');

      clientPaypalInstance.tokenize({
        flow: 'vault',
        locale,
        currency,
        enableShippingAddress: true,
        shippingAddressEditable: false,
        shippingAddressOverride: this._getShippingAddress(),
      }, (err, tokenizationPayload) => {
        if (err) {
          braintreeTokenizePaypalFailure({err});
          reject(err);
          return;
        }

        resolve({
          nonce: tokenizationPayload.nonce,
          deviceData: clientDeviceDataInstance.deviceData,
        });
      });
    });
  };

_getShippingAddress = () => {
    const configStore = getConfigStore();
    const subMarketId = configStore.getSubMarketId();
    const user = userStore.getUser();
    const userUtils = new UserUtils(user);

    return {
      recipientName: `${userUtils.getLastName()} ${userUtils.getFirstName()}`,
      line1: userUtils.getUserLine1Address(),
      line2: userUtils.getUserLine2Address(),
      city: userUtils.getUserCity(),
      countryCode: subMarketId && subMarketId.toUpperCase(),
      phone: userUtils.getUserPhoneNumber(),
    };
  };
```

I looked for any mention about zip field in your documentation and didn't find anything, is there any reason why we are getting this error only on production environment?

**Comment by danakatz** [comment]
Hi @sashakru, thanks for reporting this! Are you getting this error for a particular country, and if so, which? We'll attempt to reproduce and post here with any findings.

**Comment by crookedneighbor** [comment]
Can you also provide a link to the documentation where you expected to find this information, but couldn't? It's possible our docs need updating to make it clearer.

I see it here: http://braintree.github.io/braintree-web/current/PayPal.html#tokenize

And in the example here: https://developers.braintreepayments.com/guides/paypal/checkout-with-paypal/javascript/v3#bind-the-click-event

**Comment by crookedneighbor** [comment]
@sashakru We haven't heard back from you, so I'm going to close this issue. If you still need help, feel free to re-open it.

**Comment by parveensachdeva** [comment]
We getting this issue
![image](https://user-images.githubusercontent.com/45853238/90623930-d0f33d00-e234-11ea-85c7-9e9c6386254a.png)

**Comment by crookedneighbor** [comment]
@parveensachdeva contact Braintree support. the `originalError` property should give you more information about the error.

https://help.braintreepayments.com/

**Comment by parveensachdeva** [comment]
originalError is not giving anything specific
![image](https://user-images.githubusercontent.com/45853238/90731150-ee80df00-e2e6-11ea-83d7-a1251ea8527a.png)

**Comment by crookedneighbor** [comment]
Still contact Braintree support. There's not much I can do from here.
