### ISSUE TITLE
Samsung Galaxy S6 Hosted Fields Broken Formatting

### ISSUE THREAD

**Issue by Shaneprrlt** [braintree/braintree-web#275]
### General information

* SDK version: 3.9.0+
* Environment: Production
* Browser and OS Cordova/Crosswalk on Android (Samsung Galaxy S6)

### Issue description

Formatting is pretty much completely broken, after you type in 4 digits, a space-character is auto-inserted and then you cannot enter any more characters into the Credit Card Number Field. I know there was an issue open for other Samsung devices, but I wanted to let you know that this is failing on Galaxy S6 Devices too. I would assume most Hybrid Android apps using this library are experiencing this issue with Hosted Fields.

**Comment by Shaneprrlt** [comment]
This is affecting 3.10.0 and 3.11.0 as well.

**Comment by crookedneighbor** [comment]
Can you confirm that the input formatting is broken on your Samsung Galaxy S6 on this page: http://braintree.github.io/restricted-input/ 

I assume this is broken because of weird behavior with Samsung Galaxy webviews. Can you provide the user agent for your device? http://www.whatsmyua.com/

**Comment by Shaneprrlt** [comment]
Unfortunately, I cannot check the user agent within our app, even though it is a Cordova Hybrid app mounted in a Crosswalk Browser. https://crosswalk-project.org/ And I was not having issues when actually in Chrome or in the default browser that ships with the Galaxy S6. Can also confirm it's happening on S7 and a few other Samsung devices (we have been getting a lot of support requests and customers are unable to purchase in our App). Here is the User Agent for the Crosswalk browser (that powers most Hybrid apps), https://github.com/crosswalk-project/crosswalk-website/wiki/crosswalk-user-agent

**Comment by crookedneighbor** [comment]
Thanks, we'll look into this. In the meantime, I would suggest disabling auto-formatting. http://braintree.github.io/braintree-web/current/module-braintree-web_hosted-fields.html#~field

**Comment by Shaneprrlt** [comment]
Thank you for the quick response, that should actually be a good fix for now.

**Comment by crookedneighbor** [comment]
We have logic in place to disable formatting automatically if we can detect that the browser being used is a Samsung browser that doesn't support formatting, but since Crosswalk changes the user agent, that logic gets bypassed.

We don't [officially support hybrid environments like cordova](http://braintree.github.io/braintree-web/current/#browser-support-webviews), so our recommendation is to turn off the input formatting.
