### ISSUE TITLE
Get Nonce Been Ignore On Safari (Client)

### ISSUE THREAD

**Issue by MrGonc** [braintree/braintree-web#276]
### General information

* SDK version: 3.0.0
* Environment: Sandbox
* Browser and OS : Safari 10.0.3 (12602.4.8)(64-bit) on MacOS 10.12.3 & IOS 10

### Issue description
I'm use this code to get nonce it work well on chrome but it not work on safasi (ios), On Safari it just run forever when I test no error been throw or request time-out. 
(This code show nothing on console).

**payment.html**

<script src="https://js.braintreegateway.com/web/dropin/1.0.0-beta.5/js/dropin.min.js"></script>

<div id="dropin-container"></div>

==================================
**payment.js:**

var submitButton = document.querySelector('#submit-button');

    braintree.dropin.create({

      authorization: token,

      selector: '#dropin-container'

    }, function (err, dropinInstance) {

      console.log('Run 1');

      if (err) {       

        return;

      }

      submitButton.addEventListener('click', function () {

          console.log('Run 2');

          dropinInstance.requestPaymentMethod(function (err, payload) {

            console.log('Run 3');

            if (err) {

            }

            if (typeof  payload === 'undefined'){

              $state.reload();

            }else {

              var nonce = payload.nonce;

              $cookies.put('brainTreeNonce', nonce);

              $state.go('app.confirm');

            }

          });

      });

    });

**Comment by crookedneighbor** [comment]
I am unable to reproduce your issue. It works just fine for me: http://codepen.io/braintree/pen/d0bf6a003f86c16d7e92f661af5fec76

Can you confirm whether the provided link works for you on your device?

**Comment by crookedneighbor** [comment]
@MrGonc We haven't heard from you, so I'm assuming you figured out what your issue was. I'm going to close this now, but feel free to re-open if you need further assistance.
