### ISSUE TITLE
PayPal in WebView

### ISSUE THREAD

**Issue by dmalis** [braintree/braintree-web#277]
### General information

* SDK version: 3.11.1
* Environment: production
* Browser and OS: android Facebook app  

I thought 3.10.0 introduced webview support for PayPal, but braintree.paypal.create is still throwing the following error: 
name: BrainreeError
code: PAYPAL_BROWSER_NOT_SUPPORTED
message: Browser is not supported
type: CUSTOMER

**Comment by crookedneighbor** [comment]
3.10.0 added a helper method to detect in advance if a browser is supported: http://braintree.github.io/braintree-web/current/module-braintree-web_paypal.html#.isSupported

```js
if (braintree.paypal.isSupported()) {
  // set up PayPal
} else {
  // skip setting up PayPal
}
```

3.11.0 added support for webviews to the [PayPal Checkout component](http://braintree.github.io/braintree-web/current/module-braintree-web_paypal-checkout.html), which is a separate component that is used in conjunction with [PayPal's checkout.js library](https://github.com/paypal/paypal-checkout).
