### ISSUE TITLE
braintree.api.Client should be its own module.

### ISSUE THREAD

**Issue by arenoir** [braintree/braintree-web#28]
I am disappointed in the implementation of this lib. The size, number of dom bindings and only offering a minimized/uglified version is IMO insulting.  There should be a way to extract the client module? 

Braintree is for developers?  

Help me keep my applications lean.

**Comment by mrak** [comment]
Thank you for the feedback, @arenoir.

Could you tell us a little more about your integration and usage of Braintree's APIs? Are you using our __v.zero__ integrations?
Are you including braintree via a `<script>` tag, AMD, or CommonJS?

We currently do not provide unminified files through `npm` or `bower`, but you can link against our hosted assets that are unminified. See https://github.com/braintree/braintree-web/issues/1#issuecomment-75969617 for specifics.

Also, are you primarily developing for desktop or mobile web?

**Comment by arenoir** [comment]
@mrak thanks for the response.  I am using the v.zero script in a ember.js application.  

Currently I am lazily loading the v.zero script when transitioning to a route using the following [method](http://madhatted.com/2013/6/29/lazy-loading-with-ember).  

I don't like loading external scripts.  I am planning on transpiling the v.zero modules I am using `tokenizeCard` into my application. 

I have a version of my application for desktop and mobile web.  Credit cards are only entered on the desktop.

**Comment by mrak** [comment]
Since you are loading braintree on-demand in a single-page applications, take care not to call `braintree.setup()` more than once (it sounds like you are not calling it at all).

`braintree.api.Client` at this time needs some of the other machinery offered by other parts of braintree.js, so you may see some issues if you manage to extract it out and transpile it into your code.

The use of a lower-level, leaner library for integrating braintree is often requested, so we'll keep this issue open to track it.

**Comment by kyledetella** [comment]
As of right now there are no plans to release the `braintree-api` library as a separate module. Given the recent changes with regards to PCI, in order for a merchant to be eligible for [SAQ-A](https://www.pcisecuritystandards.org/documents/Understanding_SAQs_PCI_DSS_v3.pdf) compliance, sensitive cardholder data cannot be collected from the merchant's page.

From our [Hosted Fields](https://developers.braintreepayments.com/javascript/guides/hosted-fields/overview) documentation:

> For a merchant to be eligible for the easiest level of PCI compliance—SAQ A—payment fields cannot be hosted on your checkout page. All payment fields (credit card number, CVV, and expiration date) must be hosted on an external payment gateway's domain and presented to the user in a frame or with a redirect.

For this reason, we encourage the use of [Hosted Fields](https://developers.braintreepayments.com/javascript/guides/hosted-fields/overview) or [Drop-in](https://developers.braintreepayments.com/javascript/guides/drop-in) when using a `braintree.js` integration.

You are still welcome to use a `braintree.api.Client` to tokenize cards, but that functionality will remain bundled with `braintree.js`.
