### ISSUE TITLE
customising select hosted field

### ISSUE THREAD

**Issue by eranCo** [braintree/braintree-web#280]
* SDK version: 3.9.0

Hi, we're using two select elements to get the month/year expiration date with the hosted fields api. Everything works as expected but we would like the ability to customize it a little further:
1.  Initialize the select with a selected value, for example choose current month and year on start up.
2. Support appearance css property so we can better design the select object.

Is any of this use cases possible right now or will be possible in the near future?

Thanks!

**Comment by crookedneighbor** [comment]
Regarding number 1, if you leave off the optional placeholder parameter the month and year will default to the current month and year. We'll update the documentation to make this clearer.

We'll review supporting `appearance` and get back to you.

**Comment by eranCo** [comment]
thanks, looking forward to hearing from you

**Comment by quinnjn** [comment]
Hi @eranCo we added support for the `appearance` CSS tag in our [3.12.0 release](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#3120).

Closing this issue.
