### ISSUE TITLE
calling hosted fields create without callback throws an error

### ISSUE THREAD

**Issue by eranCo** [braintree/braintree-web#281]
* SDK version: 3.9

Hi, the documentation state that if you call hosted fields create function without a callback, it will resolve as a promise instead (and I assume also reject will an error).

However, when I try calling it without a callback I get the following error:
`{
  "name": "BraintreeError",
  "code": "CALLBACK_REQUIRED",
  "message": "create must include a callback function.",
  "type": "MERCHANT"
}`

Please advice. Thanks.

**Comment by crookedneighbor** [comment]
That functionality was added in [version 3.11.0](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#3110). Just upgdrade from 3.9.0 to 3.11.0 or higher and you should be all set.
