### ISSUE TITLE
paypal popup closed not firing callback

### ISSUE THREAD

**Issue by 719media** [braintree/braintree-web#282]
using the paypal class, the PAYPAL_POPUP_CLOSED is no longer fired when the paypal popup is closed by using the browser close button. in fact, the callback is not hit at all. tested in latest firefox, chrome, and safari.

it still fires when the paypal cancel link is clicked. i tested and this is working in 3.11.1 but stopped working in 3.12.0

**Comment by quinnjn** [comment]
Thanks for the report! We're looking into it, stay tuned.

**Comment by quinnjn** [comment]
@719media We just released [3.12.1](https://github.com/braintree/braintree-web/blob/3.12.1/CHANGELOG.md#3121) which fixes PayPal not detecting the popup being closed.

Sorry for any inconvenience that this may have caused. Closing this issue.
