### ISSUE TITLE
Hosted Fields focus event and focus css classed not aplied when changing fields using Tab key

### ISSUE THREAD

**Issue by msmolka** [braintree/braintree-web#283]
### General information

* SDK version: 3.11.1
* Environment: Sandbox
* Browser and OS: Firefox 52 Windows 10 Pro

### Issue description

When changing fields using Tab key in keyborad focus event is not fired, also focus classes are not applied on hosted fields when using keyboard.

**Comment by crookedneighbor** [comment]
Thanks for the report. Tested this in Chrome and it works fine, tested this in Firefox and was able to reproduce the behavior.

We'll look into it.

**Comment by crookedneighbor** [comment]
This is fixed in 3.13.0 https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#changelog
