### ISSUE TITLE
PayPal payment overlay in v3 API

### ISSUE THREAD

**Issue by adwil13** [braintree/braintree-web#285]
### General information

* SDK version: 3.12.1
* Environment: Sandbox

### Issue description

I'm rewriting our braintree implementation from v2 to v3 and .bt-overlay is no longer automatically added on paypal popup open. Am I doing something wrong or it just has been removed from V3?

My implementation right now:

	Order.braintreeClient((client) => {
		BraintreePaypal.create({
			client: client
		}, (paypalErr, paypalInstance) => {
			if (paypalErr) {
				return Order.errorPaymentProvider();
			}
				if (_.isPayPal && _.isLogged) {
				paypalInstance.tokenize(Order.getPayPalOptions(), (tokenizeErr, payload) => {
					if (Helper.isObject(tokenizeErr) && tokenizeErr) {
						return Order.errorPaymentProvider();
					}
						//send nonce to server
				});
			}
		});
	});

**Comment by crookedneighbor** [comment]
V3 is designed to provide as little UI as possible, so you can make it look however you want to match the look of your website. 

If you want a ready made UI, I suggest using the [PayPal Checkout component](http://braintree.github.io/braintree-web/current/module-braintree-web_paypal-checkout.html) instead with PayPal's [checkout.js library](https://github.com/paypal/paypal-checkout).
