### ISSUE TITLE
returnUrl/cancelUrl being rejected by paypal-checkout

### ISSUE THREAD

**Issue by lkb2k** [braintree/braintree-web#286]
### General information

* SDK version: 3.12.1
* Environment: sandbox
* Browser and OS: any

### Issue description

Last week, calls to PayPal-checkout createPayment were working fine, but as of today, they are failing.

The code block:
```javascript
payment: function () {
	return client.createPayment({
		flow:                  'checkout',
		intent:                'authorize',
		displayName:           '',
		amount:                10.00,
		currency:              'USD',
		locale:                'en_us',
		enableShippingAddress: true,
		enableBillingAddress:  true

	});
}
```

Generates a POST to: https://api.sandbox.braintreegateway.com/merchants/_merchantid_/client_api/v1/paypal_hermes/create_payment_resource

Which returns the following error.

```json
{
    "paymentResource": {
        "errorName": "VALIDATION_ERROR",
        "errorMessage": "Invalid request - see details --- cancel_url:{Url}|return_url:{Url}",
        "errorDetails": [
            {
                "field": "redirectUrls.returnUrl",
                "issue": "{Url}"
            },
            {
                "field": "redirectUrls.cancelUrl",
                "issue": "{Url}"
            }
        ],
        "debugId": "",
        "paypalHttpStatus": 400
    }
}
```

I see the following in paypal-checkout, but no way to override them to see it resolves the issue.
```
  var paymentResource = {
    // returnUrl and cancelUrl are required in hermes create_payment_resource route
    // but are not validated and are not actually used with checkout.js
    returnUrl: 'x',
    cancelUrl: 'x',
```

**Comment by crookedneighbor** [comment]
Thanks for reporting. This is happening because PayPal started validating `returnUrl` and `cancelUrl`. We are aware of this issue and are working to get it resolved. We'll update this issue when it is fixed.

**Comment by crookedneighbor** [comment]
This has been fixed in Sandbox. We're working on prod now.

**Comment by crookedneighbor** [comment]
This is now fixed in production. Thanks for your patience!
