### ISSUE TITLE
onFieldEvent in 3.x.x?

### ISSUE THREAD

**Issue by kevinhikaruevans** [braintree/braintree-web#287]
### General information

* SDK version: 3.12.1
* Environment: n/a
* Browser and OS: n/a

### Issue description

I'm migrating from 2.x.x to 3.12.1. In our project, we were using onFieldEvent in hosted fields to make the form prettier when the user begins entering in their card information and also disable form submission for certain card types. Does this callback exist in 3.x.x or is there a replacement for it?

Thanks!

**Comment by crookedneighbor** [comment]
You're looking for `on`. Here are the docs: http://braintree.github.io/braintree-web/current/HostedFields.html#on

You can listen for blur, focus, empty, notEmpty, cardTypeChange, or validityChange.
