### ISSUE TITLE
ERROR: "PayPal payment options are invalid"

### ISSUE THREAD

**Issue by imajus** [braintree/braintree-web#288]
* SDK version: Node, braintree-web@3.12.1
* Environment: Production
* Browser and OS: Reproducible on different systems

I'm getting the `PAYPAL_INVALID_PAYMENT_OPTION` error with the message "PayPal payment options are invalid" when I try to get PayPal authorization. PayPal dialog won't event open due to this error.

Just before this error appears I can see the following in my Chrome console: `POST https://api.braintreegateway.com/merchants/dzwnspprskyyvtm3/client_api/v1/paypal_hermes/create_payment_resource 422 (Unprocessable Entity)`

The same piece of code works fine on Sandbox environment. Seems like Braintree account misconfiguration for me but Googling the error code or message gave me nothing and I don't even know where to start digging to get any clue.

Here's where you may reproduce the error: https://airoko.com/pay/d8daHpCDE8uojP49b
However I'm not sure if it will help, the source code there is minified.

**Comment by imajus** [comment]
The problem was in options object passed to `paypal.tokenize`.

**Comment by Barabasse88** [comment]
Hello,

I have the following errors when I click on the Paypal Pay button:

Error: Error: PayPal payment options are invalid. at Object._RECEIVE_MESSAGE_TYPE. (anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:2936:122) at receiveMessage (https://www.paypalobjects.com/api/checkout .js: 2835: 77) at messageListener (https://www.paypalobjects.com/api/checkout.js:2856:13)

Can you explain to me how to solve these errors?

Thanks for your help.

**Comment by crookedneighbor** [comment]
For the record, @Barabasse88 opened a new issue at #336

**Comment by Serbiaguy96** [comment]
@imajus Hello, i have the same problem while i am trying co create paypal payment instance. Can you pleas tell me, how exactly did you solve the problem with options object?

Thank you for your help and time.

**Comment by crookedneighbor** [comment]
@Serbiaguy96 It'd be best to contact our support team with your client side code. They can help you figure out where you're going wrong: https://articles.braintreepayments.com/forms/contact
