### ISSUE TITLE
touching date select element on mobile devices print errors in console

### ISSUE THREAD

**Issue by eranCo** [braintree/braintree-web#289]
### General information

* SDK version: 3.12.1
* Environment: mobile devices
* Browser and OS: Safari, iOS
### Issue description

steps to reproduce:
1. open hosted field form with select elements for expiration dates.
2. touch on of the select elements.
3. error will be printed in console. Everything else works fine.

Cause of the bug:
Look at base-input.js, line 147:
You're calling element.select() function on touchstart event, but .select() only available on input elements, select element doesn't have that functionality.

Screenshots:
![screen shot 2017-04-26 at 2 52 12 pm](https://cloud.githubusercontent.com/assets/21173652/25433143/16c40e32-2a90-11e7-96a6-8256aeeab5a5.png)
![screen shot 2017-04-26 at 2 52 24 pm](https://cloud.githubusercontent.com/assets/21173652/25433156/20c3c3aa-2a90-11e7-845d-39061f727384.png)

**Comment by crookedneighbor** [comment]
Thanks for the report. Working on fixing this now.

**Comment by crookedneighbor** [comment]
This is fixed in 3.15.0.

Thanks for the report!
