### ISSUE TITLE
reproduce hosted fields tokenize error flow

### ISSUE THREAD

**Issue by sashakru** [braintree/braintree-web#291]
According to [hosted field tokenize](https://braintree.github.io/braintree-web/current/HostedFields.html#tokenize) documentation there is number of errors that occurs during `tokenize`: 
```
HOSTED_FIELDS_FAILED_TOKENIZATION
HOSTED_FIELDS_TOKENIZATION_FAIL_ON_DUPLICATE
HOSTED_FIELDS_TOKENIZATION_CVV_VERIFICATION_FAILED
HOSTED_FIELDS_TOKENIZATION_NETWORK_ERROR
```

Is there any way to reproduce this kind of erros? 
Tried some of the combinations from this [list](https://developers.braintreepayments.com/reference/general/testing/ruby#test-amounts), but with without success.

**Comment by crookedneighbor** [comment]
Sounds like it could be useful to go more in depth in that documentation for how to trigger those errors. In the meantime, here's an explanation for each.

## HOSTED_FIELDS_CVV_VERIFICATION_FAILED

One way to trigger this is to generate a client token with a [customer_id](https://developers.braintreepayments.com/reference/request/client-token/generate/ruby#customer_id) and the [verify_card option](https://developers.braintreepayments.com/reference/request/client-token/generate/ruby#options.verify_card). Then use one of the test CVVs that returns a failure [listed here](https://developers.braintreepayments.com/reference/general/testing/ruby#avs-and-cvv/cid-responses). If you try to vault the card (with `vault: true` in the tokenization options) with a bad CVV (such as `200` with a visa), it'll return this error.

Alternatively, you can enable [CVV checking in your fraud rules](https://articles.braintreepayments.com/support/guides/fraud-tools/basic/overview#enabling-avs-and-cvv-rules) then input the CVVs [listed here](https://developers.braintreepayments.com/reference/general/testing/ruby#avs-and-cvv/cid-responses). If you tokenize with a bad CVV, it will return this error.

## HOSTED_FIELDS_TOKENIZATION_FAIL_ON_DUPLICATE

For this, you must generate a client token with both a [customer_id](https://developers.braintreepayments.com/reference/request/client-token/generate/ruby#customer_id) and the [fail_on_duplicate_payment_method option](https://developers.braintreepayments.com/reference/request/client-token/generate/ruby#options.fail_on_duplicate_payment_method). Then, when tokenizing, include the `vault: true` option. If the card you are tokenizing already exists in your vault, it will fail.

## HOSTED_FIELDS_TOKENIZATION_NETWORK_ERROR

This occurs when the Braintree Gateway cannot be reached. One way to reproduce this is to load your page with hosted fields, fill out the form, and then disconnect your internet before proceeding with tokenization.

## HOSTED_FIELDS_FAILED_TOKENIZATION

Any other other falls under this category.

**Comment by lilaconlee** [comment]
We've updated the [Hosted Fields reference](https://braintree.github.io/braintree-web/current/HostedFields.html#tokenize) to clarify some of the error behavior. Thanks for the feedback and as always let us know if you have any ideas for improving our documentation!
