### ISSUE TITLE
CLIENT_INVALID_AUTHORIZATION in Edge browser

### ISSUE THREAD

**Issue by robinmbarnes** [braintree/braintree-web#292]
### General information

* SDK version: 3.11.1
* Environment: Sandbox
* Browser and OS Edge V15 on Windows 10 (virtual machine via browserstack)

### Issue description

The library fails when trying to authenticate a paypal token. The error is:

code: 'CLIENT_INVALID_AUTHORIZATION'
message: Authorization is invalid. Make sure your client token or tokenization key is valid.

This works fine in other browsers. I also noticed that the library seems to add an iframe and make various requests in other browsers (I don't know the details, I didn't do the integration myself). I see no evidence this happens in edge.

**Comment by crookedneighbor** [comment]
I'm pretty sure this is an issue that was fixed in [3.12.0](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#3120). Please upgrade to the latest version (3.14.0) and comment here if the issue persists. For now, I'm going to close this issue.

**Comment by arahant** [comment]
Hi,
I'm getting the same error. I had used braintree in Jan and it was working fine, but now it's throwing the same error.
The server-side token generation works fine, but on the client side, it doesn't.

**Comment by crookedneighbor** [comment]
@arahant Please reach out to Braintree support with the details of your integration. A reproducible example would be ideal.

https://help.braintreepayments.com/
