### ISSUE TITLE
Should I use paypal checkout or paypal? 

### ISSUE THREAD

**Issue by Senjai** [braintree/braintree-web#293]
### General information

* SDK version: 
3.14
* Environment: 
Sandbox
* Browser and OS 
Not relevant

### Issue description

As a developer working on an extension to support this for our stores, I'm confused as to why two seperate API's are offerd for paypal. We're currently using `braintree-web.paypal` but all official v3 docs reference `braintree-web.paypalCheckout`. `paypal` seems to work for what we aim to accomplish here, but I wouldn't know why I would want to use one over the other.

Is there a chance someone could help clear this up for me and in doing so we might be able to update documentation to reflect these differences.

**Comment by crookedneighbor** [comment]
Hi @Senjai,

The PayPal Checkout component is the preferred method for integration. The PayPal component will continue to work, but any new features will only be added to the PayPal Checkout component.

The basic difference between the two is that the PayPal component requires you to manage any UI for preventing your customer from interacting with your page while the PayPal popup is open, while the PayPal Checkout component (along with checkout.js) manages all the UI for you.

Thanks for the feedback. We'll do some work to make the documentation clearer.
