### ISSUE TITLE
2.32 SDK is broken in Firefox54

### ISSUE THREAD

**Issue by Antwan86** [braintree/braintree-web#294]
### General information

* SDK version: 2.32
* Environment: Sandbox
* Browser and OS: MacOS 10.12.5, Firefox 54b8
### Issue description

When loading the SDK library v2.32 under the latest firefox beta, several failures appear in log (but UI is working).
```
TypeError: h.getComputedStyle(...) is null[Learn More]  modernizr.js:4:1131
ReferenceError: Modernizr is not defined[Learn More]  braintree-dropin-internal.min.js:9:30623
TypeError: braintree.dropin is undefined[Learn More]  modal-frame.html:19:11
```

It is thereafter not possible to change payment method once saved in client vault. 
Clicking on "change payment method" results in error :
```
TypeError: e.frames.modal.rpcClient is undefined[Learn More]  braintree-2.32.0.min.js:5:29054
```

**Comment by crookedneighbor** [comment]
Thanks for reporting this. We've replicated it and are looking into it now.

**Comment by crookedneighbor** [comment]
Version 2.32.1 includes a fix for this bug. Thanks for the report!

**Comment by Antwan86** [comment]
Great thanx
