### ISSUE TITLE
Loading two versions of braintree/browser-detection

### ISSUE THREAD

**Issue by stonebk** [braintree/braintree-web#297]
### General information

* SDK version: 3.16.0
* Environment: All
* Browser and OS: All

### Issue description

braintree-web requires braintree/browser-detection#1.3.0
braintree-web dependency restricted-input requires braintree/browser-detection#1.1.0

Can you update your dependencies so we are not loading two different versions of browser-detection? Thanks!

**Comment by crookedneighbor** [comment]
Thanks for the report. This is because one of our dependencies is using v1.1.0 https://github.com/braintree/restricted-input/blob/master/package.json#L37

We'll get that fixed in the next release.

We'll write a test that makes sure we don't duplicate these dependencies in the future.

**Comment by stonebk** [comment]
Is there a reason why you are using github dependencies rather than using regular version numbers? I updated braintree-web to 3.17.0 to pick up the fix, but now it's just downloading two versions of browser-detection#1.4.0 (I'm guessing because they are github dependencies):

    Duplicate module browser-detection
            ./node_modules/braintree-web/node_modules/browser-detection
            ./node_modules/braintree-web/node_modules/restricted-input/node_modules/browser-detection

**Comment by crookedneighbor** [comment]
browser-detection is a github dependency because it is specific to Braintree's browser detection needs and not intended for wide use. Therefore, we haven't published it to npm.

We're talking internally about moving it to a scoped package, which would still allow us to designate it as recommended for Braintree's use only, but would alleviate the double dependency problem.

**Comment by stonebk** [comment]
Sure, that makes sense. A scoped package would be great! +1

**Comment by crookedneighbor** [comment]
Just published https://www.npmjs.com/package/@braintree/browser-detection

This will _actually_ be resolved in the next release. Thanks for bringing it up! 

I wasn't aware that Github dependencies behaved differently than npm dependencies.

Gonna re-open this issue until the release happens.

**Comment by stonebk** [comment]
Duplicate dependencies gone! Thanks!

**Comment by crookedneighbor** [comment]
:+1:
