### ISSUE TITLE
Accepted Card Validator

### ISSUE THREAD

**Issue by muhammad-ammar** [braintree/braintree-web#299]
### General information

* SDK version: 3.8.0

### Issue description

Is there any way i can add a custom validator for acceptable cards? For example, my merchant account accepts `Discover`, `MasterCard`, `Visa` and `Maestro` but hostedfields can detect other cards like `American Express` and mark them as valid. Currently the only thing i can do is to detect card type in `validityChange`, `cardTypeChange` and other events and add `braintree-hosted-fields-invalid` class to card number field to mark the input as invalid.

Is there any other better way to achieve the above instead of setting classes?

**Comment by muhammad-ammar** [comment]
Can't we inject/register a custom validator for a field in such a way that `getState` will return `isValid` set to `false` for that particular field?

**Comment by crookedneighbor** [comment]
We should not inject any functions into the Hosted Fields iframes. Allowing an arbitrary JavaScript function to run in the iframe would compromise the security of the frame. So any function that runs would need to be external from the iframe, and is pretty much equivalent to the handling you're already doing.

For the card supported card type question, that's exactly what we do in [braintree-web-drop-in](https://github.com/braintree/braintree-web-drop-in/blob/baabea36f19997191a897747e53a1445c2a8603a/src/views/payment-sheet-views/card-view.js#L331-L353), we check for the card validity of the form and then add an extra check for if the card is supported.

I can see the argument for having hosted fields check supported card types when checking validity. We'll discuss it as a team.

Are there other validity checks you're trying to do? Or is the supported card types one the only one?

**Comment by muhammad-ammar** [comment]
@crookedneighbor Thanks a lot for detailed response.

I should be more clear. I think inject is not the correct word. What i mean is that hostedfields can provide an elegant way to do extra custom validation as per developers requirement. And by elegant i mean developer provided validator should not touch anything related o iframe. I have already mentioned one such scenario above where i only want to allow input of cards accepted by my merchant account instead of all the cards accepted by hostedfields api.  

Thanks for providing the link to source file. It looks like [_isCardTypeSupported](https://github.com/braintree/braintree-web-drop-in/blob/baabea36f19997191a897747e53a1445c2a8603a/src/views/payment-sheet-views/card-view.js#L380) only checks that card is accepted by braintree gateway. What if it only checks that card is supported by merchant account or not?

In addition to checking the accepted cards, CVV field also needs extra validation because its length is different for Visa vs American Express. So if i don't want to allow american express cards then i will also restrict CVV field.

**Comment by crookedneighbor** [comment]
`_isCardTypeSupported` is checking against the supported processor connections in the merchant account in the Braintree gateway, not against all of the possible card types that the gateway supports.

The security code field should automatically adjust the length when the card type is detected. If you are certain that you do not need to process any cards that take 4 digit security codes, you can set [the maxlength of the cvv](http://braintree.github.io/braintree-web/current/module-braintree-web_hosted-fields.html#~field):

```js
braintree.hostedFields.create({
  // other options
  fields: {
    // other fields
    cvv: {
      selector: '#my-cvv-selector',
      maxlength: 3
    }
  }
}, callback);
```

**Comment by muhammad-ammar** [comment]
I have upgraded to `3.17.0` and `maxlength` is working but in `validityChange` event, american express card is validated to true. Below is my `validityChange` event handler

```javascript
hostedFieldsInstance.on('validityChange', function (event) {
    var formValid = Object.keys(event.fields).every(function (key) {
        return event.fields[key].isValid;
    });

    if (formValid) {
        $('.button-pay').removeAttr('disabled');
    } else {
        $('.button-pay').attr('disabled', true);
    }
});
```
 
Strange thing is that american express is not present in supported cards as per the configuration. Please see the screenshot.

<img width="1228" alt="screen shot 2017-06-03 at 12 01 16 am" src="https://cloud.githubusercontent.com/assets/6767924/26740650/d461976c-47ef-11e7-8b2e-6873a7fcfb27.png">

What i am doing wrong?

**Comment by crookedneighbor** [comment]
I'm going to close this now, but if you're still having trouble, feel free to comment here and I'll re-open it.
