### ISSUE TITLE
dropin iframe should have a name

### ISSUE THREAD

**Issue by tjgrathwell** [braintree/braintree-web#3]
I'm trying to write some integration tests against an application that uses the braintree dropin thingie, and I'm running into trouble because the iframe it creates doesn't have a "name" attribute.

In PhantomJS/poltergeist, if you do this:
```
page.within_frame('braintree_frame') do
  fill_in 'Card Number', with: '...'
end
```
it will only work if the name "braintree_frame" had been assigned **before** the iframe was added to the document (this seems like a phantom/poltergeist bug). There doesn't seem to be any other way for poltergeist to interact with the iframe.

So that's all a bunch of hullabaloo all just to say it would make things easier if the braintree-web javascript assigned that iframe a name. Or made it a configuration option, whatever.

**Comment by jeffcarp** [comment]
Hey @tjgrathwell, I'm sorry, I couldn't quite keep that promise going into the holiday season. Did you find a way around the problem?

**Comment by pdg137** [comment]
I am encountering this problem as well, and I see no way around it without modifying braintree.js.  Attempting `within_frame find('iframe')` returns

    Capybara::Poltergeist::FrameNotFound Exception: The frame '' was not found.

But it appears to work fine if I add this line to the function `FramecContainer`:

```javascript
this.element.name = 'braintree_iframe';
```

**Comment by kyledetella** [comment]
@tjgrathwell @pdg137 we have a fix for this that should be deployed to production soon. I will let you know when it is out.

**Comment by pdg137** [comment]
Has there been any progress on this?  It seems like such an easy fix.  I haven't seen any updates to this project, so I'm wondering if it's still alive or if braintree.js is going to get replaced by something else.

**Comment by kyledetella** [comment]
@pdg137 sorry for the delay. This is going to be deployed early next week with a batch of other updates. I will update here when it is ready.

**Comment by kyledetella** [comment]
@pdg137 this has been deployed with the latest version (`2.5.0`). The iFrame names will be `braintree-dropin-frame` and `braintree-dropin-modal-frame`. Hope it helps and sorry for the delay.

**Comment by kyledetella** [comment]
I am going to close this since it has been deployed. If anyone runs into more issues, feel free to re-open.
