### ISSUE TITLE
Does onPaymentMethodReceived gets fired with token generated from sandbox credentials

### ISSUE THREAD

**Issue by avidas** [braintree/braintree-web#30]
The sandbox iframe seems to generate mock data for shipping address/card/paypal account validation when a token generated using sandbox credentials is used. On client side, does onPaymentMethodReceived still get triggered with a payload with nonce, shipping address etc that can be sent to server side? Or can it be tested only with live credentials?

**Comment by mrak** [comment]
`onPaymentMethodReceived` should fire while using a sandbox account. The only difference will be that the values in the `payload` may be mock data.

**Comment by avidas** [comment]
Working now thanks, closing
