### ISSUE TITLE
Braintree Drop in Issue in ie with angularjs

### ISSUE THREAD

**Issue by nuttyroll** [braintree/braintree-web#302]
We have been trying to integrate braintree dropin in ie11 but the form never loads. Here is the url for the same
https://staging.healthlynked.com/#!/doctors/login?plan=STANDARD.

**Comment by crookedneighbor** [comment]
I was able to load Drop-in on your site in IE11.  

![healthlynked](https://user-images.githubusercontent.com/2916945/26982438-09e65a22-4cfe-11e7-9775-d6f7ae7f257c.gif)

Are there any console messages?

Can you provide the exact version and build of your version of IE11? Can you try running any software updates that are available?

Also, are you able to view the demo site in your copy of IE11? https://braintree.github.io/braintree-web-drop-in/

**Comment by nuttyroll** [comment]
Hi, It seems the error was on my side I was using flex feature in IE which was hiding the content. Thanks allot for the prompt reply.

**Comment by crookedneighbor** [comment]
:+1: Glad you figured it out.
