### ISSUE TITLE
Difficulty in doing unit-testing in node environment.

### ISSUE THREAD

**Issue by ohpyupi** [braintree/braintree-web#303]
### General information

* SDK version:  3.18
* Environment:  Sandbox
* Browser and OS  Node.js and Unbuntu

### Issue description

Hi,

I am currently working on braintree integration to an application. I made a unit testing script in node.js end for convenience. However, it raises lots of errors because of the lack of very browser-specific objects and methods, for example 'global (window)' and  'XDomainRequest'. It seems like braintree-web module collects user's metadata and send it to the braintree server when it creates a client object.
 
All I just wanna check is whether a client object is created well or not from a given client token. Is there any workaround to do unit-testing on braintree-web module in node.js environment? Or I think it would be nice if we have an option to turn on or off the feature to collect metadata when testing or development mode.

Thanks.

**Comment by sashaweiss** [comment]
Braintree-web is designed to in a browser. If you want to verify that a client is properly created from a particular token, it sounds like you're more interested in an integration test, which would run using a browser in sandbox, which in turn would fix the issue you described.

To unit-test around braintree-web we recommend mocking braintree-web itself, e.g. verifying your client token going into the client.create call:
``` javascript
it('passes a Client Token to braintree.client.create', function (done) {
  var fakeBraintreeClient = {
    getConfiguration: function () {},
    getVersion: function () {},
    request: function () {}
  };

  sinon.stub(braintree.client, 'create').resolves(fakeBraintreeClient);

  braintree.client.create({
    authorization: CLIENT_TOKEN
  }).then(function (clientInstance) {
    // Continue using fakeBraintreeClient
    console.log(clientInstance);

    done();
  });

  // Check that your Client Token is what you expect
  expect(braintree.client.create).to.have.been.calledWith({
    authorization: CLIENT_TOKEN
  });
});
```

**Comment by crookedneighbor** [comment]
Another option would be to use a test runner like Karma that runs within a browser or browser-like environment.

**Comment by crookedneighbor** [comment]
I'm going to close this now, but comment here if you need additional assistance.

**Comment by ohpyupi** [comment]
Thanks!

**Comment by rparsi-boxycharm** [comment]
@crookedneighbor Is there an example or guide to show how to mock braintree-web with jestJS?  Am browsing the braintree-web code but can't tell what I should be mocking.  I need to fake the client, dataCollector and paypalCheckout such that it loads without errors (the test isn't going to trigger actual braintree/paypal api calls)

**Comment by crookedneighbor** [comment]
Given a file like this:

```js
const client = require("braintree-web/client");
const hf = require("braintree-web/hosted-fields");

module.exports = function init () {
  return client.create({
    authorization: 'token'
  }).then((clientInstance) => {
    return hf.create({
      client: clientInstance,
      // other configs
    }).then((hfInstance) => {
      const button = document.createElement('button');
      button.id = "submit";
      document.body.appendChild(button);

      button.addEventListener('click', () => {
        hfInstance.tokenize();
      });
    });
  });
};
```

You could test it like this:

```js
/**
 * @jest-environment jsdom
 */
jest.mock("braintree-web/client");
jest.mock("braintree-web/hosted-fields");

const client = require("braintree-web/client");
const hf = require("braintree-web/hosted-fields");
const init = require("./");

describe("mocking braintree-web", () => {
  let fakeClient, fakeHF;

  beforeEach(() => {
    fakeClient = {};
    fakeHF = {
      tokenize: jest.fn()
    };
    client.create.mockResolvedValue(fakeClient);
    hf.create.mockResolvedValue(fakeHF);
  });

  afterEach(() => {
    // reset body DOM after every test
    document.body.innerHTML = "";
  });

  it("creates a hosted fields instance", () => {
    return init().then(() => {
      expect(client.create).toBeCalledTimes(1);
      expect(client.create).toBeCalledWith({
        authorization: 'token'
      });
      expect(hf.create).toBeCalledTimes(1);
      expect(hf.create).toBeCalledWith({
        client: fakeClient
      });
    });
  });

  it("tokenizes when button is clicked", () => {
    return init().then(() => {
      const btn = document.getElementById("submit");

      btn.click();

      expect(fakeHF.tokenize).toBeCalledTimes(1);
    });
  });
});
```
