### ISSUE TITLE
Hosted field freezes after moving cursor on iPhone

### ISSUE THREAD

**Issue by phllipo** [braintree/braintree-web#305]
### General information

* SDK version: 3.19.1 
* Environment: Sandbox and Production
* Browser and OS: In APP React Web View on iPhone 7 with iOS 10.3.2

### Issue description

We are using a React Web View in our App to render a credit card form using your hosted fields.
When you type something in one of the hosted fields and then move the cursor to a different position, you can not type anything anymore in the field.
You then have to click outside the field and inside again to continue editing.
See the video: http://screenshots.jonas.re/tnTDZ8nJJj.m4v for clarification.

Any Idea why this happens?
Does it have something to do with React or the Web View being rendered in App?
Because I couldn´t reproduce this behaviour in the hosted fields examples.

**Comment by crookedneighbor** [comment]
I believe it has to do with being in a webview. Safari webviews have some buggy behavior in regard to selection events.

**Comment by phllipo** [comment]
Hm then it´s still kinda weird to me that the card holder input that we control ourselfs works just fine.

**Comment by phllipo** [comment]
Okay one step closer to identifying the Problem.
It seems to have something to do with being in App, because I just tried our View in Safari on the Phone and can´t reproduce the behaviour there.

**Comment by crookedneighbor** [comment]
What kind of webview are you using? WK or UI? 

Can you put a demo app (with instructions for running it) that reproduces the behavior on Github? We're happy to take a look if we have a way to reproduce it.

**Comment by phllipo** [comment]
Ok looks like we found the Problem. Thanks for the Tip about what WebView we are using.
There is a known Bug when using inputs inside iframes in UIWebView. See https://bugs.webkit.org/show_bug.cgi?id=133044
Seems to have something to do with the touchstart event, but the best solution seems to be switching to WKWebView if you don´t need to support iOS versions below 8.0.

**Comment by crookedneighbor** [comment]
Awesome, thanks for the update.
