### ISSUE TITLE
Cannot use a payment_method_nonce more than once.

### ISSUE THREAD

**Issue by Gardezi1** [braintree/braintree-web#306]
### General information

* Environment:  Sand Box 
* Browser and OS Chrome and Ubuntu 64 bit 

### Issue description

Hello, guys, I've started using your APi but I'm facing a problem and that is the second I try to do a payment it returns me an error `Cannot use a payment_method_nonce more than once`. Can you guys tell what is going wrong since I was reading in your issues and I think you fixed it 
```
import BrainTree from 'braintree-web'
var dropin = require('braintree-web-drop-in');

   var button = document.querySelector('#submit-button');

            if(nextProps.user.clientToken && nextProps.user.clientToken != null ) {
                dropin.create({
                    authorization: nextProps.user.clientToken,
                    container: '#dropin-container',
                    paypal: {
                        flow: 'vault'
                    }
                },  (createErr, instance) => {
                    let me = this;
                    button.addEventListener('click', function () {

                        if(instance != undefined) {
                            debugger;
                            // me.testFunction("1")
                            // Submit payload.nonce to your server
                            instance.requestPaymentMethod(function (err, payload) {

                                if (err) {
                                    console.log('Error', err);
                                    return;
                                }


                                // Add the nonce to the form and submit
                                // document.querySelector('#nonce').value = payload.nonce;
                                // form.submit();
                                debugger;
                                me.checkoutPayment(payload.nonce);
                            });

                        }
                    });
                });
            }

                        }
                    });](url)

```

**Comment by intelliot** [comment]
Hi @Gardezi1 -

That error means you're attempting to use the `nonce` more than once. The nonce is a one-time-use token and can only be used for one operation.

I see the following:
```
me.checkoutPayment(payload.nonce);
```

What does your `checkoutPayment` function do?

Typically, you would send the nonce to your server and create a transaction with `Transaction.sale`.

If you're using `PaymentMethod.create` to store the payment method with a customer, then you can use the resulting `token` to create a transaction.

Does this help?

**Comment by Gardezi1** [comment]
The checkourPayment method is sending ounce to the server for the transaction but I was going throught your documentation and there in some issue it was written that you guys solved the problem of ouce being generated once when this function is called but in the dropin this was not the case

**Comment by intelliot** [comment]
@Gardezi1 - I don't know which issue you're referring to. With Drop-in, the nonce is generated once `requestPaymentMethod` is called.

Has your problem been solved?

**Comment by crookedneighbor** [comment]
@Gardezi1 We haven't heard back from you, so I'm going to close this issue.

It sounds like a problem with your specific integration, not the SDK itself. If you're still having issues, please contact Braintree support for help. https://developers.braintreepayments.com/forms/contact

**Comment by otanand** [comment]
Hi,

I too have this issue on PWA studio headless storefront.
I will attach the screenshot of the code and its output.

![Screenshot from 2022-08-18 23-17-42](https://user-images.githubusercontent.com/33829229/185463498-ac5e7257-af95-4355-8d45-2e5a0b66005e.png)
![Screenshot from 2022-08-18 23-18-17](https://user-images.githubusercontent.com/33829229/185463503-7223a1af-40af-43a5-b703-886591c7f6f0.png)
![Screenshot from 2022-08-18 23-20-35](https://user-images.githubusercontent.com/33829229/185463506-72765acc-8705-4b19-8ca5-66b8f27e3472.png)
![Screenshot from 2022-08-18 23-21-11](https://user-images.githubusercontent.com/33829229/185463510-6838de43-bff6-46bd-a4db-e32c6728f7f7.png)

**Comment by MRVirus007** [comment]
> Hi,
> 
> I too have this issue on PWA studio headless storefront. I will attach the screenshot of the code and its output.
> 
> ![Screenshot from 2022-08-18 23-17-42](https://user-images.githubusercontent.com/33829229/185463498-ac5e7257-af95-4355-8d45-2e5a0b66005e.png) ![Screenshot from 2022-08-18 23-18-17](https://user-images.githubusercontent.com/33829229/185463503-7223a1af-40af-43a5-b703-886591c7f6f0.png) ![Screenshot from 2022-08-18 23-20-35](https://user-images.githubusercontent.com/33829229/185463506-72765acc-8705-4b19-8ca5-66b8f27e3472.png) ![Screenshot from 2022-08-18 23-21-11](https://user-images.githubusercontent.com/33829229/185463510-6838de43-bff6-46bd-a4db-e32c6728f7f7.png)
> 
> Is the code is correct or do i need to do anything else other than this ?

i know it's a very late reply, but still, if it helps someone, i am also facing the same issue and i guess we can only try to catch this specific error and then try to generate another token for the payment method.
