### ISSUE TITLE
Hosted Fields not updating with copy and paste

### ISSUE THREAD

**Issue by sjsnider** [braintree/braintree-web#308]
### General information

SDK version: 3.19.1
Environment: Sandbox
Browser and OS: Chrome , Mac 10.12.4

### Issue description

After successfully getting a nonce for a credit card with a number that is intended to error out I get the error from our server and use `hostedFieldsInstance.addClass(errField, 'invalid');` and `hostedFieldsInstance.focus(errField)` to mark the field that generated the error and then focus on it.  If the user starts deleting and typing in there the hosted fields will start updating valid and invalid accordingly.  If I just copy and paste another valid credit card number into the field nothing changes and the card number still shows as invalid I believe because there is never any recognition that the validity changed so no class names get added or removed within the iframe if that makes sense. Is there a way to make the field recognize that this is a change and do the update to the class for valid and invalid on the input?

Or am I able to set up a listener so that after I mark a field for error I can catch a change in the inputted value and resolve it myself?

Apologies if you wouldn't actually consider this an issue, but does seem to me that some sort of change should be recognized when pasting in a new and also valid card number, which there very well may be, but I've been unable to capture it.

**Comment by crookedneighbor** [comment]
Thanks for the report. I was able to reproduce this. We'll have a fix in the next release.

**Comment by sjsnider** [comment]
Great, thanks!

**Comment by crookedneighbor** [comment]
This is fixed in v3.20.0 https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#3200

**Comment by sjsnider** [comment]
Worked like a charm, thanks!
