### ISSUE TITLE
Create dist folder with minified files for Npm

### ISSUE THREAD

**Issue by judowalker** [braintree/braintree-web#309]
Please create a dist folder with the minified files (client.min.js, hosted-fields.min.js, data-collector.min.js, etc). I don't use `require` or any javascript dependency management tool. It would be nice to grab the minified file from the Npm package so I can avoid having to manually go to, for example, https://js.braintreegateway.com/web/3.19.1/js/client.min.js and downloading the file.

**Comment by crookedneighbor** [comment]
We'll keep your feedback in mind, but we're not going to include the built files as part of the `npm` module at this time. 

I've written a  small script to grab the latest version of braintree-web and downloads those files from the braintree cdn. You can edit the variables at the top to bring in what you need and put them where you need them to serve them on your website.

```js
'use strict';

var exec = require('child_process').exec;
var fs = require('fs');
var components = [
  'client',
  'hosted-fields',
  // put any other components you need to download here
];
// put the path to your public assets here
var pathToPublicAssets = '/absolute/path/to/public/assets/';

// get latest version of braintree-web
exec('npm view braintree-web version', function (err, version) {
  // remove new line character and white space so we have just the version number
  version = version.replace(/\s/g, '');

  components.forEach(function (component) {
    // grab the latest version from the braintree cdn
    exec('curl https://js.braintreegateway.com/web/' + version + '/js/' + component + '.min.js', function (err, code) {

      // write the file to your public assets folder
      fs.writeFile(pathToPublicAssets + component + '.min.js', code, function () {
        console.log('Copied braintree-web component', component, 'version', version + '.');
      });
    });
  });
});
```

**Comment by crookedneighbor** [comment]
v3.36.0 on npm includes a browser property in the package.json that points to a browserified version of the file.

See #366
