### ISSUE TITLE
behavior difference when enableShippingAddress set to true between dropin and paypal

### ISSUE THREAD

**Issue by avidas** [braintree/braintree-web#31]
Hi,

When enableShippingAddress is set to true for the 'paypal' container in braintree setup, the shipping address choice screen is displayed after clicking agree. However, when it is set to 'dropin' the shipping address selection screen is not displayed when paypal is chosen as a payment method. Is that intentional? I am using the sandbox.

**Comment by schneiderik** [comment]
Hey there @avidas,

Could you please post your `braintree.setup(...);` for the 'paypal' and 'dropin' integrations.

The 'dropin' integration requires the paypal options to be nested within a paypal nested object. Here's a link to the [specific docs](https://developers.braintreepayments.com/javascript+ruby/sdk/client/drop-in#paypal).

If you're already doing this and the shipping address selector is still not showing up, let me know and I will take a look at what's going on.
