### ISSUE TITLE
validityChange event returns false for expirationMonth & expirationYear when using them as selects

### ISSUE THREAD

**Issue by emukhin** [braintree/braintree-web#310]
### General information

* SDK version: 3.19.1
* Environment: both
* Browser and OS Version 59.0.3071.115 (Official Build) (64-bit) WIN64 PRO

### Issue description

1) open https://codepen.io/braintree/pen/MyzXqG/
2) Add select: true for mentioned fields so it looks like:
```expirationMonth: {
  selector: '#expiration-month',
  placeholder: 'MM',
  select: true
},
expirationYear: {
  selector: '#expiration-year',
  placeholder: 'YY',
  select: true
}
```
3) set date to invalid
4) set date to valid. it never becomes valid again.

**Comment by crookedneighbor** [comment]
This was an issue with the codepen, not the sdk. We were never clearing the `has-error` and `has-warning` classes when both inputs were valid. (the issue occurred in the text box version of expiration month and year too).

I've applied the fix in the codepen. https://codepen.io/braintree/pen/MyzXqG/

Thanks for the report!

**Comment by emukhin** [comment]
My bad. Thank you!
