### ISSUE TITLE
Braintree js v3 client: clientInstance passed to braintree.3dsecure.create

### ISSUE THREAD

**Issue by alenoosh** [braintree/braintree-web#311]
### General information

* SDK version: 3.0
* Environment: Sandbox
* Browser and OS : Chrome 54.0.2840.100 (64-bit) on Ubuntu 16.04

### Issue description

I'm using braintree v3 js client. I use drop-in ui to create the braintree client and also I use the 3dsecure to verify the cards. But it seems that the client option does not support the clientInstance of drop-in, here's my code : 

> 
>           braintree.dropin.create({
>             authorization: token,
>             container: '#dropin-container',
>               paypal: {
>                 flow: 'checkout',
>                 amount: amount,
>                 currency: 'USD'
>               }
>           }, function (clientErr, clientInstance) {
>               if (clientErr) {
>                   // Handle error in client creation
>                   return;
>               }
> 
>             braintree.threeDSecure.create({
>               client: clientInstance
>             }, function (threeDSecureErr, threeDSecureInstance) {
>               if (threeDSecureErr) {
>                 // Handle error in 3D Secure component creation
>                 return;
>               }
>               threeDSecure = threeDSecureInstance;
>             });
> 
>           });

I get the following js error : 

`
three-d-secure.min.js:1 Uncaught TypeError: e.client.getConfiguration is not a function
`

How should I solve this issue ?

Thanks in advance for your help

**Comment by haraldpdl** [comment]
Please see https://github.com/braintree/braintree-web-drop-in/issues/208 for an example of Drop-in and 3D Secure.

**Comment by alenoosh** [comment]
@haraldpdl  Thanks alot for your help, it worked  :+1:

**Comment by crookedneighbor** [comment]
@alenoosh, you can also subscribe to https://github.com/braintree/braintree-web-drop-in/issues/208 for when 3D Secure support will be added to drop-in.
