### ISSUE TITLE
ERROR PayPal payment options are invalid

### ISSUE THREAD

**Issue by m-wysocki** [braintree/braintree-web#313]
### General information

SDK version: PHP, braintree-web@3.20.0
Environment: Production
Browser and OS: Reproducible on different systems

### Issue description

I'm getting the checkout.js error Object._RECEIVE_MESSAGE_TYPE.(anonymous function) error with the message "PayPal payment options are invalid" when I try to get PayPal authorization. PayPal dialog won't event open due to this error.
My code is:
```
paypal.Button.render({
              env: "production",
              commit: true,
              payment: function () { 
                return paypalCheckoutInstance.createPayment({
                  flow: "checkout", 
                  amount: 10, 
                  currency: "PLN"
                });
              },

              onAuthorize: function (data, actions) {
                  console.log(accessToken); ....
```

Just before this error appears I can see the following in my Chrome console: POST https://api.braintreegateway.com/merchants/dzwnspprskyyvtm3/client_api/v1/paypal_hermes/create_payment_resource 422 (Unprocessable Entity)

The same piece of code works fine on Sandbox environment.

**Comment by crookedneighbor** [comment]
This is unlikely to be a problem with the SDK itself. Please contact support so we can examine your account details and determine what the issue is. https://developers.braintreepayments.com/forms/contact

**Comment by dilpazirahmad** [comment]
i had the same error, and i fugured out that i was not using correct paypal credentials (client username, id and secret)
then i created a new app in paypal console, opened the app by clicking on it, got the credentials and put in braintree panel in settings ->processing ->paypal options
and it solved my error
