### ISSUE TITLE
Cannot Teardown DataCollector a second time - Braintree JS version 3.15.0

### ISSUE THREAD

**Issue by reidcooper** [braintree/braintree-web#314]
### General information

* SDK version: 3.15.0
* Environment: Sandbox & Production
* Browser and OS: Version 59.0.3071.115 (Official Build) (64-bit)

### Issue description

My current application supports being able to teardown all the braintree instances that we use on a given checkout page. However, usually if the user navigates from the page, the braintree instances are destroyed (by nature of page navigation), however I did implement functionality that would enable our developers to be able to teardown specific instances, such as the Data Collector.

Steps I follow:
1. Visit page, datacollector starts up properly
![screenshot 2017-07-26 13 01 34](https://user-images.githubusercontent.com/6921277/28634047-eb3c8170-7203-11e7-919b-cde03653a3bc.png)
2. Teardown the dataCollector instance, works correctly
![screenshot 2017-07-26 13 01 44](https://user-images.githubusercontent.com/6921277/28634105-252a513c-7204-11e7-972a-3068069b37c4.png)
3. Start up another instance of the dataCollector, works correctly
![screenshot 2017-07-26 13 01 53](https://user-images.githubusercontent.com/6921277/28634116-2e27245e-7204-11e7-9404-e902e194df05.png)
4. Teardown the dataCollector instance, it errors out
![screenshot 2017-07-26 13 02 03](https://user-images.githubusercontent.com/6921277/28634124-363d1a72-7204-11e7-88a5-a1f604c405b0.png)
![screenshot 2017-07-26 13 02 19](https://user-images.githubusercontent.com/6921277/28634139-3cfce1c6-7204-11e7-8ecd-12f3389d5a38.png)

During my examination, I noticed that there is an iFrame inserted with `id="braintreeDataFrame"` on creation of the dataCollector braintree instance. On the first tearDown, it removes this iFrame successfully. However on the next dataCollector creation, it does not append the iFrame. This I presume is causing the error.

Thanks.

### Sample Application
https://github.com/reidcooper/braintree-sample-app
(Just provide your own Braintree configs in the `/config` directory)

**Comment by crookedneighbor** [comment]
For the person that looks into this, here's the file where the client side code is defined: https://github.com/reidcooper/braintree-sample-app/blob/50039792b9f321292f821f2b22592be6efe63b59/app/views/layouts/application.html.haml

**Comment by crookedneighbor** [comment]
I have not been able to reproduce this on my own integration. Will try to spin up your provided app to track this down tomorrow.

**Comment by crookedneighbor** [comment]
I was able to reproduce the behavior. Thanks for the report.

**Comment by reidcooper** [comment]
Great :) that's good news. Any ideas?

**Comment by crookedneighbor** [comment]
We should have a fixed released later today. Stand by!

**Comment by crookedneighbor** [comment]
This is fixed in version 3.22.1.
