### ISSUE TITLE
Number keyboard forced in postcode input on iOS

### ISSUE THREAD

**Issue by maxmurdoch** [braintree/braintree-web#316]
### General information

* SDK version: 3.21.1
* Environment: Production
* Browser and OS: Any on iOS

### Issue description

The postal code input is fixed to the number keyboard on iOS devices.

A `pattern: \d*` attribute is added to all inputs unless an explicit `type` is specified while configuring inputs.

I am using this library indirectly through the braintree drop in ui. I think the way you addressed number keyboard showing up in iOS has caused it to always show on iOS devices using the drop in ui. I haven't followed the code into the drop in ui library, but my assumption is [this](https://github.com/braintree/braintree-web/commit/0178a8bbce0d83a9eb42b5423fc968f791ee4222#diff-0970dc8e5758eb8c730c187034237a4dR13) condition is being hit because the drop in ui doesn't specify a type when configuring the postal code input.

**Comment by crookedneighbor** [comment]
You are correct. We were made aware of this regression earlier today and are working on a fix for it.

**Comment by crookedneighbor** [comment]
This is fixed in version 3.22.0 https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#3220
