### ISSUE TITLE
Error with accelerationIncludingGravity

### ISSUE THREAD

**Issue by clautour** [braintree/braintree-web#320]
### General information

* SDK version: 3.19.0
* Environment: Production
* Browser and OS: Edge Mobile

### Issue description

We've captured this error in production: 

`Unable to get property 'x' of undefined or null reference.`

and is in this section of code.

`{snip} ,"touch"),a(this,0)},V:function(){a(this,2)},R:function(e){if(e=e.accelerationIncludingGravity.x||e.accelerationIncludingGravity.y||e.accele {snip}`

looking in source this appears in `braintree-web\data-collector\vendor\sjcl.js`

**Comment by lilaconlee** [comment]
We're going to close this issue as mobile Edge is not one of our [supported browsers](http://braintree.github.io/braintree-web/current/#browser-support). 

That being said, this error is part of the [sjcl](https://github.com/bitwiseshiftleft/sjcl) library which is used in data collector. We recommend you open an issue on that repo and we'll be glad to update our version if a fix is made.
