### ISSUE TITLE
Hosted field's braintree-hosted-fields-valid class doesn't get injected 

### ISSUE THREAD

**Issue by go1t** [braintree/braintree-web#321]
### General information

* SDK version: 3.22.2
* Environment: Sandbox
* Browser and OS  Chrome 60.0.3112.101 (Official Build) (64-bit) on MacOS 10.12.6

### Issue description

The Hosted field's `braintree-hosted-fields-valid` CSS class doesn't get injected to the hosted field container when starting from an empty field. The only way I can get it to show up is by coming from the error state where `braintree-hosted-fields-invalid` was there.

**Comment by ayc92** [comment]
+1

**Comment by lilaconlee** [comment]
We're seeing the expected behavior with applying the `braintree-hosted-fields-valid` class to fields. We expect the field to have the `valid` class applied when a fully valid number is entered in the field and the `invalid` class to be applied when it is invalid. If the field is empty, we do not expect it to have either class applied.

If you can provide us with some additional information about how to recreate this, we're happy to debug further!

**Comment by go1t** [comment]
@lilaconlee Oh sorry I should have been a little clearer. The error I got was from the `expirationMonth` and `expirationYear` field. 

When the field is empty, neither of the class is applied. But after that, when the field became valid (e.g. I typed in 12 in the month field), `braintree-hosted-fields-valid` doesn't get applied.

Note that if I type `13` first, the `braintree-hosted-fields-invalid` class get applied, and after that if I delete one character and type 2 to make the field `12`, the `braintree-hosted-fields-valid` class get applied correctly. However, if I instead delete both characters and type `12`, the class doesn't get applied.

**Comment by lilaconlee** [comment]
We've still been unable to replicate the issue, [here's](https://codepen.io/braintree/pen/MyzXqG) an example with split expiration dates where it looks like the classes are being applied appropriately. Let us know if you have an example where we can replicate this.

**Comment by go1t** [comment]
@lilaconlee On closer inspection, it turned out that it was the problem on my end with React from its rerendering overriding the custom injected class.

Sorry for taking your time out of this, and thanks again for a very swift response! I will close this thread.

**Comment by lilaconlee** [comment]
No problem! Glad you figured it out!
