### ISSUE TITLE
Failed tokenization [ACH]

### ISSUE THREAD

**Issue by asveloper** [braintree/braintree-web#322]
BraintreeError {name: "BraintreeError", code: "US_BANK_ACCOUNT_FAILED_TOKENIZATION", message: "The supplied data failed tokenization.", type: "CUSTOMER", details: {…}}
code
:
"US_BANK_ACCOUNT_FAILED_TOKENIZATION"
details
:
{originalError: BraintreeError}
message
:
"The supplied data failed tokenization."
name
:
"BraintreeError"
type
:
"CUSTOMER"

**Comment by crookedneighbor** [comment]
I imagine the information provided in the originalError will tell you precisely which fields are invalid.

If that doesn't illuminate the problem, please contact our support team regarding this issue. https://developers.braintreepayments.com/forms/contact
