### ISSUE TITLE
TypeError: Cannot read property 'close' of null

### ISSUE THREAD

**Issue by ylin6** [braintree/braintree-web#324]
### General information

* SDK version: 3.22.1
* Environment: Sandbox. Have not tested in Production
* Browser and OS: Test on Chrome 59, Mac OSX Sierra

### Issue description

Im getting this error from braintree JS SDK:
``` TypeError: Cannot read property 'close' of null
    at Popup.close (index.js:29)
    at FrameService.close (frame-service.js:141)
    at paypal.js:472
    at <anonymous> 
```

I see this when I successfully tokenize from paypal, then click the paypal button again ( which makes another call to initialize paypal again ).

**Comment by ylin6** [comment]
Was able to fix this by tearing down paypal instances after tokenization, is this the correct approach?

**Comment by lilaconlee** [comment]
Given that you are creating a new PayPal instance when the button is clicked, tearing down your integration and creating a new PayPal instance is the right behavior there.

Alternatively, you could create one PayPal component outside of the click handler and call `tokenize` when the button is clicked, like we do in [this example](http://braintree.github.io/braintree-web/current/module-braintree-web_paypal.html#create-examples).

Hope this helps!
