### ISSUE TITLE
Copy and pasting Credit card numbers into hosted Fields, some numbers become missing

### ISSUE THREAD

**Issue by ylin6** [braintree/braintree-web#325]
### General information

* SDK version: 3.22.1
* Environment: Sandbox and Production
* Browser and OS : Chrome 59 on OSX 10 Sierra

### Issue description
When a user copies and pasted into the hosted fields, the numbers in the hosted fields do not exactly correspond to the copied number

For example 
4005519200000004
becomes 
4005 1920 0000 4

It seems like the numbers that are missing corresponds to the spaces created by the autoformatting of credit card numbers

**Comment by lilaconlee** [comment]
This is an issue we've seen with some Chrome extensions. Any chance you're using an extension that would interfere with copying and pasting?

**Comment by ylin6** [comment]
Is last pass a possibility?

**Comment by lilaconlee** [comment]
We haven't seen that behavior with LastPass but we have seen it with [this extension](https://chrome.google.com/webstore/detail/dont-fuck-with-paste/nkgllhigpcljnhoakjkgaieabnkmgdkb?hl=en). If you want to double-check that it's an issue with a Chrome extension, you can try out your integration in incognito mode where extensions should be disabled by default.

Let us know if you can reproduce the issue without any extensions and we can debug further.

**Comment by crookedneighbor** [comment]
I'm going to close this now, but if you need further assistance, let us know.
