### ISSUE TITLE
Programmatically set selected value on expiration month and year

### ISSUE THREAD

**Issue by mjbeaumont** [braintree/braintree-web#326]
It would be great if we had the ability to programatically manage the selected value of the expirationMonth and expirationYear dropdowns. It would be really helpful when using hosted fields to update the expiration date of a vaulted payment method so we can match the initial values to those of the stored card.

Ideally it would leverage the existing `hostedFields.setAttribute` method so you can do it at runtime.

```
hostedFieldsInstance.setAttribute({
   field: 'expirationYear',
   attribute: 'selected',
   value: 2020 
})
```
If this isn't possible, it might still be a nice feature to add it as an option during setup.

``` 
fields: {
   /* ... */
   expirationYear: {
      selector: '#your-selector',
      select: true,
      selected: 2020
   }
}
```

**Comment by lilaconlee** [comment]
Awesome idea! This is something we'll take a look at adding. It's not on our immediate roadmap but we'll keep this issue open and keep you updated here.

**Comment by crookedneighbor** [comment]
This has been added in 3.25.0 with the `prefill` option in the create method. See 
http://braintree.github.io/braintree-web/current/module-braintree-web_hosted-fields.html#~field

and the last example here: http://braintree.github.io/braintree-web/current/module-braintree-web_hosted-fields.html#create-examples
