### ISSUE TITLE
Question, How do you validate credit card types client side?

### ISSUE THREAD

**Issue by jennasalau** [braintree/braintree-web#327]
How do you validate credit card types in the hosted fields plugin?

We wish to only accept Visa / MasterCard and nothing else.. your docs are confusing but it seems we have to do this validation on the back end? If so, thats a shame because you can derive this information from the number before making a request.

**Comment by kzurawel** [comment]
This is possible by checking against an array of supported card types in the `validityChange` handler for Hosted Fields. Here is a codepen that demonstrates using Hosted Fields to accept Visa (`4111111111111111`) or Mastercard (`5555555555554444`), but not others (e.g. Discover `6011111111111117`) : https://codepen.io/braintree/pen/867c31f31e86cf800070aaea56f7f3d6/

You could also use [Drop-in](https://braintree.github.io/braintree-web-drop-in/docs/current/index.html), which does this kind of validation automatically based on your Gateway card type settings.

**Comment by crookedneighbor** [comment]
I think this answers your question, so I'm going to close this issue. If you have further questions about it, feel free to let us know.

**Comment by jennasalau** [comment]
Yes, thank you.
