### ISSUE TITLE
ApplePayInstance.merchantIdentifier

### ISSUE THREAD

**Issue by aamirafridi** [braintree/braintree-web#329]
### Wrong merchang Identifier

* SDK version: 3.15.0
* Environment: Sandbox
* Safari Version 10.1.2 (12603.3.8), Macbook Sierra 10.12.6

In the [documentation](https://developers.braintreepayments.com/guides/apple-pay/client-side/javascript/v3) it says

```javascript
var promise = ApplePaySession.canMakePaymentsWithActiveCard(applePayInstance.merchantIdentifier);
```

Which refers to [this line](https://github.com/braintree/braintree-web/blob/master/src/apple-pay/apple-pay.js#L64)

It was not working for me because it was wrong. It should be the domain so it should be
```javascript
value: this._client.getConfiguration().gatewayConfiguration.applePay.merchantIdentifier,
```

`applePay` not `applePayWeb`

I hard coded the domain instead of using `applePayInstance.merchantIdentifier` and it worked.

I am not sure if I am doing anything wrong but take a look and explain if I am on wrong track.

**Comment by crookedneighbor** [comment]
This seems to me like there is something misconfigured in your merchant account for processing Apply Pay on the web. That it works by passing `applePay.merchantIdentifier` from your gateway configuration is coincidental, and may not actually work in production.

I've reviewed on our accounts, and `applePayWeb.merchantIdentifier` is correct.

Please reach out to our support team so we can take a look at your account and see if anything looks incorrect. https://developers.braintreepayments.com/forms/contact

**Comment by aamirafridi** [comment]
![image](https://user-images.githubusercontent.com/55896/30654467-d88a6648-9e25-11e7-95e0-4a7d3ac967cf.png)

Apple Merchant Id on sandbox is x.x.x.x which is availble under `applePay.merchantIdentifier` but I am getting a random which is under `applePayWeb.merchantIdentifier` when I try to get `applePayInstance.merchantIdentifier`

**Comment by crookedneighbor** [comment]
We still need you to contact our support team to dig into this further. It is highly unlikely that this is a problem with the JavaScript SDK.
