### ISSUE TITLE
Safari/Chrome credit card autofill does not work if expiration month field is a select menu 

### ISSUE THREAD

**Issue by wangjames** [braintree/braintree-web#331]
### General information

* SDK version: 3.22.0
* Environment: Production
* Browser and OS: Chrome and Safari

### Issue description

For the expiration date and expiration month fields, if you choose to style the fields with the select option, autofill with a credit card on Chrome and Safari does not work for numbers between 01 to 09. However, if your card has an expiration month between 10 to 12, the option is selected correctly. I'm guessing this has something to do with the select options not recognizing 01 as 1?

![autofillerror](https://user-images.githubusercontent.com/8403088/31955988-ef4974ee-b89e-11e7-831c-69e6309d6c49.png)

**Comment by crookedneighbor** [comment]
Thanks for the report, we'll get this fixed.

**Comment by crookedneighbor** [comment]
This is fixed in 3.25.0. Thanks for the report!

**Comment by wangjames** [comment]
@crookedneighbor 

just checked it out, it works! thanks!
