### ISSUE TITLE
Unable to get property 'close' of undefined or null reference - PayPal Payment

### ISSUE THREAD

**Issue by YodasMyDad** [braintree/braintree-web#333]
### General information

* SDK version: 3.24.1
* Environment: Sandbox (Haven't tried live as Sandbox isn't working)
* Windows 10, IE 11

### Issue description

I am testing a new site in IE11, but cannot get the PayPal payment to work. There is a constant error, when the pop up tries to load.

The error is below. It actually seems like it tries to open two pop ups? 

> TypeError - Unable to get property 'close' of undefined or null reference

And it's right here

        paypalInstance.tokenize({
        flow: 'vault'
    }, function (tokenizeErr, payload) {    
        if (tokenizeErr) {
            if (tokenizeErr.type !== 'CUSTOMER') { // ERROR HERE
                console.error('Error tokenizing:', tokenizeErr);
            }
            return;
        }
    //.... Rest of code

Edit: It's definitely opening up two pop ups?

**Comment by crookedneighbor** [comment]
Can I see the full braintree code? Or a staging site so I can reproduce it?

**Comment by YodasMyDad** [comment]
I've tweeted. I can give you test site url, but privately. Site is not live yet, and don't want to test url/site public.

**Comment by crookedneighbor** [comment]
Feel free to reach out to our support team with the test url and reference this issue: https://developers.braintreepayments.com/forms/contact

**Comment by crookedneighbor** [comment]
@YodasMyDad Were you able to sort out what was happening?

**Comment by YodasMyDad** [comment]
@crookedneighbor no. But I accidentally put the credentials to live on our test server. I was then testing again, and it just seemed to work... So I'm more confused. Right now it's working, so I'm not touching it!
