### ISSUE TITLE
Expiration date caret position shifted on Safari/iPhone 6S

### ISSUE THREAD

**Issue by piotrjaw** [braintree/braintree-web#337]
### General information

* SDK version: 3.26.0
* Environment: Sandbox and Production
* Browser and OS: Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0 Mobile/15B202 Safari/604.1 (Safari 11 on iPhone 6S running iOS 11.1.2, not reproduced anywhere else, including Safari 11 on iPhone 7 Plus running iOS 11.1.2)

### Issue description

The expiration date's input care position behaves unexpectedly, after typing a few characters it's shifted down by a hefty amount of pixels, exactly like on the screenshot below:

![24171531_1511419438893714_1839084967_n](https://user-images.githubusercontent.com/1726537/33282901-6350a878-d3aa-11e7-91fb-8a39626a641b.jpg)

**Comment by crookedneighbor** [comment]
This is, unfortunately, a bug in how iOS treats inputs inside of iframes. We've explored solutions for this, but so far have determined that there's nothing we can do other than open a bug report with Apple (which we've done).

If you'd like to submit a bug to Apple as well, you can do so here: https://developer.apple.com/bug-reporting/

**Comment by piotrjaw** [comment]
Thanks for the information! Will try, although probably that's not very likely.
