### ISSUE TITLE
Headless integration with v3?

### ISSUE THREAD

**Issue by mobitar** [braintree/braintree-web#339]
I'm not finding any documentation for headless integration with v3 of the checkout. I want to use my own button.

There's this: https://gist.github.com/danielwu426/70eac6b34ab7491610f0:

``` javascript
braintree.setup("CLIENT_TOKEN_FROM_SERVER", "custom", {
  onReady: function (integration) {
    checkout = integration;
  },
  onPaymentMethodReceived: function (payload) {
    // retrieve nonce from payload.nonce 
  },
  paypal: {
    singleUse: true,
    amount: 10.00,
    currency: 'USD',
    locale: 'en_us',
    enableShippingAddress: 'true',
    headless: true
  }
});
```

but I believe that's for v2. How would I get this to be compatible with this initialization format?

``` javascript
// Create a client.
braintree.client.create({
  authorization: "xxx"
}, function (clientErr, clientInstance) {

  // Stop if there was a problem creating the client.
  // This could happen if there is a network error or if the authorization
  // is invalid.
  if (clientErr) {
    console.error('Error creating client:', clientErr);
    return;
  }

  // Create a PayPal Checkout component.
  braintree.paypalCheckout.create({
    client: clientInstance
  }, function (paypalCheckoutErr, paypalCheckoutInstance) {

    // Stop if there was a problem creating PayPal Checkout.
    // This could happen if there was a network error or if it's incorrectly
    // configured.
    if (paypalCheckoutErr) {
      console.error('Error creating PayPal Checkout:', paypalCheckoutErr);
      return;
    }
});
```

**Comment by crookedneighbor** [comment]
The UI of the button with the paypalCheckout component is managed entirely by checkout.js. Please open an issue on the checkout.js repo if you'd like to request the ability to use your own button. https://github.com/paypal/paypal-checkout

Alternatively, you could use the older paypal component (http://braintree.github.io/braintree-web/current/PayPal.html), which requires you to set up your own custom button. This method is deprecated and will not receive bug fixes or features, but it should work.

**Comment by mobitar** [comment]
Is there any way to initiate the payment flow programmatically, similar to `checkout.paypal.initAuthFlow()`? I'm using v3 and don't want to use an older version.

**Comment by crookedneighbor** [comment]
No. It must be done through the button click. (even `initAuthFlow` needed to be done within a click handler for a button)

The UI is handled entirely by checkout.js, so you'll have to ask those folks if any feature for a custom button is on their roadmap.

**Comment by mobitar** [comment]
Ok thanks
