### ISSUE TITLE
Different Data returned in onPaymentMethodReceived in PayPal Single payment flow verses Future Payment

### ISSUE THREAD

**Issue by trainerbill** [braintree/braintree-web#34]
When you initiate the paypal single payment flow the following is returned:
{
  "nonce": "c812933e-fc0c-4786-a712-afbde4d8e280",
  "details": {
    "email": "bt_buyer_us@paypal.com",
    "firstName": "John",
    "lastName": "Doe",
    "phone": "312-123-4567",
    "shippingAddress": {
      "streetAddress": "123 Division Street",
      "extendedAddress": "Apt. #1",
      "locality": "Chicago",
      "region": "IL",
      "postalCode": "60618",
      "countryCodeAlpha2": "US",
      "recipientName": "John Doe"
    }
  },
  "type": "PayPalAccount"
}

When you initiate the future payments flow the following is returned:
{
  "nonce": "ac592269-0501-4985-a34e-9f0a6d03a8db",
  "details": {
    "email": "athroener@paypal.com",
    "shippingAddress": {
      "id": "1807238",
      "defaultAddress": true,
      "preferredAddress": false,
      "postalCode": "123456",
      "region": "CT",
      "type": "HOME_OR_WORK",
      "streetAddress": "2300 Park Road",
      "recipientName": "Jane Doe",
      "countryCodeAlpha2": "US",
      "locality": "Ridgefield",
      "extendedAddress": "56688 B Street"
    }
  },
  "type": "PayPalAccount"
}

I really need the first name and last name separated out like the single payments flow.  Should be consistent between the 2 flows.

**Comment by schneiderik** [comment]
Hi @trainerbill,

Currently we support a [Vault Flow](https://developers.braintreepayments.com/javascript+ruby/guides/paypal/vault) and [Checkout Flow](https://developers.braintreepayments.com/javascript+ruby/guides/paypal/checkout-with-paypal) for our PayPal integration.  The 'Checkout Flow' is using a UI developed and designed by PayPal which allows us easy access to buyer information including the firstName, lastName, and phone.

**Comment by trainerbill** [comment]
You are using Oauth + REST for the Vault Flow correct?  You should get all this information back when submitting the Get User Information api call:

https://developer.paypal.com/docs/api/#get-user-information

**Comment by schneiderik** [comment]
That's a valid point. We are currently working on returning additional information for both flows, and will do our best to unify the responses as a part of that initiative.

Thank you for the feedback.

**Comment by kyledetella** [comment]
As @schneiderik said, in the future we will do our best to unify those responses. Unfortunately, there is no timeline for that work.

I am going to close this issue and we will be sure to communicate any future changes that may affect the format of these responses.
