### ISSUE TITLE
Question, Disable -ms-clear on Hosted Fields

### ISSUE THREAD

**Issue by oskarv** [braintree/braintree-web#342]
Is it possible to disable -ms-clear on IE, on inputs created by hosted field iframe?

**Comment by crookedneighbor** [comment]
You can do this by passing this into the styles option:

```js
'input::-ms-clear': {
  color: 'transparent'
}
```

You can see that we do exactly that in [Drop-in](https://github.com/braintree/braintree-web-drop-in/blob/cd9b4f074ad9d2e09d38e4f4ab7e33a5b644ec54/src/views/payment-sheet-views/card-view.js#L188-L190) which uses Hosted Fields.

**Comment by oskarv** [comment]
Great, thank you so much!
