### ISSUE TITLE
SSL certificate issue in Chrome

### ISSUE THREAD

**Issue by fazpu** [braintree/braintree-web#343]
### General information

* SDK version: 3.26.0
* Environment:Sandbox
* Browser and OS: Chrome 63.0.3239.108 / Ubuntu 17.10

### Issue description

While working in Chrome on the sandbox integration, this warning appears:

> The SSL certificate used to load resources from https://api.sandbox.braintreegateway.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

Please, are there plans to handle this issue?

Thank you!

**Comment by crookedneighbor** [comment]
We are aware of the issue and taking steps to mitigate it before the deadline.

**Comment by carlosds730** [comment]
Any news regarding this?

**Comment by crookedneighbor** [comment]
It's on our security team's roadmap to take care of this well before the deadline (March 2018). There will be no disruption of service. We'll close this issue when the certificates have been rotated out for new certs.

**Comment by crookedneighbor** [comment]
I have a small update on this, I checked with our infrastructure team and our certs were issued in 2017, so the actual deadline is around October 2018 when Chrome 70 is released. We plan on having this all rolled out before then. There will be no interruption of service.

**Comment by trotexnet** [comment]
+1 Very uncool.

**Comment by nupejosh** [comment]
This is breaking for me on production. 
> The SSL certificate used to load resources from https://api.braintreegateway.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

I just updated to the latest 3.31.0 version, but still not working. :/

**Comment by crookedneighbor** [comment]
@nupejosh I am unable to reproduce the fields being unclickable in Chrome or Chrome Canary. I believe whatever issue you're having is unrelated to this issue. Please [contact our support team](https://articles.braintreepayments.com/forms/contact) so we can dig into the precise issue. 

If you could provide a staging site and exact steps to reproduce, that would be great.

**Comment by elliottohara** [comment]
What is the status on this? I'm getting the warning on my production systems. 
<img width="1433" alt="screen shot 2018-03-07 at 8 41 14 am" src="https://user-images.githubusercontent.com/470747/37098378-5d50c7fa-21e3-11e8-9e7e-cd390fbf13c1.png">

**Comment by crookedneighbor** [comment]
Same as before. Our infrastructure team is working on it and ensuring that it'll be fixed before M70 rolls out. There will be no code changes needed on y'all's side.

**Comment by bluk** [comment]
An update on the status. The infrastructure team deployed a new certificate for the sandbox environment which resolves this warning in sandbox. The production environment will be resolved before M70 is available.

**Comment by mdbootstrap** [comment]
Dear Team - this is already breaking our production environment for Chrome users. Please provide the fix ASAP.

**Comment by crookedneighbor** [comment]
@mdbootstrap Please provide a link to your site that reproduces the issue. I am able to run Hosted Fields just fine.

If you are unwilling to post a link to your site here, you can contact our support team https://articles.braintreepayments.com/forms/contact

**Comment by NikitaKrivov** [comment]
It seems our clients faced that issue. Otherwise I have no other ideas.
Client see for, stub spinner, that should be hidden on drop-in initialization callback.
So a while after there is no spinner and no form.
Can't provide more information as I cannot reproduce that behaviour on my devices.

**Comment by Solidjeuh** [comment]
I see the same at my website, any news please?

The SSL certificate used to load resources from https://chimpstatic.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

**Comment by NikitaKrivov** [comment]
update on my comment: looks like the issue was with token from our server

**Comment by crookedneighbor** [comment]
@Solidjeuh The state of this is the same. It's been resolved for sandbox environments and will be resolved for production environments before M70 is released. We're taking this slow and carefully to ensure there is no interruption of service in our production environment.

@NikitaKrivov Thank you for the confirmation that it was unrelated to this issue.

**Comment by Solidjeuh** [comment]
Great, Thanks! @crookedneighbor

**Comment by mkarnicki** [comment]
Just to remind, we're ~40 days from the deadline, [July 20th](https://security.googleblog.com/2018/03/distrust-of-symantec-pki-immediate.html). Thanks.

**Comment by dirkgr** [comment]
5 days today!

**Comment by msphair** [comment]
6 days...any updates?

**Comment by elliottohara** [comment]
Would you care to define “well before the deadline?”

**Comment by crookedneighbor** [comment]
To be clear, the canary release of Chrome M70 comes out on July 20th, but the beta release comes out in September and the stable release does not come out until October. 

We intend to have the certs rotated before the beta release comes out in September.

**Comment by deeepakm90** [comment]
@crookedneighbor  was not able to do transaction in production environment of braintree, as it is showing chrome m70 issue

**Comment by crookedneighbor** [comment]
The new certs are rolled out.

Note: if you're using PayPal with checkout.js, you will still see the warning. Looks like they are targeting August 6th to rotate the certs https://github.com/paypal/paypal-checkout/issues/691#issuecomment-405604183

**Comment by tituscrow82** [comment]
Still not fixed

**Comment by crookedneighbor** [comment]
@tituscrow82 This should not be a problem on the Braintree side of things. PayPal and Checkout.js still do not have the checkout.js cert rotated, I've asked them for an update.

If you believe you are still seeing issues related to this on the Braintree side, please reach out to Braintree support at https://articles.braintreepayments.com/forms/contact
