### ISSUE TITLE
The official Custom UI example not working correctly

### ISSUE THREAD

**Issue by fazpu** [braintree/braintree-web#344]
The official [Custom UI example with Material Design style](https://codepen.io/braintree/pen/mPgdPN) does not work correctly. 

```
// Emulates floating label pattern
    hostedFieldsInstance.on('blur', function (event) {
      var field = event.fields[event.emittedBy];
      
      if (field.isEmpty) {
        $(field.container).next('.hosted-field--label').removeClass('label-float');
      } else if (event.isValid) {
        $(field.container).next('.hosted-field--label').addClass('filled');
      } else {
        $(field.container).next('.hosted-field--label').addClass('invalid');
      }
```

I would expect that e.g. if I inputted to cvv only one number and then clicked somewhere else, the color of the number should become red. However, this is not happening...

**Comment by crookedneighbor** [comment]
Thanks for the report. Looks like the jQuery targeting of the labels is not quite right. We'll get this fixed up and post here when it's done.

**Comment by crookedneighbor** [comment]
Should be fixed now. We're going to do some additional updates to the codepen to more closely follow the Material Design spec, but for now the classes are now being applied correctly.

**Comment by fazpu** [comment]
Thank you!
