### ISSUE TITLE
[question] paypal popup getting blocked

### ISSUE THREAD

**Issue by zemd** [braintree/braintree-web#346]
### General information

* SDK version: 3.21.0
* Environment: sandbox/production
* Browser and OS: mobile safari, chrome dev tools

### Issue description

I am trying to figure out why browsers are blocking paypal modal window for our product. Initially we were not experiencing such issue and everything was fine, but now something has changed and I can't understand if this is our codebase's problem.

We have initialization code similar to this:
```js
class Braintree {
    init() {
        return braintree.client.create({
                authorization: token
            })
            .then((client) => {
                return braintree.paypal.create({
                        client,
                    })
                    .then((paypalInstance) => {
                        this.paypalInstance = paypalInstance;
                    });
            });
    }
}
```

and when 'continue' button is pressed, next code gets executed

```js
tokenizePaypal() {
    return this.paypalInstance.tokenize({
            flow: 'vault',
        })
        .catch((error) => {
            // each time user tries to make payment, modal window gets blocked and uses observes a `PAYPAL_TOKENIZATION_REQUEST_ACTIVE` error
        });
}
```

Is there any rules which we should follow to tell browser to not block this popup?

**Comment by crookedneighbor** [comment]
The error you mention in the `catch` of the tokenize call is not the error I'd expect to see from a popup blocking the action, but rather the error that occurs when tokenization is already in progress. See https://github.com/braintree/braintree-web/blob/0ae58971df381a59a7aa7b8eca7af378cbbaa19c/src/paypal/external/paypal.js#L271-L274

As long as the call to tokenize is a direct response from a button click event, you should not experience the browser blocking the popup. For instance:

```js
var btn = document.querySelector('#paypal-button');

// since the tokenize call happens outside of the direction action
// of the button click, many browsers will block this popup
btn.addEventListener('click', function () {
  // do some async stuff, like fetching things from server
  // for this example, we'll represent this async stuff with 
  // a setTimeout
  setTimeout(function () {
    tokenizePaypal();
  }, 100);
});

// since the tokenize call happens as a direct result of the click
// event, the popup is not blocked
btn.addEventListener('click', function () {
  tokenizePaypal();
});
```

I'd encourage you to add some logic around disabling and re-enabling the PayPal button to prevent the customer from clicking twice on the button.

```js
var btn = document.querySelector('#paypal-button');

btn.addEventListener('click', function () {
  btn.setAttribute('disabled', true);

  tokenizePaypal().then(function (payload) {
    // handle payload
  }).catch(function (err) {
    // handle err
  }).then(function () {
    btn.removeAttribute('disabled')
  });
});
```

Alternatively, you could switch over to using the [PayPal Checkout component](http://braintree.github.io/braintree-web/current/PayPalCheckout.html#PayPalCheckout) with PayPal's checkout.js script, which gives checkout.js the responsibility of creating the PayPal button and setting up the click handlers.

**Comment by zemd** [comment]
@crookedneighbor thanks! I had to make additional async request before `tokenizePaypal` being executed, same as you described as `setTimeout`. your answer was helpful 👍

**Comment by nadhir-falta** [comment]
@zemd  how did you end up solving this ?

**Comment by zemd** [comment]
Hey @nadhir-falta, it was so long ago that it would be hard to recall. If I'm correct, the reason was that I tried to call the SDK methods programmatically rather than as a code that executes after the user's action. There were some browser restrictions on doing that. And according to the conversation in this issue, the solution was to follow the official guidelines.

**Comment by nadhir-falta** [comment]
Thank you @zemd I ended up following the docs and altering my code.
