### ISSUE TITLE
Associating an existing customer with drop in or hosted fields integration

### ISSUE THREAD

**Issue by kmuthupa** [braintree/braintree-web#348]
### General information

I would like to know if it is possible to associate a payment method via client side sdk (js) to an existing customer thats in the Braintree system? What happens by default currently? A new customer is created? Something that is nt very clear to me from the docs.

**Comment by Epreuve** [comment]
You can associate a payment method with an existing customer when using the [Drop-in](https://developers.braintreepayments.com/guides/drop-in/overview/javascript/v3) by generating a client token [with a customer ID](https://developers.braintreepayments.com/reference/request/client-token/generate/#customer_id).  This also displays any existing payment methods for that customer when the Drop-in initially loads.

[Hosted fields](https://developers.braintreepayments.com/guides/hosted-fields/overview/javascript/v3) can do this as well when using a client token generated with a customer ID, however you must explicitly invoke this behavior by passing `vault: true` in `hostedFieldsInstance.tokenize`. 

```
hostedFieldsInstance.tokenize({
  vault: true
}, function (tokenizeErr, payload) {
  if (tokenizeErr) {
    console.error(tokenizeErr);
    return;
  }

  console.log('Got a nonce: ' + payload.nonce);
});
```

I'm going to close the issue as this should answer your questions, but feel free to comment if you have any other questions or issues.

**Comment by kmuthupa** [comment]
Thanks for the response. Another unrelated question. I m using the drop in UI currently and wondering how to use this to create a payment method in the system? Can I only use the drop in UI to process a payment transaction? Mildly confused here.

**Comment by kmuthupa** [comment]
@Epreuve ^^

**Comment by crookedneighbor** [comment]
Like @Epreuve mentioned, if you use a client token with a customer id, any card or PayPal account your customer enters will automatically be added to their customer record.

If you are using a tokenization key or a client token without a customer id, you can use the payment method nonce on the server to create a payment method that can be used to transact later. Or you can create a transaction and use the `store_in_vault` option: https://developers.braintreepayments.com/reference/request/transaction/sale/ruby#options.store_in_vault

**Comment by kmuthupa** [comment]
@crookedneighbor Thanks! So I can just create the payment method without processing a transaction.

**Comment by crookedneighbor** [comment]
Yep. See these docs: https://developers.braintreepayments.com/reference/request/payment-method/create/ruby

**Comment by kmuthupa** [comment]
This is confusing me again. Is nt this server side? I m specifically referring to doing this via the client side drop in.

**Comment by crookedneighbor** [comment]
I misunderstood. Yes, the docs I linked are server side. 

If you have a client token with a customer id, it will auto vault on the client.

**Comment by kmuthupa** [comment]
gotcha, no worries. Couple more questions for you:

1. Is there a way to disable "choose another way to pay" option in the drop in UI?
2. How do I pass the verifyCard, makeDefault options when I generate the token?

**Comment by crookedneighbor** [comment]
These are better questions for our support team. You can contact them here: https://developers.braintreepayments.com/forms/contact
