### ISSUE TITLE
Unable to find a valid FORM

### ISSUE THREAD

**Issue by kaihendry** [braintree/braintree-web#35]
Drop-in integration README.md suggests

    <div id="payment-form"></div>

It actually needs to be 

    <form id="payment-form"></form>

**Comment by mrak** [comment]
We should clarify that `container` for dropin should be inside of a form (not necessarily the form itself).

From our [official documentation for Drop-in](https://developers.braintreepayments.com/javascript+ruby/sdk/client/drop-in):

> Braintree.js adds a hidden input named payment_method_nonce to your form. When your user submits the form, you can use the nonce to create transactions, customers, or vault with an existing customer. Because of this it is required for __container__ to be inside a form.

**Comment by kaihendry** [comment]
Another comment is that the 'Dropin UI' still seems to require a Paypal login. Ummmm, the reason why we signed up to Braintree is to get the cleanest, most minimal way for users to put in the CC details and click submit. Is there some option I'm missing to keep it minimal?

**Comment by jeffcarp** [comment]
> seems to require a Paypal login

Only if you're paying with PayPal. You can keep the button from showing up by disabling PayPal in the control panel.

**Comment by kaihendry** [comment]
I don't seem to have the ability to disable Paypal.

http://s.natalian.org/2015-03-30/1427685392_1918x1058.png

**Comment by mrak** [comment]
Though the PayPal button shows up, the user does not need to use it. Entering in credit card information and submitting the form on your checkout page is enough for dropin to tokenize the card information.

I didn't realize that you were working with a sandbox account. PayPal is currently enabled for all sandbox accounts and uses a stubbed-out PayPal backend
