### ISSUE TITLE
Form field not active on click when having a dropdown open

### ISSUE THREAD

**Issue by pietersharefaith** [braintree/braintree-web#351]
* SDK version: 3.30.0
* Environment: Sandbox
* Browser and OS Newest Chrome Ubuntu 16.4

Imagine you have the following fields:
Credit card number
Expiration Month (Dropdown)
Expiration Year (Dropdown)
cvv
And more

You click on the credit card number then you click expiration month (do not select an item) and then you have to double click to select any other field.
Tab seems to work fine tough.

The issue is due to when the dropdown is open and you click another field it closes the dropdown but it does not highlight the next field.

This is not a huge issue in my opinion but something I noticed!

**Comment by crookedneighbor** [comment]
I may be misunderstanding you, but I hink this is just how select fields work. This exhibits the same behavior.

```html
<input id="my-input" type="text" />
<select>
  <option value="1">1</option>
  <option value="2">2</option>
</select>
```

Click on the input field and it focuses on the input. Click on the select, but do not choose an option. Click on the input field again, the select disappears, but the input is not selected. Click on the input and it focuses the input.

**Comment by pietersharefaith** [comment]
That makes sense however it may see odd when you filling in credit card information. Html is defaulting to this so I guess it is expected behavior. Thanks for looking into it.

**Comment by crookedneighbor** [comment]
:+1:
