### ISSUE TITLE
Placeholder not returning to show in IOS

### ISSUE THREAD

**Issue by pietersharefaith** [braintree/braintree-web#352]
I am having small UI/UX issue with the place holders for the braintree hosted fields implementation. This may not be a braintree issue perse since I created this but this could cause other issues as well so I wanted to mention it.

* SDK version: 3.30.0
* Environment: IOS 11.2.2
* Browser and OS: Safai & IOS 11.2.2

When you have placeholders on you form fields it works as expected but when you do not enter anything and you click another fields the placeholder does not come back.
I do not have labels on my fields and just placeholders so when it is blank users would not know what the fields is for.

I wanted the fields to be blank when you focus on the field and have the placeholder disappear because users may think they need to remove the placeholder in the field becuase it looks like text.

However when removing the focus it still thinks it is focused in the iFrame.

Here is a snippet of the code

client : clientInstance,
```
						styles :
						{
							'select, input' :
							{
								'font-size' : '15px',
								'font-family' : '"Open Sans", sans-serif',
								'color' : '#727070',
								'padding' : '0 0 0 18px'
							},
							'input:focus::placeholder' :
							{
								'opacity' : '0'
							}
						},
						fields :
						{
							number :
							{
								selector : '#credit-card',
								placeholder : 'Credit Card Number'
							},
							cvv :
							{
								selector : '#cvv',
								placeholder : 'CVV'
							},
							expirationMonth :
							{
								selector : '#ex-month',
								placeholder : 'Month',
								select :
								{
									options :
									[ '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12' ]
								}
							},
							expirationYear :
							{
								selector : '#ex-year',
								placeholder : 'Year',
								select : true
							},
							postalCode :
							{
								selector : '#zipcode',
								placeholder : 'Postal Code'
							}
						}
```

**Comment by crookedneighbor** [comment]
This is, unfortunately, a [bug in iOS Safari where the focus state isn't interpreted correctly](https://forums.developer.apple.com/thread/28656) when inside an iframe. We've [tried to build workarounds for this](https://github.com/braintree/braintree-web/issues/137#issuecomment-324026197), but it's impossible to cover it completely.

One thing you can do is [report it to Apple](https://developer.apple.com/bug-reporting/) so that, eventually, they do fix the bug.
