### ISSUE TITLE
Add support for autocomplete attribute in Hosted Fields

### ISSUE THREAD

**Issue by gabrycaos** [braintree/braintree-web#353]
### General information

* SDK version: 3.0.0
* Environment: Both
* Browser and OS: Chrome 64

### Issue description

From version 64, Google Chrome requires attribute autocomplete in some input field (including the ones related to credit card), otherwise it shows a warning in console like the attatched image

<img width="640" alt="schermata 2018-02-16 alle 14 37 15" src="https://user-images.githubusercontent.com/3910891/36310008-fb226342-1326-11e8-997d-8911b4edb58f.png">

Is possible to add support for it in hosted fields?

reference: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofilling-form-controls:-the-autocomplete-attribute

https://bugs.chromium.org/p/chromium/issues/detail?id=468153

**Comment by skunkworks** [comment]
We'll take a look at this

**Comment by crookedneighbor** [comment]
Just noting here for the future that to see the log error, you need to turn on verbose logging in the console. It does not appear by default.

**Comment by crookedneighbor** [comment]
This is fixed in v3.32.0
