### ISSUE TITLE
PayPal Button not working

### ISSUE THREAD

**Issue by MarcoCapoferri** [braintree/braintree-web#354]
### General information

* SDK version: PayPal 4.3.1 for PrestaShop
* Environment: Production
* Browser and OS: All browsers

### Issue description

Installed paypal module from PrestaShop module manager

Register to https://relevent.it and put a product into the cart.
Go to checkout and fill your data.
Select PayPal as payment method
Click PayPal button

you get the error 
`Error: Error: PayPal payment options are invalid. at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:3158:31) at receiveMessage (https://www.paypalobjects.com/api/checkout.js:3055:77) at messageListener (https://www.paypalobjects.com/api/checkout.js:3076:13)`

How can i solve it?

**Comment by crookedneighbor** [comment]
Inspecting the network tab, I see `Authorization error --- REFUSED_MARK_REF_TXN_NOT_ENABLED:This merchant account is not permitted to create Merchant Initiated Billing Agreement`, which indicates that your PayPal merchant account is not set up for processing billing agreements.

Please contact our support team for assistance with this.https://articles.braintreepayments.com/forms/contact
