### ISSUE TITLE
Credit Card auto fill only fills first 4 digits with Roboform

### ISSUE THREAD

**Issue by kilvroch** [braintree/braintree-web#356]
### General information

* SDK version: 3.31.0
* Environment: Sandbox and Production
* Browser and OS: Windows 10, Firefox 58.0.2,  IE 11, Chrome 65, Edge 41

### Issue description

when using Roboform to autofill credit card info, hosted fields only takes the first 4 digits VERY ANNOYING. Roboform autofill works with every other non-Braintree site I've encountered.

**Comment by crookedneighbor** [comment]
My guess is that the fix for this is going to be similar to [some issues we had with 1password](https://github.com/braintree/braintree-web/search?q=1password&type=Issues&utf8=%E2%9C%93). [Fix for reference](https://github.com/braintree/restricted-input/pull/32).

Probably the extension is doing something non-standard when sending key events, so our formatting library isn't handling it correctly. We'll investigate this. Thanks for the report.

**Comment by crookedneighbor** [comment]
A little update on this. 

The number field in Hosted Fields has some additional inputs hidden inside it to allow native browser autofill to work. For some reason, Roboform is populating each of those fields with _part_ of the credit card number.

If we switch the position styling of the Hosted Fields input from `position: absolute;` to `position: fixed;`, it fixes the issue without any noticeable visual change. Seems a little silly to make this change for what looks to be weird behavior by Roboform, but it doesn't seem to have any negative effects to make the change, so we're going to do some further testing and assuming nothing comes up, try to get it out in the next release.

**Comment by crookedneighbor** [comment]
This is fixed in v3.32.0

**Comment by crookedneighbor** [comment]
The fix for this caused an issue in Safari where if the container was hidden (`display: none;`, and then later revealed (`display: block;`), the hosted fields inputs wouldn't be visible.

Re-opening this until we can figure out a better work around to support Roboform.

**Comment by crookedneighbor** [comment]
Just tried this on the latest version of Roboform, and I know longer see the issue. Closing.
