### ISSUE TITLE
payment request api default card

### ISSUE THREAD

**Issue by 719media** [braintree/braintree-web#357]
Hello

I'm writing about the payment request API. Using latest version 3.31.0. I'm trying to get the braintree payment request api to more closely mirror the example here:

https://googlechrome.github.io/samples/paymentrequest/shipping-options/

Specifically, how the defaults are all prefilled out.

I can't get the braintree version to select a default card, it always requires a selection instead of preselected:

![screen shot 2018-03-22 at 4 28 17 pm](https://user-images.githubusercontent.com/5942229/37803787-1bc08728-2dee-11e8-8f22-b1f7d3542377.png)

Testing on my macbook using Chrome 65, the example link above preselects a credit card, whereas braintree does not

**Comment by crookedneighbor** [comment]
We'll take a look. Thanks for the report.

**Comment by 719media** [comment]
The reproduction test case I have no longer has the problem after upgrading to the 3.33 version, so I think it was most likely related to the chrome crash bug we reported earlier that you have fixed. Thanks! This issue can be closed as far as I'm concerned.

**Comment by 719media** [comment]
For anyone else who comes across this thread, the error I was hitting here was indeed related to a chrome crash bug. However, with Payment Request, a good read for how the shipping address can be pre-selected can be found here:

https://developers.google.com/web/fundamentals/payments/deep-dive-into-payment-request#variants_to_above_flow

It seems like most merchants won't be able to pre-select the address by having a pre-selected shipping option in production because you don't get the address on load of the payment request object, which I think it a huge oversight in how payment request works. This is problematic because:

1) If your shipping options are different based on the ship to location, you can't really pre-pop the shipping options. What if the user's default ship to is invalid (you don't ship to that country, or the country/region/etc. doesn't match the shipping options you have)?

2) You can't properly calculate tax if you don't know where it's going

Pretty much you're left with two alternatives:
1) Collect the user shipping beforehand, and don't allow the user to select their shipping address in the payment request. This obviously defeats a large reason of using payment request in the first place.

2) Don't prepop shippingOptions, basically forcing the user to have to explicitly choose an address.
