### ISSUE TITLE
Enhancement: Add field containers to the tokenizer error object details if applicable

### ISSUE THREAD

**Issue by scottymac** [braintree/braintree-web#359]
* SDK version: 3.32.0 Hosted Fields

The ability to retrieve a hosted field's container for events like `validityChange` e.g. `event.fields[event.emittedBy].container` is really helpful in adding contextual validation errors. 

It would be great if we could also have field containers returned in the `tokenizeErr` object as well. So for example instead of `tokenizeErr.details.invalidFieldKeys` we might have `tokenizeErr.details.invalidFields` that contains both the key and the container. That would make adding contextual errors just as easy.

**Comment by crookedneighbor** [comment]
This seems reasonable to me. Would you be interested in opening a PR?

If not, we'll add it to our backlog.

**Comment by scottymac** [comment]
@crookedneighbor I'd love to, just a matter of finding the time to work on it. I'll see what I can do.

**Comment by crookedneighbor** [comment]
This will go out in the next release.

**Comment by scottymac** [comment]
Wow fantastic, thanks!

**Comment by crookedneighbor** [comment]
Gonna leave this open until the release is actually out.

**Comment by crookedneighbor** [comment]
This is included in v3.34.0
