### ISSUE TITLE
DropIn UI: Function.prototype.apply: Arguments list has wrong type

### ISSUE THREAD

**Issue by dshaw002** [braintree/braintree-web#36]
The Drop In UI hangs at the ajax loading stage on my page. Then it gives me the error in the console:

Function.prototype.apply: Arguments list has wrong type braintree-dropin-internal.min.js

**Comment by mrak** [comment]
Are you linking to `<script src="https://js.braintreegateway.com/v2/braintree.js"></script>`?

**Comment by dshaw002** [comment]
Yes. Here is a snipped from code. All of this is wrapped in form tag. I also tried moving the script section outside of the form tag (leaving only dropin on form tag) and I still have issues. Also on https site, though I'm using self-signed cert for now.

<div id="dropin"></div>
            
      <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
      <script>
        braintree.setup("<?php echo $payment_nonce; ?>", "dropin", {
          container: "dropin",
          paypal: {
            singleUse: true,
            amount: 10.00,
            currency: 'USD'
          }
        });
        </script>

**Comment by EvanHahn** [comment]
@dshaw002 We took a look at this and couldn't reproduce the issue, even when using a site with a self-signed cert. Could you tell us a few things?

1. What browser(s) you see this error in
1. The stack trace (if you could take a screenshot of the trace, that'd be perfect)
1. Any relevant merchant settings

**Comment by dshaw002** [comment]
Sorry for delay. 

1. Chrome
2.
![screen shot 2015-05-19 at 4 56 21 pm](https://cloud.githubusercontent.com/assets/1524593/7713835/5ca582ee-fe48-11e4-9896-8addfe1d843e.png)
3. I think merchant settings are fine.

I got the dropin UI to work on another page on the site. I used simplest settings. Also tried that on the this page and got the same error. I think it's something with page formatting. Let me know if this helps you out.

**Comment by dshaw002** [comment]
I figured out the issue. Working on a template file and it included prototype.js. It creates a conflict with the braintree script (or maybe it's just when prototype.js and jQuery together...). Thank you for your assistance in this issue!

**Comment by kyledetella** [comment]
@dshaw002 thats a good catch and thanks for finding that. We will do some digging of our own to see if there is a way to prevent this in the future.

**Comment by machonemedia** [comment]
It's definitely an issue with Prototype and jQuery. We still have prototype in an app for legacy reasons and run both just fine but we namespace to "jQ".

I tried namespacing it like the following but it won't work:

`<script src="https://js.braintreegateway.com/v2/braintree.js"></script>
<script>
(function ($) {
  // We generated a client token for you so you can test out this code
  // immediately. In a production-ready integration, you will need to
  // generate a client token on your server (see section below).
  var clientToken = "_SANDBOX_TOKEN_";

  braintree.setup(clientToken, "dropin", {
    container: "payment-form"
  });
})(jQuery);
</script>`

**Comment by machonemedia** [comment]
I was having the same problem but have resolved it by simply updating our old Prototype lib which was 1.6.1 to 1.7.3. Patch until we can fully convert all our old Prototype code.

In case someone runs into the same issue and simply removing Prototype isn't an option.
