### ISSUE TITLE
Feature Request: Take font color selection from CSS

### ISSUE THREAD

**Issue by tracerx** [braintree/braintree-web#361]
In an effort to make things easier for our designers, I've been looking for a method to use the braintree-hosted-fields -inavalid and -valid css classes to define the font color in addition to the other styles we're using. I have found a way that works and was wondering if this had been considered for inclusion into the braintree system (since I might be missing a reason you guys decided it wasn't a good fit). Otherwise, could this be used so we'd have the option of not defining the color in create?

```javascript
//get colors from css
var span = document.createElement('span');
span.className = "braintree-hosted-fields-invalid";
document.body.appendChild(span);
var invalidColor = getComputedStyle(span).color;
span.className = "braintree-hosted-fields-valid";
var validColor = getComputedStyle(span).color;
document.body.removeChild(span);
```

**Comment by crookedneighbor** [comment]
I am not against adding this, I think the API would be something like:

```
braintree.hostedFields.create({
  // stuff
  styles: {
    '.valid': '.braintree-hosted-fields-invalid'
  }
});
```

Where you'd pass a classname to pull off all the properties of the whitelisted attributes. https://github.com/braintree/braintree-web/blob/master/src/hosted-fields/shared/constants.js#L42-L74

Though we'd have to `camelCase` them to make that work. Do you have any interest in opening a PR?

**Comment by tracerx** [comment]
I attempted forking and cloning but npm run build doesn't appear to work in Windows. Am I missing something simple or is development typically done in a non-Windows environment?

**Comment by crookedneighbor** [comment]
All our development at Braintree is linux based, so we unfortunately haven't gotten around to making development on this repo easy for windows based machines.

**Comment by crookedneighbor** [comment]
v3.33.0 includes this feature. See the example with the caption `Applying styles with a class name` here: http://braintree.github.io/braintree-web/current/module-braintree-web_hosted-fields.html
