### ISSUE TITLE
example.com URL used instead of a returnUrl / cancelUrl

### ISSUE THREAD

**Issue by lacimarsik** [braintree/braintree-web#362]
### General information

* SDK version: 3.32.1
* Environment: sandbox and production
* Browser and OS: any

### Issue description

Hi Braintree, we experienced an issue where `example.com/?token= ...` URL was used instead of a valid `returnUrl`/`cancelUrl` (see image below, the `example.com` domain is used as the URL for "Cancel and return to" link). Although in reality while shopping, clicking the link would merely close the Paypal checkout's tab, we still had a customer reaching out that they were redirected to `example.com`. They claimed it happened after finishing the payment, using iOS. We couldn't reproduce this behavior, but clearly, something is going on with the return URL (open link in New Tab on the "cancel" link is a safe way to see the redirection).
![screen](https://user-images.githubusercontent.com/2544475/39473438-30970408-4d4f-11e8-8a27-c3519d9d5620.png)

This [similar issue](https://github.com/braintree/braintree-web/issues/286) shows that [createPayment function](https://braintree.github.io/braintree-web/current/PayPalCheckout.html#createPayment) from your paypal-checkout.js uses dummy values `returnUrl:"x",cancelUrl:"x"`. As is noted also in the other thread, we found it hard to override these values with anything meaningful. Can you please look whether this can be treated to avoid anything going to `example.com`?

**Comment by crookedneighbor** [comment]
The real solution here is to update [PayPal's checkout.js](https://github.com/paypal/paypal-checkout) to not require a redirect or cancel url as they are not actually supposed to be used in the flow. Whenever they do occur, that's a bug in the PayPal flow.

I've been lobbying to have these params removed as required parameters, but have had little success so far. I'll bring it up again with the checkout.js folks.

**Comment by lacimarsik** [comment]
Thank you Blade, I found the related issue https://github.com/paypal/paypal-checkout/issues/562

I will wait for a resolution in that thread, we can close this issue.
