### ISSUE TITLE
Hosted Fields are not working on IE 11 browser

### ISSUE THREAD

**Issue by dinoopl7** [braintree/braintree-web#364]
I am using Braintree 3.19 for hosted fields. 

Below file is throwing a javascript error **Object.keys: argument is not an Object**, hence hosted fields are not loading in IE 11 browser.  

https://assets.braintreegateway.com/web/3.19.0/html/hosted-fields-frame.min.html

**Comment by crookedneighbor** [comment]
Is it still not loading when using the latest version, 3.32.1?

**Comment by dinoopl7** [comment]
@crookedneighbor 
It was happening because of the customs styles were having CSS3 properties.
It worked after removing it.
