### ISSUE TITLE
List of values of code property in BraintreeError missing in documentation.

### ISSUE THREAD

**Issue by lpikora** [braintree/braintree-web#367]
### General information

* SDK version: 3.22.2
* Environment: Sandbox
* Browser and OS 

### Issue description

On page https://braintree.github.io/braintree-web/current/BraintreeError.html there is no list of potential values of `code` property.

Only `list` of values of `BraintreeError.code` is available in code example of tokenize method of HostedFields https://braintree.github.io/braintree-web/current/HostedFields.html#tokenize-examples

It could be useful to know which values can BraintreeError.code have.

**Comment by crookedneighbor** [comment]
The docs now show the error codes for each component. https://braintree.github.io/braintree-web/current/BraintreeError.html
