### ISSUE TITLE
Protecting Kount device data on client side

### ISSUE THREAD

**Issue by adimallikarjunareddy** [braintree/braintree-web#370]
### General information

* SDK version: JS v3
* Environment: Sandbox/Production

### Issue description
I am trying to integrate Kount standard integration on an e-commerce platform. Because of the nature of this data and is generated on the client side, I wanted to know if there are any measure Braintree already takes to detect tampering of device data on the client side?

E.g I go to **site1** and grabs the device data (valid user) and hands it over to the fraudster, and then the fraudster uses it on **site1** to pass the Kount decision. 

Are there any measures that we can take or available to protect this data?

**Comment by crookedneighbor** [comment]
There's nothing in particular Braintree needs to do to protect that data. All that is passed along is a UUID that corresponds to the data Kount has captured and Kount makes the determination about fraud from there.

It's up to Kount to determine fraudulent usage, so you do not have to worry about it.

**Comment by adimallikarjunareddy** [comment]
I am not sure if it is sensitive enough to put the data here. But we have tried out a case where the tampering of data (as in copy from someone else's browser) actually worked with the transaction.

**Comment by crookedneighbor** [comment]
I'd contact our support team directly so they can review with our fraud team and investigate if anything is amiss. https://articles.braintreepayments.com/forms/contact

**Comment by skunkworks** [comment]
This seems like an unlikely scenario.

If you are able to hijack the device data from someone else's browser -- for example if your e-commerce site is compromised -- then there are bigger issues than Braintree or Kount are able to address.

If this is a case where a fraudster has access to a "clean" device that passes Kount fraud checks, it's more likely that they would use the clean device to create transactions rather than hijacking the device data from the clean device and using it to create transactions on the dirty device.

**Comment by adimallikarjunareddy** [comment]
@crookedneighbor I have sent the support request.

@skunkworks - apologies if the scenario is not clear from the description. FYI, that device data is always computed on the client side and there is nothing as a platform can do to avoid tampering that data.

BT Device data which is an unique identifier for the current user can be copied in several ways. 

E.g.  I can have a malicious chrome extension that is sending this data from browser to malicious server

Given the above case, buyer/merchant does not know about this device data being used maliciously. If that malicious server uses this data on another site where kount standard integration is implemented and if he can pass the test, then it is a successful misuse of device data.

We have simulated the above scenario by copying device data from a clean device onto an a device where previous kount decision was declined. In this case, we were able to impersonate as a clean device and able to place the transaction with kount decision being approved.

**Comment by crookedneighbor** [comment]
> If that malicious server uses this data on another site

The Kount data is tied to the merchant id, so as far as I know, it cannot be used on another site.

**Comment by adimallikarjunareddy** [comment]
@crookedneighbor - we have simulated this using one merchant id and I am also under the impression that it may not work in general across different merchant ids. However, even with one merchant id case, it is a potential issue.
