### ISSUE TITLE
'Unexpected Token' exception when HostedFields is used together with the DataCollector

### ISSUE THREAD

**Issue by fbrosda** [braintree/braintree-web#371]
### General information

* SDK version: 3.33.0, 3.34.0
* Environment: Sandbox
* Browser and OS: Chromium Version 66.0.3359.181 (Offizieller Build) Built on Ubuntu , running on Ubuntu 16.04 (64-Bit)

### Issue description

We use HostedFields, Paypal and the DataCollector from your SDK. After trying to update from `3.32.1` to `3.34.0` we noticed an Javascript Error: 'Uncaught SyntaxError: Unexpected token / in JSON at position 0', which is caused when when the HostedFields and the DataCollector are included on the same site.

[Here](https://codepen.io/anon/pen/RJbpyP) is a fork of your HostedField example with the DataCollector added, to demonstrate the problem. When you click in one of the input fields, an exception is thrown (please have a look at the dev tools to see the error log). If the script version is changed to `3.32.1` everything works as expected.

In the Changelog I could not find any hint, that the behavior changed with the latest release?

**Comment by crookedneighbor** [comment]
Thanks for the report. We did upgrade the PayPal fraud tools in DataCollector recently, and my guess is that there's a bug with post message causing that error. We will investigate it.

**Comment by demerino** [comment]
We believe we've identified the issue with the PayPal data collector component. We are working on a fix. No update should be required once it goes out. I'll update once it is released.

**Comment by demerino** [comment]
This should be fixed now - let us know if you're still having problems.

**Comment by fbrosda** [comment]
Looks good, thank you :-)
