### ISSUE TITLE
1Password X credit card focus issues

### ISSUE THREAD

**Issue by dferdian** [braintree/braintree-web#375]
### General information

* SDK version: 3.34.0
* Environment: Sandbox & Production
* Browser and OS: Chrome 67.0.3396.99 (Official Build) (64-bit) on MacOS 10.12.6 
* Browser extension: 1Password X Chrome version 1.8.0

#### Context

I have a page that consists of a normal form for billing address details and Braintree Hosted Fields. Everything works fine until recently I upgraded my 1Password X Chrome extension from version 1.7.3  to 1.8.0. The main problem is unexpected focus behaviour which can lead to users frustration because they have to perform an attempt to fill in the form several times before they are able to successfully complete their details.

### Issue description

**1Password X takes out field focus to Braintree Hosted Field credit card number input.**

Everytime I tried to put my cursor focus to the "First Name" input for the _first time_, 1Password X takes out the focus to credit card number. If I try again for the _second time_ to put my cursor to the "First Name" input, it works fine.

The problem occurs again everytime I hit `tab`button from "First Name" input, where it is supposed to go to the "Last Name" input, but 1Password X takes out the focus to credit card number again.

![1password x takes out field focus](https://user-images.githubusercontent.com/21890/42255439-17d92a8c-7f8f-11e8-8068-aef6e75b3129.gif)

**Pressing `tab` button on credit card number field gives unexpected result** 

When I tried to filled in credit card number, then pressed `tab` button for the _first time_, I got the credit card number selected instead of moving the cursor to expiration month input, when I pressed `tab` button for second time only give me expected behaviour.

![1password x tab next focus wrong](https://user-images.githubusercontent.com/21890/42255801-f9694fa8-7f90-11e8-9003-55da4bb287f1.gif)

I can confirmed that those issue only happen with 1Password X version 1.8.0. The issues are not reproducible with following scenarios:
- Works fine with regular 1Password extension (non X version).
- I have tried to remove the 1Password extension completely and everything works fine.

Let me know if there are any further information that I can provide to clarify the issues.

**Comment by dferdian** [comment]
I have contacted 1Password support regarding this issue, but haven't heard back from them

**Comment by crookedneighbor** [comment]
Is this still happening in v1.9.0? I have not been able to reproduce it.

![demo](https://user-images.githubusercontent.com/2916945/43651862-28d2142a-9709-11e8-9e22-6800d920ffa5.gif)

If it's still occurring for you, can you provide a simple code example to reproduce it?

One issue I _am_ experiencing is that the 1Password X extension is opening the "select card" dialog from _within_ the iframe, meaning that it is not clickable as it appears below the fold for the iframed inputs. Aside from not being able to click the saved card, it also hijacks the tabbing and I can't tab to the next input.

This, unfortunately, is out of our control as the 1Password extension is the thing doing it.

**Comment by dferdian** [comment]
This is fixed in 1.9.0, apologies for the late reply, closing this issue, thank you!
