### ISSUE TITLE
Bypass CVV and Expiration required validation

### ISSUE THREAD

**Issue by stevebrownlou** [braintree/braintree-web#377]
### General information

* SDK version: v2 Hosted Fields
* Environment: Any
* Browser and OS: N/A

### Issue description

We are now excepting Maestro cards which some do not have CCV or expiration.
Our sandbox and production environments do not require CCV or AVS validation, but we are not able to submit the transaction without receiving a 'Some payment method input fields are invalid.' message.
Is there a setting to make the CVV and expiration not required?
Or a way to bypass this validation?

**Comment by crookedneighbor** [comment]
Can you provide more information about this? It's my understanding that Braintree requires expiration dates for all credit card transactions. 

You can set up hosted fields without a cvv, however. [Just leave the cvv option out of the setup options](https://developers.braintreepayments.com/reference/client-reference/javascript/v2/hosted-fields#top-level-options).

There are some Maestro debit cards that do not contain a cvv or expiration date, but those cannot be used for online transactions.

**Comment by stevebrownlou** [comment]
I might have bad information from our client on the expiration date.

What if it is unknown at setup if the customer will be using a Maestro card?
Is it possible to make CVV dynamic after setup?

**Comment by crookedneighbor** [comment]
There is currently no way to dynamically turn on and off the cvv field. You can [teardown hosted fields](https://developers.braintreepayments.com/reference/client-reference/javascript/v2/best-practices#teardown) and set it up again without CVV, but not collecting cvv can result in more declines.

My guess is that your client is mistaken about the need to not collect CVV. I'm going to close this for now, but comment here if you find out additional information and I can re-open the issue.
