### ISSUE TITLE
Prefilled fields doesnt' emit events

### ISSUE THREAD

**Issue by manujimenez23** [braintree/braintree-web#385]
### General information

* SDK version: 3.27.0, using hosted fields
* Environment: Sandbox
* Browser and OS: Windows 10. Chrome Versión 68.0.3440.106 (Build oficial) (64 bits)

### Issue description

 Prefilled fields seems to not emit events. 

I need to prefill Expiration Month and Expiration Year to show Customer's credit card information. That information should be able to be changed in the future, so When the customer make any change I need to register this event. Strangely , these fields above are not capable of emitting any type of event when modified.

```
creditCardFormConfig() {
      return {
        fields: {
          number: {
            selector: '#card-number',
            placeholder: 'xxxx xxxx xxxx '.concat(this.last4),
          },
          cvv: {
            selector: '#cvv',
            placeholder: 'Never Stored',
          },
          expirationMonth: {
            selector: '#expiration-month',
            placeholder: 'Expiration month',
            select: {
              options: this.monthOptions,
            },
            prefill: '07',
          },
          expirationYear: {
            selector: '#expiration-year',
            placeholder: 'Expiration year',
            select: true,
            prefill: '2031',
          },
        },
      };
    }

**Comment by crookedneighbor** [comment]
I've edited your comment to make the code snippet easier to read.

Did a quick check, and I was getting events firing for all the fields with prefills in them. Can you provide your event handling logic?

**Comment by manujimenez23** [comment]
Of course.

```
onValidityChange(event) {
      return Promise.resolve().then(() => {
        const isFormValid = Object.keys(event.fields).every(key => event.fields[key].isValid);

        if (isFormValid) {
          this.complete = true;
          this.isLoading = true;
          return this.createCreditCardToken()
            .then(creditCardToken => {
              this.isLoading = false;
              this.isValidToken = true;
              this.$emit('complete', creditCardToken);
            })
            .catch(err => {
              this.isValidToken = false;
              this.$emit('error', err);
            });
        } else {
          this.complete = false;
          this.isValidToken = false;
          this.$emit('invalid');
        }
      });
    },
createCreditCardToken() {
      return this.hostedFieldsInstance.tokenize();
    },

**Comment by manujimenez23** [comment]
I accidentally closed it. 
Here is the event handler.

```
onValidityChange(event) {
      return Promise.resolve().then(() => {
        const isFormValid = Object.keys(event.fields).every(key => event.fields[key].isValid);

        if (isFormValid) {
          this.complete = true;
          this.isLoading = true;
          return this.createCreditCardToken()
            .then(creditCardToken => {
              this.isLoading = false;
              this.isValidToken = true;
              this.$emit('complete', creditCardToken);
            })
            .catch(err => {
              this.isValidToken = false;
              this.$emit('error', err);
            });
        } else {
          this.complete = false;
          this.isValidToken = false;
          this.$emit('invalid');
        }
      });
    },
createCreditCardToken() {
      console.log('++++++++++++++');
      return this.hostedFieldsInstance.tokenize();
    },

**Comment by manujimenez23** [comment]
Without the prefilled info the fields works fine and emit events.

**Comment by crookedneighbor** [comment]
Is the same true for the number and cvv fields?

**Comment by manujimenez23** [comment]
Strangely enough, when I prefill number and cvv fields and then I change both values an event is emitted. So number and cvv works fine. Still having issues with month and year...

**Comment by manujimenez23** [comment]
Text input prefilled fields working fine!! The issue is with prefilled select fields.

**Comment by crookedneighbor** [comment]
@manujimenez23 I wasn't able to reproduce the issue on v3.36.0. Can you confirm that you are changing the selects either from a `valid -> invalid` state or `invalid -> valid` state?

For instance, if you pre-fill the selects with `month = 11` and `year = 2018`, changing the month to `12` or the year to anything higher will not trigger the validity change event, since it went from a `valid -> valid` state. If you'd change the month to 5, that'd make the computed date 5/2018, which would be going from `valid -> invalid` and an event _should_ fire. (and it does in my test)

**Comment by crookedneighbor** [comment]
@manujimenez23 I haven't heard back from you, so I'm assuming everything is working. Going to close this now, but comment here if you still need assistance.
