### ISSUE TITLE
sjcl imports crypto, which drags in crypto-browserify when built for web, which is very large

### ISSUE THREAD

**Issue by lencioni** [braintree/braintree-web#386]
### General information

* SDK version: 3.36.0
* Environment: production
* Browser and OS: irrelevant

### Issue description

1. Set up webpack to build for production for browsers
2. import braintree-web
3. Run webpack

Although [bundlephobia shows that braintree-web is 185 KiB](https://bundlephobia.com/result?p=braintree-web@3.36.0) (which is already very large), in practice it is closer to 470 KiB because it is importing crypto, which webpack uses crypto-browserify for, which is 309 KiB. Here's a visualization:

<img width="1013" alt="sourcemap graph 2018-08-30 15-16-50" src="https://user-images.githubusercontent.com/195534/44882342-c4e8cc00-ac67-11e8-9bc3-89d56bc45c00.png">

This comes in via kount, which imports vendor/sjcl: https://github.com/braintree/braintree-web/blob/a99f2ee3d7a56f4392bbe74e8ccb722d413cbe14/src/data-collector/kount.js#L3

And vendor/sjcl has a line that reads `require('crypto')`: https://github.com/braintree/braintree-web/blob/a99f2ee3d7a56f4392bbe74e8ccb722d413cbe14/src/data-collector/vendor/sjcl.js#L29

I think you could dramatically reduce the bundle size impact of this package by avoiding this!

**Comment by crookedneighbor** [comment]
If you don't utilize data-collector for your braintree integration, you can always require the components directly:

```js
var client = require('braintree-web/client')
var hostedFields = require('braintree-web/hosted-fields')
```

That way you only pull in what you need. If using webpack, this _will_ require you to handle the use of `global` in your webpack configuration.

I do agree though that pulling in a browserified shim of crypto is not great, but unless we can provide a substitute for the functions provided by the Stanford Javascript Crypto Library, we can't simply just drop it.

**Comment by crookedneighbor** [comment]
It'd also be great to get more voices on https://github.com/bitwiseshiftleft/sjcl/issues/362 to encourage bitwise to seek an alternative to crypto.

**Comment by iancmyers** [comment]
@crookedneighbor I noticed that SJCL has a fallback to Web Cryptography: https://github.com/bitwiseshiftleft/sjcl/blob/cc887b518c026407e4ad11ecef37ad9e40d4bd40/core/random.js#L501

What do you think about using the web-crypto shim rather than bundling the browserified node.js crypto? https://github.com/vibornoff/webcrypto-shim

**Comment by crookedneighbor** [comment]
Can you explain a little more what you are suggesting? Are you asking us to switch from sjcl to webcrypto-shim? Or somehow make sjcl use webcyrpto-shim instead of crypto? (if the second, how?)

**Comment by crookedneighbor** [comment]
I just did some checking on the bundle size, and we're not actually using the browserify crypto shim in our bundle. 

In fact, starting in v3.37.0, we provide a `browser` field in the package.json with pre-bundled versions of the modules. So if you're using webpack and have it configured to prefer the browser versions, you'll get the same bundling that we provide on our cdn. The files provided their are unminifed, so you'll have to include minification as part of your build step, if you're not doing that already.

```
du -h ./node_modules/braintree-web/dist/browser/data-collector.js # 32k unminifed
```

**Comment by crookedneighbor** [comment]
Going to close this now because I think the underlying issue has been addressed, but feel free to comment here if y'all are still having issues.
