### ISSUE TITLE
Upgrade new version 3.xxx and keep old version 2.x.x

### ISSUE THREAD

**Issue by tyanhly** [braintree/braintree-web#387]
Hello!

I would like upgrade to v3 but I still want to keep using v2 for some pages.
So, I try to add to my package.json:
```
    "braintree-web-3": "git://github.com/braintree/braintree-web#3.6.0",
```
But When I import this in code
```
import client from "braintree-web3/client";
```
Then it throw an error
```
Error: Can't resolve braintree-web3/client
```

So, how can I do?

**Comment by crookedneighbor** [comment]
The version on github is not 1:1 the version that gets published to npm. See https://github.com/braintree/braintree-web/blob/a99f2ee3d7a56f4392bbe74e8ccb722d413cbe14/tasks/build.js#L42-L93

You _might_ be able to do `import client from "braintree-web3/src/client"`, but that is going to be a hack at best.

Can you explain why you need v2 on some pages? Would it work better to just use the [cdn script for v2](https://js.braintreegateway.com/js/braintree-2.32.1.min.js) on those particular pages?

**Comment by tyanhly** [comment]
Thank for your response @crookedneighbor 
Current code is using v2. So, I am moving code to v3. But, start at 1 first and update step by step for the others. 

> You might be able to do import client from "braintree-web3/src/client", but that is going to be a hack at best.

Maybe have problem, event hack code like this.

I change code to:
```
import braintree from "braintree-web3";
braintree.client.create(...);
```
It throw an Error of package version. 

So, I just want use 2 versions in 1 project. Do you have any suggestions (not change code that is using v2)

**Comment by crookedneighbor** [comment]
Like I said before, there is some processing we do on the repo before publishing to npm to remove development only code, so I don't think your attempt is going to work at all. 

I suggest either using the cdn for one or both versions while you're in transition, or vendor one of them into your project until you're done doing the upgrade.

**Comment by tyanhly** [comment]
@crookedneighbor 
Thanks for your reply.
