### ISSUE TITLE
Change Log

### ISSUE THREAD

**Issue by trainerbill** [braintree/braintree-web#39]
Can we get a change log or some comments on the commits about the changes that were made when you bump versions?  I am guessing they are just bug fixes but it would be nice to know when new functionality is added.

**Comment by kyledetella** [comment]
@trainerbill we are going to add a public changelog with the next release. I will make sure to let you know when its out. Sorry for the delay and thanks for bringing up the issue!

**Comment by kyledetella** [comment]
@trainerbill we have just released version `2.7.2`. As part of this release, we have introduced a public [`CHANGELOG`](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md)

**Comment by trainerbill** [comment]
Awesome!  Thanks!
