### ISSUE TITLE
Programmatically set expirationMonth options

### ISSUE THREAD

**Issue by alimfree** [braintree/braintree-web#393]
I'm using different languages on my  checkout form and I'd like to change the options array programmatically. Is it possible to do something like this? How do I change the select options on the expirationMonth?

I'm trying to do something like this. But doesn't work.       

   ```
    months = ['some', 'date', 'options'] ;
    hostedFieldsInstance.setAttribute({
          field: 'expirationMonth',
          attribute: 'select',
          value: { options: months }
    });
```

**Comment by alimfree** [comment]
I noticed select isn't a supported attribute. I found a workaround for my particular use case. Would be nice to be able do this through the sdk.

**Comment by crookedneighbor** [comment]
You're correct that this is not functionality currently supported by the SDK. 

If this is added, I don't think set attribute is the correct spot, since that is designed to mirror the [set attribute api](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute), and option elements within a select cannot be updated that way. We'd need to expose a new method to accomplish it.

I can see the use case, so I'll bring it up with the rest of the team.

**Comment by alimfree** [comment]
I've also tried tearing down the hosted fields instance and then recreating it by passing in a translated fields object into the fields property when the language is updated on my payment form. 


```
function createHostedFields(clientInstance, lang){
  braintree.hostedFields.create({
    client: clientInstance,
    styles: {
      'input, select': {
        'font-size': '14px',
        'font-family': 'helvetica, tahoma, calibri, sans-serif',
        'color': '#3a3a3a'
      },
      ':focus': {
        'color': 'black'
      }
    },
    fields: lang
  } ,function ...........
});

hostedFieldsInstance.teardown().then((err) => {
            if (err) {
              console.error('Could not tear down hosted fields instance!');
            } else {
              console.info('Hosted fields instance has been torn down!');
              translatedFields = {}
              createHostedFields(braintreeClient, translatedFields);
            }
});
```

Later I check the state of each field and prompt user to please fill out  any empty fields after clicking the submit button. I use the getState() method to check if any fields are empty.  I'm getting an error which states i cannot call hostedFieldsInstance.getState() after calling teardown(). The translation works as expected but i cannot validate and submit the form. Is there anything i can do to get around using getState?



Validation and submission works when i use setAttribute but unfortunately I cannot translate the month options.

**Comment by alimfree** [comment]
I had to unbind the jquery event handler i created. Works for me now.

**Comment by crookedneighbor** [comment]
That makes sense that the old event listener was attempting to call the torn down instance.

You could also do:

```
var hostedFieldsInstance;

someBoundEvent(function () {
  hostedFieldsInstance.getState();
});

function createHostedFields(clientInstance, lang){
  braintree.hostedFields.create({
    /* config */
  } ,function (err, instance) {
    hostedFieldsInstance = instance;
  });
});
```

That way the reference to `hostedFieldsInstance` is always the last created one.

**Comment by crookedneighbor** [comment]
This was added in 3.47.0

https://braintree.github.io/braintree-web/current/HostedFields.html#setMonthOptions
