### ISSUE TITLE
Google Pay Web integration fails with an error "Cannot read property '0' of undefined"

### ISSUE THREAD

**Issue by grigorovich-clearscale** [braintree/braintree-web#396]
### General information

* SDK version: 3.38.1
* Environment: Sandbox
* Browser and OS: 70.0.3538.77 (Official Build) (64-bit) Windows 10 Home v1803
### Issue description

Given a previously working Google Pay integration, when I try to complete a payment in the sandbox, the payment fails with an exception

```
BraintreeError
  code: "GOOGLE_PAYMENT_GATEWAY_ERROR"
  details: {originalError: TypeError: Cannot read property '0' of undefined
    at eval (webpack:///./node_modules/braintree-web/dist/browser/google-payment.js?:514:45)"}
  message: "There was an error when tokenizing the Google Pay payment method."
  name: "BraintreeError"
  type: "UNKNOWN"
```

The error originates at https://github.com/braintree/braintree-web/blob/master/src/google-payment/google-payment.js#L130: apparently, token format generated by the server APIs has changed to return `googleWalletCards` rather than `androidPayCards` and `braintree-web` hasn't been updated accordingly.

This is what the response from Braintree API looks like:
```json
{
  "cardInfo": {
    "cardNetwork": "MASTERCARD",
    "cardDetails": "1111",
    "cardImageUri": "https://lh6.ggpht.com/h6TBIVV7tlYGr1zkIA8CmCzINizzASbPIetpxh_5otBu3VkPEC5_Kk_wH5szy7gDhMkRhVVp",
    "billingAddress": {
      "countryCode": "US",
      "postalCode": "94043",
      "name": "alexei grigorovitch"
    },
    "cardDescription": "Mastercard •••• 1111",
    "cardClass": "DEBIT"
  },
  "paymentMethodToken": {
    "tokenizationType": "PAYMENT_GATEWAY",
    "token": "{\"googleWalletCards\":[{\"description\":\"Google Wallet\",\"details\":{\"cardType\":\"Visa\",\"lastTwo\":\"11\"},\"nonce\":\"this-is-a-token-string\",\"type\":\"Google Wallet Card\"}]}"
  },
  "email": "alexey.grigorovich@clearscale.net"
}
```
Edit: added sample API response.

**Comment by crookedneighbor** [comment]
Thanks for the report. That should not be the case as that is a breaking change.

**Comment by crookedneighbor** [comment]
We'll look into it.

**Comment by crookedneighbor** [comment]
I can no longer reproduce the problem, so it should be back to normal now. Our best guess is that Google changed something with how they communicate with us on the backend. 

Can you check with your integration? If everything is normal again, we can close this issue.

**Comment by grigorovich-clearscale** [comment]
@crookedneighbor confirmed, our integration is back to normal.
