### ISSUE TITLE
What is `CLIENT_AUTHORIZATION`?

### ISSUE THREAD

**Issue by AlexWayfer** [braintree/braintree-web#397]
### Issue description

Hello!

Code examples have `CLIENT_AUTHORIZATION`, but this not described (what is format of this? String? some object from SDK?). 

Also, in some examples it's a String, like key/switcher. There is, for example: https://developers.braintreepayments.com/guides/client-sdk/setup/javascript/v3

I have a key looking like `access_token$sandbox$alpha_numeric$another_alpha_numeric`, and I don't understand what to do next.

**Comment by crookedneighbor** [comment]
Here are the docs for a client authorization: https://developers.braintreepayments.com/guides/authorization/overview

The short answer is that it's either:

• a [client token](https://developers.braintreepayments.com/reference/request/client-token/generate) that you generate on your server for each page load. 

• a [tokenization key](https://developers.braintreepayments.com/guides/authorization/tokenization-key/javascript/v3), which is generated in the Braintree control panel and can basically only tokenize payment methods. (it can't do client side vaulting or 3d secure, etc)

Please reach out to our support team if you have additional questions: https://help.braintreepayments.com/
