### ISSUE TITLE
Ability to disable dropin form event handlers

### ISSUE THREAD

**Issue by mjstallard** [braintree/braintree-web#4]
Hello!

We're using braintree on a form in which the user can opt to pay a subscription fee via Braintree, or opt for a free account instead. If the user chooses the free option, then we hide the Braintree form.

Unfortunately, running braintree.setup('dropin') installs a 'submit' handler on the form permanently, which will validate the credit card information even when the form is hidden. We would like a way to disable the form validation after initializing the dropin component.

We've worked around this for now by monkey-patching addEventListener, but obviously this feels sub-optimal.

Thanks!

Mike

**Comment by rnsloan** [comment]
:+1: to have a safe teardown mechanism. 

If you have a form that allows users to choose from multiple payment options and they select to use braintree a user cannot change option because it does not allow the form to submit unless braintree's form fields have values.

**Comment by tim-massey** [comment]
I also need this solution if you can share it.

**Comment by allenlsy** [comment]
I have a solution, and tested on my local machine:

Set the `onError` handler in `braintree.setup` method (example in coffeescript) :

```coffee
braintree.setup "ENCRYPTED STRING",
      "dropin", {
        container: "js-dropin",
        onError: ->
          $('#new-merchant-form').submit()  // force submit form
      }
```

Hope it works for you guys

**Comment by istolga** [comment]
+1

**Comment by mrak** [comment]
We have recently released a `teardown()` function that will remove all event handlers, DOM objects and iframes put on the page by `braintree.setup()`.

See [our docs on teardown()](https://developers.braintreepayments.com/javascript+node/guides/client-sdk#teardown) for more information.

Let us know if this does not address your issue.

**Comment by crookedneighbor** [comment]
Going to close this now since teardown should take care of this issue. You can re-open the issue and let us know if it doesn't meet your needs.

**Comment by Boycce** [comment]
Hey @crookedneighbor, in my case when giving the user the choice between Paypal and credit card, tearing down the current method when toggling a radio is not optimal. I give kudos though for the `teardown` method!

**Comment by abhijeetahuja** [comment]
+1

**Comment by intelliot** [comment]
Hi @abhijeetahuja -

With v3 (the current version) of braintree-web, each component is separate, making it easy to give users the choice between PayPal and credit card. If there's still a problem, please feel free to open a new Issue. Thanks!
