### ISSUE TITLE
How do I invoke the Paypal integration in a modal? (like how Github is doing it right now)

### ISSUE THREAD

**Issue by sogko** [braintree/braintree-web#40]
I noticed github is using braintree for its payment gateway (e.g. try creating a new private repository).

![screen shot 2015-04-18 at 6 11 38 pm](https://cloud.githubusercontent.com/assets/78585/7215009/64c07368-e5f6-11e4-9602-1973308ca2f7.png)

When I click the Paypal button, it opens an iframe within a modal.

I can't figure out from the documentation whether this is supported. I believe this behaviour comes with braintree client because the iframe id  ```"braintree-paypal-frame"``` is referenced in ~~https://assets.braintreegateway.com/v2/braintree.js~~ https://js.braintreegateway.com/v2/braintree.js

A little bit of digging shows that the github page uses the following configuration to setup the braintree client. I tried the same but I couldn't get the Paypal login to show within a modal.

```
braintree.setup(t, "paypal", {
    displayName: "GitHub",
    container: i,
    paymentMethodNonceInputField: n,
    onSuccess: function() {
         //
    }
});
```

Any help/thoughts?

**Comment by kyledetella** [comment]
@sogko the way the PayPal library works is that it internally determines if it can open the flow in a popup window. If it cannot, we fallback to a modal implementation. 

GitHub was one of our beta partners for Pay with PayPal, and are using a version which has much narrower support for the popup.  We are currently undertaking efforts to help migrate merchants off of beta releases.

We are also working to improve support for popups and with each release we diminish the use cases where we revert to the modal experience. We recommend hotlinking to the latest release of [braintree.js](https://developers.braintreepayments.com/javascript/start/hello-client#js-sdk-setup) to ensure you are able to regularly receive these improvements.

**Comment by sogko** [comment]
hi @kyledetella, thanks for the reply =) I have better understanding about it now.
Just couple more thoughts.

1) Are there reasons for favouring popups over modal experiences for PayPal login? (I remember vaguely reading somewhere in braintree docs or related pages that it was for security / ensuring the user that the paypal login is legitimate? Am I remembering it correctly, and are there more to it?)

2) How about the UX considerations of using popups over modal for paypal login, particularly on mobile browsers? On desktop browsers, the popup does not feel as jarring as it does on my Safari iOS, for example.
Other aspects of the braintree.js (such as adding new payment method, changing it, for example), feels really great, UX-wise, with the exception of the paypal login.

Could there be enough justifications to allow an option to override the default behaviour for Paypal login?
I guess this would be related to the other thread regarding SPAs #29 

Thanks for your time!

**Comment by kyledetella** [comment]
@sogko no problem!

We understand the potential UX benefits of using the modal, but having an address bar (in the popup) allows users the ability to see that they are entering credentials on a secure PayPal domain. We considered this a worthwhile tradeoff.

There are no plans to allow users (merchant developers) the ability to override the popup vs. modal decision. That is an aspect of the experience we need to maintain control over.

**Comment by lvillasica** [comment]
@kyledetella 

Maybe it is better if there is an option in `braintree.setup` for paypal which we can set to either show the paypal form in a new window (default) or within the page (perhaps a modal).

**Comment by danielwu426** [comment]
Hi @lvillasica,

For reasons @kyledetella stated above we will likely not be reintroducing the modal as an option in our PayPal flows. While the UX of a modal is most certainly preferable, our priority is to ensure buyers understand that their credentials are secure during checkout.

Hope this helps clarify and sorry for any inconvenience.

**Comment by maxisam** [comment]
IMHO,

1. Most of general users don't check the URL. You can ask your Mom to verify this theory.

2. Most of general users don't know how to authenticate an URL.

Because of above 2 points, using popup window doesn't really gain any advantage, but losing UX benefit.

To ensure security, I think mandatory enable 2-factor login is the only way. 

But I understand, the kinda decision making is probably not up to engineers.
