### ISSUE TITLE
TypeError: Cannot read property 'host' of undefined

### ISSUE THREAD

**Issue by qwexvf** [braintree/braintree-web#401]
### General information

* SDK version: tested on 3.81.1 and 3.39.0
* Environment: Sandbox
* Browser and OS: Chrome/71.0.3578.62 on Arch Linux (Kernel Version: 4.19)

### Issue description

```
(node:46) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'host' of undefined
at /app/node_modules/braintree-web/client/get-configuration.js:21:38
at new Promise (<anonymous>)
at getConfiguration (/app/node_modules/braintree-web/client/get-configuration.js:17:10)
at /app/node_modules/@braintree/wrap-promise/wrap-promise.js:17:33
at Function.Client.initialize (/app/node_modules/braintree-web/client/client.js:124:13)
at Object.create (/app/node_modules/braintree-web/client/index.js:38:17)
at Object.create (/app/node_modules/@braintree/wrap-promise/wrap-promise.js:17:33)
at Object.create (/app/node_modules/braintree-web-drop-in/index.js:527:17)
at Object.create (/app/node_modules/@braintree/wrap-promise/wrap-promise.js:17:33)
at VueComponent.createDropIn (pages/index.js:117:68)
at VueComponent.created (pages/index.js:107:10)
at callHook (/app/node_modules/vue/dist/vue.runtime.common.js:2919:21)
at VueComponent.Vue._init (/app/node_modules/vue/dist/vue.runtime.common.js:4628:5)
at new VueComponent (/app/node_modules/vue/dist/vue.runtime.common.js:4796:12)
at createComponentInstanceForVnode (/app/node_modules/vue-server-renderer/build.js:7353:10)
at renderComponentInner (/app/node_modules/vue-server-renderer/build.js:7527:40)

(node:46) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

(node:46) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the 
future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Hi, i'm facing a small issue which doesn't affect the web application at all. but thought of leave it on the issues for just in case. Please let me know if more info is needed. Thanks.

**Comment by crookedneighbor** [comment]
Can you give more information about your web app's setup? The line in question is here: https://github.com/braintree/braintree-web/blob/1c052d1fd43cef67229fb5e0d85a526b1700835a/src/client/get-configuration.js#L21

Based on the stack trace, I assume you're using the npm version of the script. 

The only reason that `location` would be undefined is if `global` wasn't being transformed to the window object at build time. (or possibly if you were attempting to use the package in a browser-less environment)

**Comment by qwexvf** [comment]
Hi! Thank you for your support!
As soon as you told me this,
> The only reason that location would be undefined is if global wasn't being transformed to the window object at build time. (or possibly if you were attempting to use the package in a browser-less environment)

I realized that, my braintree-web components was being rendered on the server side.
so, since I'm using nuxtjs for ssr i did 
```
<no-ssr>
<!-- Braintree Web Code here -->
</no-ssr>
```
which fixed the issue! sorry for the inconvenience!

**Comment by lhtdesignde** [comment]
When running mocha tests, I ran into this error so we are actually in a browser-less env. I ended up setting. Is there a reason why you are assuming that the merchant **ID** is a url?

```
global.location = {
  host: 'url'
};
```

**Comment by crookedneighbor** [comment]
@lhtdesignde That's how we identify the merchant in our analytics calls for the JS SDK. In iOS and Android, that would be the app id.

You could, alternatively, mock the Braintree calls since it's unlikely that you actually want to call out to the Braintree gateway in your unit tests.

**Comment by crookedneighbor** [comment]
By mock the Braintree calls, I meant, mock the methods.

Example using sinon:

```js
var sinon = require('sinon');
var fakeClient = {};
var fakeHostedFields = {
  tokenize: sinon.stub().yields(null, {nonce: 'a-nonce'})
};

sinon.stub(braintree.client, 'create').yields(null, fakeClient);
sinon.stub(braintree.hostedFields, 'create').yields(null, fakeHostedFields);
```

**Comment by lhtdesignde** [comment]
awsome thanks for the example!

**Comment by yadav-anil92** [comment]
@crookedneighbor
I'm attempting to use the package in a browser-less environment
I have same issue. I'm using mobile apps as a client.
Send client token to a server and trying to create bankAccountInstance.

```
let clientToken = request.body.data.token;
  client.create({
    authorization: clientToken
  }, (clientErr, clientInstance) => {
    if (clientErr) {
      return response.status(200).send({ data: { "status": 0, "error": clientErr, "message": 'There was an error creating the Client.' } });
    }
    else {
      console.log(JSON.stringify(clientInstance))
      usBankAccount.create({
        client: clientInstance
      }, (usBankAccountErr, usBankAccountInstance) => {
        if (usBankAccountErr) {
          console.log(JSON.stringify(usBankAccountErr))
          return response.status(200).send({ data: { "status": 0, "error": usBankAccountErr, "message": 'There was an error creating the USBankAccount instance.' } });
        }
        else {
          return response.status(200).send({ data: { "status": 1, "account": JSON.parse(JSON.stringify(usBankAccountInstance)), "message": 'USBankAccount instance.' } });
        }
      });
    }
  });
```
Please guide me how to integrate ACH payment flow using a mobile application.

**Comment by crookedneighbor** [comment]
@yadav-anil92 Please contact our support team https://help.braintreepayments.com/

You will want to use the GraphQL API directly, rather than use the web sdk on the server

**Comment by yadav-anil92** [comment]
> than

Could you please guide me on how to create ClientInstance and BackAccountInstance using GraphQL?

**Comment by saraedum** [comment]
I am experiencing the same issue when I set `node: false` in webpack. I could produce a small reproducer if that's helpful.

Is there a known workaround while keeping `node: false`?

I have not looked into this much but what's the reason to use `global.location` and not just `location`?

**Comment by crookedneighbor** [comment]
@saraedum we should look into using `window` for everything instead. The only reason it was `global` is because we have been using browserify to compile the source code into a browser ready script tag, and that was the convention when started using it.

We'll be transitioning to webpack and typescript in the future anyway, but I think we can safely make this change soon. I'll re-open this issue in the meantime.

**Comment by crookedneighbor** [comment]
Gonna re-open this until the release actually goes out

**Comment by crookedneighbor** [comment]
We've switched over from global -> window in v3.63.0, which should take care of your issue @saraedum
