### ISSUE TITLE
NEW :: Payment fields not rendering with hosted fields

### ISSUE THREAD

**Issue by chandanbenjaram** [braintree/braintree-web#404]
### General information

* SDK version: 3.20.1
* Environment: production
* Browser and OS : Safari Version 12.0 (14606.1.36.1.9)

### Issue description
Hello, we are intermittently seeing hosted fields(CC number, exp, cvv) getting into rendering problems...essentially no errors are seen on console however fields are disabled. Our customers can't enter their CC details!

Here is a sample URL to try out:
https://goo.gl/svnctq

From what we see from your changelog, it should have been fixed already. however, this is still coming back!?

Would you mind

**Comment by crookedneighbor** [comment]
Can you update to v3.39.0 (the latest) and report back if it is still not fixed?

**Comment by crookedneighbor** [comment]
(also report back if updating does fix it, there have been numerous updates and fixes to Hosted Fields since v3.20.1)

**Comment by chandanbenjaram** [comment]
let me try and revert back to you then.

**Comment by crookedneighbor** [comment]
Wonderful. Thanks for the update.
