### ISSUE TITLE
dynamically update the "amount" for the PayPal

### ISSUE THREAD

**Issue by chrisschaub** [braintree/braintree-web#406]
Is there a way to dynamically update the "amount" for the paypal button? You can do this now with the drop-in client with updateConfiguration api call. Does a similar call exist for this library? The issue is on a single page app, wanting to adjust the amount if a cart item changes etc.

SDK version: 3
Environment : Sandbox

**Comment by crookedneighbor** [comment]
The `payment` function in checkout.js is called whenever the flow is started, so just grab the details for the payment resource at that point.

Here's a very simple example:

```javascript
function getPaymentOptions() {
  return {
    flow: 'checkout',
    currency: currencyInput.value,
    amount: amountInput.value
  }
}

paypal.Button.render({
  env: 'production', // or 'sandbox'

  payment: function () {
    return paypalCheckoutInstance.createPayment(getPaymentOptions());
  },

  onAuthorize: function (data, actions) {
    // some logic here before tokenization happens below
    return paypalCheckoutInstance.tokenizePayment(data).then(function (payload) {
      // Submit payload.nonce to your server
    });
  }
}, '#paypal-button');
```

**Comment by crookedneighbor** [comment]
If you need additional help with your integration, I encourage you to reach out to our support team: https://help.braintreepayments.com/
