### ISSUE TITLE
DropIn UI: locales

### ISSUE THREAD

**Issue by michelem09** [braintree/braintree-web#41]
I see you can change the Paypal flow locale passing the option "locale", but what about the DropIn form fields?

It should be really helpful to have an option for the dropin too to be able to change the locale of the form.

Otherwise I think the only way to do this is to not use the dropin and create a "custom" form right?

**Comment by kyledetella** [comment]
@michelem09 that is correct. We plan to add support for locales in a future version of Drop-in but I do not have an estimate for that timeline.

**Comment by ubaldo** [comment]
I'll be very interested in locale support for Drop-in. At the time of writing, the only option is to use the hosted fields

**Comment by kyledetella** [comment]
@ubaldo yes, at this point Hosted Fields is your best bet if you want locale support. I will be sure to update here when I have information on locale support for Drop-in.

**Comment by ubaldo** [comment]
So, is it 'Closed" and 'Won't fix'  in the immediate future, right?

**Comment by kyledetella** [comment]
@ubaldo unfortunately, yes this is something that won't be introduced anytime soon. If/when there is something to update on this front, we will be sure to pass along a notice.

**Comment by mullvaden** [comment]
Is there any way for us to help with this? The step from dropin to hosted fields/custom form is quite big. 

And it is only a few fields that needs new texts (and the date input).

**Comment by lilaconlee** [comment]
The [new version of Drop-in](https://developers.braintreepayments.com/guides/drop-in/javascript/v3) is localized in 23 languages. Check out our [developer docs](https://developers.braintreepayments.com/guides/drop-in/javascript/v3#availability) or the [braintree-web-drop-in repo](https://github.com/braintree/braintree-web-drop-in/tree/release#localization) for more details!

**Comment by mullvaden** [comment]
Yay!
