### ISSUE TITLE
Expiration year field supports only 4 digit number

### ISSUE THREAD

**Issue by ivlevkir** [braintree/braintree-web#412]
Hi All,

According to the documentation (https://braintree.github.io/braintree-web/3.41.0/module-braintree-web_hosted-fields.html#~fieldOptions) braintree hosted fields only supports 4 digit format for the expiration year field which is sort of inconvenient because on most credit cards it shows a 2 digit number for the field instead of 4.
I am wondering why braintree chose this path as there have been numerous researches where it's just much better user experience to use 2 digit format. What's the logic behind this decision?

And most importantly is there any way to use 2 digits now or in the future?

**Comment by crookedneighbor** [comment]
Both 2 digits and 4 digits work. We'll update the documentation to make that clearer.
