### ISSUE TITLE
Braintree Javascript SDK v2  OnCancelled not triggered

### ISSUE THREAD

**Issue by muhammad-asad-26** [braintree/braintree-web#414]
### General information

* SDK version: Javascript SDK v 2.32.1
* Environment: Sandbox
* Browser and OS: Chrome on MacOS (10.13.6) High Sierra

### Issue description

Hi, 
We have implemented Braintree Javascript SDK v2 in one of our application, We are using custom setup for paypal, the issue is that when user cancels or close the iframe, we don't get any callback. We want to perform some specific task on cancellation but onCancelled event is not being fired.

```
braintree.setup(clientToken, "custom", {
      paypal: {
        singleUse: true,
        intent: "sale",
        amount: amount,
        currency: "USD",
        locale: "en_us",
        commit: true,
        enableShippingAddress: false,
        headless: true
      },
      onReady: function(integration) {
      ....
      },
      onCancelled: function(obj) {
       ....
      },
      onPaymentMethodReceived: function(payload) {
       ....
      }
    });
```
Another Attempt
```
braintree.setup(clientToken, "custom", {
      paypal: {
        onCancelled: function(obj) {
          .......
        },
       same as above
      },
      onReady: function(integration) {
        ....
      },
      onPaymentMethodReceived: function(payload) {
       ....
      }
    });
```

Nothing seems to work here, any help will be greatly appreciated.

**Comment by crookedneighbor** [comment]
`onAuthorizationDismissed` is the callback that will trigger in that scenario. Use that instead.

And, to be honest, I'd recommend upgrading to version 3 of the sdk rather than using version 2.

**Comment by muhammad-asad-26** [comment]
Thanks,
It worked, Can you please tell me how to render the same custom button in v3. We are facing some challenges in v3 regarding the custom button, that's the only reason why we are still sticked to v2

**Comment by crookedneighbor** [comment]
Version 3 is used in conjunction with PayPal's checkout.js library, which [doesn't allow custom buttons](https://github.com/paypal/paypal-checkout/issues/295) to be used.

(I wish it did)

**Comment by muhammad-asad-26** [comment]
Also can you please tell me when v2 will be completely gone. Like it won't work anymore

**Comment by crookedneighbor** [comment]
There's no planned end date for v2 (in fact, v1 still works), but it currently only receives necessary security updates, which is why I recommend upgrading to version 3 instead.
