### ISSUE TITLE
Unmatched Postal Code throws CVV error

### ISSUE THREAD

**Issue by Heher** [braintree/braintree-web#415]
### General information

* SDK version: 3.42.0
* Environment: Sandbox
* Browser and OS: Chrome Version 72.0.3626.81 on macOS 10.13.6

### Issue description

When testing postalCode validation using the test info on https://developers.braintreepayments.com/reference/general/testing/php#avs-and-cvv/cid-responses, inputting a `20000` postalCode returns a `HOSTED_FIELDS_TOKENIZATION_CVV_VERIFICATION_FAILED` error.

**Comment by crookedneighbor** [comment]
Thanks for the report. That error code is poorly named, it should have been named something to cover avs and cvv responses.

We can't change that now because it would break previous integrations relying on the code, but I've made a note to rename this in the next major version.

**Comment by nidhinarendra** [comment]
To be implemented in the next major version.
