### ISSUE TITLE
GooglePay 2 - Required member supportedMethods is undefined error on setup

### ISSUE THREAD

**Issue by simeyla** [braintree/braintree-web#416]
### General information

* SDK version: 3.42
* Environment: Sandbox
* Browser and OS : Chrome Latest - Windows

### Issue description

Ok - so this issue was several pages long a minute ago, but I narrowed everything down and it seems that the issue actually lies with GooglePay rather than Braintree. 

I thought (very reasonably) that when updating to GooglePay version 2 that I was doing something wrong, but I don't believe that's the case.

**Good news:** 
- The GooglePay sheet opens up in Chrome and lets me select a payment. 
- I get a nonce back just fine.
- I can mark this script as 'blackboxed' to avoid the error with Javascript console open. However based on the URL below it very much looks like it is subject to change.

So I am simply running this:

        const paymentsClient = new google.payments.api.PaymentsClient({environment: 'TEST'});

And here's the error I get:

**TypeError: Failed to construct 'PaymentRequest': required member supportedMethods is undefined**

> "TypeError: Failed to construct 'PaymentRequest': required member supportedMethods is undefined.
>     at iF (https://www.gstatic.com/_/mss/boq-payments-consumer/_/js/k=boq-payments-consumer.InstantbuyFrontendBuyflowPayframeUi.en.B4YMOoaV5dY.O/ck=boq-payments-consumer.InstantbuyFrontendBuyflowPayframeUi.yeoIDllFnqE.L.W.O/rt=j/d=1/exm=_b,_tp,wmwg8b/excm=payframeview,_b,_tp/ed=1/rs=AMitfrhArRyDDDQ2l6GVoUbdibtA08eTig/m=Das5Le,IZT63,PrPYRd,Ru0Pgb,Y2UGcc,ZyYHPb,hc6Ubd,p8L0ob,wI7Sfc,ws9Tlc:232:89)

This error is coming from the following URL (modified a few random characters in case this represents my wallet!): 

https://www.gstatic.com/_/mss/boq-payments-consumer/_/js/k=boq-payments-consumer.InstantbuyFrontendBuyflowPayframeUi.en.B5YMOpaV5dWY.O/rt=j/d=1/excm=payframeview,_b,_tp/ed=1/dg=0/rs=BPitfrhOz_WaLIWMcqt9C6ZEKFcXSk9SKh/m=_b,_tp

I am able to duplicate it error with the absolute minimal page here, and even when adding further code from [Google's own sample code](https://developers.google.com/pay/api/web/guides/tutorial) I still get the same error:

```

<!doctype html>
<html lang="en">
<head>

    <script src="https://pay.google.com/gp/p/js/pay.js"></script>

    <script>
        const paymentsClient = new google.payments.api.PaymentsClient({environment: 'TEST'});
        
    </script>
<body>
    
Run this page in javascript debugger mode

</body>
</html>
```

So I suspect this is a temporary Google bug - but if there's some way to pass in the 'missing' `supportedMethods` and avoid this error I'd love to know how.

In any case I wanted this to be here because others will likely be having this same issue whether temporary or not - and assuming it's BT and not Google at fault.

**Comment by crookedneighbor** [comment]
I can't reproduce the problem you are seeing (and like you said, there's absolutely no Braintree code involved in this). I'd try running it in incognito mode in case you have a browser extension that is causing issues. If you're still having issues after that, contact Google.
