### ISSUE TITLE
Hosted Fields vaulting and Advanced Fraud Tools

### ISSUE THREAD

**Issue by darcy** [braintree/braintree-web#417]
### General information

* SDK version:  3.42.0
* Environment: Production & Sandbox
* Browser and OS: Any

### Issue description

When using `vault: true` on a card with hosted fields via the `tokenize()` method, there is not a way to run Kount on the card before verifying and vaulting it. It seems like we should be able to pass the device data from Kount through on this tokenization method to handle that.

Without being able to do that, we are going to need to re-implement our integration to move the vaulting to the server-side to run the fraud check.

It would be great to support this on the client, are there plans to do so?

In the meantime, it might be good to mention in the `tokenize()` documentation that using the `vault` property is not supported with Advanced Fraud tools. 

![screen shot 2019-03-03 at 9 09 45 pm](https://user-images.githubusercontent.com/6201/53708384-c3f04d00-3df8-11e9-9806-f2a1a40fde5e.png)

https://braintree.github.io/braintree-web/current/HostedFields.html#tokenize

**Comment by crookedneighbor** [comment]
Hi @darcy, this is an issue we're aware of. I'll pass along your feedback to our Fraud Tools team.

In the meantime, if you'd like to open a PR to clarify the documentation, feel free. The param is documented here: https://github.com/braintree/braintree-web/blob/86a6ac4121f0f91b8ebeabfd77e47b5f6403af51/src/hosted-fields/external/hosted-fields.js#L615

**Comment by crookedneighbor** [comment]
This will be fixed in the next release, so I'm going to close this as there's nothing more actionable about it.
