### ISSUE TITLE
How to get the first six digits

### ISSUE THREAD

**Issue by chrishan1995** [braintree/braintree-web#419]
Hello, how can i get the first six digits of the credit card? It looks like we can only get the last four digits. As far as I know, it's okay to display the first six digits according to https://www.pcisecuritystandards.org/pdfs/pci_fs_data_storage.pdf

**Comment by crookedneighbor** [comment]
Hi @chrishan1995, this will be available in the next release of the JS SDK. You'll be able to find it in the tokenization payload under `details.bin`.

I'll update here when it's out.

**Comment by chrishan1995** [comment]
wow, that will be great, thanks @crookedneighbor

**Comment by chrishan1995** [comment]
@crookedneighbor do we have a ETA for the next release of the JS SDK? 🏖

**Comment by crookedneighbor** [comment]
I'm trying to get it out this week, but don't want to promise that it will happen. If not this week, then next week for sure.

**Comment by crookedneighbor** [comment]
This is released in v3.43.0

https://braintree.github.io/braintree-web/current/HostedFields.html#~tokenizePayload

**Comment by chrishan1995** [comment]
thanks! 💯 ❤️
