### ISSUE TITLE
tokenizeMerchant ?

### ISSUE THREAD

**Issue by olingern** [braintree/braintree-web#42]
I got in touch with support about potentially adding this, but it sounds like it's not in the plans.

I'm creating submerchants in a SPA-like environment. It would be amazing to have support for something like this:

         client.tokenizeMerchant({
             dob: dateOfBirth,
             routing: bankRouting,
             account: bankAccount
         }, function(err, submNonce) {
            //off it goes
         });

**Comment by mickeyreiss** [comment]
That’s a great idea! We’ll look into what it would take to make this possible. (Sadly, we can’t commit to the change at this point.)

**Comment by olingern** [comment]
Gotcha. I'll keep an eye out for it down the road. Cheers!
