### ISSUE TITLE
Convert card request data to camel case or not?

### ISSUE THREAD

**Issue by GitProdEnv** [braintree/braintree-web#420]
In [format-card-request-data](https://github.com/braintree/braintree-web/blob/master/src/hosted-fields/internal/format-card-request-data.js) we return an object property `billing_address`. Which we use in
https://github.com/braintree/braintree-web/blob/master/src/hosted-fields/internal/index.js#L232:L242

I copied the important lines:
```

const creditCardDetails = formatCardRequestData(mergedCardData);

      return client.request({
        api: 'clientApi',
        method: 'post',
        endpoint: 'payment_methods/credit_cards',
        data: {
          _meta: {
            source: 'hosted-fields'
          },
          creditCard: creditCardDetails
        }
      })
```

But in the [AVS check example](https://braintree.github.io/braintree-web/current/Client.html#request-examples) the request data contains a camelcased `billingAddress` instead.

**Comment by crookedneighbor** [comment]
The API accepts either version.
