### ISSUE TITLE
Is there a way to fill the form programmatically?

### ISSUE THREAD

**Issue by juliamaksimchik** [braintree/braintree-web#421]
### General information

* SDK version: **3.41.0**
* Environment: **Sandbox** 
* Browser and OS: **Automation with Appium and Browserstack** 

### Issue description

Hi guys,

That not an issue with the library, but more a generic question. 

I am trying to run an automation tests on Iphone X for my project that uses Braintree for payment flow. I have ancounted an issue that [with Appium that it can't load iframe due to same-origin policy](https://github.com/appium/appium/issues/9464) (in my case it's braintree card input iframes). I didn't manage to find any solution for that.

Question: Is there any way to fill the braintree inputs programatically via `postMessage` maybe ? 

Thanks in advance :)

**Comment by hollabaq86** [comment]
Hi @juliamaksimchik, thanks for reaching out. 

When [creating](https://braintree.github.io/braintree-web/current/module-braintree-web_hosted-fields.html#.create) hosted fields, we have options that let you set [fieldOptions](https://braintree.github.io/braintree-web/current/module-braintree-web_hosted-fields.html#~fieldOptions) on the different [fields](https://braintree.github.io/braintree-web/current/module-braintree-web_hosted-fields.html#~field) that will be generated. The `prefill` property sounds like it might be a good fit for your use case:

```
var storedCreditCardInformation = {
  month: '09',
  year: '2017'
};

braintree.hostedFields.create({
  client: clientInstance,
  fields: {
    expirationMonth: {
      selector: '#expiration-month',
      prefill: storedCreditCardInformation.month
    },
    expirationYear: {
      selector: '#expiration-year',
      prefill: storedCreditCardInformation.year
    }
  }
}, callback);

```

`prefill` will pre-populate the field with a value you specify. In the example above, the generated card form would have the expiration dates prefilled with `09` as the month and `2017` as the year.
