### ISSUE TITLE
Paypal create_payment_resource return an error

### ISSUE THREAD

**Issue by elkusto** [braintree/braintree-web#423]
### General information

* SDK version: 3.44.0 
* Environment: LIVE 
* Browser and OS : Chrome 56.0.2924.87 (64-bit) on Linux 

### Issue description

We're using express checkout for paypal. After reder the paypal button, when the user click it, braintree-client sends the following post :
https://api.braintreegateway.com/merchants/<- myMerchandAccount ->/client_api/v1/paypal_hermes/create_payment_resource

and we receive:
{"paymentResource":{"errorName":"invalid_client","errorMessage":"Client Authentication failed","errorDetails":null,"debugId":"f2061d7af437","paypalHttpStatus":401}}
with status : 422 Unprocessable Entity
and in the Chrome console We can see : 
Uncaught Error: Error: PayPal payment options are invalid.
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.4.0.263.js:4570:31)
    at receiveMessage (www.paypalobjects.com/api/checkout.4.0.263.js:4612)
    at messageListener (www.paypalobjects.com/api/checkout.4.0.263.js:4633)

Same request in sandbox works perfectly.
Can you help me to understand what means this error and what can we do to solve it?

**Comment by crookedneighbor** [comment]
Can you provide the code for your integration?

**Comment by crookedneighbor** [comment]
Going to close this for now due to inactivity, but feel free to post your code here and we'll re-open it and take a look.

**Comment by jeancarlos2020** [comment]
THE SAME PROBLEM

`  protected BraintreeFragment initializeBraintreeFragment() throws InvalidArgumentException {
        BraintreeFragment braintreeFragment = BraintreeFragment.newInstance(this, this.token);
        braintreeFragment.addListener(new BraintreeCancelListener() {
            @Override
            public void onCancel(int requestCode) {
                Log.d("JR","==============================ERROR user_cancellatio==============================");
                Log.d("JR",  "User cancelled one time payment");
               //promise.reject("user_cancellation", "User cancelled one time payment");
            }
        });
        braintreeFragment.addListener(new PaymentMethodNonceCreatedListener() {
            @Override
            public void onPaymentMethodNonceCreated(PaymentMethodNonce paymentMethodNonce) {

               // result.putString("nonce", paymentMethodNonce.getNonce());
                if (paymentMethodNonce instanceof PayPalAccountNonce) {
                    PayPalAccountNonce payPalAccountNonce = (PayPalAccountNonce)paymentMethodNonce;
                    // Access additional information
//                    result.putString("payerId", payPalAccountNonce.getPayerId());
//                    result.putString("email", payPalAccountNonce.getEmail());
//                    result.putString("firstName", payPalAccountNonce.getFirstName());
//                    result.putString("lastName", payPalAccountNonce.getLastName());
//                    result.putString("phone", payPalAccountNonce.getPhone());
                    Log.d("JR","==============================ERROR PayPalAccountNonce==============================");
                    Log.d("JR",   payPalAccountNonce.getPayerId());
                }

                //promise.resolve(result);
            }
        });
        braintreeFragment.addListener(new BraintreeErrorListener() {
            @Override
            public void onError(Exception error) {
                if (error instanceof ErrorWithResponse) {
                    ErrorWithResponse errorWithResponse = (ErrorWithResponse) error;
                    Log.d("JR","==============================ERROR ErrorWithResponse==============================");
                    Log.d("JR", errorWithResponse.getErrorResponse());

                }
            }
        });

        return braintreeFragment;
    }`

**Comment by crookedneighbor** [comment]
@jeancarlos2020 This repo is for the JavaScript sdk. Not android.
