### ISSUE TITLE
3DS2 Cannot read property 'cardinalAuthenticationJWT' of null

### ISSUE THREAD

**Issue by adorum** [braintree/braintree-web#426]
### General information

* SDK version: 3.43.0-beta.4
* Environment:Sandbox
* Browser and OS Chrome 72.0.3626.121 on Linux Mint 19.1

### Issue description

Getting promise rejection when calling:
```
threeDSecure.create({
  client,
  version: 2,
}, (err, threeDSecureInstance) => {
  console.log(err);
});
```
Seems that graphql query `ClientConfiguration` does not return `threeDSecure` property on the payload.

**Comment by crookedneighbor** [comment]
Your merchant account must not have been configured to use 3DS 2.0. I'll escalate this to our 3ds team.

What's your public merchant id?

**Comment by crookedneighbor** [comment]
If you need help finding your public merchant id, contact our support https://help.braintreepayments.com/

**Comment by crookedneighbor** [comment]
I've been notified that you are being assisted by our support team. Your issue should be resolved soon.

**Comment by alexbridge** [comment]
We have similar issue. 

SDK version: 3.50.0
Environment: Production

How can we fix it ASAP ?

**Comment by crookedneighbor** [comment]
@alexbridge You will need to contact our support team: https://help.braintreepayments.com/
