### ISSUE TITLE
Sandbox 3DSecure v1 frame password

### ISSUE THREAD

**Issue by kstarzyk** [braintree/braintree-web#427]
### General information

* SDK version: 3.42.0
* Environment: Sandbox
* 3D Secure version 1

### Issue description

Hi, we are using Braintree for last three years (with server side) and recently we've decided to add 3D secure verification.

I cannot find any information specifying one matter: does password passed into 3D secure iframe (sandbox) must be 1234?

<img width="325" alt="Screenshot 2019-05-06 at 10 59 23" src="https://user-images.githubusercontent.com/3145080/57215718-0c410c80-6fee-11e9-8e9c-c6612e4a0021.png">

As far as I've checked given password ('1234', not '1234' or its lack) has **no impact** on received verification object(i.e liabilityShifted, liabilityShiftPossibly) so I suppose that to test incorrect SMS password one need to use proper credit card number. Am I right? Or is there extra layer of verification that must be done on server side?

**Comment by hollabaq86** [comment]
Hi @kstarzyk, please [contact Support](https://help.braintreepayments.com/) referencing this issue, they will be able to assist.

**Comment by kstarzyk** [comment]
Thanks @hollabaq86 for redirection, just wanted to share response that I've received in case if anyone will look for it:

> In the past, Cardinal requested that the test password 1234 should be used with 3D Secure testing but this is no longer the case as they (Cardinal) are now using different card numbers/expiry dates to test different scenarios, so technically you can enter anything as the password in sandbox.
