### ISSUE TITLE
Typescript support missing

### ISSUE THREAD

**Issue by fazpu** [braintree/braintree-web#429]
I know it is a duplicate of https://github.com/braintree/braintree-web-drop-in/issues/157, however I find it annoying that in this time and age there is no Typescript typing for this commonly used library.

Please, it would be awesome if you could add it.

**Comment by gesa** [comment]
I absolutely get why & how this would be annoying, and it's certainly on our radar. I'm sorry that we don't have any plans to provide typing for v3 of this library, but I _am_ expecting that we'll release the next major version with typedefs on day one. In the meantime, [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/braintree-web) accepts PRs! (I cannot endorse those typedefs—they're not provided by us and I haven't tested them)

**Comment by schmod** [comment]
The currently-published types are woefully out of date. 

I've taken the liberty of opening a PR (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35610) to bring the types up to date, and in line with modern TypeScript conventions.  

Unfortunately, it appears that the current maintainer of the typings is looking for somebody else to take over maintenance.  Would this be something that Braintree could assume responsibility for? Given that braintree-web is generally pretty stable, this hopefully wouldn't be a particularly large effort!

**Comment by crookedneighbor** [comment]
We'll look into maintaining it if/when Braintree uses Typescript for the JavaScript SDK. We're tentatively planning on it for the next major version. If that ends up being the case, we'll be happy to maintain type defs for it (as we'll need to write them anyway).

**Comment by jkassis** [comment]
woefully behind stripe. https://www.npmjs.com/package/@types/stripe

**Comment by crookedneighbor** [comment]
The next major release of the SDK (working on now) will be written in typescript, so no need for a separate @types module. We'll update this (and previous issues asking for the same thing) when the new version is ready for beta testing.

**Comment by DwieDima** [comment]
> The next major release of the SDK (working on now) will be written in typescript, so no need for a separate @types module. We'll update this (and previous issues asking for the same thing) when the new version is ready for beta testing.

any news on that @crookedneighbor ?

**Comment by crookedneighbor** [comment]
Only that we're actively working on it. No timelines yet.

**Comment by edwinfinch** [comment]
_insert spongebob time card here_
