### ISSUE TITLE
feature request: teardown should return a promise

### ISSUE THREAD

**Issue by maxisam** [braintree/braintree-web#430]
### Issue description

Is it possible that teardown can return a promise just like create does?

**Comment by crookedneighbor** [comment]
It does. Where are you seeing that it does not?

**Comment by maxisam** [comment]
https://braintree.github.io/braintree-web/current/#teardown 

Just saying if you guys can maintain the type https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/braintree-web/index.d.ts ,

It will be very awesome for people who using Braintree.

**Comment by crookedneighbor** [comment]
The documentation for the methods shows that it does support promises: https://braintree.github.io/braintree-web/current/HostedFields.html#teardown

Like we've said previously, we'll be happy to maintain type definitions once we adopt Typescript for the SDK. It's on our roadmap, but we have other higher priority things to work on at the moment.

**Comment by maxisam** [comment]
But could you guys update the type definition for the time being? it is not like you guys are changing API all the time.
