### ISSUE TITLE
Venmo callback hash is not decoded before parsing fragment parameters causing persistent VENMO_CANCELED error

### ISSUE THREAD

**Issue by tejbirwason** [braintree/braintree-web#432]
### General information

* SDK version: 3.36.0
* Environment: Sandbox
* Browser and OS: Chrome 74.0.3729.157 on Android 8.1.0

### Issue description

The success callback URL that gets sent off to the Venmo app (in the param 'x-success') is encoded. I believe that happens inside `Venmo._intialize` where we stringify the params and encode the callback.

So a return URL that looks like:
`https://example.com#venmoSuccess=1`

would actually return to the following path: 
`https%3A%2F%2Fexample.com%23venmoSuccess%3D1`

with the fragment parameters in the form:
`#venmoSuccess%3D1%26username%3Dtwason%26paymentMethodNonce%3Dfake-venmo-account-nonce`

While testing I noticed that on returning from the Venmo app to my website, the URL is not being decoded before we process the results and retrieve the fragment parameters. Therefore, I keep failing to retrieve the fragment parameters and running into a VENMO_CANCELED error on both iOS and Android.

Looking into the codebase a little more, I noticed that `Venmo._processResults` attempts to get the fragment parameters by splitting on `&`, but this of course fails because the URL is still encoded.

Can you share what might be the problem here?

Thanks!

**Comment by crookedneighbor** [comment]
Does the behavior persist when you upgrade to v3.45.0?

**Comment by tejbirwason** [comment]
Yes, I upgraded to v3.35.0 and I still see the same issue.

**Comment by tejbirwason** [comment]
Any timeline for an update? We are eager to finish the integration.

**Comment by crookedneighbor** [comment]
Ya'll are the only ones who have reported it so far, so we're still trying to reproduce it. Do you have a staging site that can repro it?

**Comment by crookedneighbor** [comment]
I just went through the flow, and the params were not encoded. My guess is there's something peculiar with your integration that is causing this, so I'm going to close this now and have you work with our support team so we can better inspect your specific integration. Provide the link to this Github issue in your ticket.

You can provide them with a staging site that reproduces the issue and they can pass it along to my team for further inspection.
