### ISSUE TITLE
Emitter not having `off` option

### ISSUE THREAD

**Issue by PepijnSenders** [braintree/braintree-web#437]
### Issue description

With the coming of React hooks developers are more inclined to clean up after their components get unmounted. I was wondering why the braintree eventemitter doesn't have an `off` method to remove event listeners from the client.

**Comment by crookedneighbor** [comment]
You're right, for completeness, there should be an `off` method. Added it to the underlying event-emitter package here: https://github.com/braintree/event-emitter/pull/1

However, in the meantime, calling `teardown` on the component instance will also prevent any additional messages from being sent out. Which is the use case I believe you're looking for, cleaning up the component before navigating away from the part of your app that is using it.

**Comment by PepijnSenders** [comment]
Yeah, we're currently using `teardown`, but `off` would be even nicer!

**Comment by crookedneighbor** [comment]
This is fixed in 3.47.0.
