### ISSUE TITLE
Support DOM node in fields.selector

### ISSUE THREAD

**Issue by claytongulick** [braintree/braintree-web#438]
### General information

* SDK version: 
* Environment: all
* Browser and OS all

### Issue description

I'm developing a simple web component wrapper around brain tree hosted fields.

Eventually, I'd like to publish it, and allow the user to select from various prebuilt UI's based off of the examples. Currently, I'm just using it in a project for a client.

The javascript API for hosted fields requires a string selector to determine the container DOM node to inject the iframe into. The current source code does a document.querySelector on that string.

This precludes wrapping the SDK in a web component unless it's rendered to the light DOM, and pollutes the DOM id namespace.

A simple enhancement is to check the selector property to see if it is a string, or if it derives from Element, and set the container accordingly. I've made this change and I'll create a PR that references this issue.

Thanks!

**Comment by crookedneighbor** [comment]
Thanks for the PR, I've left some feedback for you on it.

**Comment by crookedneighbor** [comment]
This is fixed in 3.47.0.
