### ISSUE TITLE
Paypal button layout customization & manual paypal flow trigger

### ISSUE THREAD

**Issue by andrey-ka** [braintree/braintree-web#44]
Hi Braintree team!

Are there any updates on customizing Paypal button since this issue's been closed https://github.com/braintree/braintree-web/issues/17 ?

And if it's not possible to customize paypal button, is there any braintree.js method that opens Paypal's validation iframe and returns payment token ? Because I can't find any explicit method description in documentation.

Thanks in advance!

**Comment by kyledetella** [comment]
@andrey-ka thanks for reaching out. It is still not possible to style the PayPal button with `braintree.js`. We have been exploring avenues for providing a mechanism for developers to invoke the PayPal flow themselves, but there is no timeline on a release for that.

**Comment by andrey-ka** [comment]
@kyledetella thanks for your reply. We will consider it.
