### ISSUE TITLE
Version 3.49.0 does not send expiration date / year

### ISSUE THREAD

**Issue by PepijnSenders** [braintree/braintree-web#447]
### General information

* SDK version: 3.49.0
* Environment: All environments
* Browser and OS: All browsers / OS's

### Issue description

For some reason, the `3.49.0` has code in there where the expirationDate is not being returned when you tokenize the form. I found some internal code differences, like for example here in `credit-card-tokenization.js`:

<img width="658" alt="Screen Shot 2019-08-08 at 11 25 08 AM" src="https://user-images.githubusercontent.com/2052659/62715981-7b544580-b9cf-11e9-96be-a57758561e19.png">

Compare it with `3.50.0`:

<img width="729" alt="Screen Shot 2019-08-08 at 11 28 20 AM" src="https://user-images.githubusercontent.com/2052659/62716090-a3dc3f80-b9cf-11e9-9f3e-a21fcd61e21e.png">

Seems like something went wrong in publishing 3.49.0, because the code that changed this was added in March and 3.49.0 was definitely published after that date.

**Comment by crookedneighbor** [comment]
expiration date in the tokenization payload was added in 3.50.0, so I would not expect it to be present in 3.49.0

https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#3500
