### ISSUE TITLE
Support margin in internal styles

### ISSUE THREAD

**Issue by trumpet2012** [braintree/braintree-web#449]
### General information

* SDK version: 3.31.0
* Environment: Sandbox and Production
* Browser and OS: Chrome 76.0.3809.100 on macOS Mojave 0.14.6

### Issue description

Can we get support for `margin` rule in internal styles for hosted fields?

My problem is essentially the same one as #104. We have a `select` hosted field that is smaller than the field container. 

The padding solution works fine for Firefox, however Chrome does not support adding padding to a select without completely taking over the appearance of the `select` (https://bugs.chromium.org/p/chromium/issues/detail?id=69986). However being able to add a margin will give the same effect.

**Comment by crookedneighbor** [comment]
Thanks for bringing this to our attention, we'll take a look at it.

**Comment by crookedneighbor** [comment]
This is now supported in 3.52.0
