### ISSUE TITLE
Paypal iframe additional information

### ISSUE THREAD

**Issue by andrey-ka** [braintree/braintree-web#45]
Hi Braintree team,
I'm working on paypal button applying on rails application. Here is my raw example of button initialization:
```javascript
braintree.setup(token, 'paypal', {
        container: 'paypal_container_vault',
        singleUse: true, // We don't store paypal payment method in vault
        currency: 'USD',
        paymentMethodNonceInputField: 'paypal_vault_input',
        onPaymentMethodReceived: function(responseObj){
            console.log(responseObj);

            $('form#braintree_transaction_paypal_vault').submit();
        },
        onCancelled: function(responseObj){
            console.log(responseObj);
            alert('Canceled')
        }
    });
```

form html:

````html
<form accept-charset="UTF-8" action="/payment/create_transaction_paypal" id="braintree_transaction_paypal_vault" method="post">
   <div class="element">
   <div class="label">
   <label>Enter Amount and loging Paypal</label>
   </div>
   <input name="amount" type="text" value="">
   <input id="paypal_vault_input" name="payment_method_nonce" type="hidden" value="">
   </div>
   <div class="element">
   <div class="label">
   <label>Enter Any invoice id</label>
   </div>
   <input name="id" type="text" value="">
   </div>
   <div id="paypal_container_vault"></div>
</form>
````
As a result within braintree sandbox credentials I receive an opportunity to login with any valid email and password:
![paypal_creds](https://cloud.githubusercontent.com/assets/10156946/7538883/f108b7a8-f5ab-11e4-8373-e3ff1ca04790.png)

After pressing login I receive only updated paypal button container 
![paypal_auth_result](https://cloud.githubusercontent.com/assets/10156946/7539042/e85463cc-f5ac-11e4-9350-49984a8d80e9.png)

Is it possible to send certain purchase details in order to show it paypal's iframe?
Because we think it's a little bit confusing for customer to be redirected to website page just after successful paypal authorization without any notification on paypal's iframe.

Thanks in advance!

**Comment by schneiderik** [comment]
Hey @andrey-ka, I'm a front-end developer on the Pay with PayPal team at Braintree.  Thanks for providing the code snippets and images.  Currently when a user completes the PayPal authorization, the popup will close and the button container will switch to a "logged in" resolution state as you've shown above.  We currently don't provide any way of showing a successful authentication within the popup.   The popup closing, and the act of the button switching to the resolution state are the only indicators that a PayPal flow have successfully authenticated.

You could hook in to the `onPaymentMethodReceived` and display a successful authentication view to your users on your page before you submit the form.

Let us know if you have anymore questions.
