### ISSUE TITLE
A general error has occurred with Cardinal (Invalid JWT)

### ISSUE THREAD

**Issue by gzurbach** [braintree/braintree-web#450]
### General information

* SDK version: 3.50.1
* Drop-in UI: 1.20.0
* Environment: Production
* Browser and OS: Unknown

### Issue description

We recently started using 3DS 2.0 in our Ember app. After a few days we've addressed most issues. However, several times a day we're seeing this error in our Sentry logs:
```
BraintreeError: A general error has occurred with Cardinal. See description for more information.
```
Here is the content of `error.details`:
```js
{
  originalError: {
    code: 1020, 
    description: "Invalid JWT. Error verifying and deserializing JWT."
  }
}
```
The error occurs while calling:
```js
await instance.requestPaymentMethod({ threeDSecure });
```

Is this something we could prevent somehow? We're seeing a few occurrences of this error every day. Let me know if you need more details. Thanks!

**Comment by gesa** [comment]
hey @gzurbach, this seems like it might be a job better-suited for our support team at https://help.braintreepayments.com/. Shoot them a message, and they'll pull myself or someone else on the SDK team back in if we're needed once they have a little more merchant-specific info.

**Comment by adorum** [comment]
Hi, same issue here. Any solution? What the helpcenter says?

**Comment by crookedneighbor** [comment]
@adorum Please contact our support team so we can look into your account. https://help.braintreepayments.com/

**Comment by terryyin** [comment]
I'm having the same issue. The Braintree support didn't help in this situation as they don't have any log on the server side. It seems this error happens within the js code. Would love to know how other people fixed this. Or, at least, how to debug this.

**Comment by adorum** [comment]
@terryyin I contacted braintree support team and they fixed it. It was a configuration issue on their side. Check out the related issue #426

**Comment by terryyin** [comment]
Thanks! I will forward this to my supporting thread.
