### ISSUE TITLE
Cannot test ACH in sandbox for tokenized check.

### ISSUE THREAD

**Issue by paul-gene** [braintree/braintree-web#451]
### General information

* SDK version: 3.48.0
* Environment: Sandbox
* Browser and OS: Mac OS High Sierra + Chrome 76

### Issue description

Trying to tokenize Bank Login details, using the method shown [here](https://developers.braintreepayments.com/guides/ach/client-side/javascript/v3#tokenize-bank-account-information).

When submitting my payment form, I'm not seeing any popups or the like, so not sure why it's saying I closed the bank login.

An error is returned:

```
code: "US_BANK_ACCOUNT_LOGIN_CLOSED"
details: undefined
message: "Customer closed bank login flow before authorizing."
name: "BraintreeError"
type: "CUSTOMER"
```

**Comment by crookedneighbor** [comment]
Can you provide your full code for creating the bankLogin object? Including the example values being passed in.

That error should only trigger when the `onExit` callback is called in the Plaid SDK: https://github.com/braintree/braintree-web/blob/60300e5ff86654546a6a74d35ef6102ebfa497e1/src/us-bank-account/us-bank-account.js#L277

I _thought_ that only occurred when a customer closes without proceeding, but it may also happen with invalid input.

**Comment by paul-gene** [comment]
Please see my JS code below. The `achInstance` is initialized beforehand, and this code is triggered when clicking the order button.

```
            clickAchBtn: function () {
                var self = this;
                var billingAddress = quote.billingAddress();

                var bankDetails = {
                    routingNumber: self.routingNumber(),
                    accountNumber: self.accountNumber(),
                    accountType: self.accountType(),
                    ownershipType: self.ownershipType(),
                    billingAddress: {
                        streetAddress: billingAddress.street[0],
                        extendedAddress: billingAddress.street[1],
                        locality: billingAddress.city,
                        region: billingAddress.regionCode,
                        postalCode: billingAddress.postcode,
                    }
                };

                if (bankDetails.ownershipType === 'personal') {
                    bankDetails.firstName = self.firstName();
                    bankDetails.lastName = self.lastName();
                } else {
                    bankDetails.businessName = self.businessName();
                }

                var mandateText = document.getElementById('braintree-ach-mandate').textContent;

                this.achInstance.tokenize({
                    bankDetails: bankDetails,
                    mandateText: mandateText
                }, function (tokenizeErr, tokenizedPayload) {
                    if (tokenizeErr) {
                        self.setErrorMsg($t('There was an error with the provided bank details. Please check and try again.'));
                        self.hasAuthorization(false);
                    } else {
                        self.handleAchSuccess(tokenizedPayload);
                    }
                });
            },
```

**Comment by crookedneighbor** [comment]
^ this could is using the bankDetails flow, not the bankLogin flow. There should be no reason you are getting the `US_BANK_ACCOUNT_LOGIN_CLOSED` error.

**Comment by crookedneighbor** [comment]
Do you have alternate code that _is_ using the `bankLogin` flow? Can you provide a staging site/repo that reproduces the error?

**Comment by paul-gene** [comment]
Apologies, I have edited the code. It's practically the same ;)

**Comment by crookedneighbor** [comment]
This works just fine for me:

```js
var bankLogin = {
  displayName: 'My JavaScript Integration App',
  ownershipType: 'personal',
  billingAddress: {
    firstName: 'First',
    lastName: 'Last',
    streetAddress: '222 W Merchandise Mart Plaza',
    extendedAddress: '',
    locality: 'Chicago',
    region: 'IL',
    postalCode: '60654'
  }
};

usBank.tokenize({
  bankLogin: bankLogin,
  mandateText: 'I authorize Braintree to charge my bank account on behalf of Test Merchant.'
}, function (tokenizeErr, tokenizedPayload) {
  // send tokenizedPayload.nonce to server
});
```

The most likely thing is that your account is not enabled for plaid. If you see something like `vendors~LazyLink.js:50 Error: Invalid key: key cannot be missing.` in your console, that's definitely it.

Reach out to our support team so we can inspect your account. Feel free to reference this issue. https://help.braintreepayments.com/
