### ISSUE TITLE
Shift-Tabbing on desktop in IE and Firefox is not working

### ISSUE THREAD

**Issue by jmsjr** [braintree/braintree-web#455]
### General information

* SDK version: 3.52.1
* Environment: Sandbox
* Browser and OS : IE11, Chrome 77.0.3865.75 (Official Build) (64-bit), and Firefox 69.0

### Issue description

This is a continuation from https://github.com/braintree/braintree-web/issues/380

With 3.52.1, tabbing forward now works. A lot better than before.
However, Shift-Tab ( to go backwards ) when hosted field has focus ...:

- Works with Chrome
- Does not work In IE ( IE11 at work ) ...e g. stuck on the hosted field 
- Works only if you do it twice In Firefox ... e.g. do Shift-Tab twice to get unstuck from hosted field

Attached is a ZIP file with a self-contained HTML using 3.52.1 and using hosted fields. Just replace the "sandbox_xxxxxxxx" with your own static authorisation key, then open with your browser. Do tabs and shift-tabs in IE and in Firefox.

[braintree-test.zip](https://github.com/braintree/braintree-web/files/3612278/braintree-test.zip)

**Comment by crookedneighbor** [comment]
Thanks for the report, we'll take a look.

**Comment by crookedneighbor** [comment]
This should be fixed now in v3.53.0
