### ISSUE TITLE
Hosted fields tabbing on iOS disabled in 3.52.1 version

### ISSUE THREAD

**Issue by deviousknight** [braintree/braintree-web#457]
### General information

* SDK version: 3.52.1
* Environment: Sandbox/Prod
* React Native iOS WebView

### Issue description

In 3.52.1 ability to 'tab' between hosted fields on iOS was removed/broken.
![Screen Shot 2019-09-18 at 18 14 59](https://user-images.githubusercontent.com/19371283/65162143-7c9e7680-da41-11e9-9cdb-2ea329b2f393.png)

As you see on the screenshot there is no active arrows for tabbing. Previously we were using v3.51.0 and tabbing with iOS keyboard arrows works. We would like to still use v3.51.0 but there are another issue with tabbing https://github.com/braintree/braintree-web/issues/456.

**Comment by crookedneighbor** [comment]
We made some changes to how tabbing works on devices with software keyboards, but the only way we could do it reliably was to depend on the inputs being in a form element. Simply wrapping your hosted fields in a `<form>` element should cause the tab arrows to re-appear.

I'll get the documentation updated to reflect this.

**Comment by deviousknight** [comment]
yep, wrapping in the form tag helped, thank you
