### ISSUE TITLE
PayPal integration in Android WebView not working

### ISSUE THREAD

**Issue by hlaueriksson** [braintree/braintree-web#459]
### General information

* SDK version: Javascript SDK, version 3.52.1
* Environment: Production
* Browser and OS: WebView (Chrome 77.0.3865.73), Android 9

### Issue description

We use the Braintree JavaScript SDK for our PayPal checkout. The checkout is used on our site, as well as rendered from within our mobile apps. Everything works fine, except for the WebView in the Android app.

Here's a step-by-step:
1. Initiate the PayPal flow. This is done by calling [`tokenize`](https://braintree.github.io/braintree-web/current/PayPal.html#tokenize) on an [PayPal instance](https://braintree.github.io/braintree-web/current/PayPal.html) that we created using `braintree.paypal.create({...})`
2. A PayPal log in screen is rendered where only e-mail address can be entered. We enter a valid e-mail address.
3. Next screen rendered is one where PayPal prompts for a password. We enter the correct password.
4. We are redirected to another PayPal login screen, this time with both e-mail address and password. The same credentials are entered again.
5. We are redirected to a PayPal page with a reCAPTCHA
6. After completing the reCAPTCHA challenge, we arrive at a "pay with credit card" page with a button to "Agree & Continue".
7. When clicking the "Agree & Continue" button, a spinner with "Processing" appears, and when it disappears we are left with a blank white page.

When trying the same checkout on a browser on the same device, we are prompted with only one login flow (the one where email address and password in rendered together). This time, no reCAPTCHA challenge. After pressing "Agree & Continue", we return to our checkout.

Any ideas why this is?

**Comment by scannillo** [comment]
Hello. To help us get a better understanding of your integration, are you using the [pop-up bridge](https://github.com/braintree/popup-bridge-android)? Since by default WebViews cannot open pop-ups, which is what the PayPal flow relies on, we offer this pop-up bridge as a solution for integrations embedded in a WebView. If you are not using the pop-up bridge, we can’t guarantee that your current setup will work, as a PayPal checkout does not officially support WebViews.

**Comment by hlaueriksson** [comment]
Hi! Thanks for the info. We are not using the pop-up bridge. We will integrate it now.

**Comment by ZoltanSzokodi** [comment]
Hi @hlaueriksson,

I am facing a similar problem with my PayPal flow (Smart Payment Buttons) on Android via webview. I would be grateful if you could answer a few brief questions:

Is your app a React Native app? 
If yes did you use the community edition react-native-webview? (the original RN built-in one is no longer supported)
And finally did the Braintree pop-up bridge solve your problem?

Many thanks in advance!

**Comment by hlaueriksson** [comment]
Hi @ZoltanSzokodi 

No, we are using Kotlin.

**Comment by crookedneighbor** [comment]
@ZoltanSzokodi please reach out to our support team about this: https://help.braintreepayments.com/
