### ISSUE TITLE
Expose "will present challenge" to 3DSv2's onLookupComplete callback

### ISSUE THREAD

**Issue by martinandert** [braintree/braintree-web#461]
When the `onLookupComplete` callback is executed, there seems to be no easy way for merchants to find out whether the user is going to be challenged or not. We'd like to have this info in order to be able to, e.g., adjust our success/error messages accordingly later in the payment flow.

Thus, it would be nice to be able to do something like this:

```js
let challengePresented;

await threeDSecure.verifyCard({
  onLookupComplete(lookupResponse, next) {
    challengePresented = lookupResponse.willPresentChallenge;
    next();
  },
  // other options...
});

// later on...
if (someThreeDSecureError) {
  if (challengePresented) {
    alert("You failed the 3-D Secure challenge");
  } else {
    alert("3-D Secure authorization unsuccessful");
  }
}
```

So basically, we'd like to see [the result of this line](https://github.com/braintree/braintree-web/blob/9180075cfa673ab6a83ad114107b9262dde37780/src/three-d-secure/external/three-d-secure.js#L770) exposed in some way to the `onLookupComplete` callback.

**Comment by danburzo** [comment]
@martinandert I may be misunderstanding the code you referenced, but it looks like it's the same `lookupResponse` available in the `onLookupComplete` callback, so technically you can do the same computation?

```js
    var challengePresented = Boolean(lookupResponse.lookup && lookupResponse.lookup.acsUrl);
```

If that's the case, it might need to be documented here, as long as it's the canonical way to tell whether the user will be presented with a challenge:
https://braintree.github.io/braintree-web/current/ThreeDSecure.html#~verificationData

**Comment by martinandert** [comment]
> so technically you can do the same computation?

@danburzo I could do this, yes, but it's an undocumented private API. I'd rather use something official instead of having to rely on a library-internal API that could change any time.

**Comment by crookedneighbor** [comment]
@martinandert thanks for the feedback, in v3.53.0 we've added a `requiresUserAuthentication` value to the lookup data that indicates if a challenge will be shown or not. https://braintree.github.io/braintree-web/current/ThreeDSecure.html#~verificationData

```js
threeDS.verifyCard({
  // other verifyCard params here
  onLookupComplete: function (data, next) {
    if (data.requiresUserAuthentication) {
      // logic to determine if 3ds flow should be cancelled goes here
      return threeDS.cancelVerification();
    }
    next();
  }
}).then(function (payload) {
```

(alternatively, you can use the new event method of listening for the lookup)

```js
// right after setting up 3ds instance
threeDS.on('lookup-complete', function (data, next) {
  if (data.requiresUserAuthentication) {
    // logic to determine if 3ds flow should be cancelled goes here
    return threeDS.cancelVerification();
  }
  next();
});

// after tokenizing card
threeDS.verifyCard({
  // verification params (no need to include an onLookupComplete callback)
}).then(function (payload) {
```
