### ISSUE TITLE
CLIENT_GATEWAY_NETWORK error in test environment

### ISSUE THREAD

**Issue by timcraft** [braintree/braintree-web#463]
### General information

* SDK version: braintree-web v3.54.0 (braintree-web-drop-in v1.20.3)
* Environment: Sandbox
* Browser and OS: Google Chrome 77

### Issue description

We've started getting this error from braintree-web in our sandbox test environment:

![Screenshot 2019-10-10 at 11 14 03](https://user-images.githubusercontent.com/896098/66562714-1befee80-eb54-11e9-9287-c1e5b5df5905.png)

Everything is working as expected in development and production environments. Everything was working as expected in our test environment previously (the error first started showing up in CI around August 30th). For some unknown reason it has stopped working in our test environment, the knock on effect being that the braintree-web-drop-in UI does not load and our tests fail.

It's not clear which credentials these are referring to? Our Braintree API credentials haven't changed. Is this related to the Cardinal Authentication JWT fix in 3.50.1, or a different issue?

**Comment by crookedneighbor** [comment]
Can you share the client authorization you are using?

Are you using an access token on the server (do not share it)? And are you generating a client token with a customer Id? If so, I have an idea about what is happening.

**Comment by timcraft** [comment]
> Can you share the client authorization you are using?

Yes—the authorization passed to `braintree.dropin.create` is a client token, which is generated on the server with `Braintree::ClientToken.generate` (Ruby).

The client token isn't generated with a customer id afaict.

**Comment by crookedneighbor** [comment]
Can you share a sample client token here?

Also, can you confirm if you're using an access token or public/private keys on the server to generate the client token?

**Comment by timcraft** [comment]
> Can you share a sample client token here?

```
eyJ2ZXJzaW9uIjoyLCJhdXRob3JpemF0aW9uRmluZ2VycHJpbnQiOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpGVXpJMU5pSXNJbXRwWkNJNklqSXdNVGd3TkRJMk1UWXRjMkZ1WkdKdmVDSjkuZXlKbGVIQWlPakUxTmpjeU5qa3lOallzSW1wMGFTSTZJbVUxTldZNFlqSTFMV016WTJRdE5HWmpaUzFpTUdKbExXRTBNelE0TUdFM1pXWmxZeUlzSW5OMVlpSTZJbkkxZGpnelltWm5iVFZ4YUdnNVluWWlMQ0pwYzNNaU9pSkJkWFJvZVNJc0ltMWxjbU5vWVc1MElqcDdJbkIxWW14cFkxOXBaQ0k2SW5JMWRqZ3pZbVpuYlRWeGFHZzVZbllpTENKMlpYSnBabmxmWTJGeVpGOWllVjlrWldaaGRXeDBJanBtWVd4elpYMHNJbkpwWjJoMGN5STZXeUp0WVc1aFoyVmZkbUYxYkhRaVhTd2liM0IwYVc5dWN5STZlMzE5LnVzRWNOX3NtZjdFX2Njdmdob1NCZ24zNFBiUmVGOHI1QUZTcFVMeE90Tmt2VDFGc0RFV1FTamxEcVpPZUE1cU9OOGtCaE1La0MxdUF2UGI4SjBtRGtnIiwiY29uZmlnVXJsIjoiaHR0cHM6Ly9hcGkuc2FuZGJveC5icmFpbnRyZWVnYXRld2F5LmNvbTo0NDMvbWVyY2hhbnRzL3I1djgzYmZnbTVxaGg5YnYvY2xpZW50X2FwaS92MS9jb25maWd1cmF0aW9uIiwiZ3JhcGhRTCI6eyJ1cmwiOiJodHRwczovL3BheW1lbnRzLnNhbmRib3guYnJhaW50cmVlLWFwaS5jb20vZ3JhcGhxbCIsImRhdGUiOiIyMDE4LTA1LTA4In0sImNoYWxsZW5nZXMiOltdLCJlbnZpcm9ubWVudCI6InNhbmRib3giLCJjbGllbnRBcGlVcmwiOiJodHRwczovL2FwaS5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tOjQ0My9tZXJjaGFudHMvcjV2ODNiZmdtNXFoaDlidi9jbGllbnRfYXBpIiwiYXNzZXRzVXJsIjoiaHR0cHM6Ly9hc3NldHMuYnJhaW50cmVlZ2F0ZXdheS5jb20iLCJhdXRoVXJsIjoiaHR0cHM6Ly9hdXRoLnZlbm1vLnNhbmRib3guYnJhaW50cmVlZ2F0ZXdheS5jb20iLCJhbmFseXRpY3MiOnsidXJsIjoiaHR0cHM6Ly9vcmlnaW4tYW5hbHl0aWNzLXNhbmQuc2FuZGJveC5icmFpbnRyZWUtYXBpLmNvbS9yNXY4M2JmZ201cWhoOWJ2In0sInRocmVlRFNlY3VyZUVuYWJsZWQiOnRydWUsInBheXBhbEVuYWJsZWQiOnRydWUsInBheXBhbCI6eyJkaXNwbGF5TmFtZSI6IlN0YWxsaWMgTHRkIiwiY2xpZW50SWQiOm51bGwsInByaXZhY3lVcmwiOiJodHRwOi8vZXhhbXBsZS5jb20vcHAiLCJ1c2VyQWdyZWVtZW50VXJsIjoiaHR0cDovL2V4YW1wbGUuY29tL3RvcyIsImJhc2VVcmwiOiJodHRwczovL2Fzc2V0cy5icmFpbnRyZWVnYXRld2F5LmNvbSIsImFzc2V0c1VybCI6Imh0dHBzOi8vY2hlY2tvdXQucGF5cGFsLmNvbSIsImRpcmVjdEJhc2VVcmwiOm51bGwsImFsbG93SHR0cCI6dHJ1ZSwiZW52aXJvbm1lbnROb05ldHdvcmsiOnRydWUsImVudmlyb25tZW50Ijoib2ZmbGluZSIsInVudmV0dGVkTWVyY2hhbnQiOmZhbHNlLCJicmFpbnRyZWVDbGllbnRJZCI6Im1hc3RlcmNsaWVudDMiLCJiaWxsaW5nQWdyZWVtZW50c0VuYWJsZWQiOnRydWUsIm1lcmNoYW50QWNjb3VudElkIjoic3RhbGxpY2x0ZCIsImN1cnJlbmN5SXNvQ29kZSI6IkVVUiJ9LCJtZXJjaGFudElkIjoicjV2ODNiZmdtNXFoaDlidiIsInZlbm1vIjoib2ZmIn0=
```
> Also, can you confirm if you're using an access token or public/private keys on the server to generate the client token?

Public/private keys on the server.

**Comment by crookedneighbor** [comment]
This doesn't match the known issue I was thinking about, so I think your best course of action is to reach out to our support team so we can dig into your account: https://help.braintreepayments.com/

Feel free to include a link to this issue so I can work with the support rep to track this down. I'm going to close this issue, because I'm certain there are no sdk changes that will be needed to address this.

**Comment by timcraft** [comment]
Problem solved. For anyone running into these symptoms: this is what happens when a VCR cassette is re-recorded without including all the necessary requests.

@crookedneighbor Not a bug! Thanks for the quick response.
