### ISSUE TITLE
Authenticating user locally from PayPal nonce 

### ISSUE THREAD

**Issue by simeyla** [braintree/braintree-web#464]
### General information

* SDK version: Any
* Environment: Any
* Browser and OS : N/A

### Issue description

I have a completely custom shopping cart implementation using Braintree Javascript + .NET SDK (not drop-in UI).

When I used to implement the PayPal flow with their native Express Checkout API I was able to validate unequivocally on the server that a user was really logged in with a particular email address. I was then able to log them into my website automatically - assuming that if they have access to a PayPal account they should be allowed access to my site.

I wanted to do the same again, but there doesn't seem to be a way to verify the PayPal account email on the server side. It is only given to me on the client side - so I obviously can't it to log somebody in.

I was hoping that I could decode the PayPal nonce on the server, but there's no user email information inside a PayPal nonce.  

Is 'Connect with PayPal' still a thing or got any integration with Braintree? I think even if it does it's overkill for this. Is there no good way to authenticate someone locally after they've proven to me they own a particular PayPal account? It was very convenient and without this mechanism I'm sure I'm losing some sales.

**Comment by crookedneighbor** [comment]
If you're using the latest version of the .NET sdk (added in [v4.13.0](https://github.com/braintree/braintree_dotnet/blob/master/CHANGELOG.md#4130)), you have the ability to look up the PayPal email from the nonce on your server: https://developers.braintreepayments.com/reference/response/payment-method-nonce/dotnet#details.payer_info

You can get this object by calling the find method: https://developers.braintreepayments.com/reference/request/payment-method-nonce/find/dotnet

I've never heard of someone using the PayPal email as an authentication method, but this server side method should do the trick.

**Comment by simeyla** [comment]
@crookedneighbor Best news all day :-) Thanks.

Also very nice to see first name and last name separated - unlike in the shipping address direct from PayPal. Helps in my logic to extract first/last :-)
