### ISSUE TITLE
client.create: 'uncaught exception' on invalid authorization

### ISSUE THREAD

**Issue by sizzlefinger** [braintree/braintree-web#465]
### General information

* SDK version: 3.54.1
* Environment: https://js.braintreegateway.com/web/3.54.1/js/client.min.js
* Browser and OS: Firefox, Chrome (Windows)

### Issue description

Calling:

**braintree.client.create({ authorization: "12345" })**

as a promise or with callback returns error as it should, but also causes browser to throw an 'uncaught exception' message in the console.  

Calling the same method with 'authorization: ""' does not cause the exception to be thrown.

Thanks!

**Comment by hollabaq86** [comment]
👋 @sizzlefinger thanks for reporting, we're looking into it.

**Comment by crookedneighbor** [comment]
This is fixed in 3.54.2
