### ISSUE TITLE
3D Secure not redirecting on Barclays debit card

### ISSUE THREAD

**Issue by scottasmith** [braintree/braintree-web#469]
### General information

* SDK version: 3.54.2
* Environment: Production
* Browser and OS: Chrome 78.0.3904.70 (64bit) on Windows 10

### Issue description
Trying to pay with a Barclays Debit card when using 3D Secure.
The 3D Secure is not enabled on our live site but we use the vue-braintree-hosted-fields and braintree-web packages. We have tried numerous CSP's (Content Security Policy) with no avail.
The problem seems to be non existent when using a Halifax card.

When the 3D Secure iframe comes up it tries to redirect and throws this error:
```
Unsafe JavaScript attempt to initiate navigation for frame with URL 'https://0eaf.cardinalcommerce.com/EAFService/jsp/v1/redirect' from frame with URL 'https://0eaf.cardinalcommerce.com/EAFService/jsp/v1/term'. The frame attempting navigation is sandboxed, and is therefore disallowed from navigating its ancestors.
```

Expanding on the problem in the Chrome console it comes up with `(anonymous) | @ | VM43 term:27`, which when clicked on shows (in the sources tab) `document.forms[0].submit();`

This *seems* comes from the iframe inside the main iframe with the body tag as such. But may not be the actual issue?
```
<body>
		<form action="https://centinelapi.cardinalcommerce.com/V1/TermURL/Overlay/CCA" target="_parent" method="post">
			<input type="hidden" name="PaRes" value="...long string...">
			<input type="hidden" name="MD" value="..value..">
			<noscript>
				<div style="font-align:center;">
					<h1 style="color:red;">Processing Your Transaction</h1>
					<h2 style="color:red;">JavaScript is currently disabled or is not supported by your browser.</h2>
					<h3 style="color:red;">Please click Submit to continue the processing of your transaction.</h3>
					<input type="submit" value="Submit">
				</div>
			</noscript>
		</form>
		<script type="text/javascript">
			document.forms[0].submit();
		</script>
	
</body>
```

We have the following CSP headers directly relating to Braintree, etc:
```
script-src 'self' 'unsafe-eval' js.braintreegateway.com assets.braintreegateway.com www.paypalobjects.com *.paypal.com 'unsafe-inline' songbird.cardinalcommerce.com;
img-src 'self' assets.braintreegateway.com data: *.paypal.com;
worker-src 'self' assets.braintreegateway.com *.paypal.com;
frame-src assets.braintreegateway.com *.paypal.com *.cardinalcommerce.com;
connect-src 'self' api.braintreegateway.com client-analytics.braintreegateway.com *.braintree-api.com *.cardinalcommerce.com www.paypal.com;
style-src 'self' 'unsafe-inline';
sandbox allow-forms allow-same-origin allow-scripts allow-popups allow-modals allow-orientation-lock allow-pointer-lock allow-presentation allow-popups-to-escape-sandbox allow-top-navigation;
frame-ancestors 'self' *.cardinalcommerce.com;
```

**Comment by scottasmith** [comment]
> 👋 @scottasmith from looking at the error message, can you confirm if you are sandboxing iframes? If you are, do you run into the same issue when you do not sandbox the iframe?

Hi @hollabaq86 

We don't use an iframe ourselves and its created by the code in the `threeDSecure` import from the `braintree-web` npm package I believe

**Comment by hollabaq86** [comment]
Thanks for this info- in that case, we're going to need to escalate to our MPI provider CardinalCommerce for further investigation. Can you contact [Braintree Support](https://help.braintreepayments.com/) referencing this issue, along with the following:

- your merchant ID
- timestamps of when you attempted this 3DS verification with the Barclays card
- first six or last four digits of the card used (do not send the full card number)

Support will need this info to partner with CardinalCommerce on investigating and ultimately escalating to the card brands and Barclays.
