### ISSUE TITLE
load the form in colorbox returns error

### ISSUE THREAD

**Issue by vipconsult** [braintree/braintree-web#47]
trying to load the dropui using colorbox most of the time returns (usually after a page refresh)
Uncaught ReferenceError: braintree is not defined

$(".colorbox_ajax").colorbox({
        
});

latest chrome version  , and the  same with IE

**Comment by kyledetella** [comment]
@vipconsult it sounds like `braintree.js` has not finished loading by the time you try to run it.

Make sure the `script` tag that loads `braintree.js` is placed before the script tag(s) that run your code. It is recommended that you place your script tags as close to the closing `</body>` tag as possible to ensure the DOM is ready.

```html
<html>
  <head>...</head>
  <body>
    <!-- Your DOM here -->
   <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
   <script>
    // braintree.setup will be ready
    </script>
  </body>
</html>

**Comment by vipconsult** [comment]
I tried all combinations but no luck 

here is a link to replicate
http://dev1.portal.vip-consult.co.uk/loader.php

the first time you click the link it returns the error , but if you close the colorbox and click the same link again then it works ok.

If you refresh the page the same thing happens.

**Comment by kyledetella** [comment]
@vipconsult since you are adding those script tags to the DOM at runtime in the `form.php` partial, the `braintree.js` script does not get loaded and parsed before your next script tag is executed. That is why the second time you invoke colorbox, `braintree` has loaded and you do not see the error.

Here is what I recommend:

1. Include the `braintree.js` script _immediately_ after you include `jquery.colorbox.js`
2. In the `onCompleteCallback` for `colorbox`, run `braintree.setup`
3. In `form.php`, remove everything except the `<form>` node

Your two files should end up looking like this:

**loader.php**
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script type="text/javascript" src="http://www.jacklmoore.com/colorbox/jquery.colorbox.js"></script>
  <!-- Adding braintree.js -->
  <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
  <link rel="stylesheet" type="text/css" href="http://www.jacklmoore.com/colorbox/example1/colorbox.css"/>
</head>
<body >
  <a class="colorbox_ajax" href="/form.php">form</a>
  <script type="text/javascript">
    function bind_all(){
      $(".colorbox_ajax").colorbox({
        scrolling:false,
        maxWidth: "80%",
        onComplete:function(){
          setupBraintree();
        },
        onClosed:function(){
          bind_all();
        }
      });
    }

    function setupBraintree() {
      braintree.setup(TOKEN, "dropin",  {
        container: "container",
        onReady:function () {
          $.colorbox.resize();
        }
      });
    }

    $(document).ready(function(){
      bind_all();
      setupBraintree();
    });
  </script>
</body>
</html>
```

**form.php**

```html
<form action="" method="post" accept-charset="utf-8" >
  <div id="container" style="min-height:150px;min-width:250px;"></div>
</form>
```

I hope this helps. Let me know if you run into any more issues.

**Comment by vipconsult** [comment]
is there no way to keep the js file in the form itself ?  i would prefer it that way

**Comment by vipconsult** [comment]
managed to solve it by loading the external script inside the ajax call:

$.getScript("https://js.braintreegateway.com/v2/braintree.js", function() {
        braintree.setup("<?php print $clientToken?>", "dropin",  {
            container: "container",
            onReady:function () {
                $( ".hidden" ).removeClass("hidden");
                $( "#cboxLoadingGraphic" ).remove();
                $.colorbox.resize();            
            }
        });
    });
