### ISSUE TITLE
Documentation PayPal shippingOptions and onShippingChange

### ISSUE THREAD

**Issue by 719media** [braintree/braintree-web#470]
In the latest release, there is an addition to paypal shipping options.

I see the new code in `src/paypal-checkout/paypal-checkout.js` 
`@typedef {object} PayPalCheckout~shippingOption`

and documented on braintree's side at
https://braintree.github.io/braintree-web/current/PayPalCheckout.html#createPayment

But am having problems finding this documented anywhere on paypal's side. Specifically trying to see how to tie this into paypal buttons `onShippingChange` handler, to see if the shippingOptions can be updated as a result of customer address change. (I have yet to attempt to integrate onShippingChange with braintree's paypalCheckoutInstance, so there may be an incorrect assumption on my part that this is possible).

Was excited because now seems possible to avoid a hosted confirm page after paypal flow for checkouts where both tax + available shipping options/changes change based on ship address, and preferring to have paypal handle the address.

Thanks for any help

**Comment by 719media** [comment]
On the same page referenced above (https://braintree.github.io/braintree-web/current/PayPalCheckout.html#createPayment) there is an example that starts with the comment

`// shippingOptions are passed to createPayment. You can review the result from onAuthorize to determine which shipping option id was selected.`

But it's using the older style `paypal.Button.render(` instead of `paypal.Buttons(` so I'm just a little lost on what's supported where in terms of shippingOptions + onShippingChange

**Comment by 719media** [comment]
A workaround is to make the div use d-flex, although I haven't been able to test how that works when venmo button pops up

**Comment by 719media** [comment]
Closing. Some documentation helps:
https://developer.paypal.com/docs/checkout/integration-features/shipping-callback/
https://developer.paypal.com/docs/api/orders/v2/
https://braintree.github.io/braintree-web/current/PayPalCheckout.html#~shippingOption

**Comment by crookedneighbor** [comment]
FYI, Braintree does not use the orders api v2, so anything in the shipping callback that uses `actions.order.patch([` will not work. The rest of it should work just fine.

**Comment by 719media** [comment]
So are you saying there is no way to update the order within onShippingChange in Braintree?
