### ISSUE TITLE
Issue Open Popup 3D SecureCode in Browser Safari 10.1.2 and 9.1.2

### ISSUE THREAD

**Issue by bonny3** [braintree/braintree-web#471]
### General information

* SDK version:  4.4.0
* Environment:  issue in Production
* Browser and OS MacOS Safari 10.1.2 and 9.1.2

### Issue description

I have encountered a problem with Braintree
in the browser Safari 10.1.2 and 9.1.2 on the desktop
the 3D securcode pop-up is not opened
I hope you can solve this problem.
Thanks

**Comment by bonny3** [comment]
I tested the "Sierra" operating system
with safari version 10.1 and this works
instead the operating system "Yosemite" version safari 10.1.3
does not work.
The 3D Securcode popup is not opened

**Comment by hollabaq86** [comment]
👋 @bonny3, thanks for reaching out. We're going to need some additional information to look into the issue further in partnership with our MPI provider CardinalCommerce. Can you [contact Support](https://help.braintreepayments.com/) referencing this issue along with the following:

- Your merchant ID
- Confirmation of the SDK version you're using
- Timestamps of the verifications that did not result in a popup being generated
- First six or last four digits of the card used (do not provide the full credit card number)
