### ISSUE TITLE
onShippingChange clarity

### ISSUE THREAD

**Issue by 719media** [braintree/braintree-web#472]
This is a follow up to #470 

In that issue, @crookedneighbor mentioned that `actions.order.patch([` would not work in the `onShippingChange` callback. However, with limited testing, I was able to get it to work just fine as far as representing the change within the paypal modal popup. So, I'm not sure if I'm misunderstanding here (perhaps it appears to work fine, but in some production mode, or on the braintree side, it doesn't work?), or if there is more to understand here?

The desired use case is to have the paypal modal be able to:
* change shippingOptions based on addressChange
* change `amount` (total) based on selected shippingOptions due to changes in tax and shipping * charges

Is this possible?

**Comment by crookedneighbor** [comment]
I may be misunderstanding what `actions.order.patch` does under the hood, but I _thought_ it was an API call to the v2 orders API, which as far as I knew wasn't supported by Braintree. I'll reach out to my colleagues that work on the PayPal SDK and get some clarification around it.

**Comment by 719media** [comment]
Upon further testing, it appears the onShippingChange only takes affect after the initial order creation. That is, the onShippingChange handler fires in the following cases, all of which you would expect:

1. Initial paypal modal load (or after login if user is not  logged into paypal)
2. change in `selected` within shippingOptions 
3. change in ship to address

However, only in the 3rd case does the "total" actually updated within the paypal modal. Case 1 doesn't reflect the order patch, and case 2 instead adds the total from the shipOption to the `amount`, which is incorrect, and case 3 does correctly update the ship

There appears to be some circumstances in which case 3 will still not work, such as when going "back" to the original shipping address that was used on the first load of the modal, it won't reflect the order patch, but instead use the original amount in the order.


So, I believe this is what is meant by "Braintree doesn't support `actions.order.patch`"... it has unexpected/non-working behavior!

You can close this issue, I was just hoping for any more solid/concrete information, including any updates to timeline on having this work.

**Comment by 719media** [comment]
To be clear, the order.patch I am issuing as a test is:

```
actions.order.patch([
  {
    op: 'replace',
    path: '/purchase_units/@reference_id==\'default\'/amount',
    value: {
      currency_code: 'USD',
      value: 99,
    }
  }
]);
```

simply the `amount`

Ideally, there would be a way to update `shipOptions` as well, which there may be, but I haven't found out how to do that yet.

**Comment by 719media** [comment]
@crookedneighbor any update on what's possible with braintree + paypal in regards to changing the order totals when the shipping address is changed, and also changing the ShipOptions in the same scenario?

**Comment by crookedneighbor** [comment]
Sorry for the delay. No updates, but I've passed this issue onto the team responsible for communicating with the PayPal APIs.

**Comment by 719media** [comment]
Hi @crookedneighbor,

Any update here? I think that such a feature would prove *invaluable* to the paypal/braintree ecosystem. I mean we're talking about a whole entire less page on conversion here, and the ability to close the order within the paypal flow, which would be huge.

I'll happily annoy/request the proper team responsible for this implementation if they have an open channel somewhere?

Thank you for your time.

**Comment by crookedneighbor** [comment]
I've pinged the team responsible for this. Will post here if there's any updates.

**Comment by 719media** [comment]
@crookedneighbor Any updates on this feature?

**Comment by crookedneighbor** [comment]
No updates right now, but I'll ping the team responsible for the feature again.

**Comment by 719media** [comment]
@crookedneighbor Hello! We're coming up on a year later for support for this, any word? I am trying, without success, to use something like

```
onShippingChange(data, actions) {
  return actions.order.patch([
    {
      op: 'replace',
      path: '/purchase_units/@reference_id==\'default\'/shipping/options',
      value: [
        {
          id: 'shipping-speed-fast',
          type: 'SHIPPING',
          label: '22222 Shipping',
          selected: true,
          amount: {
            value: '2.00',
            currency: 'USD',
          },
        },
        {
          id: 'shipping-speed-slow',
          type: 'SHIPPING',
          label: '1111 Shipping',
          selected: false,
          amount: {
            value: '1.00',
            currency: 'USD',
          },
        },
      ],
    },
  ]);
},
```

and paypal doesn't seem to like that, giving an error of UNPROCESSABLE_ENTITY. At one point, someone mentioned braintree creating orders using v1 instead of v2 paypal may be the culprit, but I don't really know how to investigate that, since paypal documentation is a wilderness of confusion.

Thanks for any support.

**Comment by crookedneighbor** [comment]
Braintree has plans to update our internal API to use the v2 PayPal orders API, but it is not available yet, and there is no timeline for it.

**Comment by 719media** [comment]
Thanks. Seems like the v2 api has been out since Feb of 2019 (https://medium.com/paypal-engineering/launch-v2-paypal-checkout-apis-45435398b987). Any word on this front?

**Comment by crookedneighbor** [comment]
No updates at this time.

**Comment by crookedneighbor** [comment]
There are still no updates on this.

**Comment by mdo5004** [comment]
@719media did you find a workaround for this that didn't involve redesigning your checkout?

**Comment by cwarkentin** [comment]
@crookedneighbor any updates on this. it's been like 3 years since paypal launched v2. This is incredibly important to integrate for my merchants.

**Comment by crookedneighbor** [comment]
@cwarkentin I've passed on your comment to the team responsible for our API integration with PayPal and will let you know what they say.

**Comment by crookedneighbor** [comment]
Sorry for the long delay, but I finally did get confirmation that supporting the shipping callback is on the roadmap for this year. We will definitely update this issue when it is supported.

**Comment by malewis5** [comment]
> @crookedneighbor any updates on this. it's been like 3 years since paypal launched v2. This is incredibly important to integrate for my merchants. I can patch the total but it's not reliable and my sandbox throws me errors about permission denied. Not sure if this will just auto fail in production. Seems patching shipping options is not supported at all still. Is it possible to patch server side or something

@crookedneighbor Are you able to confirm if patching the total amount will work in production? I'm getting the same errors as @cwarkentin. Thank you.

**Comment by shawncook** [comment]
Thanks for putting this on the roadmap! These updates may unblock a handful of checkout optimizations we'd like to do on our Braintree integration.

**Comment by jortizsao** [comment]
Thanks for putting this on the roadmap, would be great to have this soon. This is definitely a huge blocker in the Braintree/Paypal flow for us

**Comment by jortizsao** [comment]
@crookedneighbor I have noticed that `onShippingChange` works if I call `createOrder` using the Paypal API directly  with `actions.order.create`. 

However, I wonder if it would work to tokenize the Paypal data that comes in `onApprove` callback using the checkout instance from Braintree as before. Thus I don't need to change anything else in the code, specially in the backend

**Comment by shawncook** [comment]
@jortizsao I have noticed the same. The following does not currently work, but here is where I'm at:

In `createOrder`, if I sidestep Braintree and use `actions.order.create({...})` instead of `instance.createPayment({...})`, I'm able to load a PayPal modal with its expected functionality (including correct behavior for `onShippingChange`). 

Next, I attempt to authorize the order, hooking into Braintree `instance.tokenizePayment` to obtain a payment method nonce:
```
actions.order.authorize().then((authorizePayload) => {
  instance.tokenizePayment(data).then((tokenizePayload) => {
    authorizePayload.payment_method_nonce = tokenizePayload.nonce;
    return self.onAuthorizeCallback(authorizePayload);
  });
});
```

Unfortunately, running `gateway.transaction.sale()` on the backend using the nonce generated by `tokenizePayment` returns an error [82902](https://developer.paypal.com/braintree/docs/reference/general/validation-errors/all#code-82901). Perhaps I need to include `facilitatorAccessToken` in some form.

**Comment by jortizsao** [comment]
Yes @shawncook, I'm also stuck in the same issue

**Comment by 719media** [comment]
@crookedneighbor hi, any update on this issue for those of us eager to address this problem? I have a small hope that you're busy about to drop v4 of this library with all sorts of improvements including this, as activity seems to have been silent lately. Thanks!

**Comment by crookedneighbor** [comment]
No updates as of yet. Y'all will be the first to know when this has been fixed :)

**Comment by tilman** [comment]
Hey, some more month have passed. Any new Updates? Is it now possible to change shipping Option with Braintree integration or can you provide at least any working Workaround?

**Comment by 719media** [comment]
@crookedneighbor any updates here?
It does seem very strange/unexpected/baffling that the new paypal v2 has been out for almost 4 years now, and braintree, the company we went with specifically for their first-party paypal support, still doesn't support it. I mean no offense, I'm just surprised that this hasn't been a higher initiative. Perhaps there are reasons that may help us understand why this continues to be backburnered? Should we look into just implementing paypal integration outside of braintree?

**Comment by bywood** [comment]
The Braintree upgrade to PayPal v2 is still ongoing. In the meantime, we are working on adding onShippingChange patching support through Braintree using PayPal v1. This requires a new Braintree API endpoint to be added, which is currently being worked on. Once that is completed, the Braintree SDK will be updated to make use of it. We are targeting early January 2023 to have it released.

**Comment by ediogodias** [comment]
@bywood we are also struggling with this issue. Waiting on more updates! Thank you

**Comment by ibooker** [comment]
I'm happy to announce that we released Braintree SDK 3.90.0 on Jan 18, 2022.  It adds support for `PayPalCheckout.updatePayment()` function.
This function is designed to be used in place of `actions.order.patch` in the `onShippingChange` callback.  It provides means to update shipping options and/or order line items.

We have code example available at in the [PayPal developer documentation](https://developer.paypal.com/braintree/docs/guides/paypal/checkout-with-paypal).

**Comment by ediogodias** [comment]
@ibooker awesome! will check it right away

**Comment by jakub300** [comment]
@ibooker Hi, I think this version number in the docs should be updated to 3.90.0
![image](https://user-images.githubusercontent.com/610941/214101755-2a4937fc-ab40-4368-9b74-7472aae8da6c.png)

**Comment by ediogodias** [comment]
@ibooker im not being able to get this working. It fails with the message

```
Transaction amount does not match line items and shipping options amount
```

With this request params:

```json
{
  "paymentId": "PAYID-XXXXXXXX",
  "currencyIsoCode": "USD",
  "amount": "59.00",
  "lineItems": [
    {
      "name": "Tax Total",
      "unitAmount": "5.37",
      "quantity": "1",
      "kind": "debit"
    },
    {
      "name": "Item Total",
      "unitAmount": "42.66",
      "quantity": "1",
      "kind": "debit"
    }
  ],
  "shippingOptions": [
    {
      "label": "USPS (Priority)",
      "amount": {
        "value": "10.97",
        "currency": "USD"
      },
      "id": "414633f0-6900-4516-9c0b-37ca0ee04a8e|63ced09355e61|65ca3812d421493364adda43b24b768b",
      "type": "SHIPPING",
      "selected": true
    },
    {
      "label": "FedEx (2 Days)",
      "amount": {
        "value": "16",
        "currency": "USD"
      },
      "id": "414633f0-6900-4516-9c0b-37ca0ee04a8e|63ced09355e61|2ac572411052d0c0e1186f4426094b0f",
      "type": "SHIPPING",
      "selected": false
    },
    {
      "label": "FedEx (Overnight)",
      "amount": {
        "value": "30.1",
        "currency": "USD"
      },
      "id": "414633f0-6900-4516-9c0b-37ca0ee04a8e|63ced09355e61|e86c5d4f65e9134a37a1be96d33eb9ba",
      "type": "SHIPPING",
      "selected": false
    }
  ],
  "braintreeLibraryVersion": "braintree/web/3.90.0",
  "_meta": {
    "merchantAppId": "localhost:3000",
    "platform": "web",
    "sdkVersion": "3.90.0",
    "source": "client",
    "integration": "custom",
    "integrationType": "custom",
    "sessionId": "ee9a620b-e3e5-4594-bca1-bc93175ed2e8"
  },
  "tokenizationKey": "xxxxxxx"
}
```

I've tried multiple combinations of `lineItems` and `amount` but always get the same error message.

**Comment by armandodlvr** [comment]
@ediogodias This is an example that works (based on the payload you provided):

```javascript
  onShippingChange: function (data, actions) {
     return PayPalInstance.updatePayment({
          paymentId:"PAYID-xxxxxxxxx",
          currency: 'USD',
          lineItems: [{
            "name": "Tax Total",
            "unitAmount": "5.37",
            "quantity": "1",
            "kind": "debit"
          },
         {
         "name": "Item Total",
          "unitAmount": "42.66",
          "quantity": "1",
          "kind": "debit"
        }],
        shippingOptions: [{ /* your list here */}],
      })
```

If the `amount` is not present the SDK will calculate that for you.

**Comment by ediogodias** [comment]
@armandodlvr that is exactly wha't im doing. What i posted is the answer from BraintreeAPI call, which always fail

**Comment by ibooker** [comment]
@ediogodias  Do you get the same result if you do not include the 'amount' in the data submitted the `updatePayment` method?

**Comment by ediogodias** [comment]
Correct, posted above.

**Comment by ibooker** [comment]
@ediogodias I had to change the `amount` to '59'; otherwise I was able to use the line items and shipping options in your example code.

**Comment by 719media** [comment]
@ibooker Thanks for the great news! Quick question, is there an "abort" call that can happen during the updatePayment callback? For example, if the order winds up "out of stock" for a high transactional item during the checkout process, and we want to back out of the paypal flow cleanly.

The documentation isn't very verbose on this, so it's hard to tell if such an option exists, and ideally we would want to do more than just `throw new Error`, unless that happens to be the method you recommend.

Thanks!

**Comment by ediogodias** [comment]
@ibooker that still does not work, i tested all the combinations previously.

Here the timeline of events.

1. Calling the updatePayment method:

```javascript
paypalCheckoutInstance.updatePayment(
  {
  "paymentId": "PAYID-XXXXXXXX",
  "currency": "USD",
  "shippingOptions": [
    {
      "label": "USPS (Priority)",
      "amount": {
        "value": "10.97",
        "currency": "USD"
      },
      "id": "414633f0-6900-4516-9c0b-37ca0ee04a8e|63cfc05893726|65ca3812d421493364adda43b24b768b",
      "type": "SHIPPING",
      "selected": true
    },
    {
      "label": "FedEx (2 Days)",
      "amount": {
        "value": "16",
        "currency": "USD"
      },
      "id": "414633f0-6900-4516-9c0b-37ca0ee04a8e|63cfc05893726|2ac572411052d0c0e1186f4426094b0f",
      "type": "SHIPPING",
      "selected": false
    },
    {
      "label": "FedEx (Overnight)",
      "amount": {
        "value": "30.1",
        "currency": "USD"
      },
      "id": "414633f0-6900-4516-9c0b-37ca0ee04a8e|63cfc05893726|e86c5d4f65e9134a37a1be96d33eb9ba",
      "type": "SHIPPING",
      "selected": false
    }
  ],
  "amount": "59",
  "lineItems": [
    {
      "name": "Tax Total",
      "unitAmount": "5.37",
      "quantity": "1",
      "kind": "debit"
    },
    {
      "name": "Item Total",
      "unitAmount": "42.66",
      "quantity": "1",
      "kind": "debit"
    }
  ]
}
)
```

2. POST API call triggered to: `https://api.braintreegateway.com/merchants/{merchant_id}/client_api/v1/paypal_hermes/patch_payment_resource` 
3. Call gives 422 having the following request params and response:

Request params:

```json
{
  "paymentId": "PAYID-xxxxxxxxxx",
  "currencyIsoCode": "USD",
  "amount": "59",
  "lineItems": [
    {
      "name": "Tax Total",
      "unitAmount": "5.37",
      "quantity": "1",
      "kind": "debit"
    },
    {
      "name": "Item Total",
      "unitAmount": "42.66",
      "quantity": "1",
      "kind": "debit"
    }
  ],
  "shippingOptions": [
    {
      "label": "USPS (Priority)",
      "amount": {
        "value": "10.97",
        "currency": "USD"
      },
      "id": "414633f0-6900-4516-9c0b-37ca0ee04a8e|63cfc05893726|65ca3812d421493364adda43b24b768b",
      "type": "SHIPPING",
      "selected": true
    },
    {
      "label": "FedEx (2 Days)",
      "amount": {
        "value": "16",
        "currency": "USD"
      },
      "id": "414633f0-6900-4516-9c0b-37ca0ee04a8e|63cfc05893726|2ac572411052d0c0e1186f4426094b0f",
      "type": "SHIPPING",
      "selected": false
    },
    {
      "label": "FedEx (Overnight)",
      "amount": {
        "value": "30.1",
        "currency": "USD"
      },
      "id": "414633f0-6900-4516-9c0b-37ca0ee04a8e|63cfc05893726|e86c5d4f65e9134a37a1be96d33eb9ba",
      "type": "SHIPPING",
      "selected": false
    }
  ],
  "braintreeLibraryVersion": "braintree/web/3.90.0",
  "_meta": {
    "merchantAppId": "localhost:3000",
    "platform": "web",
    "sdkVersion": "3.90.0",
    "source": "client",
    "integration": "custom",
    "integrationType": "custom",
    "sessionId": "xxxxxxx"
  },
  "tokenizationKey": "xxxxxxxxx"
}
```

Response:

```json
{
  "error": {
    "message": "[\"Transaction amount does not match line items and shipping options amount\"]"
  },
  "fieldErrors": [
    {
      "field": "amount",
      "message": "Transaction amount does not match line items and shipping options amount"
    }
  ]
}
```

It could help with debugging the fact that the default paypal address is not a supported address. So the first time `onShippingChange` runs i return the `actions.reject();` as per docs. After i select a supported address then this happens.

Take into consideration that i had the code working before with original PaypalAPI with patch methods, i only updated to use BraintreeAPI and this is failing.

**Comment by armandodlvr** [comment]
@ediogodias can you please try calling the `updatePayment` method without passing the `amount`? (I can see it above `lineItems`)

**Comment by ediogodias** [comment]
yes, did that already. The internal amount calculation is also wrong, not fixing to 2 decimals points:

```json
{
  "paymentId": "PAYID-xxxxxxxxx",
  "currencyIsoCode": "USD",
  "lineItems": [
    {
      "name": "Tax Total",
      "unitAmount": "5.37",
      "quantity": "1",
      "kind": "debit"
    },
    {
      "name": "Item Total",
      "unitAmount": "42.66",
      "quantity": "1",
      "kind": "debit"
    }
  ],
  "amount": 58.99999999999999,
  "shippingOptions": [
    {
      "label": "USPS (Priority)",
      "amount": {
        "value": "10.97",
        "currency": "USD"
      },
      "id": "414633f0-6900-4516-9c0b-37ca0ee04a8e|63ced30d4ea34|65ca3812d421493364adda43b24b768b",
      "type": "SHIPPING",
      "selected": true
    },
    {
      "label": "FedEx (2 Days)",
      "amount": {
        "value": "16",
        "currency": "USD"
      },
      "id": "414633f0-6900-4516-9c0b-37ca0ee04a8e|63ced30d4ea34|2ac572411052d0c0e1186f4426094b0f",
      "type": "SHIPPING",
      "selected": false
    },
    {
      "label": "FedEx (Overnight)",
      "amount": {
        "value": "30.1",
        "currency": "USD"
      },
      "id": "414633f0-6900-4516-9c0b-37ca0ee04a8e|63ced30d4ea34|e86c5d4f65e9134a37a1be96d33eb9ba",
      "type": "SHIPPING",
      "selected": false
    }
  ],
  "braintreeLibraryVersion": "braintree/web/3.90.0",
  "_meta": {
    "merchantAppId": "localhost:3000",
    "platform": "web",
    "sdkVersion": "3.90.0",
    "source": "client",
    "integration": "custom",
    "integrationType": "custom",
    "sessionId": "xxxxxxx"
  },
  "tokenizationKey": "xxxxxx"
}
```

**Comment by armandodlvr** [comment]
I did the same and it's working for me.

```
{
    "paymentId": "PAYID-xxx",
    "currencyIsoCode": "USD",
    "lineItems": [
        {
            "name": "Tax Total",
            "unitAmount": "5.37",
            "quantity": "1",
            "kind": "debit"
        },
        {
            "name": "Item Total",
            "unitAmount": "42.66",
            "quantity": "1",
            "kind": "debit"
        }
    ],
    "amount": 58.99999999999999,
    "shippingOptions": [
        {
            "label": "USPS (Priority)",
            "amount": {
                "value": "10.97",
                "currency": "USD"
            },
            "id": "414633f0-6900-4516-9c0b-37ca0ee04a8e|63ced30d4ea34|65ca3812d421493364adda43b24b768b",
            "type": "SHIPPING",
            "selected": true
        },
        {
            "label": "FedEx (2 Days)",
            "amount": {
                "value": "16",
                "currency": "USD"
            },
            "id": "414633f0-6900-4516-9c0b-37ca0ee04a8e|63ced30d4ea34|2ac572411052d0c0e1186f4426094b0f",
            "type": "SHIPPING",
            "selected": false
        },
        {
            "label": "FedEx (Overnight)",
            "amount": {
                "value": "30.1",
                "currency": "USD"
            },
            "id": "414633f0-6900-4516-9c0b-37ca0ee04a8e|63ced30d4ea34|e86c5d4f65e9134a37a1be96d33eb9ba",
            "type": "SHIPPING",
            "selected": false
        }
    ],
    "braintreeLibraryVersion": "braintree/web/3.90.0",
    "_meta": {
        "merchantAppId": "localhost:3000",
        "platform": "web",
        "sdkVersion": "3.90.0",
        "source": "client",
        "integration": "custom",
        "integrationType": "custom",
        "sessionId": "xxxx"
    },
    "authorizationFingerprint": "xxxx"

**Comment by armandodlvr** [comment]
@ediogodias  I totally agree with you about the floating precision. We're going to fix it.

**Comment by ediogodias** [comment]
@armandodlvr i tested with only 1 line item, it bypasses the 422 amount error - but now i get a different error.

This is the request params:

```json
{
  "paymentId": "PAYID-xxxxxxx",
  "currencyIsoCode": "USD",
  "amount": "42.04",
  "lineItems": [
    {
      "name": "Tax Total",
      "unitAmount": "3.83",
      "quantity": "1",
      "kind": "debit"
    },
    {
      "name": "Item Total",
      "unitAmount": "29.95",
      "quantity": "1",
      "kind": "debit"
    }
  ],
  "shippingOptions": [
    {
      "label": "USPS (Priority)",
      "amount": {
        "value": "8.26",
        "currency": "USD"
      },
      "id": "414633f0-6900-4516-9c0b-37ca0ee04a8e|63d016b69198e|8b86ba80cf39049a431b910b7bf2fefa",
      "type": "SHIPPING",
      "selected": true
    },
    {
      "label": "FedEx (2 Days)",
      "amount": {
        "value": "13.23",
        "currency": "USD"
      },
      "id": "414633f0-6900-4516-9c0b-37ca0ee04a8e|63d016b69198e|161b822df64e6da31f27853076c3f7bc",
      "type": "SHIPPING",
      "selected": false
    },
    {
      "label": "FedEx (Overnight)",
      "amount": {
        "value": "26.98",
        "currency": "USD"
      },
      "id": "414633f0-6900-4516-9c0b-37ca0ee04a8e|63d016b69198e|c7d10ff005d9e1e3ceebb0863e791711",
      "type": "SHIPPING",
      "selected": false
    }
  ],
  "braintreeLibraryVersion": "braintree/web/3.90.0",
  "_meta": {
    "merchantAppId": "localhost:3000",
    "platform": "web",
    "sdkVersion": "3.90.0",
    "source": "client",
    "integration": "custom",
    "integrationType": "custom",
    "sessionId": "xxxxxx"
  },
  "tokenizationKey": "xxxxxxx"
}
```

Now the response is:

```json
{
  "authorization": {
    "error": "VALIDATION_ERROR",
    "errorDescription": "Invalid request - see details",
    "debugId": "ab7928bbd24a4",
    "processorResponseCode": "2073"
  }
}
```

**Comment by ediogodias** [comment]
just as an update, the only way i can make this work is if i remove all shippingOptions from the call to `updatePayment`. This way API call does not returns 422 (which defeat the whole purpose of this feature). Can you please double check server implementation? 

This works perfectly with PaypalAPI and it works when i stop sending shippingOptions, so it must be server side problem.

**Comment by kalitk0** [comment]
I am running into the same issue

@ediogodias any update on this ?

**Comment by ediogodias** [comment]
no, this on braintree side and clearly its not important for them

**Comment by kalitk0** [comment]
@ediogodias After many tries and variants of the lineItems and  amount properties I finally got it working.

So the shipping should not be included in the lineItems and the amount should be order total - shipping cost

**Comment by ediogodias** [comment]
@ediogodias thanks for that!

**Comment by imshuffling** [comment]
// So the shipping should not be included in the lineItems and the amount should be order total - shipping cost

I've found an issue where if the address changes inside the Paypal modal the total price is excluding the delivery, it is then calculated normally if i then change the delivery option. 

Braintree... Is anyone able to assist here?

**Comment by ibooker** [comment]
@imshuffling 
Unfortunately, we do not monitor (or are not notified about) comments on closed issues. 

Do you have any test code for setting up this scenario? Also, it would help if you included the version of `braintree-web` you are using.

thanks
