### ISSUE TITLE
Street Address fields are not appearing in Dropin-UI

### ISSUE THREAD

**Issue by cbrit** [braintree/braintree-web#475]
### General information

* SDK version: .NET library 4.16.0
* Environment: Sandbox, localhost
* Browser and OS: Chrome Version 77.0.3865.120 (Official Build) (64-bit), Windows 10 

### Issue description

After doing the Getting Started guide for the Dropin-UI I wanted to add CVV and AVS fields, so I followed the documentation and went to Processing -> CVV/AVS options -> etc.

Everything I enabled rules for appeared as expected except for Street Address:
![Fields](https://user-images.githubusercontent.com/23322838/68228221-b3f9c000-ffba-11e9-8705-8c2b9f94b7d3.PNG)
![Options](https://user-images.githubusercontent.com/23322838/68228234-b9efa100-ffba-11e9-99f3-f44ccbc6551c.PNG)

Am I missing something?

Also, my scripts loaded are below if it's any help. I'm a little confused if client.min.js and dropin.min.js are both required:
```
    <!-- Load PayPal's checkout.js Library. -->
    <script src="https://www.paypalobjects.com/api/checkout.js" data-version-4 log-level="warn"></script>

    <!-- Load the client component. -->
    <script src="https://js.braintreegateway.com/web/3.55.0/js/client.min.js"></script>

    <!-- Load the PayPal Checkout component. -->
    <script src="https://js.braintreegateway.com/web/3.55.0/js/paypal-checkout.min.js"></script>
    <script src="https://js.braintreegateway.com/web/dropin/1.20.4/js/dropin.min.js"></script>
```

**Comment by crookedneighbor** [comment]
For the future, please open issues for Drop-in in the dedicated repo for it: https://github.com/braintree/braintree-web-drop-in/issues

Drop-in does not yet support collecting billing address within Drop-in itself. You can collect that info yourself in your own form and pass it into the `transaction.sale` call on your server.

You don't need to load the PayPal script or the client/paypal-checkout Braintree scripts. Drop-in does all of that internally in the Drop-in script.
