### ISSUE TITLE
Paypal checkout button executes inline script 'unsafe-inline' csp problems

### ISSUE THREAD

**Issue by Deam94** [braintree/braintree-web#476]
### General information

* SDK version: 3.55.0
* Environment: Sandbox
* Browser and OS Version 78.0.3904.70 (Offizieller Build) (64-Bit) Windows 10

### Issue description

Im using hosted fields and created a paypal button like this:
```
braintree.paypalCheckout.create({
      client: clientInstance
    }, function (paypalCheckoutErr, paypalCheckoutInstance) {
  
      if (paypalCheckoutErr) {
        console.error('Error creating PayPal Checkout:', paypalCheckoutErr);
        return;
      }
  
      paypal.Button.render({
        env: 'sandbox',
        commit: true,
        buttonStyle: {
            color: 'blue',
            shape: 'rect',
            size: 'medium'
      },  	
      payment: function () {
          return paypalCheckoutInstance.createPayment({
              flow: 'checkout', 
              amount: '10.00', 
              currency: 'EUR'
          });
        },
          
        onAuthorize: function (data, actions) {
          return paypalCheckoutInstance.tokenizePayment(data, function (err, payload) {
              document.getElementById("paynonce").value = payload.nonce;
              document.getElementById("paymentform").submit();
          });
        },
  
        onCancel: function (data) {
          console.log('checkout.js payment cancelled', JSON.stringify(data, 0, 2));
        },
  
        onError: function (err) {
          console.error('checkout.js error', err);
        }
      }, '#paypal-button').then(function () {
          
      });
          
    });
```

I added all needed resources to my csp and nonces to my script tags but my console is raging because of refused evaluating and executing inline script of paypal resources.
I checked my html and discovered there are multiple inline scripts wich get throw into my html (check attachment)
![Unbenannt](https://user-images.githubusercontent.com/17741911/68283414-cd167580-007b-11ea-8e2e-3014b17067a4.png)

The button is working but this is a huge problem for me. 
May you working together with Paypal to fix this problem like delivering the whole script inside the paypalobject checkout js/ asset or atleast add a nonce so developers can add this to csp or completly remove it if it isnt necessary.

**Comment by crookedneighbor** [comment]
This is resolved with v5 of PayPal's SDK. You can see how to integrate it with the first example shown here: https://braintree.github.io/braintree-web/current/PayPalCheckout.html

**Comment by Deam94** [comment]
This is even worse, whys there isnt a simple method to launch the paypal window on my own button ?
This would make so many things easier like dynamic amount and inline script.

So at time i press my own checkout button the script runs trough get amount etc prevents default and opens the window to pay. After we could add the nonce and the form.submit like we do on hosted field.

**Comment by crookedneighbor** [comment]
Please bring this up at https://github.com/paypal/paypal-smart-payment-buttons

**Comment by Deam94** [comment]
Is it necessary for you "braintree" to render this button ?
Why you couldnt skip that part and instantly fire the window at an own button ?

I dont know how this paypal implementation works exactly but this should be an option for each developer.

**Comment by crookedneighbor** [comment]
PayPal requires Braintree to use their JS SDK. Please bring up your feedback in the repo for their SDK.
