### ISSUE TITLE
Braintree API Client Misconfigured: the clientApiUrl provided in the clientToken is invalid.

### ISSUE THREAD

**Issue by jitoot** [braintree/braintree-web#477]
### General information

* SDK version: 2.18.0, 2.32.1
* Environment: Sandbox
* Browser and OS: Chrome 78.0.3904.97 on Mac OS 10.15.1

### Issue description

Recently we are receiving the following error message when trying to load braintree.js payment:
Error: Braintree API Client Misconfigured: the clientApiUrl provided in the clientToken is invalid.

We looked at the client token generated and can see the clientApiUrl value being as follows (xxxxxx being the merchant id): 

clientApiUrl : "https://gateway-sand.sandbox.braintree-api.com:443/merchants/xxxxxx/client_api"

The production environment keys are working fine. Has there been any changes to the format of the URL generated above which is failing the validation check? Kindly advise what might be the cause. Thanks.

**Comment by jchli** [comment]
@jitoot Yes, we've been testing out a domain change and mistakenly included your sandbox merchant as part of the rollout. We've reverted the change, so your sandbox integration should be back to normal now.
