### ISSUE TITLE
Credit cards 3DS 1 vs 3DS 2

### ISSUE THREAD

**Issue by Bartoszek-91** [braintree/braintree-web#478]
### General information

* SDK version: 3.55.0
* Environment: Production
* Browser and OS: Chrome 78.0.3904.108 

### Issue description
 I want to migrate to JS SDK v. 3.55.0 with 3DS 2, and I  have some problems:

1. I use version "2-inline-iframe" and create all needed instances. While creating threeDsInstance yours JS throw uncaugth error in you library:
`uncaugth (in promies) o {name: "BraintreeError", code: "THREEDS_CARDINAL_SDK_SETUP_TIMEDOUT", message: "Cardinal's Songbird.js took too long to setup.", type: "UNKNOWN", details: undefined}
code: "THREEDS_CARDINAL_SDK_SETUP_TIMEDOUT"
details: undefined
message: "Cardinal's Songbird.js took too long to setup."
name: "BraintreeError"
type: "UNKNOWN"`
      -  Could you catch this error and return?
      - I need to configure something options in Braintree panel for Cardinal or something else?
      - Can you help mi with this problem? Some additional documentation?

2. Before I used JS SDK 3.43.0 and my integration working but actually I have some problems with 3DS 1, and I have error below. Why is suddenly not working? Maybe is affected by PSD2 regulations?
`Refused to display 'https://www.ipko.pl/3dsecure/auth/login/submit?flow_id=vVoJWGRdiGNEH6VmTsjdRe&flow_cont=1' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

**Comment by crookedneighbor** [comment]
The underlying cardinal sdk should not timeout like that every time.

To address both issues, please reach out to our support team with this so we can better debug your integration: https://help.braintreepayments.com/

**Comment by romankoshynskyi** [comment]
@Bartoszek-91 Did you resolved this issue? Please, let me know because a similar one. Thank you!
