### ISSUE TITLE
HostedFields interface missing functions for setAttribute, removeAttribute.

### ISSUE THREAD

**Issue by ausmurp** [braintree/braintree-web#481]
### General information

* SDK version: 3.56.0
* Environment:  Sandbox and Production
* Browser and OS Chrome 56.0.2924.87 (64-bit) on MacOS 10.12.3

### Issue description
interface HostedFields does not include functions for setAttribute, removeAttribute. So I cannot use that type in code.

**Comment by crookedneighbor** [comment]
We do not maintain the type definitions for the js sdk. You will need to open an issue/pr on the repo hosting the type definitions.
