### ISSUE TITLE
Error Tokenizing braintree Error paypal payments invalid options

### ISSUE THREAD

**Issue by ShubhamChakraborty** [braintree/braintree-web#486]
![braintree](https://user-images.githubusercontent.com/43884580/73270417-a09a7180-4204-11ea-9d35-efd43575c2c2.jpeg)

**Comment by crookedneighbor** [comment]
Upgrade to the latest version of the sdk (3.57.0) and then contact our support team so we can better help you troubleshoot your integration. 

https://help.braintreepayments.com/

**Comment by ShubhamChakraborty** [comment]
one is running on live server and thats working fine but the other which is in developing stage is showing the errors as you saw earlier

**Comment by crookedneighbor** [comment]
My guess is that you're not running your code over an http server when developing locally. In any case, please send your client code and any information about how you are developing locally to our support team for assistance.
