### ISSUE TITLE
Hosted fields throws an error when passing container in React 16

### ISSUE THREAD

**Issue by wiranoid** [braintree/braintree-web#487]
### General information

* SDK version: 3.57
* Environment: Sandbox
* Browser and OS: Chrome 79 Windows 10

### Issue description

When trying to use container instead of selector during hosted fields configuration, it gives an error: 
```
Could not stringify event: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLDivElement'
    |     property '__reactInternalInstance$ahvo3qp93tt' -> object with constructor 'FiberNode'
    --- property 'stateNode' closes the circle
```

I'm using React 16.12 and here's my configuration:

```
const cardNumberRef = useRef(null);
...
braintree.hostedFields.create(
    {
        client: clientInstance,
        fields: {
            number: {
                container: cardNumberRef.current,
                placeholder: "4111 1111 1111 1111"
            },
    ...
...
<div 
    ref={cardNumberRef}
    id="card-number"
    className="hosted-field"
></div>
```

It's trying to JSON.stringify options during following call 
(hosted-fields.js:613)
`reply(self._merchantConfigurationOptions);`
and fails because some of them are HTMLDivElement instances (see screenshot)

![Screenshot_7](https://user-images.githubusercontent.com/10433437/74368722-4218ea00-4de5-11ea-8fd6-3faee4e5faa7.png)

From the changelog I see that container param for field is supported since 3.47.0.
What am I missing here?

Thanks.

**Comment by crookedneighbor** [comment]
Just to be sure that the HTMLDivElements are the problem, does it work alright if you pass in a selector instead?

I wasn't able to reproduce by doing:

```
container: document.getElementById('number-field')
```

So if it is the `container` stuff that is causing the problem, it's likely something particular to your setup. That said, we don't need to send up the container/selector as part of the merchant configuration that the iframes need to function. So if we can determine conclusively about what is going wrong, we can simply omit those fields from being sent up.

**Comment by wiranoid** [comment]
It appears to be React-specific problem. It adds circular structures to the elements, causing JSON.stringify to fail.

**Comment by crookedneighbor** [comment]
:+1: I've got a fix started that drops the `container` field before sending it to the hosted fields iframes. Will update here when it's released.

**Comment by crookedneighbor** [comment]
This is out in 3.58.0, would you mind verifying for me that it's working as expected now?

**Comment by wiranoid** [comment]
Yes, it's working now. Thank you!
