### ISSUE TITLE
iOS 13  HostedFields: Fails to tokenize on Simulator or Device but Succeeds in Browser

### ISSUE THREAD

**Issue by aventurella** [braintree/braintree-web#488]
### General information

**SDK version:** 3.58.0 (also attempted with 3.50.0, 3.40.0, 3.30.0 to test for a regression)
**Environment:** Sandbox
**Browser and OS:** WKWebView (iOS 13 Simulator), WKWebView (iOS Device 13.3.1)
**Device User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

### Issue description
**TL;DR:** 
Attempting to run `.tokenize()` on hosted fields running in a `WKWebView` fails with the following error:

```
Unhandled Promise Rejection: SyntaxError: The string did not match the expected pattern.
```

--- 

I have a sample `HostedFields` setup running in a WKWebView on the Simulator, Device, and Browser. 

The WKWebView is loaded from a Framework. I created the Framework, it just contains the 1 WKWebView + Associated Controller + HTML/JS Resources.  I have also omitted the Framework and just placed everything in the App Target to no effect; same error reported here.

The WKWebView is configured as follows:

```swift
override public func loadView() {
        
    let preferences = WKPreferences()
    
    // The default is true, but it's always
    // nice to make thinks explicit for ourselves later.
    preferences.javaScriptEnabled = true
    
    let configuration = WKWebViewConfiguration()
    let contentController = WKUserContentController()
    configuration.preferences = preferences
    configuration.userContentController = contentController
    
    webView = WKWebView(frame: .zero, configuration: configuration)
    webView.uiDelegate = self
    
    view = webView
}
```
 
and is loaded as follows:

```swift
public func loadUsing(token: String){
    let script =    """
    var BRAINTREE_INIT_TOKEN = "\(token)";
    """
    let userScript = WKUserScript(source: script, injectionTime: .atDocumentStart, forMainFrameOnly: true)

    // I can omit this line and for the sake of debugging, just embed the token I have in the JS directly.
    // JS still errors on tokenization with the same error reported in this issue.
    webView.configuration.userContentController.addUserScript(userScript)
    
    let bundle = Bundle(for: BraintreeHostedFieldsController.self)
    
    if let url = bundle.url(forResource: "index", withExtension: "html", subdirectory: "dist") {
        let request = URLRequest(url: url);
        webView.load(request)
    }
}
```

_(browser just to preview and dev more quickly than constant rebuilds in the Simulator or Device. Browsers used in this issue: Safari, Chrome, Edge, Firefox - All latest consumer builds)_

My Sample HostedField Setup:
```js
hostedFields.create({
    client: myClient,
    styles: {
        input: {
            'font-size': '14px',
            'font-family': 'helvetica, tahoma, calibri, sans-serif',
            color: '#7d6b6b',
            
        },
        
        ':focus': {
            color: 'black'
        },

        'input.invalid': {
            'color': 'red'
        },
        'input.valid': {
            'color': 'green'
        }
    },
    fields: {
        number: {
            selector: '#card-number',
            placeholder: '4111 1111 1111 1111'
        },
        cvv: {
            selector: '#cvv',
            placeholder: '123'
        },
        expirationDate: {
            selector: '#expiration-date',
            placeholder: '10/2019'
        }
    }
});
```

Things render and take input. In the browser when I invoke `tokenize` after filling out the fields:

```js
hostedFields.tokenize()
.then((payload) => {
    console.log(payload);
})
.catch((e) => {
    console.error(e)
})
```

I get a payload successfully in the Desktop Browser(s) only _(Safari, Chrome, Edge, Firefox_. On the  iOS Simulator or on Device I get the following error:

```
Unhandled Promise Rejection: SyntaxError: The string did not match the expected pattern.
```

What's more, is on Simulator or Device web inspector I see the graphql response return successfully in the network inspector:

```json
{
    "data": {
        "tokenizeCreditCard": {
            "token": "<the token>",
            "creditCard": {
                "bin": "411111",
                "brandCode": "VISA",
                "last4": "1111",
                "expirationMonth": "03",
                "expirationYear": "2022",
                "binData": {
                    "prepaid": "UNKNOWN",
                    "healthcare": "UNKNOWN",
                    "debit": "UNKNOWN",
                    "durbinRegulated": "UNKNOWN",
                    "commercial": "UNKNOWN",
                    "payroll": "UNKNOWN",
                    "issuingBank": null,
                    "countryOfIssuance": null,
                    "productId": null
                }
            }
        }
    },
    "extensions": {
        "requestId": "HNqO1rxB20ptCUh-vs7-fK_YE5cd6sfWnFHeNtMMu_396iVqOBgstQ=="
    }
}
```

**Comment by crookedneighbor** [comment]
Can you provide a repo for an ios app that reproduces the problem?

**Comment by aventurella** [comment]
https://github.com/aventurella/braintree-hostedfield-ios

**Comment by crookedneighbor** [comment]
OK, so the issue is that when run via the webpack server, you're running it over localhost. When you run it via your framework, it runs it over the file protocol, which doesn't fully support post message, which is required for hosted fields to work.

However, since you're building a mobile app, you shouldn't need hosted fields to be PCI compliant. You should be able to use the graphql api directly to tokenize the card details. https://graphql.braintreepayments.com/

You can inspect the network requests that you were seeing for the exact queries that need to be made to tokenize the card details and reach out to our support team for additional help: https://help.braintreepayments.com/

**Comment by aventurella** [comment]
@crookedneighbor Thanks for looking into this!!!

**Comment by Piero87** [comment]
@crookedneighbor Hi, I have the same problem I switched my Cordova app to WKWebView (it's a compulsory for apple instead of the old uiwebview) and when I call the tokenize method of the hosted filed i receive the same error explanied above. you suggest to call the graphql direcly but the response of the graphql doesn't contain the `payload.nonce` that I use to passo to the server, how can I fix this?

**Comment by crookedneighbor** [comment]
@Piero87 reach out to our support team for help integrating with the graphql api.

I believe the value you want is simply the `id` and pass that as the payment method nonce, but our support team can help you troubleshoot your integration. https://help.braintreepayments.com/

**Comment by shewison** [comment]
@aventurella Did you find a solution to this which doesn't require direct use of GraphQL?
