### ISSUE TITLE
3DSecure frame is blank when cookie are deactivated

### ISSUE THREAD

**Issue by wagonli** [braintree/braintree-web#489]
### General information

* SDK version: 3.58.0
* Environment: PRODUCTION only
* Browser and OS Chrome, Fedora and Android

### Issue description

When the user set his security and confidentiality preference to deactivate Cookies (which also deactivate all storage in Firefox and Chrome), some 3DSecure frame can be blank when displayed. I actually verified it against BNP Paribas 3DS page.

This issue has a direct impact on our business as we're addressing customers that are careful of their security and confidentiality settings.

It guess it's not really a Braintree issue but is more related to the bank implementation of the 3DSecure pages.
But as you are our only public interface, you should have the adequate resource to make that issue bubble up to parties that can actually fix that. Or maybe redirect us toward the right place to raise this up.

**Comment by crookedneighbor** [comment]
Please reach out to our support team with screenshots of the issue. This will help our support team reach out to our 3D Secure provider to let them know so they can contact the relevant bank to determine if there is a problem: https://help.braintreepayments.com/
