### ISSUE TITLE
storeInVaultOnSuccess Feature Request

### ISSUE THREAD

**Issue by trainerbill** [braintree/braintree-web#49]
This may not be the right repository but it seems to get the most attention.  When using transaction.sale and the option to storeInVaultOnSuccess can we have the ability to pass in an existing customer id to have it appended to the record?  Currently if you try and pass in a current customer ID you get the following:

 ```json
"customer": {
  "validationErrors": {
    "id": [
      {
        "attribute": "id",
        "code": "91609",
        "message": "Customer ID has already been taken."
      }
    ]
  },
```

This makes it more difficult to vault a payment method for a current customer as you now have to do the paymentMethod.create and then the transaction.sale creating the transaction from the vaulted token.  Would be SO much easier to be able to do this in transaction.sale and have it append to the customers payment methods if it is an existing customer.

**Comment by obiwarn** [comment]
+1

**Comment by crookedneighbor** [comment]
Hi @trainerbill,

Thanks for your thoughts on this. If you'd like help optimizing your integration, feel free to reach out to Braintree support and we'll help you out.

Closing this as it's not relevant to this particular repo.

**Comment by wrabit** [comment]
@trainerbill did you get anywhere with this, I know, 5 years.
