### ISSUE TITLE
Difference between nonce formats of `client.request` and `hostedFields.tokenize`

### ISSUE THREAD

**Issue by Diyorbek** [braintree/braintree-web#492]
### General information

* SDK version:  3.59.0 

### Issue description

I wanted to get an explanation about my case:

I have noticed that while tokenizing a credit card information with `client.request()` method, nonce is in `354d11b4-****-**` format (something like uuid).
However, when we tokenize by `hostedFields.tokenize()`, the nonce will be in `token_*******` format. 

I am going to use `client.request` instead of `hostedfields` but because of this issue I am receiving an error from server saying `"Payment method nonces cannot be used to update an existing card."`

**Comment by crookedneighbor** [comment]
First, I'd be sure that you are eligible to handle raw credit card details on your website.

If you are, can you provide the code for how you are tokenizing the raw card details? Nonces with a leading `tokencc_` are being tokenized by our GraphQL API, while nonces with leading numbers/letters are tokenized by our older API. Under the hood, the SDK should be intercepting the request made to our old API and using the GraphQL API instead, so both hosted fields and raw tokenization should result in nonce with a leading `tokencc_` prefix.

There are some edge cases that would prompt it to use the old API, but we would need to see your code, and what brand of credit card you are tokenizing, to determine if what you are doing falls into that case or not.

All that said, there should be no functional difference between the nonce that starts with `tokencc_` and a nonce generated by the older API. So I would reach out to our support team about the `Payment method nonces cannot be used to update an existing card.` message to dig into to what is going on there. https://help.braintreepayments.com/

**Comment by Diyorbek** [comment]
I have just analyzed my code carefully and found out that while I was `POST`ing a credit card information, `options: { validate: false }` was missing inside `data.creditCard`. I wrote my code based on the example in README. I guess I should have checked the other examples on the documentation website.

**Comment by crookedneighbor** [comment]
That explains the message you were getting. My guess is you were generating a client token with a customer id. If you don't pass `validate: false`, the API will default to `validate: true` when tokenizing with a client token generated with a customer id, which will result in the card being vaulted on the client. Since that's the case, the resulting nonce will refer to a vaulted payment method, which can't be used to update a separate card.
