### ISSUE TITLE
Is braintree-web a replacement for braintree_php, or do they work together?

### ISSUE THREAD

**Issue by jamminjames** [braintree/braintree-web#494]
### General information

* SDK version:5.0.0
* Environment: Sandbox
* Browser and OS: Firefox on Windows 7

### Issue description

Is braintree-web a replacement for braintree_php, or do they work together? I can't get fetchPaymentMethods to work. Is it supposed to show the client a list of their saved payment methods?

I have a drop-in and these scripts in the header:
```
<script src="https://js.braintreegateway.com/web/3.11.0/js/client.min.js"></script>
<script src="https://js.braintreegateway.com/web/dropin/1.22.1/js/dropin.min.js"></script>
<script src="https://js.braintreegateway.com/web/3.11.0/js/vault-manager.min.js"></script>
```

And I'm using this example I saw:
```
braintree.dropin.create({authorization: client_token, selector: '#bt-dropin'}, function (err, client) {
	braintree.vaultManager.create({client: client}, function (err, vm) {
       vm.fetchPaymentMethods(function (err, paymentMethods) {
           paymentMethods // an array of payment methods
    })
  })
})
```

But it's only producing the same thing I had before, a form the customer has to fill out with credit card info.  But I'd like to let them choose from saved payment methods.

Also, I'm unclear on how to incorporate the hostedFieldsInstance.

Thanks for any help.

**Comment by hollabaq86** [comment]
👋 @jamminjames, please contact [Braintree Support](https://help.braintreepayments.com/) for assistance. They can help you troubleshoot your integration and walk you through the process of integrating with Braintree's client and server SDKs.
