### ISSUE TITLE
A cookie associated with a cross-site resource at http://braintreegateway.com/ was set without the `SameSite` attribute

### ISSUE THREAD

**Issue by jmsjr** [braintree/braintree-web#499]
### General information

* SDK version: 3.53.0
* Environment: Production
* Browser and OS  83.0.4103.61 (Official Build) (64-bit) Linux

### Issue description

We are using Hosted fields integration with Braintree Javascript 3.53.0.
Everything is working as expected as we have been in production since last month, April 2020.

However, the following warning message is displayed in Chrome's developer console:

> A cookie associated with a cross-site resource at http://braintreegateway.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

As these cookies are not controlled by us, is there a planned future version of Braintree Javascript SDK that would address the issue above before Chrome blocks them ?

**Comment by hollabaq86** [comment]
👋 @jmsjr thanks for reaching out. The SDKs share the domain `braintreegateway.com` with our [Control Panel](https://articles.braintreepayments.com/control-panel/overview), and that's the source of these warnings. These do *not* come from the SDK itself. Users would only encounter these warning messages if they are visiting your checkout and also have used Braintree's Control Panel, which is probably a very small number of people. 

We've notified the team that owns the Control Panel about these warnings. In the meantime, you can ignore them.

**Comment by jmsjr** [comment]
Hi @hollabaq86 

But I saw that warning message on the developer console of a user who do NOT have access to the Control Panel .. so it cannot be that. Also, the URL referred to is HTTP and not HTTPS.
