### ISSUE TITLE
Drop-In & payment methods

### ISSUE THREAD

**Issue by CheapData** [braintree/braintree-web#5]
Drop-In is not paying any attention what payment method marked as default.
Steeps to reproduce:
1. Customer in Vault has 2 methods (CC and PayPal)
2. PayPal is second in the list and marker as default
3. Drop-In load payment methods and always display first row which is CC.

**Comment by bborn** [comment]
+1 Dropin does not respect default CC. Drop in should display the customer's default credit card.

![example](https://cloud.githubusercontent.com/assets/3760/6065378/858caed6-ad2a-11e4-8dc1-f2c2823f228c.jpg)

**Comment by jeffcarp** [comment]
Thanks for pointing this out @CheapData + @bborn, we're working out when we can ship a fix for this - I will post updates to this thread once I have them.

**Comment by CheapData** [comment]
v2.5.3 still not respect which payment method marked as default. However, after each transaction methods rearranged and the last used method becomes Nr.1 in the Vault. For the next payment the last used method is loaded even if it is not marked as default.
This functionality is totally ok with me. How about you @bborn ?

**Comment by bborn** [comment]
Nope. Still won't display the customer's default card in the Drop In UI.

**Comment by sogko** [comment]
+1 on drop-ui not showing default payment method

**Comment by gaugau** [comment]
+1 too

**Comment by tnunes** [comment]
:+1:

**Comment by kalinchuk** [comment]
What's the status of this bug fix?

**Comment by micha-LEAP** [comment]
This needs to either respect the default OR show all methods without requiring another click.

**Comment by kyledetella** [comment]
The ordering of payment methods is determined by our API and not by Drop-in.

As per [this issue](https://github.com/braintree/braintree_android/issues/23):

> Unfortunately, the payment method ordering in Drop In does not account for the customer's default payment method. This ordering is determined internally by our API based on a payment method's last updated at and last used at timestamps.

As of right now there are no plans to update this behavior. If that changes we will re-open this issue.

**Comment by hootener** [comment]
@kyledetella [I posted on another bug report why I thought this solution was unacceptable](https://github.com/braintree/braintree_android/issues/23). I urge you all to reopen this issue and get it resolved.

**Comment by cameronbourgeois** [comment]
+1 @hootener - This is unacceptable. Please fix this ASAP braintree.

**Comment by shanthakumarf22** [comment]
+1 😇

**Comment by crookedneighbor** [comment]
Hey all, Drop-In now has a boolean parameter you can pass in called `defaultFirst`

> When you specify a customerID that has vaulted payment methods associated with it, Drop-in displays a list of those payment methods and automatically pre-selects the one used most recently. If you pass defaultFirst, Drop-in will instead pre-select the payment method marked as default for the customer. 

The docs for this are the last entry in [this table](https://developers.braintreepayments.com/reference/client-reference/javascript/v2/configuration#setup-method-options)
