### ISSUE TITLE
PayPal and multi-factor auth support?

### ISSUE THREAD

**Issue by avinash-ananth** [braintree/braintree-web#50]
Currently the PayPal flow does not seem to support any kind of MFA from PayPal w/ no error being displayed. Is there any planned support for PayPal + MFA soon ? 

Currently the login page just looks like it failed without any indication that two-factor is not supported  (even though the 2.7.3 changelog indicates that there should/might be a two-factor failure message). 

There are a significant number of our potential users who have been turned away due to a lack of MFA support and confused by the lack of a failure message  FWIW.

**Comment by tklun** [comment]
While 2FA is not currently supported, version 2.7.3 includes an update to our error messaging explaining these failures. If you're using the latest version of this library from GitHub, npm, or Bower, you should be seeing these new error messages. Can you confirm you're using the most recent version?

**Comment by avinash-ananth** [comment]
I use the JS vended form https://js.braintreegateway.com/v2/braintree.js which looks like its in version 2.7.2 and hence I don't see the new version. 

Any time estimates on : 
1- https://js.braintreegateway.com/v2/braintree.js vending version 2.7.3 of the library? 
2- 2FA + PayPAl support ?

**Comment by kyledetella** [comment]
@avinash-ananth the currently hotlinked version is now [`2.8.1`](https://js.braintreegateway.com/v2/braintree.js) so the `2.7.3` changes have been released.

As of right now there are no plans to support 2FA.

Sorry for the delay in response.

**Comment by night** [comment]
Just tried paying on a site using this SDK.. No 2FA support? No plans to support it? You must be joking right... With PayPal heavily pushing Braintree's v.zero SDK at https://developer.paypal.com you'd imagine this product would have complete support for PayPal authentications.

**Comment by sornon1** [comment]
@night, there have since been updates to the sdk to support a PayPal with two factor auth, but would require updates on the merchant's side to enable the new flow. See here: https://developers.braintreepayments.com/guides/paypal/vault/javascript/v2

**Comment by night** [comment]
@sornon1 The site I was checking out on uses the "Checkout with PayPal" option by enabling `singleUse` on payments. This is probably because it's not a subscription service, so they have no reason to vault my information. I'm not sure why anyone would choose to support 2FA only on part of their SDK. There should be a fix that works for all existing setups, not making it a problem that merchants have to resolve.

**Comment by sornon1** [comment]
The one time checkout flow [also supports Two Factor Auth](https://developers.braintreepayments.com/guides/paypal/checkout-with-paypal/javascript/v2)

**Comment by danielwu426** [comment]
Hi all,

2FA is indeed supported for both of our new payment flows - in our [new vaulted payment flow](https://articles.braintreepayments.com/guides/paypal/processing#new-vault-flow) and our [Checkout with PayPal flow](https://developers.braintreepayments.com/guides/paypal/checkout-with-paypal/javascript/v2). Our older payment flows are in the process of being deprecated and have no plans to support 2FA at this time. 

If you have any questions on how to enable these new flows please let us know.

Thanks,
Dan

**Comment by night** [comment]
Can you explain what the older flows look like then. The site I was using was loading https://checkout.paypal.com/pwpp/2.15.4/html/braintree-frame.html

Attempting to login yields the following message:

>  Login failed. PayPal Security Key is not supported.

**Comment by danielwu426** [comment]
This merchant is using one of our older payment flows that is in the process of being deprecated. We are working with all of our merchants to ensure they are using the latest payment flows that support things like multi-factor auth, funding selector, etc.

**Comment by alanhamlett** [comment]
Just verified 2fa works by checking the "Vault" checkbox in Processing settings:

1. Log into the [Control Panel](https://www.braintreegateway.com/login?_ga=1.199559598.1682865644.1459698965)
2. Navigate to Settings > Processing
3. Under Accept PayPal click Edit
4. Check the Use Vault Flow checkbox

No code changes necessary, just checking that box is all that's needed to enable 2-factor authentication.
