### ISSUE TITLE
Cannot re-enable the submit button after failure. 

### ISSUE THREAD

**Issue by martinstreicher** [braintree/braintree-web#500]
### General information

* SDK version: `    "braintree-web": "^3.62.1"`
* Environment: Sandbox 13.1, 14609.1.20.111.8, Mac OS X 10.14.6
* Browser and OS: Safari 

### Issue description

Steps to reproduce: 

1. Use the hosted fields to show CC#, CVV and expiration date. 
2. Fill in the fields with valid test credit card values. When filled, notice that the Submit button is enabled, indicating the fields are valid. 
3. Disconnect the computer from the network. 
4. Press Submit. 
5. Capture the network error in the JS. 
7. Notice the fields are still filled and are still valid.
8. Set the `disabled` property of the Submit button to `false` to re-enable the button. 
9. Hmmmm... sometimes it does not work; sometimes it works once or many times. 

The entire JS code is below. Nothing is confidential. 

Is there a better way to do this? 

```
import braintree from "braintree-web"

//
// Begin custom JS for New Payment Method Page
//

const clientToken = document.getElementById('client_token').value;

braintree.client.create({
  authorization: clientToken
}, function (clientErr, clientInstance) {
  if (clientErr) {
    console.error(clientErr);
    return;
  }

  // This example shows Hosted Fields, but you can also use this
  // client instance to create additional components here, such as
  // PayPal or Data Collector.

  braintree.hostedFields.create({
    client: clientInstance,

    fields: {
      number: {
        selector: '#card_number',
        placeholder: ''
      },
      cvv: {
        selector: '#cvv',
        placeholder: ''
      },
      expirationDate: {
        selector: '#expiration_date',
        placeholder: ''
      }
    },

    styles: {
      'input': {
        'font-size': '14px',
        'box-shadow': 'inset 0 1px 2px rgba(0, 0, 0, 0.1)'
      },
      'input.invalid': {
        'color': 'red'
      },
      'input.valid': {
        'color': 'green'
      }
    },

  }, function (hostedFieldsErr, hostedFieldsInstance) {
    if (hostedFieldsErr) {
      console.error(hostedFieldsErr);
      return;
    }

    var form = document.querySelector('#braintree_form');
    var submit = document.querySelector('input[type="submit"][name="commit"]');
    $(submit).prop('disabled', true);

    hostedFieldsInstance.on('validityChange', function (event) {
      var fields = event.fields;
      var field = fields[event.emittedBy];
      var validState = fields.cvv.isValid && fields.expirationDate.isValid && fields.number.isValid;
      $(submit).prop('disabled', !validState);
    });

    form.addEventListener('submit', function (event) {
      event.preventDefault();

      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
        if (tokenizeErr) {
          switch (tokenizeErr.code) {
            // occurs when the Braintree gateway cannot be contacted
            case 'HOSTED_FIELDS_TOKENIZATION_NETWORK_ERROR':
              // hostedFieldsInstance.clear('number');
              // hostedFieldsInstance.clear('cvv');
              // hostedFieldsInstance.clear('expirationDate');
              var state = hostedFieldsInstance.getState();
              var formValid = Object.keys(state.fields).every(function (key) {
                return state.fields[key].isValid;
              });

              $(submit).prop('disabled', !formValid);
              break;

            default:
              console.error('Something bad happened!', tokenizeErr);
          }
        }
        else {
          document.querySelector('#card_payment_method_nonce').value = payload.nonce;
          form.submit();
        }
      });
    }, false);
  });
});

//
// End custom JS for New Payment Method Page
//

```

**Comment by crookedneighbor** [comment]
Can you be more specific about what is happening when you try to submit again? 

The Braintree SDK has no control over the disabled state of your button, so can you confirm that `tokenize` is being called on the hosted fields instance after you've re-enabled the button? 

Does it pass back an error?

**Comment by martinstreicher** [comment]
Thanks for your reply. Submit works just fine. There is no issue with that. 

My issue is that something seems to interfere with the state of the button when I set `disabled` with the code `$(submit).prop('disabled', !formValid);`

It works intermittently -- so I was wondering if there are some machinations that are interfering.

**Comment by crookedneighbor** [comment]
I see. The issues is that you're setting the validity of the button based on the client side validity of the form. 

In the case of a network based interruption, the client side validity would remain all valid, so the 
button would always be disabled in this case. 

In the case of a tokenization error, I would simply re-enable the button and disable it again only when tokenization is in process.
