### ISSUE TITLE
Inconsistent validation error with PayPal Smart Buttons API (not Checkout.js)

### ISSUE THREAD

**Issue by simeyla** [braintree/braintree-web#501]
### General information

* SDK version: 3.62.1
* Environment: Production
* Browser and OS: Chrome Windows + iOS 13.5

### Issue description

I have recently tried to migrate to PayPal's Smart Buttons integration using the /sdk/js API instead of Checkout.js. While [a lot of your documentation](https://developers.braintreepayments.com/guides/paypal/paypal-credit/javascript/v3) still uses `checkout.js` it seems like it is [supported](https://braintree.github.io/braintree-web/current/PayPalCheckout.html).

> First want to say I understand this very well could be a PayPal SDK issue and not Braintree, but the fact I am getting **`supplemental_order_missing_payees`** suggests that the Braintree side isn't sending something correctly.

I am using the following URL and parameters to load the PayPal SDK:

    'https://www.paypal.com/sdk/js?client-id=' + environment.payment.payPalClientID + 
                                                            '&vault=true' +
                                                            '&intent=capture' +
                                                            '&commit=false' +
                                                            // '&debug=true' +
                                                            '&components=buttons,funding-eligibility' 
                                                        },

I call their Buttons API with these basic options:

```
env: payPalCheckoutInstance.env, 

fundingSource: paypal.FUNDING.PAYPAL,

createBillingAgreement: { 
   enableShippingAddress: true
   flow: "vault"
   intent: "capture"
   shippingAddressEditable: true
},

onApprove: { ... }
```

I only have issues with the `vault` flow, the `checkout` flow never fails.

I am testing on my local machine IN PRODUCTION (not sandbox) and I did not get an error once over hundreds of button clicks. As soon as I moved to production I started getting errors:

I get two errors:

   From `buttons` js error log:

    supplemental_order_missing_payees 

    {timestamp: "1591919508317", referer: "www.paypal.com", 
     sessionID: "57516c8176_mjm6ndg6nti", env: "production", buttonSessionID: "faf4df8175_mjm6nte6nde"}

The second error I am getting is some sort of validation error, but I can't make any sense of any of the debug logging:

From `JS SDK`

```
order_validation_error
order_validation_error_ATXEvHftEwIlsJvG6ojGd5FvsGa9Kj2iLhD9iOHCjcZQzMYaOZ2F6U2l1St5k961QlPSr5NTTih4Id4H
```

The extra information is here: 

```
buttonSessionID: "87b71610d4_mjm6ndg6nti"
env: "production"
err: "Error: VALIDATION_ERROR↵    at https://www.paypal.com/smart/buttons?env=production&fundingSource=paypal....
referer: "www.paypal.com"
sessionID: "57516c8176_mjm6ndg6nti"
timestamp: "1591919344582"
```

I managed to find more details in the XHR request / response.

https://www.paypal.com/graphql?GetCheckoutDetails

![image](https://user-images.githubusercontent.com/3656278/84454063-6a3b1d00-ac0e-11ea-9db2-4bed61a3b057.png)

with response:

![image](https://user-images.githubusercontent.com/3656278/84454100-8048dd80-ac0e-11ea-9f96-28603e66660b.png)

Sometimes it DOES work though, and I can get a nonce back just fine. Honestly it has the characteristics of a race condition, so maybe PayPal is having issues.

It's looking more and more to me now like it's a PayPal issue exclusively, but I think maybe the `vault` flow with `JS SDK` just doesn't work well with Braintree?

**Comment by simeyla** [comment]
OK so you know when you identify a problem and think you solved it, but you never did...

Here's what happened:

First of all my checkout has an option to 'Join club' which dictates whether or not `vault=true` (because customers get scared if you try to establish an agreement if you want a single purchase).

In the previous `checkout.js` integration you didn't have to specify whether or not you were using the vault flow until the user clicked it. So you did not need to destroy and recreate the button if that changed. With the new version you have to specify `vault=true` or `vault=false` when you create the button. I knew this and I set it up accordingly.

Just turned out there was a glitch in my logic which was made worse by in production due to latency of hitting a remote server (versus my local machine). So that's why I didn't see the glitch during development.

Note: You can use `vault=true` or `vault=false` with the URL I have above, you just have to create the individual buttons yourself and pass the `vault` parameter to the button.

**Comment by crookedneighbor** [comment]
Glad you were able to figure it out. I agree that it's confusing to not be able to set the vault case dynamically.

Also, we're hoping to get the official docs updated to the latest version of the PayPal SDK in the next few weeks and we'll be sure to call out this quirk.
