### ISSUE TITLE
Floating dropdown issue on Windows Chrome

### ISSUE THREAD

**Issue by ksuralta** [braintree/braintree-web#503]
### General information

* SDK version: 3.62.2
* Environment: Production
* Chrome on Windows 10

### Issue description
Expiration Month and Year dropdowns will be floating when we scroll across the page. It is happening only in chrome as per our initial observation and working fine in firefox and Edge

These two dropdowns are rendered from Braintree Hosted fields and the source code is not in our control. However we have an option to control the CSS from our JS code. We tried various css options and nothing seems to be working. We tried to fix it through JS function by capturing scroll event, but we were not able to do that as we were not getting the ID of that dropdown as it is rendered inside the iFrame from hostedfields.
 
We had tried the braintree provided JS function for event capturing, like onBlur/onFocus. But scrolling is not being captured for these events.
 
Also we observed that this issue replicates only on Scroll wheel of mouse and not on touchpad/on Click scrolling. This issue is apparently happening in Windows but not in Mac.

Screen recording of issue:
https://media.giphy.com/media/hTCxP4aFN7JK339a8O/giphy.gif

CodePen sample:
https://codepen.io/braintree/pen/QGrXav

**Comment by crookedneighbor** [comment]
The is a bug with Window Chrome itself. I've opened a ticket about it with the chrome team.

Here's a screenshot replicating the issue outside of the Braintree SDK:

![select bug](https://user-images.githubusercontent.com/2916945/84668931-d4431300-aee9-11ea-9317-ff63c504880f.png)

We'll leave this issue open for now and explore workarounds on our side if the Chrome team does not fix it.

**Comment by crookedneighbor** [comment]
Closing this as it is not an issue with the Braintree SDK, but rather a bug in Chrome for windows regarding select elements inside of iframes.

One workaround you could apply is to detect the focus event for the expiration selects and prevent scrolling on your page until the field is no longer focussed.

See https://braintree.github.io/braintree-web/current/HostedFields.html#on for info on listening for the blur and focus events.
