### ISSUE TITLE
It is not possible to change challenge window size

### ISSUE THREAD

**Issue by mairo744** [braintree/braintree-web#505]
### General information

* SDK version: 3.60.0
* Environment: Sandbox and also Production
* Browser and OS: Firefox 76.0.1 (64-bit) or Chrome 83.0.4103.106 (64-bit) on Windows 10 Pro Version 1709

### Issue description

When trying to change the challenge window size to '01' (250x400) it always display default challenge window size '03' (500x600). The addition information `acsWindowSize` has not effect and the ACS always reply default content with default window size. Window size does not change also with production configuration and real payment.

Field `acsWindowSize` look correct requested because for bad value I receive "ACS window size format is invalid.".

Quick example:
```
import {braintreeClient} from './braintreeClient'
import braintreeHostedFields from 'braintree-web/hosted-fields'
import braintreeThreeDSecure from 'braintree-web/three-d-secure'


class HostedFields {

    constructor() {
        this._instance = null;
        this._threeDS = null;

        this.init = this.init.bind(this);
        this.onSubmit = this.onSubmit.bind(this)
    }

    init() {
        braintreeClient.client
          .then((clientInstance) => this.create(clientInstance))
          .catch(err => {
              showGlobalError(err)
          })
    }


    create(clientInstance) {
        Promise.all([
            braintreeHostedFields.create({
                client: clientInstance,
                fields: {
                    number: {
                        selector: config.cardSelector
                    },
                    cvv: {
                        selector: config.cvvSelector
                    },
                    expirationDate: {
                        selector: config.expiryDateSelector
                    }
                }
            }),
            braintreeThreeDSecure.create({
                client: clientInstance,
                version: 2
            })
        ]).then(instances => this.handle(instances));
    }


    handle(instances) {
        this._instance = instances[0];
        this._threeDS = instances[1];

        this._threeDS.on('lookup-complete', function (data, next) {
            next();
        });

        braintreeClient.form.addEventListener('submit', this.onSubmit, false)
    }


    onSubmit(event) {
        this._instance.tokenize((tokenizeErr, payload) => {
            this._threeDS.verifyCard(
              {
                  amount: ...,
                  nonce: payload.nonce,
                  bin: payload.details.bin,
                  email: typeof emailElement !== 'undefined' ? emailElement.value : '',
                  billingAddress: {
                      ...
                  },
                  additionalInformation: {
                      acsWindowSize: '01' // **HAS NO EFFECT ON CHALLENGE WINDOW SIZE - THE SAME FOR '05'**
                  }
              },
              function (verifyError, verifyResponse) {
              ...
              });
        });
    }
}
```

![image](https://user-images.githubusercontent.com/8237028/85670147-e29ae700-b6c0-11ea-833f-ba38101eaf38.png)

**Comment by crookedneighbor** [comment]
The screenshot you're showing looks like the 3ds 1.0 test flow, which I think does not respect the acs window size. Can you try it again with a test card that prompts for a challenge in the 2.x flow?

`4000000000001091` should bring up the 2.x flow.

**Comment by mairo744** [comment]
Also same window for `4000000000001091`
![image](https://user-images.githubusercontent.com/8237028/85824564-623bbb00-b780-11ea-9317-37f77105b754.png)

Same for Mastercard `5200000000001096`
![image](https://user-images.githubusercontent.com/8237028/85825852-919ff700-b783-11ea-8c77-79028df1912a.png)

I think it always displays 3DS 1 because no one of my merchants have implemented 3DS 2 yet.
![image](https://user-images.githubusercontent.com/8237028/85824899-25bc8f00-b781-11ea-891d-29f5e9a318b4.png)

Documentation says (https://developers.braintreepayments.com/guides/3d-secure/migration/javascript/v3): 
"3DS 2 works on top of your existing 3DS 1 integration. The SDK will fall back to 3DS 1 when 3DS 2 is unavailable for the card being verified."

Is there another way how to change challenge window size for 3DS 1? 
If is 3DS 1 default fall back I need also change window size for 3DS 1.

I tried to create a new Merchant account in sandbox for EUR but 3DS 2 is not enrolled yet. I do not know how to try 3DS 2 at the moment.

**Comment by crookedneighbor** [comment]
You can always manually change the CSS yourself. This is what we do in Drop-in https://github.com/braintree/braintree-web-drop-in/blob/70e191c98f302e7146b50598c27e530fcb1319a8/src/less/cardinal-overrides.less
