### ISSUE TITLE
Braintree: Restrict input fields

### ISSUE THREAD

**Issue by lovish0008** [braintree/braintree-web#506]
I am using braintree payment gateway with hosted fields. My requirement is to have postal code with restricted input accepting only digit with either 5 or 9. I tried using maskIput property but not able to achieve, might be i am using it in wrong way. I tried using outside library for mask input but unable to get element through any selector suspect because of hosted fields. Could anyone help me out what wrong i am doing. 
<img width="275" alt="hostedFields" src="https://user-images.githubusercontent.com/22189712/85936174-011dff80-b8c6-11ea-8dfe-bb6580920dff.PNG">

**Comment by crookedneighbor** [comment]
`maskInput.character` does not take a regex. It takes a string. https://braintree.github.io/braintree-web/current/module-braintree-web_hosted-fields.html#~field

**Comment by lovish0008** [comment]
@crookedneighbor , Thanks for your reply, but what should I pass to restrict it from entering other character than digit.
