### ISSUE TITLE
docs on using applepay-checkout with React?

### ISSUE THREAD

**Issue by ksaleem25** [braintree/braintree-web#507]
### General information

* SDK version: 3.0.0
* Environment: Sandbox
* Browser and OS MacOS 10.12.3

please share docs to render apple pay with react just like i found for Paypal in #413

**Comment by crookedneighbor** [comment]
There are no react specific docs. The SDK works with any frontend framework. See https://developers.braintreepayments.com/guides/apple-pay/client-side/javascript/v3
