### ISSUE TITLE
PayPal button in react application

### ISSUE THREAD

**Issue by ksaleem25** [braintree/braintree-web#508]
### General information

* SDK version: 3.0.0
* Environment: Sandbox
* Browser and OS Chrome

### Issue description

we are trying to integrate Paypal in react application as mention in #413 , the button is rendered but when the user open the in-context dialog following exception is shown and the window is not loaded properly 

![image](https://user-images.githubusercontent.com/17887732/86482285-1635db00-bd6b-11ea-9676-17524f5a40f2.png)

**Comment by ksaleem25** [comment]
few more details, if we use API method paypal.Button.render({ ... }, el)  instead of method mention above , its starts showing Paypal in context window properly but multiple Paypal button start rendering in case we reinit the component in case of total changes

**Comment by crookedneighbor** [comment]
Please reach out to Braintree support so we can get a better understanding of you integration: https://help.braintreepayments.com/
