### ISSUE TITLE
Drop-In on Windows Phone 8.1

### ISSUE THREAD

**Issue by CheapData** [braintree/braintree-web#51]
browser = IE Mobile 11.0  
os = Windows Phone 8.1

"Card Number", "Expiration Date" & "CVV" not activated after normal tapping (1 finger).
However, fields are activated for data entry after taping with 2 fingers.

**Comment by rturumella** [comment]
@CheapData Thanks for bringing this to our attention! We'll take a look and keep you posted.

**Comment by acorreiatp** [comment]
Hello @CheapData 
you managed to solve this problem ?

**Comment by lilaconlee** [comment]
@acorreiatp So far, we've been unable to reproduce this problem. Could we get more information (browser, device model, etc.) about where you've seen this issue?

**Comment by crookedneighbor** [comment]
We haven't been able to reproduce this. If you can provide more specific information about how to reproduce it, please re-open the issue.
