### ISSUE TITLE
Postal code validation in hosted card form

### ISSUE THREAD

**Issue by tomasklim** [braintree/braintree-web#510]
### General information

* SDK version: 3.63.0
* Environment: production
* Browser and OS: 83.0.4103.116, macOS 10.15.5

### Issue description
It is allowed to put special characters (@#~,...) into the hosted postcode field, which then breaks when submitted - results in following error: 
 
Braintree Transaction Failed: Postal code can only contain letters, numbers, spaces, and hyphens.

Right now you check only the min length of the input.
`    
validationResult = validate(value, {
      minLength: this.configuration.fields.postalCode && this.configuration.fields.postalCode.minlength
    });
`

I think you should use some regex like this one:
`[a-zA-Z0-9][a-zA-Z0-9\- ]{0,10}[a-zA-Z0-9]`

**Comment by crookedneighbor** [comment]
I brought this up with my team and the team responsible for that validation. We've decided it's best to leave that validation up to the Braintree gateway.

If you'd like to include validation yourself for the postal code, you can omit the postal code field from your hosted fields integration, set up your own postal code input, validate it, and send it along as part of the `billingAddress.postalCode` field when tokenizing: https://braintree.github.io/braintree-web/current/HostedFields.html#tokenize
