### ISSUE TITLE
`HostedFieldEventType` type is incomplete

### ISSUE THREAD

**Issue by ardevelop** [braintree/braintree-web#511]
### General information

* SDK version: `@types/braintree-web@3.62.0`
* Environment: Development
* Browser and OS: Any

### Issue description

`@types/braintree-web@3.62.0` has incomplete types specifically for `HostedFieldEventType` where `inputSubmitRequest` is missing:

```ts
export type HostedFieldEventType =
  | "blur"
  | "focus"
  | "empty"
  | "notEmpty"
  | "cardTypeChange"
  | "validityChange";
```

**Comment by crookedneighbor** [comment]
Braintree does not maintain those type definitions.

We're in the process of migrating all our JS SDKs to Typescript. Once we do, we'll [remove the types definition on definitely typed](https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package).
