### ISSUE TITLE
Unable to open PayPal popup on Safari 

### ISSUE THREAD

**Issue by chiaogu** [braintree/braintree-web#515]
### General information

* SDK version:
  - 3.59.0
* Environment:
  - Sandbox
  - Production
* Browser and OS:
  - Safari 13.0.4 on macOS 10.15.2
  - Safari 13.0.5 on iOS 13.3

### Issue description
`paypal.tokenize()` works fine on Chrome, but isn't working on Safari.
The promise will be rejected with the following error:
```
BraintreeError: PayPal popup failed to open, make sure to tokenize in response to a user action.
```

Here is the minimal reproducible example:
https://codepen.io/Chiao_PG/pen/GRZKwzy?editors=1011
```javascript
function onClick() {
  braintree.client.create({ authorization })
    .then(client => braintree.paypal.create({ client }))
    .then(paypal => paypal.tokenize({ flow: 'checkout' }))
    .catch(console.error)
}
```

**Comment by crookedneighbor** [comment]
The call to run `tokenize` must be done as the direct result of a user action, when you wait to create the component until after the customer clicks the button, this disconnects the action of opening the popup from the button click.

Try creating the component upfront and only calling `paypal.tokenize` in the `onClick` handler.

**Comment by chiaogu** [comment]
Thanks! But what I don't understand is, usually it doesn't take longer than 300ms to create the component. `window.open` won't be blocked even if I delay calling it for 500ms after user interaction. Then what made Safari decide to block the PayPal popup?

**Comment by crookedneighbor** [comment]
Don't know what to tell you, but it's not something we're doing intentionally inside the sdk.

Also, you're using a deprecated integration pattern. PayPal prefers everyone to use `braintree.paypalCheckout` along with the PayPal SDK to manage the PayPal popup.
