### ISSUE TITLE
braintree.threeDSecure is 'undefined'

### ISSUE THREAD

**Issue by PeterA1** [braintree/braintree-web#520]
### General information

* SDK version: 3.65.0
* Environment: Sandbox
* Browser and OS:  Chrome 84.0.4147.135 (Official Build) (64-bit)

### Issue description

The braintree object created by the SDK has only two exposed methods, 'client' and 'hostedFields'.  

Therefore when I try and set up threeDSecure, I get the error:-
```
braintree.threeDSecure.create error TypeError: Cannot read property 'create' of undefined
    at eval (VM12731 Pay.vue:236)
    at VM12441 hosted-fields.js:515
```
Here's the code that creates the error:-

```
braintree.threeDSecure.create({
           client: clientInstance,
           version: 2
},(e,threeDSecureInstance) => {
           this.threeDSecure = threeDSecureInstance
});
```

Any help is appreciated.

**Comment by crookedneighbor** [comment]
Are you including the 3d secure javascript on your page?

https://js.braintreegateway.com/web/3.63.0/js/three-d-secure.min.js

**Comment by PeterA1** [comment]
Now that you mention it - it appears I did not.

Silly error on my part!

Thanks
