### ISSUE TITLE
Should I prefer the `onLookupComplete` callback over the `lookup-complete` event? 

### ISSUE THREAD

**Issue by M-Sayed** [braintree/braintree-web#521]
### General information

* SDK version: 3.65.0 

### Issue description

I'm trying to upgrade the SDKs from version `3.50.0` to the latest version `3.65.0`, and I am going through the CHANGELOG and the changes of version [3.53.0](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#3530) are stating that `onLookupComplete` callback is deprecated in favor of `lookup-complete` event. So, I guess `lookup-complete` event is preferred over using `onLookupComplete` callback, right?

I can also see that if I defined both of the event and the callback, the callback will take precedence, and [in the codebase](https://github.com/braintree/braintree-web/blob/ebca7a195e8a9efed75507267193452eb427742b/src/three-d-secure/external/frameworks/songbird.js#L533) it's mentioned that the callback is preferred over the event

So, what is the best practice here? Should I use the `onLookupComplete` callback or `lookup-complete` event?

**Comment by hollabaq86** [comment]
👋 @M-Sayed thanks for reaching out. Follow the CHANGELOG and use the event-emitter model with `lookup-complete`. We can clarify that comment you linked so that this is more clear.
