### ISSUE TITLE
Implementing a paypal button that returns a nonce

### ISSUE THREAD

**Issue by iagustin** [braintree/braintree-web#524]
Using npm packages where do values come from?
In my react project 
```
import client from 'braintree-web/client';
import paypal from 'braintree-web/paypal-checkout';

//inside useEffect
client.create({
      authorization: 'passing my braintree sandbox token'
    }).then(function (clientInstance) {
      return braintree.paypalCheckout.create({
        client: clientInstance
      });
    }).then(function (paypalCheckoutInstance) {
      // this paypal object is created by the PayPal JS SDK
      // see https://github.com/paypal/paypal-checkout-components
      return paypal.Buttons({...
```

I wanted to use `client.paypalCheckout.create` instead of `braintree.paypalCheckout.create ` but throws `react_devtools_backend.js:2273 Error! TypeError: Cannot read property 'create' of undefined`

I'm having a hard time implementing a paypal button when ui is successful returns me a nonce so I can send it to my server.
I'm following this doc https://developers.braintreepayments.com/guides/client-sdk/migration/javascript/v3#paypal but doesn't really say from what npm packages the methods come from. Anything useful for a beginner would be appreciated.

**Comment by crookedneighbor** [comment]
You are importing the Braintree SDK like:

```js
import client from 'braintree-web/client';
import paypal from 'braintree-web/paypal-checkout';
```

I'd recommend importing the PayPal bit as `paypalCheckout` or `paypalBraintree` so you don't conflict with the PayPal SDK.

```js
import client from 'braintree-web/client';
import paypalBraintree from 'braintree-web/paypal-checkout';

client.create({
      authorization: 'passing my braintree sandbox token'
}).then(function (clientInstance) {
  return paypalBraintree.create({
    client: clientInstance
  });
}).then(function (paypalCheckoutInstance) {
```

You'll then need to load the PayPal SDK. See https://developers.braintreepayments.com/guides/paypal/client-side/javascript/v3#load-the-paypal-js-sdk

And follow the rest of the steps on that page. If you need additional assistance, contact our support team: https://help.braintreepayments.com/
