### ISSUE TITLE
Hosted Fields create times out on Chrome for Android with Lite Mode enabled

### ISSUE THREAD

**Issue by dimpey** [braintree/braintree-web#529]
* SDK version: 3.66.0
* Environment: Sandbox and Production
* Browser and OS: Chrome 86.0.4240.99 on Samsung Galaxy A50 Android 10

hostedFields.create times out when Lite Mode is enabled in Chrome on Android, with the following error.  

`{
  "name": "BraintreeError",
  "code": "HOSTED_FIELDS_TIMEOUT",
  "message": "Hosted Fields timed out when attempting to set up.",
  "type": "UNKNOWN"
}`

This was not an issue in version 3.55.0 of Braintree Web which our app used previously.  After turning off Lite Mode and reloading the page hostedFields.create works as expected.

**Comment by crookedneighbor** [comment]
I wasn't able to reproduce the error on my Samsung android phone. 

Is there any indication in the network tab of the developer tools about what piece of the Hosted Fields setup is being blocked (and thus causing the timeout)?

**Comment by dimpey** [comment]
> I wasn't able to reproduce the error on my Samsung android phone.
> 
> Is there any indication in the network tab of the developer tools about what piece of the Hosted Fields setup is being blocked (and thus causing the timeout)?

No, no indication in the network tab.  I'm fetching a client token from our server, initializing a client instance and then using that instance in hostedFields.create.  Just one call to https://payments.sandbox.braintree-api.com/graphql which completes in ~400 ms and then two analytics calls following that which both complete in < 20ms.  Then one final analytics call after the hosted fields times out which also completes in < 20ms.

**Comment by crookedneighbor** [comment]
Are you able to reproduce the problem on this staging site? https://hf-lite-mode.glitch.me/

If you can't, that could indicate something strange with your specific integration. Can you provide a staging site that reproduces the error so I can dig into it?

If you _can_ reproduce the problem on my staging site, I'm not sure where to go from here because it seems to be specific to your device, since it works just fine on mine.

**Comment by dimpey** [comment]
No the staging site works fine.

I tried some more debugging on my implementation and it turns out it's because I'm showing the card entry form when a user clicks a button so there must be some issue in Lite Mode to do with browser renders or something.  It's nothing to do with Braintree Web.  Sorry for wasting your time!
