### ISSUE TITLE
Braintree-Data.js is not working with Content-Security-Policy

### ISSUE THREAD

**Issue by le0pard** [braintree/braintree-web#53]
Hello.

My name is Alexey. I am using Braintree for one of our product. Right now I trying to add “Content-Security-Policy”, because we show HTML emails for users and need to block js code execution (eval and inline js). After set header “Content-Security-Policy” I found, what braintree-data.js (https://developers.braintreepayments.com/javascript+ruby/guides/advanced-fraud-tools/client-side) is cause errors:

“Refused to execute JavaScript URL because it violates the following Content Security Policy directive: "script-src *.uservoice.com *.google-analytics.com widget.intercom.io js.intercomcdn.com *.braintreegateway.com *.sandbox.braintreegateway.com *.paypalobjects.com". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.”

![123](https://cloud.githubusercontent.com/assets/98444/8214602/f466af1c-1532-11e5-9382-40d1f1951a5b.png)

First error because of this line of code: `iframe.src='javascript:false’;`. This can be fixed by `iframe.src='about:blank';`.

Next error go from this line of code: `doc.write('<body onload="document._l();">');`. document.write should be disabled for good Content Security Policy http://www.cspplayground.com/compliant_examples#eval This can be fixed by an replace `doc.addEventListener('DOMContentLoaded',function(){doc._l();});`.

But even after this changes I couldn't use `braintree-data.js`, because it load "https://www.paypalobjects.com/webstatic/r/fb/fb-all-prod.pp.min.js" which have similar problems inside. Of course, I can fix even this script and change url in `braintree-data.js`, but I just want, what this will work without `'unsafe-inline' 'unsafe-eval'` for http://content-security-policy.com/. 

Do you have some version, which works with "Content-Security-Policy”? How can I send PR for this lib (2 js libs, as I understand)?

**Comment by le0pard** [comment]
Anyone?

**Comment by kyledetella** [comment]
@le0pard sorry you are running into this. We are looking into it and I will update you here as soon as we have something.

**Comment by le0pard** [comment]
@kyledetella Thanks. Will wait for any update (hope my fixes will help)

**Comment by le0pard** [comment]
Any updates? Does my fixes help to fix code for braintree-data.js?

**Comment by le0pard** [comment]
Ping. Still waiting for fix. Maybe I can help in some way? If library will be in open-source - I can make PR to it.

**Comment by schneiderik** [comment]
Hey @le0pard, I'm a front-end developer at Braintree. I just wanted to give you a quick update.  We have put in some work to address the errors CSPs like yours were raising.  This work is staged to release. I will update this thread when the release happens.

Thanks for your feedback on this issue.

**Comment by le0pard** [comment]
Big thanks, @schneiderik ! Very good news. Will wait for your update.

**Comment by avinash-ananth** [comment]
I'm running into similar CSP issues when trying to use the https://js.braintreegateway.com/v1/braintree-data.js. These issues are blocking our Braintree fraud tools integration, which is an important prerequisite for a few things on our side . 

@schneiderik , any chance you can push for the release to be prioritized soon ?

**Comment by schneiderik** [comment]
Hey everyone, https://js.braintreegateway.com/v1/braintree-data.js has been updated.  The update addresses all of the concerns raised by @le0pard in this thread. Thank you very much for your patience!

**Comment by le0pard** [comment]
Wow. Thanks @schneiderik ! I will try on weekends and will write results here

**Comment by avinash-ananth** [comment]
It looks like the CSP issues on both the Braintree and PayPal libraries are resolved - for our CSP configuration set at least.

Thank you so much for pushing these changes out @schneiderik and @le0pard for raising this issue.

**Comment by le0pard** [comment]
@schneiderik Thanks, it really works! Now I can release my app with CSP :)

**Comment by ikysil-rmn** [comment]
have this fix been included in some release of `braintree-web` client? which version?
Does paypal `checkout.js` have this issue too or it was fixed too?
