### ISSUE TITLE
What happens if you do an advanced integration rather than hosted fields?

### ISSUE THREAD

**Issue by acomito** [braintree/braintree-web#530]
I'm finding the hosted fields are a little bit of a pain in the 🍑  to manage/style.

It's way easier to build the card form myself and just send the HTTP request to braintree for the nonce... we still wouldn't be sending card info to our server or storing card info in our database. Given that, what exactly does that mean for SAQ A and if we don't get SAQ A, what exactly do we need to do? There's not really any explanation of the difference or what steps you need to take if you go the advanced integration route that you wouldn't have to take if you go the hosted routes field.

I know this is partly something to bring up with a support channel, but thought I'd mention it here because the repo docs or brantree's site documentation could use a few more sentences on this.

**Comment by crookedneighbor** [comment]
We have a specific PCI support team that can help you answer these questions. Contact them through the support form here: http://help.braintreepayments.com/
