### ISSUE TITLE
Browser warns about non-unique ids when using multiple Hosted Fields instances

### ISSUE THREAD

**Issue by martinandert** [braintree/braintree-web#533]
### General information

* SDK version: 3.68.0
* Environment: any
* Browser and OS: Chrome, any OS

### Issue description

We're using two Hosted Fields instances on our checkout page. One for the customer's saved card, where they only have to provide the CVV, and another one for setting up a new payment card, where they have to provide all the card details.

This results in two CVV fields being displayed on the page, which Chrome doesn't like since both fields share the same element id. Here's a screenshot:

![browser-warning](https://user-images.githubusercontent.com/6715978/97441567-2892e080-1929-11eb-9912-ebe8b9b42d3c.png)

Perhaps a solution would be to prefix these ids with some kind of instance identifier?

**Comment by crookedneighbor** [comment]
Thanks for pointing this out, we should definitely namespace them.

**Comment by crookedneighbor** [comment]
This should be fixed in v3.69.0

**Comment by martinandert** [comment]
> This should be fixed in v3.69.0

I can confirm it is fixed. Thank you!
