### ISSUE TITLE
How to set fields with nested selector?

### ISSUE THREAD

**Issue by ariefsn** [braintree/braintree-web#536]
### General information

SDK version: 3.68.0
Environment: any
Browser and OS: Chrome, any OS

* SDK version: 3.68.0
* Environment: Sandbox
* Browser and OS: Chrome, Firefox

### Issue description

Is there a way to set the field with nested selector?
i try with
```
          cardholderName: {
            selector: '#cardHolderName input',
            placeholder: 'Name as it appears on the card'
          },
```
but still not work

**Comment by crookedneighbor** [comment]
the selector must reference a dom node that can have nested children, such as a div. an `input` cannot have child nodes. Try:

```js
 cardholderName: {
  selector: '#cardHolderName .class-that-represents-an-empty-div',
  placeholder: 'Name as it appears on the card'
},
```

**Comment by ariefsn** [comment]
@crookedneighbor oh I see. One more, so in this case I used in Vue, there's component to handle each of input, and it has been built with their own style, with other components inside it. Is there a way to connect those components with the config? Because I think too difficult to styling the input to be like the existing component

**Comment by crookedneighbor** [comment]
You can pass a class name as a string in place of a style config. See the `Applying styles with a class name` example here: https://braintree.github.io/braintree-web/current/module-braintree-web_hosted-fields.html

For additional support, reach out to our support team: https://help.braintreepayments.com/

They'll be better equipped to help you with your specific integration.

**Comment by ariefsn** [comment]
![image](https://user-images.githubusercontent.com/33569737/98135933-fb2ecf80-1ef2-11eb-91b4-b8847b861e62.png)
@crookedneighbor that's my input components, inside of it there are some components too, see blue box, and they have their own event too.
any idea how to make like that component with applying style/class?

**Comment by crookedneighbor** [comment]
Please reach out to our support team for help with your specific integration. https://help.braintreepayments.com/
