### ISSUE TITLE
Possible to enable US Bank accounts in sandbox mode? "US_BANK_ACCOUNT_NOT_ENABLED"

### ISSUE THREAD

**Issue by acomito** [braintree/braintree-web#538]
### General information

I'm getting a "US_BANK_ACCOUNT_NOT_ENABLED" when trying to implement plaid with my sandbox braintree account.

Is this something that I need to have braintree support enable? Or is it enabled in plaid? Or am I just missing where you enable it?

I don't see any option for it under the processing settings in my sandbox control panel

![screencapture-sandbox-braintreegateway-merchants-hymc8ynxtbwyqr3z-processing-2020-11-12-11_23_34](https://user-images.githubusercontent.com/12701635/98966821-bbab4900-24d9-11eb-87de-c7ea8327bd01.png)

**Comment by crookedneighbor** [comment]
You will need to reach out to support for help with this: https://help.braintreepayments.com/
