### ISSUE TITLE
Fraud tools: test credit card values not working as expected

### ISSUE THREAD

**Issue by warrendialpad** [braintree/braintree-web#539]
### General information

* SDK version: 3.58.0
* Environment: Sandbox
* Browser and OS: Chrome Version 85.0.4183.102 (Official Build) (64-bit) on MacOS 10.15.6

### Issue description

How can we test end-to-end for Fraud Credit Card given the following test value?

**Expectation**: the following test card number [4000111111111511](https://developers.braintreepayments.com/reference/general/testing/python#fraud-tools) should return an error with status `gateway_rejected` either as an exception error from the client when calling the following:
```js
const c = await BraintreeWebClient.create({ authorization: TOKEN });
await c.request({
  endpoint: 'payment_methods/credit_cards',
  method: 'POST',
  data: { ... },
});
```
or it should return the following `nonce` value of [fake-gateway-rejected-kount-nonce](https://developers.braintreepayments.com/reference/general/testing/python#nonce-fake-gateway-rejected-kount-nonce) which then returns the error status `gateway_rejected` when consumed from our server.

**Current behavior**: No error is returned from the braintree-web POST request and the returned `nonce` is a valid one.

Question:
- Is it expected for the application dev to do the mapping if we want to have an end-to-end test (from checkout UI to a transaction payment)?

I would assume as a SDK user that when testing on sandbox with the provided test credit card values that the corresponding fake-nonce is returned from the braintree-web client instead. Any help is appreciated, thank you.

**Comment by crookedneighbor** [comment]
Do you have Kount enabled? That'll only reject for the Kount reason if Kount is enabled.

**Comment by warrendialpad** [comment]
@crookedneighbor yes we do have it enabled:

![98838995-f8603d00-2412-11eb-9231-e2f141b8e564 (1)](https://user-images.githubusercontent.com/45013017/98997017-ae498b00-24e8-11eb-8834-c1cdae257f66.png)

**Comment by crookedneighbor** [comment]
Very strange. I'm getting the expected gw rejected error when I use that test card in sandbox. Please reach out to our support team so we can investigate your account: https://help.braintreepayments.com/
