### ISSUE TITLE
Add binData to binAvailable event payload

### ISSUE THREAD

**Issue by brykov** [braintree/braintree-web#543]
### General information

* SDK version: 3.x
* Environment: Sandbox/Production

### Issue description

There is a hosted fields event "[binAvailable](https://braintree.github.io/braintree-web/3.69.0/HostedFields.html#event:binAvailable)" that contains a bin number as a string.

There is also "binData" structure in the [tokenizePayload](https://braintree.github.io/braintree-web/3.69.0/HostedFields.html#~tokenizePayload) object. binData contains more detailed information.

We would like to see binData in the binAvailable event payload.

The reason is that the life cycle of these events is different. "binAvailble" fires immediately as soon as the user enters CC details. Whereas tokenizePayload is only available after payment is submitted.

**Comment by crookedneighbor** [comment]
The bin data comes from the Braintree tokenization of the card number, it's not something that is derived on the client, so it's only available on the client after making the API request to tokenize the card details. 

The `binAvailable` event is specifically so merchants can do their own bin lookup call outside of Braintree as soon as it becomes available.

**Comment by githoober** [comment]
@crookedneighbor Our workflow dictates we need to react to a fact a customer fills in a debit card number. We want to avoid making an extra call to a third-party service that can provide us the answer because the Braintree itself can be that service. Is there any other way to achieve what we need with the Braintree JS SDK?

**Comment by crookedneighbor** [comment]
@githoober No, the only way to get the bin data from Braintree is to tokenize the full card number.
