### ISSUE TITLE
Autofilled card number is invalid

### ISSUE THREAD

**Issue by tuurbo** [braintree/braintree-web#547]
### General information

* SDK version: 3.69.0 hosted fields
* Environment: Sandbox and Production
* Browser and OS: Tested in Chrome 87, Edge 87, Firefox 84, Windows 10

### Issue description

If you try to autofill a credit card by clicking on "Cardholder Name", "Expiration" or "CVV", the "Credit card number" will show as invalid. 

Issue exists on my 2 completely different websites. One built with angular and the other with vanilla js. Issue also exists on all of the braintree demos https://developers.braintreepayments.com/guides/hosted-fields/examples/javascript/v3

Steps to reproduce...
- Go to first braintree demo. 
- Click the "Cardholder Name" input, then autofill the card.
- Click "Pay With Card".
- See error "Credit card number is required".
- Focus the "Credit card number" input and hit the space key.
- See that "Credit card number" field is now valid.

**Comment by crookedneighbor** [comment]
Thanks for pointing this out! We'll get this fixed up. My guess here is the particular listeners we have in place to update the validity state aren't firing on the autofill code for the number field.

**Comment by crookedneighbor** [comment]
This should be fixed now in v3.71.0.
