### ISSUE TITLE
threeDSecure npm package

### ISSUE THREAD

**Issue by hollabaq86** [braintree/braintree-web#549]
[source](https://github.com/braintree/braintree_node/issues/185)
@damianpm

### General information
SDK/Library version: 3.70.0
Environment: sandbox and production
Language, language version, and OS: Node v10

### Issue description
I'm using the npm package braintree-web, it includes braintree-web/client and braintree-web/hosted-fields, but it doesn't include threeDSecure
Does threeDSecure has its own npm pakage?
I know I can include the script tag to fetch https://js.braintreegateway.com/web/3.70.0/js/three-d-secure.min.js, but I'd like to have threeDSecure in my webpack pipeline

**Comment by crookedneighbor** [comment]
@damianpm The path is `braintree-web/three-d-secure`

```
npm install braintree-web
ls node_modules/braintree-web/three-d-secure
> external index.js shared
```

**Comment by damianpm** [comment]
Thanks for your fast and clear response @crookedneighbor 
It would be great if you can include this in the docs
