### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by Buguerman** [braintree/braintree-web#55]
I want to use [Sourcegraph](https://sourcegraph.com) for braintree-web code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/braintree/braintree-web. (It should only take 30 seconds.)

Thank you!

**Comment by kyledetella** [comment]
@Buguerman could you share what the goals are of enabling Sourcegraph? Do you have a specific case where you need it?
