### ISSUE TITLE
VPN software blocking https://js.braintreegateway.com/

### ISSUE THREAD

**Issue by simeyla** [braintree/braintree-web#550]
### General information

* SDK version: N/A
* Environment: Production
* Browser and OS : NordVPN

### Issue description

We occasionally have customers that say the hosted forms control does not come up. One customer with this problem claims to be using [NordVPN ](https://nordvpn.com/secure-vpn-site/)and that disabling it allowed them to continue.

I just installed it myself (default install on Windows 10) and it does in fact block the **js.braintreegateway.com** domain in both Chrome & Edge. I did not change any settings. And yes toggling it off immediately allows the domain to be accessed.

    https://js.braintreegateway.com/web/3.68.0/js/hosted-fields.js     **BLOCKED**

    https://www.braintreegateway.com/   **NOT BLOCKED**

Interestingly (and I'm no VPN expert) the way it seems to route traffic to `127.0.0.1` and I know this because it served **my own** developer certificate to me when I access the link above. In Chrome it is just a failed request:

![image](https://user-images.githubusercontent.com/3656278/103940706-a2daa080-50e2-11eb-8640-29998e3c8fa8.png)

Presumably this would need to be addressed as a whitelisting process between Braintree and NordVPN.

The following screenshots are with the VPN active:

![image](https://user-images.githubusercontent.com/3656278/103941094-36ac6c80-50e3-11eb-9844-b073c3e63389.png)
![image](https://user-images.githubusercontent.com/3656278/103941169-53e13b00-50e3-11eb-9a26-cd6455756397.png)
![image](https://user-images.githubusercontent.com/3656278/103941748-2e086600-50e4-11eb-9a66-7cc825406d0f.png)

**Workaround**

Can you confirm that hosted fields functionality is not impacted if I just serve the JS locally myself. I have no idea how many people are using such a VPN service - I may just to retry and fetch a local version if I get a script error, but still benefit from your CDN for the majority of people.

**Comment by crookedneighbor** [comment]
> Can you confirm that hosted fields functionality is not impacted if I just serve the JS locally myself. I have no idea how many people are using such a VPN service - I may just to retry and fetch a local version if I get a script error, but still benefit from your CDN for the majority of people.

Can you check if https://assets.braintreegateway.com/web/3.70.0/html/hosted-fields-frame.html is being blocked? If the `assets` subdomain is allowed, then your workaround should be fine. If it is blocked as well, then no, your workaround will not work since the JavaScript files rely on iframes hosted on the `assets` domain.

I will check in with our infrastructure team about this. Thanks for opening the issue and providing so much detail.

**Comment by simeyla** [comment]
**Phew that page does work!**

Here's your own demo page to see all the domains being blocked. I sorted by 'Status' and these are all the failures! 

![image](https://user-images.githubusercontent.com/3656278/103946954-35337200-50ec-11eb-8a10-8611bb60e8da.png)

**Comment by simeyla** [comment]
Hosting locally is working fine. 

Another domain being blocked by the VPN is (not surprisingly) `https://client-analytics.braintreegateway.com` but I was able to submit a nonce to my server for a credit card just fine :-)

Turns out a few other things are being blocked, including our cookie consent provider. It's privacy working against privacy :-/

I've configured mine as a fallback, so I'll report back how many users a day are on VPN (or have another failure accessing your hosted JS).

**Comment by crookedneighbor** [comment]
I'm in a support chat with NordVPN, they said:

> Oh, I see. I would recommend disabling the CyberSec feature inside of our application to see if the issue persists.

I told them that doing so would not solve the actual issue of the customers being unable to check out, but could you try that so we can at least troubleshoot what portion is blocking it?

**Comment by crookedneighbor** [comment]
The support rep is opening a ticket with their technical team. Since you have a workaround, and there's nothing further we can do from the Braintree side, I'm going to close this issue. I will post here if I receive an update from NordVPN.

**Comment by simeyla** [comment]
@crookedneighbor yes - can confirm the CyberSec feature is what is doing it, but this feature is described as `CyberSec: block ads and malicious websites` so who would pay for a VPN and not want that on! There doesn't seem to be any way to list exceptions either.

I would imagine that getting this whitelisted with them or other VPN providers should be possible, but for me I'm ok with my workaround. I actually created a Cloudflare worker that just proxies through to you - so I don't even need to download the scripts. Of course there are many VPN providers. Maybe you need some kind of 'loader stub' that manages loading the other scripts.

In my smallish sample size since yesterday I've had 4 failures loading the script from your site - out of 313 hosted field sessions. So it's not a trivial amount of people. 

Of course I can't right now tell:

* if those users all had VPN
* how many of those with VPN are smart enough to realize by themselves they need to disable it
* if those recovered sessions resulted in sales - but no reason to think they're any less likely to purchase than anybody else.

**Comment by crookedneighbor** [comment]
Yeah, turning off the cybersec feature isn't the solution, just a way to confirm the problem.

At this point, it's in NordVPN's hands now. I'll update this issue if/when they get back to me about it.

**Comment by crookedneighbor** [comment]
According to Nord VPN, this should now be fixed. Can you double check?

**Comment by simeyla** [comment]
Shoot I just literally cancelled and uninstalled it late last night!
But I made sure to give your URL when the support agent asked why I was
cancelling!

The percentage of failures is dropping closer to half a percent of users
when it was quite high at close to 1% a week ago.
I'll reset the counter and report back again in a few days.
