### ISSUE TITLE
Uncaught Error: Braintree API Client Misconfigured: the clientApiUrl provided in the clientToken is invalid

### ISSUE THREAD

**Issue by AneesMalik** [braintree/braintree-web#553]
### General information

* SDK version: 2.32.1
* Environment: Sandbox
* Browser and OS: Chrome 88.0.4324.150 on Windows 10 2004

### Issue description

Recently I'm receiving the following error message when trying to load braintree.js payment:
Error: Braintree API Client Misconfigured: the clientApiUrl provided in the clientToken is invalid. 
I don't understand the cause of problem!! I'm doing everything right!!!

**Comment by crookedneighbor** [comment]
Reach out to our support team with a sample client token and refer to this issue. We'll be able to debug it from there.

https://help.braintreepayments.com/
