### ISSUE TITLE
IE 11 Promise issue introduced in 3.71.1 (still exists in 3.73.0)

### ISSUE THREAD

**Issue by CoderBrad** [braintree/braintree-web#554]
### General information

* SDK version: 3.71.1-3.73.0
* Environment: Production
* Browser and OS: IE 11 on Windows 10

### Issue description

Console is showing "'Promise' is undefined" for paypal-checkout and hosted-fields starting with 3.71.1.

**Comment by crookedneighbor** [comment]
Thanks for the report, I know exactly where this happened. We'll get this fixed up.

**Comment by crookedneighbor** [comment]
Here's the fix for the underlying issue: https://github.com/braintree/framebus/pull/50

**Comment by crookedneighbor** [comment]
This should be fixed in v3.73.1
