### ISSUE TITLE
Number of PayPal iframes keeps on increasing after repeated setup and teardown

### ISSUE THREAD

**Issue by jmsjr** [braintree/braintree-web#555]
### General information

* SDK version: 3.73.1
* Environment: Sandbox
* Browser and OS: 
Chrome 88.0.4324.182 (Official Build) (64-bit) on Ubuntu 20.04.2 LTS
Edge 88.0.705.53 (Official build) (64-bit) on Windows10
Firefox 86.0 (64-bit) on Ubuntu 20.04.2 LTS

### Issue description

Need to allow user's to switch from Vaulted Flow to Checkout Flow and vice-versa. As you know, the call to PayPalCheckout.loadPayPalSDK() is different between the two flows.

So I have a checkbox that the user can switch to between Vaulted Flow and Checkout Flow. On changing selection, the existing PayPalCheckoutInstance, DataCollectorInstance, BraintreeClientInstance are all torn down ( via calls to the teardown() function on each of them ), and new instances created for the selected flow.

However, as you will see using the attached example, the number of iframes for paypal keeps on increasing ( as if the old ones were not properly torn down ):

![image](https://user-images.githubusercontent.com/28499925/109451355-5d62a000-7aa1-11eb-8283-4aca3a204710.png)

### Test Case

**To replicate:**

* Extract the contents of the following ZIP archive:

[paypal-iframes-increasing.zip](https://github.com/braintree/braintree-web/files/6059130/paypal-iframes-increasing.zip)

* Replace the sandbox authentication ( sandbox_xxxxx ) with your own in
Line 223 ( for hosted fields ) and 
Line 288 ( for PayPal )

* Load the modified HTML in your browser

* Open your browser's development tools ( F12 ) and observe the HTML structure ( under "Elements"  in Chrome )

* Select "PayPal" as your payment type. Amount is fixed to 10.00 for the purpose of the test.

* Check the checkbox with label _"Store PayPal details for future recurring payments?"_

* Uncheck the checkbox

* Repeat the two steps above continuously, checking and unchecking, and just observe the number of iframes with source https://checkout.paypal.com/web/3.73.1/html/dispatch-frame.min.html in the HTML body increasing ( as per screenshot above ).

**Comment by crookedneighbor** [comment]
Thanks for bringing this up! You're right that the teardown method is missing handling for tearing down the iframe: https://github.com/braintree/braintree-web/blob/0729410e2a2d4e5a3fe07a6b127364a0fad0231a/src/paypal-checkout/paypal-checkout.js#L1162-L1170

We'll get this fixed up.

**Comment by crookedneighbor** [comment]
This is fixed in 3.74.0

**Comment by jmsjr** [comment]
Thanks. Confirmed fixed using 3.74.0
