### ISSUE TITLE
options.client is required when instantiating Data Collector.             

### ISSUE THREAD

**Issue by KseniiaBlinova** [braintree/braintree-web#556]
function createClientInstance(clientToken) {
      return braintree.client.create({
        authorization: clientToken
      })
      .then(function (resultClientInstance) {
        clientInstance = resultClientInstance;
        return braintree.dataCollector.create({
          clientInstance: resultClientInstance
        }).then(function (dataCollectorInstance){
          deviceData = dataCollectorInstance.deviceData;
        })
      });
    }

**Comment by crookedneighbor** [comment]
This looks like it was opened accidentally. If you need help with your integration, reach out to our support team. https://help.braintreepayments.com/
