### ISSUE TITLE
IE 11 Find issue 3.70.1, 3.73.1

### ISSUE THREAD

**Issue by DavidsRaptor** [braintree/braintree-web#557]
### General information

* SDK version: 3.70.1, 3.73.1
* Environment: Sandbox and Production
* Browser and OS: Internet Explorer 11.630.19041.0 on Windows 20H2 19042.685

### Issue description

Hi, IE11 console is showing error. The PayPal button is rendered, but doesn't work.

Production 3.70.1:

![image](https://user-images.githubusercontent.com/50201848/110133959-2f48cd00-7dcd-11eb-831e-cbca3dc8e21b.png)

Sandbox 3.73.1:
<details>
  <summary>click_initiate_payment_reject</summary>
  
> click_initiate_payment_reject [object Object]
>    "click_initiate_payment_reject"
>    {
>       [functions]: ,
>       __proto__: { },
>       buttonCorrelationID: "36ecbd34d390a",
>       buttonSessionID: "55da6f864f_mtu6nte6mjq",
>       env: "sandbox",
>       err: "TypeError: Das Objekt unterstützt die Eigenschaft oder Methode "find" nicht
>    at isEligible (https://www.sandbox.paypal.com/smart/buttons?fundingSource=paypal&style.layout=horizontal&style.color=gold&style.shape=rect&style.tagline=false&components.0=buttons&locale.country=DE&locale.lang=de&sdkMeta=eyJ1cmwiOiJodHRwczovL3d3dy5wYXlwYWwuY29tL3Nkay9qcz9jb21wb25lbnRzPWJ1dHRvbnMmY3VycmVuY3k9RVVSJmNvbW1pdD1mYWxzZSZpbnRlbnQ9YXV0aG9yaXplJmNsaWVudC1pZD1BWTN2U01WNG5iMms3Qi1zUWU3NFBDVjQ3YUZIWmtEMlNnOXlJck4weGozMmRkTEc5eXdRaHNrUk90enRkNFZIUTRyVG9lVDlQV0JsdlBUWCIsImF0dHJzIjp7ImRhdGEtdWlkIjoiOTgzZDdmOGExYV9tdHU2bnRlNm1qcSJ9fQ&clientID=AY3vSMV4nb2k7B-sQe74PCV47aFHZkD2Sg9yIrN0xj32ddLG9ywQhskROtztd4VHQ4rToeT9PWBlvPTX&storageID=93584ce36a_mtq6ndy6ndc&sessionID=d7c06a685d_mtu6mzy6mzc&buttonSessionID=55da6f864f_mtu6nte6mjq&env=sandbox&fundingEligibility=eyJwYXlwYWwiOnsiZWxpZ2libGUiOnRydWUsInZhdWx0YWJsZSI6dHJ1ZX0sInBheWxhdGVyIjp7ImVsaWdpYmxlIjpmYWxzZSwicHJvZHVjdHMiOnsiZmxleCI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJwYXlJbjQiOnsiZWxpZ2libGUiOmZ",
>       referer: "www.sandbox.paypal.com",
>       sdkCorrelationID: "a979c89581a37",
>       sessionID: "d7c06a685d_mtu6mzy6mzc",
>       timestamp: "1614959559725",
>       user_id: "55da6f864f_mtu6nte6mjq"
>    }

</details>

**Comment by crookedneighbor** [comment]
I am unable to reproduce the issue. The error looks like it's coming from the PayPal SDK, not the Braintree SDK. Please open an issue there: https://github.com/paypal/paypal-checkout-components

**Comment by DavidsRaptor** [comment]
@crookedneighbor thanks, the same problem in the last issue:
https://github.com/paypal/paypal-checkout-components/issues/1560
