### ISSUE TITLE
Support for autofill styles in allowedStyles - hosted fields

### ISSUE THREAD

**Issue by mithunkt** [braintree/braintree-web#559]
Support for autofill styles in allowedStyles

### General information

* SDK version: 3.73.0
* Environment: SandBox/Production
* Browser and OS Chrome 88.0.4324.192 (64-bit) on MacOS 10.15.7

### Issue description

Can we get support for autofill styles - `-webkit-autofill`, `-webkit-autofill:focus`, `-webkit-autofill:hover`? This will help to override the browser default styles to customize the looks and feel.

![Screen Shot 2021-03-09 at 5 10 28 pm](https://user-images.githubusercontent.com/11576788/110426881-f5dcce00-80fa-11eb-995e-f3cb009af484.png)
![Screen Shot 2021-03-09 at 5 10 47 pm](https://user-images.githubusercontent.com/11576788/110426892-f9705500-80fa-11eb-847c-b9f441bb91bc.png)

**Comment by crookedneighbor** [comment]
We'll look into adding support for box shadow. My initial investigation indicates it should be fine to add.

**Comment by jplukarski** [comment]
This is out in version 3.75.0.
