### ISSUE TITLE
Saved cards in chrome break the validation

### ISSUE THREAD

**Issue by vipconsult** [braintree/braintree-web#56]
When you use the saved card in chrome and don;t put focus on the field the validation fails and it doesn't trigger the onError callback so I cannot re enable the submit button

http://screencast.com/t/eYSAHTF56ze

**Comment by kyledetella** [comment]
@vipconsult thank you for posting this issue. We have a fix in place and it will go out with an upcoming release. I will update here when it is out.

**Comment by kyledetella** [comment]
@vipconsult this issue has been fixed in the [2.9.0](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#290) release.
