### ISSUE TITLE
Paypal integration CORS error

### ISSUE THREAD

**Issue by enricodeleo** [braintree/braintree-web#564]
### General information

* SDK version: 3.71.0
* Environment: Production
* Browser and OS: Hybrid app (ionic)

### Issue description

I enabled PayPal integration and exposed it through the Braintree web drop in. Even if this implementation works in sandbox, it does fail in production apparently due to a CORS error.

![image](https://user-images.githubusercontent.com/3534555/114216461-3aac8c80-9967-11eb-9c2d-14db3285d625.png)

Is there any additional configuration needed in production in order to make Braintree work with PayPal? I searched for known issues but didn't find anything relevant so far.

**Comment by crookedneighbor** [comment]
I'm not sure if the PayPal SDK supports using the Ionic framework. I would open an issue here and ask: https://github.com/paypal/paypal-checkout-components
