### ISSUE TITLE
Amount too large validation error

### ISSUE THREAD

**Issue by claudiowilson** [braintree/braintree-web#565]
### General information

* SDK version: 3.57.0
* Environment: Production
* Browser and OS: 

### Issue description
We recently saw validation error messages for 3DS because the amount passed in was too large. We had a legitimate $765,040.42 transaction. Looking online, I don't know what the maximum amount we can pass in to 3DS is. Can we get some possible values so that I can perform validation on my end and ensure we don't show 3DS for these large transactions? Thank you.

![image](https://user-images.githubusercontent.com/1671085/114625465-274f3900-9c67-11eb-9b9f-976dbf3f47d0.png)

**Comment by crookedneighbor** [comment]
It's the same enforcement as the amount that gets passed to `transaction.sale` in your server sdk.

> The billing amount of the request. This value must be greater than 0, and must match the currency format of the merchant account. Can only contain numbers and one decimal point (e.g. x.xx). Can't be greater than the maximum allowed by the processor. Contact us for your specific limit.

Feel free to reach out to our support team to find out what your limit is: https://help.braintreepayments.com/

**Comment by crookedneighbor** [comment]
Meant to include this link: https://developers.braintreepayments.com/reference/request/transaction/sale/#amount
