### ISSUE TITLE
Something wrong with "payment_methods" endpoint response?

### ISSUE THREAD

**Issue by antonisprovidakis** [braintree/braintree-web#566]
### General information

* SDK version: 3.73.1
* Environment: Sandbox
* Browser and OS: Chrome 90.0.4430.85 (64-bit) on MacOS 10.15.7

### Issue description

Hello,

I'd like to know If there are any recent changes to the `/payment_methods` endpoint?
Specifically to the `hasSubscription` property of each payment method.

Up to ~3 weeks ago, the `hasSubscription` prop of a payment method would be `true` when that payment method was "tied" to a subscription. That's not the case any more, though.

**Comment by crookedneighbor** [comment]
Nothing has changed to my knowledge, but I'll check with the team that owns this API. Is it happening for all payment methods? Or only particular types? (cards, paypal accounts, etc)

**Comment by antonisprovidakis** [comment]
I'm only working with cards.

**Comment by crookedneighbor** [comment]
Did some testing, and it looks like this is _just_ affecting cards. PayPal accounts are reporting correctly for subscriptions. Very strange.

**Comment by antonisprovidakis** [comment]
Hey @crookedneighbor 👋, any updates on this?

**Comment by crookedneighbor** [comment]
The team that owns this API is still investigating. I'll give them another ping about it.

**Comment by crookedneighbor** [comment]
Just an update that I'll be working with the team that is responsible for this tomorrow morning to help with their investigation.

**Comment by antonisprovidakis** [comment]
Thanks for the update 🙇

**Comment by crookedneighbor** [comment]
I think we've figured out the source of the problem. Will let you know when a fix is out.

**Comment by crookedneighbor** [comment]
This is fixed in sandbox and should be going to prod this week. I'll update here when it's fixed in production.
