### ISSUE TITLE
braintree.js Content Security Policy

### ISSUE THREAD

**Issue by MrChoclate** [braintree/braintree-web#57]
Hi,

I use the dropin container but it does not work on my chrome app (it works on my web browser).

My code looks like:

```
var clientToken = data;

braintree.setup(clientToken, "dropin", {
    container: "payment-form"
});
```

But i got this error:

```
Refused to load the script 'https://api.sandbox.braintreegateway.com/merchants/xxxx because it violates the following Content Security Policy directive: "default-src 'self' chrome-extension-resource:".
```

I did not find any thing in the documentation that could help me. Is there a way to make it work?

**Comment by mrak** [comment]
Could you try the same procedure with all chrome extensions disabled?

Oftentimes browser extensions will try and access content in iframes and get these errors (as they should)

**Comment by MrChoclate** [comment]
The same procedure is working with Iceweasel, Safari and Chrome. 

But the point is that can not deactivate CSP. I want to use cca to make an iOS and Android app from my Chrome App. In order to do so, I need to comply with the CSP.

**Comment by le0pard** [comment]
@MrChoclate did you add `https://api.sandbox.braintreegateway.com` to permissions section (https://developer.chrome.com/apps/app_external#external)?

**Comment by MrChoclate** [comment]
I forgot it but I am still getting the same error message.

In a Chrome App you can not load external script and https://api.sandbox.braintreegateway.com/merchants/xxxx is a javascript file.

**Comment by le0pard** [comment]
@MrChoclate whet about set csp directly from manifest? https://developer.chrome.com/extensions/contentSecurityPolicy#relaxing-remote-script

**Comment by MrChoclate** [comment]
This is for Chrome extenstions.
"Chrome extensions will let you relax the default Content Security Policy; Chrome Apps won’t." (https://developer.chrome.com/apps/contentSecurityPolicy)

**Comment by le0pard** [comment]
@MrChoclate I think for you case better use link to web page with payment ability from chrome extension.

**Comment by kyledetella** [comment]
@MrChoclate prior to today's [2.10.0](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#2100) release, we made requests viaJSONP. With the new release, make the requests via XHR (using CORS) which should fix your issue since there is no longer a need to load scripts from `https://api.sandbox.braintreegateway.com/merchants/xxxx`.

Let me know if you run into any more issues.
