### ISSUE TITLE
feature request: CVV retry attempt limitation

### ISSUE THREAD

**Issue by maxisam** [braintree/braintree-web#572]
### General information

* SDK version: 
* Environment: 
* Browser and OS 

### Issue description

Should have a feature to avoid people trying to guess CVV over certain times of attempt.

**Comment by crookedneighbor** [comment]
Please reach out to our support team with this request, as it would be locked down at the API level, not the individual SDK level. https://help.braintreepayments.com/

**Comment by maxisam** [comment]
And shouldn't you guys talk to your API team to handle it? As a customer, I should only care if the SDK I used have this feature. Because when I enable CVV, your company complains that we don't take care of bot trying to crack CVV. But this obviously should be handled from Braintree by simply blocking the card number with certain amount of retries. If we use reCaptcha, it only can slow them down to a point until better AI. And we have to add an extra step to our Checkout. (if we use invisible one, we still need to add certain text) 

I think it is kind of odd that Braintree doesn't take care of this.
