### ISSUE TITLE
binAvailable does not trigger on copy pasting credit card numbers

### ISSUE THREAD

**Issue by g-srirag** [braintree/braintree-web#573]
### General information

* SDK version: 3.76.0
* Environment: Sandbox/Production
* Browser and OS: Chrome 91.0 MacOS Catalina 10.15.4

### Issue description

Apologies if this is not an issue but could be a feature request. 

The Hosted fields event "binAvailable" does not get fired when a user copy paste's a credit card number into the number field which already has another credit card number in it. The event only gets fired if the field's previous value was empty.

Current behaviour: 

credit card number field is empty. User paste's previously copied CC number. "binAvailable" gets triggered.

Expected behaviour:

credit card number field has a value (eg: 4111111111111111). User paste's another CC number into it (eg: 5555555555554444). "binAvailable" doesn't get triggered.

This behaviour would help us in fetching new surcharge values every time the card number changes this way.

**Comment by crookedneighbor** [comment]
Thanks for reporting this, we'll look into fixing it.

**Comment by crookedneighbor** [comment]
This is now fixed in v3.78.3
