### ISSUE TITLE
Usage in React Native?

### ISSUE THREAD

**Issue by anutting** [braintree/braintree-web#577]
Is this the correct module to implement braintree within a React Native client? Or would braintree_node be the correct module?

**Comment by jplukarski** [comment]
We don't officially support React Native; [our SDK is currently optimized for the browser and its security policies and may not function correctly outside of them.](https://braintree.github.io/braintree-web/current/#browser-support-webviews)

However, there are some open-source, [third-party projects](https://github.com/alanhhwong/react-native-braintree) you can use if you want to move forward with a React Native integration. Note, however, that we will not be able to provide support should you run into any issues.
