### ISSUE TITLE
applySafariFocusFix issue when using expiration* hosting fields

### ISSUE THREAD

**Issue by roko91** [braintree/braintree-web#578]
### General information

* SDK version: 3.78.2
* Environment: Sandbox
* Browser and OS: Chrome 91.0.4472.114 (64-bit) on Ubuntu 20.04.2 LTS

### Issue description

Since SDK version 3.78.2 I'm getting the following error in the browser console when using "expirationMonth" and "expirationYear" Hosting Fields:
`hosted-fields-frame.min.html:1 Uncaught TypeError: this.element.setSelectionRange is not a function
    at a.d.applySafariFocusFix (hosted-fields-frame.min.html:1)
    at hosted-fields-frame.min.html:1`

Here is my Hosting Fields config:
`{
                'authorization': ...,
                'fields': {
                    'number': {
                        'container': '#card-number'
                    },
                    'cvv': {
                        'container': '#cccvv'
                    },
                    'expirationMonth': {
                        'container': '#ccexpirymonth',
                        'placeholder': 'MM',
                        'select': {
                            options: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']
                        }
                    },
                    'expirationYear': {
                        'container': '#ccexpiryyear',
                        'placeholder': 'YYYY',
                        'select': true
                    }
                }
            }`

I'm pretty sure it has something to do with the recent Safari focus fix but it seems to appear only on ''expiration*" fields and that's why it probably went under the radar.

**Comment by crookedneighbor** [comment]
Yeah, this is definitely only an issue when using `select`s with expiration fields. Thanks for pointing it out, we'll get it fixed up.

**Comment by crookedneighbor** [comment]
This is fixed in v3.79.0
