### ISSUE TITLE
How to check if google pay is supported

### ISSUE THREAD

**Issue by primedev22** [braintree/braintree-web#584]
### General information

* SDK version: 3.77.0
* Environment: Any
* Browser and OS Any

### Issue description
```
// In older version;
import {
  isSupported as googlePayIsSupported,
} from 'braintree-web/google-payment';
```
In older version, we were able to check if google pay is supported using `isSupported` method. But not able to find alternative in recent version.

**Comment by crookedneighbor** [comment]
What version are you referring to where that helper method was available? Was it in a beta or something?

As far as I know, Google Pay is supported everywhere, since it relies on the Google Pay SDK to provide a fallback popup window for non-Chrome based browsers.

**Comment by primedev22** [comment]
Older version means 3.24.0

**Comment by crookedneighbor** [comment]
Yeah, in that version, Google Payment was still in beta and wasn't using the Google Pay SDK. 3.32.0 was the first non-beta release of the Google Payment component. At that point, the helper method was no longer needed.

**Comment by crookedneighbor** [comment]
Closing this, because there's nothing more actionable on our part.
