### ISSUE TITLE
Update repo's website url

### ISSUE THREAD

**Issue by srianbury** [braintree/braintree-web#589]
### General information
The repo's website URL is returning 404
(https://developer.paypal.com/braintree/docs/javascript/sdk/client/)

* SDK version: N/A
* Environment: N/A
* Browser and OS: Chrome  92.0.4515.131 on MacOS 10.15.7

### Issue description
The link is showing a blank page and the network tab in chrome dev tools shows the following:
![Screen Shot 2021-08-12 at 3 07 18 PM](https://user-images.githubusercontent.com/27159564/129276232-5e29cd61-4a72-428c-a844-c26263c3babf.png)

**Comment by jplukarski** [comment]
I believe the correct URL should be https://developer.paypal.com/braintree/docs/guides/client-sdk/setup/javascript/v3

We'll get that updated; thanks for pointing that out!
