### ISSUE TITLE
Drop-In: no callback for server errors?

### ISSUE THREAD

**Issue by tobiasandersen** [braintree/braintree-web#59]
I'm using the `onError` callback, introduced in release 2.8.0, to handle client side errors in the Drop-In UI. But I can't find a way to detect server errors. E.g:

If I enter an invalid credit card (in correct format) it passes the client side validation (i.e. `onError` is never called), but it shows: 
![image](https://cloud.githubusercontent.com/assets/3599069/8649377/0489fe08-296a-11e5-8729-7fbc248c5c9d.png)

Is there a way to get a callback for those types of errors as well?

**Comment by kyledetella** [comment]
@tobiasandersen right now those errors are not surfaced to `onError`. But it is something on our radar and we will make it available in a future release. Apologies for any inconvenience.

**Comment by markvandertol** [comment]
+1, having this issue as well

**Comment by cdion** [comment]
As am I.  @kyledetella do you have a ETA for this feature?

**Comment by alculquicondor** [comment]
+1

**Comment by ir-fuel** [comment]
+1

**Comment by ir-fuel** [comment]
I think it is pretty important.

Just had an example: I entered an American Express card. My account does not support American Express. Result: "There was an error processing your request ..."

When I dig in the network logs in Chrome it shows me:
`/**/callback_jsona3b86582690b439297423b855e80eab9({"error":{"message":"Credit card is invalid"},"fieldErrors":[{"field":"creditCard","fieldErrors":[{"field":"number","code":"81703","message":"Credit card type is not accepted by this merchant account"}]}],"status":422})`

It would be a lot better for the customer if at least I could show this message on screen. Right now it looks like some system error.

**Comment by Irostovsky** [comment]
+1

**Comment by wmnnd** [comment]
Is there currently a workaround for this so you can at least detect that the server-side validation has been finished?
If that is not the case, this bug report should probably be reopened because it causes some pretty severe misbehavior.
Say you show a custom loading animation or blocking your UI while the payment is being processed, you have no way of terminating that when the validation comes back with an error.

**Comment by ManuelMacchia** [comment]
+1

**Comment by mrak** [comment]
This issue has been addressed in the `2.23.0` release. Those still having problems should give it a try.
