### ISSUE TITLE
paylater is not eligible conditions

### ISSUE THREAD

**Issue by Malstar21** [braintree/braintree-web#593]
### General information

* SDK version: 3.79.1
* Environment: sandbox
* Browser and OS: Chrome Mac

### Issue description
I can't seem to find a clear answer to this and was wondering what conditions determine when a pay later button is shown over a pay credit or vice versa? I've noticed when using another machine I get back `paylater is not eligible` but on my local machine it seems to render just fine. I tried testing out different amounts but it doesn't seem to be a determining factor between my two machines.

**Comment by jplukarski** [comment]
You can find the eligibility requirements for Pay Later in [PayPal's documentation.](https://developer.paypal.com/docs/business/pay-later/us/#eligibility).

Let us know if you have any further questions, or if you continue to have any issues with your integration!

**Comment by Malstar21** [comment]
I'm still unsure of what determines a pay pal credit button from showing over a pay later button?

**Comment by crookedneighbor** [comment]
@Malstar21 this is all on the PayPal side, the Braintree SDK doesn't make any decisions on how the buttons get rendered. I'd reach out to PayPal's support team to get it cleared up. https://developer.paypal.com/support/ or https://github.com/paypal/paypal-checkout-components
