### ISSUE TITLE
3DS Errors related to Cardinal SDK

### ISSUE THREAD

**Issue by echodreamz** [braintree/braintree-web#594]
### General information

* SDK version: 3.81.0
* Environment: Sandbox
* Browser and OS Edge Version 93.0.961.47 (Official build) (64-bit), Windows 10

### Issue description

After complementing a 3DS payment (3DS popup shows, OTP is provided) the 3DS calls immediately fail with errors related to THREEDS_CARDINAL_SDK_ERROR. Nothing specific as it states a "general error" occurred. As well as some pb_handshake syntax error.

![Screenshot_1](https://user-images.githubusercontent.com/18668727/133525056-65c73270-6173-4264-98e4-ff70ccb0b08a.png)

Our previous implementation based on 3.62.0 was working, but stopped with the above issue, figured it was time to upgrade, went to 3.81.0 and the issue continues. So I tossed something together on a simple page without any other extra JS files loading to verify it wasnt something external causing issues and  the error continues.

[code.txt](https://github.com/braintree/braintree-web/files/7173782/code.txt)

Attached a sample.

**Comment by hollabaq86** [comment]
:wave: hi @echodreamz, please [contact Braintree Support](https://developer.paypal.com/braintree/help) referencing this issue, they'll partner with our MPI provider Cardinal Commerce to investigate.

**Comment by Jimbo-Jambo** [comment]
@echodreamz We are experiencing the same issue at the moment, did Braintree Support provide a solution? We have raised a ticket with them but they haven't replied in a few days so I'd be interested to know if they did eventually sort your issue
