### ISSUE TITLE
ThreeDSecure teardown function not closing the authentication modal.

### ISSUE THREAD

**Issue by NabilShahid** [braintree/braintree-web#596]
### General information

* SDK version: 3.79.1
* Environment: Both
* Browser and OS: All

### Issue description

The ThreeDSecure version 2 authentication modal, that comes up after invoking `verifyCard` function, does not close when `teardown` function is invoked.

**Code for creating initializing verification:**
```
const threeDSecureClient = await threeDSecure.create({
      client: braintreeClient,
      version: 2,
    });
// initialize verification. This will open the modal
await threeDSecureClient.verifyCard(options);
```

**Teardown method call:**
```
// same client created above
threeDSecureClient.teardown()
```

I am also calling teardown for braintree client but that also doesn't closes the modal.

The scenario here is that, we a building a single page application. When the user navigates to the payment screen and this modal shows up, the user can click on the browser's back button, we are calling the teardown methods which works without any error, but the modal stays on the screen while the page behind it changes due to back navigation. As this is an SPA, no page load on clicking the browser's back button.

**Comment by crookedneighbor** [comment]
Unfortunately, the modal is controlled by a 3rd party sdk (Cardinal's Songbird SDK), and we have no hook to close it programatically. https://cardinaldocs.atlassian.net/wiki/spaces/CC/pages/557065/Songbird.js

You can use the `2-inline-iframe` option for `version` when creating the component. (see the `Creating a v2 3D Secure component using 2-inline-iframe version` example here: https://braintree.github.io/braintree-web/current/module-braintree-web_three-d-secure.html#.create). Though, that will require you to create your own modal experience and insert the provided iframe into it, but then you have full control over how it displays.
