### ISSUE TITLE
Confusion/Bug about encryption and validation on tokenizeCard

### ISSUE THREAD

**Issue by cavi21** [braintree/braintree-web#60]
Hi there! I'm following the [Credit Cards Tokenization | JS+Ruby](https://developers.braintreepayments.com/javascript+ruby/guides/credit-cards#tokenize-card) guide and experiencing a hard time understanding the idea or purpose behind this way of calling it (I'm in **sandbox** fyi):
```javascript
var client = new braintree.api.Client({clientToken: "TOKEN"});
client.tokenizeCard({
  number: "4000111111111115",
  cardholderName: "John Smith",
  expirationMonth: "10",
  expirationYear: "2018",
  cvv: "832",
  billingAddress: {
    postalCode: "94105"
  }
}, function (err, nonce) {
  console.log(err)
  console.log(nonce)
});
```
I had 2 doubts:
 - For one side the data is not being encrypted before is sent to your servers you can see that in this attachment:
![screen-shot-2015-08-06-at-4 38 54-pm](https://cloud.githubusercontent.com/assets/146249/9124268/edb6395c-3c6b-11e5-902c-5c9a81d02696.jpg) I also could not set neither change the `creditCard[options][validate]: false` to `true`
 - And on the other side I CC I'm trying in there is the one mention in the list of [Unsuccessful credit card verification](https://developers.braintreepayments.com/ios+ruby/reference/general/testing#unsuccessful-credit-card-verification) but the call to `client.tokenizeCard` returns without any error and with a `nonce`, wondering if this call is not in charge of **verify** the card and only just retrieve a nonce.

Also I could not found anywhere any doc or wiki explaining all the JS methods available:
```javascript
Client.addCoinbase()
Client.addCreditCard()
Client.addPayPalAccount()
Client.createSEPAMandate()
Client.decryptBrowserswitchPayload()
Client.encryptBrowserswitchReturnPayload()
Client.exchangePaypalTokenForConsentCode()
Client.getCreditCards()
Client.lookup3DS()
Client.sendAnalyticsEvents()
Client.tokenizeCard()
Client.tokenizeCoinbase()
Client.tokenizePayPalAccount()
Client.unlockCreditCard()
Client.verify3DS()
```
Is there a doc for this?

Thanks a lot!
Hope you have a nice day

**Comment by mrak** [comment]
Hey @cavi21! I'm a developer at Braintree. I hope I can address all of your concerns.

### RE no encryption
Direct use of `braintree.api.Client` does not use encryption. If you are using it directly, it is assumed that you have gone through the appropriate SAQ questionnaire where you handle credit card data through your own form. Details are sent over `https` and are encrypted, in a sense, with TLS.

### RE verifying cards
`tokenizeCard` will always specify `validate: false`.  It is a wrapper around the lower-level `addCreditCard` function which we do not currently document. We could do a better job with naming conventions to make the separation between functions that are intended to be public (such as `tokenizeCard`) and those that are internally used.

If you are looking for solutions that handle credit card information for you while still being able to use your own styles and checkout, you can take a look at our __Hosted Fields__ integration.

* [Hosted Fields on the marketing page](https://www.braintreepayments.com/features/hosted-fields)
* [Hosted Fields documentation](https://developers.braintreepayments.com/javascript+ruby/guides/hosted-fields/overview)

If you still want to only use the `Client` directly, you can use `addCreditCard` as follows:

```javascript
client.addCreditCard({
  options: { validate: true },
  number: "4000111111111115",
  cardholderName: "John Smith",
  expirationMonth: "10",
  expirationYear: "2018",
  cvv: "832",
  billingAddress: {
    postalCode: "94105"
  }
}, function (err, result) {
  if (err) {
    throw new Error('Oh, no!');
  }

  var nonce = result.nonce;
});
```

Keep in mind that `addCreditCard` is not documented because it is subject to change!

**Comment by cavi21** [comment]
Hey @mrak thanks a lot for the detailed response!... about each concern
#### RE no encryption :ok_hand:
Clear enough! I was aware that the connection was over `https` but thought that despite that the data was encrypted with the `clientToken`. Thanks for the clarification!

#### RE verifying cards :+1: 
It would be great if there is a chance to set the `options: {validate: true}` when calling the `tokenizeCard`, looking into the code that function looks like:
```javascript
r.prototype.tokenizeCard = function (t, e) {
    t.options = {
        validate: !1
    },
    this.addCreditCard(t, function (t, n) {
        n && n.nonce ? e(t, n.nonce, {
            type: n.type,
            details: n.details
        })  : e('Unable to tokenize card.', null)
    })
},
``` 
and maybe can be re-write it to something like this:
```javascript
r.prototype.tokenizeCard = function (t, e) {
    t.options = t.options || {}
    t.options.validate = t.options.validate || !1
    this.addCreditCard(t, function (t, n) {
        n && n.nonce ? e(t, n.nonce, {
            type: n.type,
            details: n.details
        })  : e('Unable to tokenize card.', null)
    })
},
```
I realise that it's a little bit more verbose but it will give the chance to send that option on a ***public*** function. About the private naming agreed that the naming convention it would be great :wine_glass:. At least just an underscore on the ***private*** functions like `client.addCreditCard` will become `client._addCreditCard`.

Also I imagine that this repo is not meant to accept PR, if that's not the case happy to open one, just don't hesitate to let me know!

Thanks a lot for the time and all the explanations!
Enjoy your day!

**Comment by mrak** [comment]
You're correct in assuming that we don't accept PRs through this repository, but suggestions are most welcome!

We track issues internally as they are added here and update our GitHub issues as we work on them.

**Comment by cavi21** [comment]
Awesome! thanks @mrak 

One last thing about the **verifying cards** using as you mention the underlying function `client.addCreditCard` with the `options: { validate: true }` I saw that the request now had properly set that key but despite that I didn't get an error, but a valid `nonce`. So maybe I misunderstood the idea behind the `validate: true` I thought that in this particular case should return an error because the cc number I'm using is one of the ones that should return `processor_decline` as specify in [Unsuccessful credit cards](https://developers.braintreepayments.com/ios+ruby/reference/general/testing#unsuccessful-credit-card-verification)

**Comment by mrak** [comment]
That's a great question, and it's a particular (and slightly confusing) feature of sandbox accounts. Those test card cases were conceived before we had browser-side tokenization capabilities.

[Credit Card Verification docs](https://developers.braintreepayments.com/ios+ruby/guides/payment-methods#credit-card-verification)

We currently only return those verification results when creating/updating a customer or creating/updating a payment method through our __server__ SDKs. You will also need to [turn on card verification in the Control Panel](https://articles.braintreepayments.com/control-panel/vault/card-verification#enabling-card-verification)

While using a sandbox account and `validate: true`, only the luhn-10 validity is checked. It's only when you go to creating a payment method or customer with that nonce on your server that you will see the error cases described in [Unsuccessful credit card verification](https://developers.braintreepayments.com/ios+ruby/reference/general/testing#unsuccessful-credit-card-verification)

If you want an invalid card response from `addCreditCard` and `validate: true`, you can try `4111111111111112` as the card number

**Comment by cavi21** [comment]
Excellent! all cristal clear :eyeglasses: thanks a lot @mrak!

If you want you can close this issue, and if in the future you have any update on the `tokenizeCard` function allowing to set the `options: {...}` object will be welcome!

Have a great end of week and a nice weekend!

**Comment by mrak** [comment]
Happy to help!
