### ISSUE TITLE
Missing property threeDSecureInfo on verifyPayload in typings of ThreeDSecure

### ISSUE THREAD

**Issue by kubocob** [braintree/braintree-web#602]
### General information

* SDK version: 3.81.0 ("@types/braintree-web": "3.75.7")
* Environment: Production
* Browser and OS: Chrome 95.0.4638.69 (64-bit) on MacOS 11.3 (20E232)

### Issue description

Based on the [documentation](https://braintree.github.io/braintree-web/current/ThreeDSecure.html#~verifyPayload), `verifyPayload` contains property (object) `threeDSecureInfo`. We're using this value to get result of the lookup status `payload.threeDSecureInfo.status`. This is whole object is missing on the typings of braintree-web - [@types/braintree-web](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/059633346275762e169bd38b6f9989d76c81b942/types/braintree-web/modules/three-d-secure.d.ts#L9).

**Comment by crookedneighbor** [comment]
:wave: we don't maintain those type definitions, they are maintained by the community, but you can open a PR for them over at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/braintree-web/index.d.ts

The next major version of the SDK will be written in Typescript, so we'll have direct support for type definitions built into the SDK at that time.

**Comment by kubocob** [comment]
Typings updated, [PR merged](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/c68c437b9303d07aac4dfc8f282fdebcf653b0e4)
