### ISSUE TITLE
Hosted Fields in braintree-web@3.83.0 - maxlength property ignored for expirationDate

### ISSUE THREAD

**Issue by nstuyvesant** [braintree/braintree-web#603]
### General information

* SDK version: 3.83.0
* Environment: Sandbox
* Browser and OS: Safari 15.1 on macOS 12.0.1

### Issue description

When I do a hostedFields.create() and pass options for fields, the **maxlength** property for **expirationDate** is ignored. I am trying to limit entry to MM/YY instead of MM/YYYY so I set the **maxlength** to 5.

```javascript
  const { hostedFields } = await import('braintree-web')
  const hostedFieldsInstance = await hostedFields.create({
    authorization: clientToken,
    fields: {
      number: {
        container: "#number",
        placeholder: "4111 1111 1111 1111"
      },
      cvv: {
        container: "#cvv",
        placeholder: "CVV",
        maxlength: 4
      },
      expirationDate: {
        container: "#expirationDate",
        placeholder: "MM/YY", // Do not want MM/YYYY!
        maxlength: 5
      },
...
```
In this example, the **maxlength** for **cvv** is honored while it is ignored for **expirationDate**.

**Comment by cgdibble** [comment]
@nstuyvesant `maxlength` is not a supported property for `expirationDate`. You can find the docs on that [here](https://braintree.github.io/braintree-web/current/module-braintree-web_hosted-fields.html#~field). Specifically: ```This option applies only to the CVV and postal code fields.```

We recognize that this is a reasonable request, but investigations/research on our end have shown it is better to maintain consistency on the expiration date field for the overall customer experience. If you have other questions on this topic, feel free to re-open the issue.
