### ISSUE TITLE
THREEDS_MISSING_VERIFY_CARD_OPTION

### ISSUE THREAD

**Issue by mattsputnikdigital** [braintree/braintree-web#607]
### General information

* SDK version: 3.83

### Issue description

I get an error on 3D Secure Verify Card

code: "THREEDS_MISSING_VERIFY_CARD_OPTION"
details: undefined
message: "verifyCard options must include an onLookupComplete function."
name: "BraintreeError"
type: "MERCHANT"

Yet in the docs, onLookupComplete -> <optional>

Can you please advice, it doesn't seem I can use this with an await...

**Comment by crookedneighbor** [comment]
See https://braintree.github.io/braintree-web/current/ThreeDSecure.html#verifyCard for examples for how to structure your verifyCard call. You must either use the event listener:

```js
// set up listener after initialization
threeDSecureInstance.on('lookup-complete', function (data, next) {
  // use `data` here, then call `next()`
  next();
});
```

Or pass it directly to verifyCard:

```js
// call verifyCard after tokenizing a card
threeDSecure.verifyCard({
  amount: '123.45',
  nonce: hostedFieldsTokenizationPayload.nonce,
  bin: hostedFieldsTokenizationPayload.details.bin,
  onLookupComplete: function (data, next) {
    // use `data` here, then call `next()`
    next();
  },
  // other options
```

I expect you are missing that.

If you need further help, reach out to our support team with your integration code: https://developer.paypal.com/braintree/help
