### ISSUE TITLE
onUnsupported is not being called if connection is http

### ISSUE THREAD

**Issue by istolga** [braintree/braintree-web#61]
Hello, 

We set up braintree dropin with credit card and paypal button.
When we ran it in our staging environment: http(not https) paypal didn't show up. 
I immediately found an issue as I saw the code:)

The problem is that onUnsupported method was not called. 
While debugging I found that the method:

Client.prototype.initialize = function () {
  if (!this._clientToken.paypalEnabled) {
is not being called. 
Btw there is a second the same method, which is actually called:
Client.prototype.initialize = function () {
  var i;
  var self = this;

  this._initializeModal();

I think those methods should be combined into one and onUnsupported callback will be called.

**Comment by mrak** [comment]
Hey @istolga, thanks for report! I'm a developer at Braintree.

Can I ask what version of the braintree library you are using? If you are including it via

```html
<script src="https://js.braintreegateway.com/v2/braintree.js"></script>
```

could you see if the problem still persists? We recently updated our code in the section that you were debugging.

**Comment by istolga** [comment]
Hello @mrak, 
Thank you for the quick response.
We use it through bower: "braintree-web": "2.10.0" and then <script src="bower_components/braintree-web/dist/braintree.js"></script>
Let me know which version you suggest to use.

**Comment by mrak** [comment]
Could you give 2.11.2 a try?

**Comment by istolga** [comment]
When I look at the source code:
https://js.braintreegateway.com/js/braintree-2.11.2.js
I still see 2 definitions:
Client.prototype.initialize=
Based on how javascript works only the last will be used.

Am I missing something?
@mrak

**Comment by mrak** [comment]
You might see several definitions of `Client` in that file. They won't conflict as each definition will be contained within it's own functional closure. The two that you pointed out are the initializers for our internal dropin and paypal modules.

I agree that looking at the built code can be confusing in this respect.

**Comment by istolga** [comment]
Hello @mrak, 
Thank you for the clarification. We'll finish one feature for our project and then will try to upgrade.

**Comment by mrak** [comment]
@istolga Did upgrading the version of braintree address your issue?

**Comment by istolga** [comment]
Hello @mrak , 
Thank you for following up. Unfortunately not yet, this was low priority as it is only check for http and doesn't happen in https. If you can verify it on your side, this would be great. Please close it if you are sure it's been fixed.

Thanks, 
Olga.

**Comment by mrak** [comment]
Closing for now. Feel free to comment back if you see this persist in the lastest release.
