### ISSUE TITLE
Dynamic "vault" property without re-render button

### ISSUE THREAD

**Issue by hixel** [braintree/braintree-web#610]
### General information

* SDK version: 3.82.0
* Environment: Sandbox  
* Browser and OS: No matter

### Issue description

If I use `vault: false` and `intent: capture` I am able to dynamically change the amount and line items without re-render the PayPal buttons
```
braintree.client
            .create({
                authorization: <clientToken>,
            })
            .then(function(clientInstance) {
                return braintree.paypalCheckout.create({
                    client: clientInstance,
                });
            })
            .then(function(instance) {
                return payPalInstance.loadPayPalSDK(
                   dataAttributes: <dataAttributes>,
                   currency:'USD',
                );
            })
            .then(function(instance) {
                return paypal.Buttons({ createOrder: function() { return payPalInstance.createPayment({ amount: <global amount> }) })
.render('#paypal-button');
            })
            .then(function() {
            })
            .catch(function(err) {
                // Handle component creation error
            });
```
But I am not able to change the flow from the type "Vault" to the "Checkout With Vault" for example, because I have to pass the vault parameter to the `loadPayPalSDK()` method. Is it possible to set the vault parameter inside the object for the `Buttons `method? Otherwise, I need to call `loadPayPalSDK `and then re-render the PayPal buttons.

**Comment by jplukarski** [comment]
Thanks for writing in, @hixel. PayPal requires both the `intent` and `vault` parameters [to be set while loading the PayPal SDK](https://developer.paypal.com/docs/regional/th/checkout/reference/customize-sdk/#link-queryparameters), and have default values set if they are not passed in. So if you need to dynamically change the `vault` paramter in the middle of the flow, you will have to reload the PayPal SDK onto your page.

Let us know if you have any other questions.
