### ISSUE TITLE
8-digit BIN support

### ISSUE THREAD

**Issue by jmsjr** [braintree/braintree-web#612]
### General information

* SDK version: 3.53.0
* Environment: Production
* Browser and OS : Version 97.0.4692.71 on Windows 10

### Issue description

This is not really an issue but more of a question. 
Is there a minimum version that guarantees support for 8-digit BINs ?

https://blog.pcisecuritystandards.org/8-digit-bins-and-pci-dss-what-you-need-to-know
https://www.mastercard.com/content/dam/public/mastercardcom/globalrisk/pdf/8-Digit%20BIN%20Expansion%20and%20PCI%20Standards%20-%20FINAL%20(10-20-2021).pdf
https://usa.visa.com/dam/VCOM/global/partner-with-us/documents/visa.com-numerics-faq.pdf

**Comment by jplukarski** [comment]
Hey @jmsjr thanks for bringing this up. We are currently working on implementing support for 8-digit BINs. We will keep this issue open and let you know what you will need to do on your end to guarantee support.

**Comment by jmsjr** [comment]
> Hey @jmsjr thanks for bringing this up. We are currently working on implementing support for 8-digit BINs. We will keep this issue open and let you know what you will need to do on your end to guarantee support.

That @jplukarski  ... Hopefully Braintree will also provide some 8-digit BIN test card numbers to test out 8-digit BINs in sandbox environments.

**Comment by jmsjr** [comment]
Hi @jplukarski ... any update on the 8-digit BIN support ... and when is a new version expected that supports this ? Will there also be supporting versions for the backend ? ( e.g. Java SDK, etc )

**Comment by jplukarski** [comment]
Hey @jmsjr , we don't have a timetable of when the new versions will be released at this moment, but there will be new versions of both our Client and Server SDKs to support the 8-digit bin.

**Comment by bruce-at-events** [comment]
hey guys any update on this? it's only 28 days away

**Comment by jmsjr** [comment]
Looks like there is no need for any changes for 8-digit BIN support:

https://developer.paypal.com/braintree/articles/control-panel/transactions/bank-identification-numbers#8-digit-bin-expansion-readiness
