### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'push') on hosted fields

### ISSUE THREAD

**Issue by bcavenagh-foxtrot** [braintree/braintree-web#618]
### General information

* Environment: Production
* Browser and OS:  Chrome Version 95.0.4638.54 (Official Build) (arm64) on MacOS 11.5.1

### Issue description

We are experiencing an error that appears to be coming from `braintree-web` through our use of the `react-braintree-fields` library. More information about the issue can be found on this thread: https://github.com/nathanstitt/react-braintree-fields/issues/35 but to re-iterate—we are getting this error on our console whenever we load in braintree fields on our app. 
![Screen Shot 2022-02-28 at 10 21 25 AM](https://user-images.githubusercontent.com/93142880/156019033-a006682b-42c8-4fe3-bcb4-d75e75ec0e78.png)
It appears to be happening here in the minified code: 
![Screen Shot 2022-02-28 at 10 22 32 AM](https://user-images.githubusercontent.com/93142880/156019167-5054eb5c-200c-49e2-b847-a6b1cb7470d6.png) which, after talking to the react-braintree-fields author, isn't something written in that library. Any assistance you're able to provide would be greatly appreciated!

**Comment by bcavenagh-foxtrot** [comment]
Ahh error was caused by us using the `react-braintree-fields` library but also embedding the hosted-fields script in our `<head>`... closing for now as removing the script from the head seems to have fixed the issue

**Comment by crookedneighbor** [comment]
thanks for the update!
