### ISSUE TITLE
PayPal Checkout Line Items

### ISSUE THREAD

**Issue by dkemp4816** [braintree/braintree-web#621]
### General information

* SDK version: v3
* Environment: Sandbox
* Browser and OS Example: Chrome 99.0.4844.74 (64-bit) on Windows 10 21H2

### Issue description

Can't use Line Items with PayPal checkout integration.

```javascript


braintree.paypalCheckout.create({
                authorization: clientToken,
                }, function (paypalCheckoutErr, paypalCheckoutInstance) {
                paypalCheckoutInstance.loadPayPalSDK({
                currency: 'USD',
                intent: 'capture',
                vault: 'false'
                }, function () {
                paypal.Buttons({
                    style: {
                        height: 50
                    },

                    fundingSource: paypal.FUNDING.PAYPAL,

                    createOrder: function () {
                    return paypalCheckoutInstance.createPayment({
                        flow: 'checkout
                        amount: '100.00'
                        currency: 'USD'

                        intent: 'capture',

                        displayName: 'Test Name',
                        landingPageType: 'login',
                        lineItems: [
                            {
                                quantity: '1',
                                unitAmount: '50.00',
                                name: 'Test Name',
                                kind: 'debit'
                            },
                            {
                                quanity: '1',
                                unitAmount: '50.00'
                                name: 'Test Name 2',
                                kind: 'debit'
                            }
                        ],

                        enableShippingAddress: true,
...


```

All I get is an undefined error, 'Could not initialise payment flow'.
Works fine if I remove the lineItems or put `lineItems = [],` (obviously without the line items).

Reference: https://braintree.github.io/braintree-web/current/PayPalCheckout.html#createPayment

**Comment by jplukarski** [comment]
Hello @dkemp4816,  Thanks for bringing this to our attention. We are able to reproduce your issue. We are working with our PayPal team to see what the issue is and will follow up once we have answers. Thanks for your patience.

**Comment by jplukarski** [comment]
Hey @dkemp4816 , After trying to align everything the same as your integration, we are no longer able to reproduce the error. Can you take a look at this codepen and enter a [tokenization key](https://developer.paypal.com/braintree/docs/guides/authorization/tokenization-key/javascript/v3) for your integration? We believe there could be some permission issues here => https://codepen.io/jplukarski/pen/ZEvpmzN

If you can't reproduce the issue on that codepen, is it possible to send us a codepen/test site that does reproduce the issue so we can take a further look? Thanks.

**Comment by dkemp4816** [comment]
Hi @jplukarski,

I appreciate you looking into this. I've now noticed that in the 2nd line item, I have misspelt 'quantity'! I completely missed this but after correcting, I'm now able to get this working.

Thank you for your time.
