### ISSUE TITLE
4-digit AMEX CIDs incorrectly being validated when only 3 digits entered

### ISSUE THREAD

**Issue by meeham04** [braintree/braintree-web#623]
### General information

* SDK version: ^3.51.0
* Environment: Production
* Browser and OS  Version 99.0.4844.83 (Official Build) on MacOS 11.4

### Issue description

When using Card Number and CVV hosted fields, it looks like AMEX CIDs are being incorrectly marked as valid when only 3 digits have been entered, rather than at the expected 4 digits.

When debugging I can see an eventData object containing a merchantPayload object which seems to be getting populated correctly, i.e. we receive an array of cards including an entry for `american-express` with:

```js
code : { name: "CID", size: 4 }
```

On the client, when entering the security code value "123", the `TokenizeCreditCard` operation fires with the payload:

```
input: {creditCard: {cvv: "123"}, options: {validate: false}}
```

But back in the createInputEventHandler implementation in hosted-fields, we receive the following merchant payload for the CVV nonce:

```js
{
    isEmpty: false,
    isValid: true,
    isPotentiallyValid: true,
    isFocused: true,
    container: div#root_payment_cvv_nonce
}
```

And the field passes validation in the client. At this point I would have expected `isValid` to be false and for the field to be marked invalid.

**Comment by crookedneighbor** [comment]
I couldn't reproduce this. I used the AMEX test card `3782 822463 10005` and the cvv field correctly reported that it was not valid.

Can you provide a staging site/codepen that reproduces the problem or a test card that triggers the behavior (if the one I provided does not)?

**Comment by cgdibble** [comment]
If the problem persists for you, please provide more info as Blade mentioned above and we can take a look and re-open the issue.

**Comment by ArtjomsFomins** [comment]
I Encountered with this bug too
- SDK version: ^3.85.3
- Browser and OS Version: 111.0.5563.146 (Official Build) (64-bit) on Ubuntu 20.04.6 LTS


state.cards[0]
``` 
code: {name: "CID",  size:4},
niceType : "American Express"
supported : true
type: "american-express"
```
Braintree error:
```

**Comment by ArtjomsFomins** [comment]
I Encountered with this bug too
- SDK version: ^3.85.3
- Browser and OS Version: 111.0.5563.146 (Official Build) (64-bit) on Ubuntu 20.04.6 LTS


state.cards[0]
``` 
code: {name: "CID",  size:4},
niceType : "American Express"
supported : true
type: "american-express"
```
Braintree error:
```
code: "HOSTED_FIELDS_FIELDS_INVALID"
deitals: {
 invalidFieldKeys: ['cvv']
},
message: "Some payment input fields are invalid. Cannot tokenize invalid card fields.",
name : "BraintreeError"
```
