### ISSUE TITLE
PayPal popup loads indefinitely after opening

### ISSUE THREAD

**Issue by ciriousjoker** [braintree/braintree-web#627]
### General information

- SDK version: 3.75.19
- Environment: both
- Browser and OS: Chrome 100.0.4896.127 (Official Build) (64-bit) (cohort: Stable)

### Issue description

This issue is not reproducible, but happens every now and then, on sandbox, production, during development and for real users.

After the PayPal popup was opened during Checkout, it would show the small loading spinner (the same thing that you see when you open the [popup url](https://checkout.paypal.com/web/3.85.2/html/paypal-landing-frame.min.html) directly in the browser), but it just keeps spinning and never stops.

This is not the big loading spinner to indicate your account is loading. 

If I close the popup in this state, the the call to `tokenize()` (which opened the popup) will never return and reloading the page seems to never complete. During development, I have to create a new tab, and start the checkout all over to get a usable state.

**Comment by hollabaq86** [comment]
👋 @ciriousjoker thanks for reaching out. Next time you encounter this issue in sandbox or production, can you [contact support](https://developer.paypal.com/braintree/help) referencing this issue and make a note of the following info to help our investigation?

- timestamps of when it occurred (UTC preferred but honestly just let us know the timezone if it's not UTC)
- browser(s) impacted (I see you mentioned Chrome in this issue, if there's any other browsers where you're seeing this happen please let us know).
- link to the site where you saw this behavior or a code sample

As you mentioned, this is fairly difficult to reproduce, but that doesn't mean we shouldn't try and get more info. Can you confirm that you're using the paypal-checkout component and not the paypal component?

**Comment by bufordtaylor** [comment]
You might want to check out https://github.com/braintree/braintree-web/issues/642

**Comment by hollabaq86** [comment]
Closing this issue since we haven't heard from OP to get more info.
