### ISSUE TITLE
Cannot specify width and height for 3DS inline iframe element

### ISSUE THREAD

**Issue by liuxiaofeng1981** [braintree/braintree-web#629]
### General information

- SDK version: 3.85.3
- Environment: Sandbox
- Browser and OS: Chrome 100.0.4896.127 (Official Build) (x86_64) on MacOS Big Sur 11.5.1 

### Issue description

I'm using 3DS by setting `version: '2-inline-iframe'` when creating the 3DS instance. Then in the `authentication-iframe-available` event handler the HTML element received always has a fixed value for the iframe width=390 and height=400 as below

![image](https://user-images.githubusercontent.com/998268/168702603-acbecc73-b3c4-4638-95c5-ca4bfd41d768.png)

This is causing issue as vertical scrolling bar. Right now I'm hardcoding the value via
`event.element.children[0].style.setProperty('height', '727px', 'important');` sth like that. But I'd like to be able to dynamically set the height of the iframe to the height of its content as each bank may have different UI for 3DS challenge I suppose? Just trying to figure out what's the best way to achieve this?

**Comment by cgdibble** [comment]
Hey, @liuxiaofeng1981 we don't provide a harness for styling the 3DS auth page that is returned in this case. 

If I'm understanding your goal correctly, you should be able to specify a dynamic height using CSS without hardcoding or relying on the value we have specified.
