### ISSUE TITLE
Pull Accepted Payment Methods from Merchant Accounts

### ISSUE THREAD

**Issue by ThoamsClark** [braintree/braintree-web#63]
Hi,

I'd like to request the ability to pull a list of the payment methods which a given Merchant Account supports, please. We can currently access various errata such as FundingDetails, IndividualDetails and BusinessDetails, but not the supported payment methods.

Cheers,
Tom Clark

**Comment by lilaconlee** [comment]
Hey @ThoamsClark, this is more of a overall Braintree API request that's not specific to braintree.js. You should reach out to `support@braintreepayments.com`. We appreciate your feedback!
