### ISSUE TITLE
postalCode not included in payload details

### ISSUE THREAD

**Issue by cmacdonnacha** [braintree/braintree-web#630]
### General information

- SDK version: 3.85.3 
- Environment: Sandbox
- Browser and OS: Chrome 101 / Mac OS 12.4

### Issue description

When using the `tokenize` method I can use `payload.details` to retrieve the values of the input fields, but `postalCode` is missing from it.

```
 hostedFieldsInstance?.tokenize(function (tokenizeErr, payload) {
 ```
 
 The following are available:
 
 ```
  payload.details.cardholderName
  payload.details.cardType
  payload.details.expirationMonth
  payload.details.expirationYear
  payload.details.lastFour
  payload.details.lastTwo
```

but  `payload.details.postalCode` does not exist.

**Comment by hollabaq86** [comment]
👋 @cmacdonnacha that's correct, not every integration includes postal code. Can you elaborate on your use case for needing it?

**Comment by cmacdonnacha** [comment]
> 👋 @cmacdonnacha that's correct, not every integration includes postal code. Can you elaborate on your use case for needing it specifically in the tokenization payload response?

Hey @hollabaq86 thanks for the reply. Basically I am sending a payload of values to our backend like so:

```
{ 
  cardholder_name: braintreePayload.details?.cardholderName
  token: braintreePayload?.nonce
  postalCode: 'NEED TO GET POSTAL CODE FROM INPUT FIELD HERE'
 }
 ```
 
 So I need to retrieve the value the user entered into the `postalCode` input field and send that to my server where it does more things with the cardholder name and postal code.

**Comment by cmacdonnacha** [comment]
Hey @hollabaq86 any thoughts on this one?

**Comment by cgdibble** [comment]
@cmacdonnacha hey! Our docs mention this here: https://developer.paypal.com/braintree/docs/guides/hosted-fields/setup-and-integration

> Depending on your [AVS settings](https://developer.paypal.com/braintree/articles/guides/fraud-tools/basic/avs-cvv-rules) you may also want to include a postal/ZIP code field for later use in server-side Transaction calls.

Is your case that you have addressed it from this angle but that the payload inconsistently returns the `postalCode`?

**Comment by cmacdonnacha** [comment]
It's ok now - I actually don't need it anymore. Thanks anyway.

**Comment by chetanakum007** [comment]
I need this postalCode because I have to add "Postal Code" and pass that in our API request. Please help me to get postalCode in payload. I'm using the version of client.min.js and hosted-fields.min.js is 3.86.0.
