### ISSUE TITLE
Challenge url to return

### ISSUE THREAD

**Issue by pimproyect** [braintree/braintree-web#633]
### General information

- SDK version: 
- Environment: 
- Browser and OS 

### Issue description
647 / 5.000
Resultados de traducción
Hello
We are doing an integration with C# and I need to know if there is any way to change the return url of the challenge so that it returns with the information to a certain controller.
The challenge is not being launched from a BrainTree frame, and it returns an information to an address that does not exist. I get an address like this:

https://assets.braintreegateway.com/3ds/html/authentication_complete_frame?auth_response=%7B%22threeDSecureInfo%22%3A%7B%22liabilityShifted%22%3Atrue%2C%22liabilityShiftPossible%22%3Atrue%7D%2C%22paymentMethod%22%3A%7B%22type%22%3A%22CreditCard%22%2C%22nonce%22%3A%22b82049d8-df2b-0d4a-cf9b-10d78e44f4d9%22%2C%22description%22%3A%22ending+in+91%22%2C%22isLocked%22%3Afalse%2C%22securityQuestions%22%3A%5B%22cvv%22%5D%2C%22threeDSecureInfo%22%3A%7B%22enrolled%22%3A%22Y%22%2C%22liabilityShifted%22%3Atrue%2C%22liabilityShiftPossible%22%3Atrue%2C%22status%22%3A%22authenticate_successful%22%2C%22threeDSecureAuthenticationId%22%3A%22gcgpk4x33cr272fbm5%22%7D%2C%22consumed%22%3Afalse%2C%22default%22%3Atrue%2C%22hasSubscription%22%3Afalse%2C%22details%22%3A%7B%22cardType%22%3A%22Visa%22%2C%22lastTwo%22%3A%2291%22%2C%22lastFour%22%3A%221091%22%2C%22bin%22%3A%22400000%22%2C%22cardholderName%22%3A%22Pablo+I%C3%B1areta+64%22%2C%22expirationYear%22%3A%222023%22%2C%22expirationMonth%22%3A%2201%22%7D%2C%22binData%22%3A%7B%22prepaid%22%3A%22Unknown%22%2C%22healthcare%22%3A%22Unknown%22%2C%22debit%22%3A%22Unknown%22%2C%22durbinRegulated%22%3A%22Unknown%22%2C%22commercial%22%3A%22Unknown%22%2C%22payroll%22%3A%22Unknown%22%2C%22issuingBank%22%3A%22Unknown%22%2C%22countryOfIssuance%22%3A%22Unknown%22%2C%22productId%22%3A%22Unknown%22%7D%7D%2C%22success%22%3Atrue%7D

And what I need, now being tested, to return to an address like this

https://localhost:4000/Controller/Action

with the same information.

I have tried to change the termUrl parameter that 3DSlookup returns and it returns two parameters PaRes and MD, but it is not what I need to finalize the transaction.

**Comment by cgdibble** [comment]
@pimproyect hello! Can you please clarify the values in the Issue template such as SDK Version, etc.? Please re-open once you have that info available and we can take a look.

**Comment by pimproyect** [comment]
Don't worry, the company has invited me to leave my job
