### ISSUE TITLE
Is VaultManager.deletePaymentMethod usable or not?

### ISSUE THREAD

**Issue by lol768** [braintree/braintree-web#638]
The code includes this comment:

https://github.com/braintree/braintree-web/blob/e6cdc7856b94654f759e19c44bb8e5eca348481e/src/vault-manager/vault-manager.js#L88

So, in practice, can we use this method or not?

**Comment by hollabaq86** [comment]
👋 @lol768 thanks for reaching out. You can use this method, that TODO was added a long time ago and we neglected to stay up to date with the comment. If you encounter any issues, please don't hesitate to [contact Support](https://developer.paypal.com/braintree/help).

**Comment by hollabaq86** [comment]
for internal tracking, ticket 1885

**Comment by lol768** [comment]
Many thanks :)
