### ISSUE TITLE
postalCode not included in payload details

### ISSUE THREAD

**Issue by chetanakum007** [braintree/braintree-web#639]
I need this postalCode because I have to add "Postal Code" and pass that in our API request. Please help me to get postalCode in payload. I'm using the version of client.min.js and hosted-fields.min.js is 3.86.0.

_Originally posted by @chetanakum007 in https://github.com/braintree/braintree-web/issues/630#issuecomment-1226934774_

**Comment by hollabaq86** [comment]
👋 @chetanakum007 please [contact Support](https://developer.paypal.com/braintree/help) for troubleshooting assistance.
