### ISSUE TITLE
PayPal support in Drop-In UI for PhoneGap

### ISSUE THREAD

**Issue by isacjames** [braintree/braintree-web#64]
Is PayPal supported for the drop-in UI (js) via PhoneGap? I get a blank page when I click on the PayPal button ( vault and card works) and I was wondering if its supported and/or requires any specific steps to  enable within hybrid apps.

**Comment by mrak** [comment]
Hey @isacjames, we currently do not support PhoneGap with our v.zero SDKs. You may have more luck wrapping our native Android and iOS v.zero SDKs for use within your PhoneGap application.

Our web-based solution centers a lot of it's work on utilizing browser security policies that may not be reflected by PhoneGap's webview-based application container.

You may be able to find unofficial, community-supported plugins.

**Comment by guimba13** [comment]
Hey @isacjames did you find any solution for that? I'm having the same problem you had and I was counting to be able to use Braintree in my phonegap application.

**Comment by kyledetella** [comment]
@guimba13 I would take a look at #106, specifically [this comment](https://github.com/braintree/braintree-web/issues/106#issuecomment-163019915).

**Comment by guimba13** [comment]
Thanks a lot @kyledetella

**Comment by isacjames** [comment]
@guimba13 : I eventually just turned paypal off, but looks like I should start exploring this again :). Would be nice if we could just turn if off on devices where it would not work.
