### ISSUE TITLE
Merchant Metadata from API

### ISSUE THREAD

**Issue by andrewstephens** [braintree/braintree-web#640]
This is more of a question / request about the API. I don't know if this is the best place for this issue/request. If it isn't, feel free to delete it. 

My company provides a way for multiple merchants to setup accounts with us, using their Braintree credentials. It's essentially a marketplace system. But, from time to time, we'd like to query certain details about those merchants. Most recently, it was their enrollment status in 3D Secure. We'd like to be able to modify our code to include (or exclude) the 3D secure object and additional information if the merchant's account doesn't support it. 

I don't know if anything like this is on your roadmap, but I just wanted to throw it out there for consideration. Thanks!

**Comment by hollabaq86** [comment]
👋 @andrewstephens, thanks for reaching out. I'll forward this feedback to our Product folks for consideration.
