### ISSUE TITLE
Error on 3DSecure: Base.DFUtility: Bin profiling  exceeded QOS setting [10000]ms

### ISSUE THREAD

**Issue by vladminsky** [braintree/braintree-web#644]
### General information

- SDK version: "braintree-web-drop-in": "1.33.4"
- Environment: Production
- Browser and OS: Google Chrome Version 105.0.5195.127 (Official Build) (64-bit) on Windows 11 Pro. Windows Feature Experience Pack 1000.22000.978.0

### Issue description

Some clients experience some strange errors from api.braintreegateway.com (HTTP error 422) when perform 3DSecure verification:

`Base.DFUtility: Bin profiling  exceeded QOS setting [10000]ms`

![image](https://user-images.githubusercontent.com/1128316/192269089-328da320-3709-4a73-a0b0-9b4e883efd7c.png)

I can't give you exact steps to reproduce since the issue appears for some clients only. I'm not sure it is a rule but this happened recently for clients with cards issued by Cyprus or Indonesia.

I have no idea.. maybe I do something wrong on my side but billing with 3DSecure works well for the most cases.
Can you point me how to proceed with such kind of issue?

Thanks in advance.

**Comment by hollabaq86** [comment]
👋 @vladminsky please [contact Support](https://developer.paypal.com/braintree/help) referencing this issue so they can partner with our MPI provider CardinalCommerce to investigate.
