### ISSUE TITLE
Show clearer error message instead of "There was an error processing your request"

### ISSUE THREAD

**Issue by markvandertol** [braintree/braintree-web#65]
When you enter a creditcard number which fails to pass credit card verification, then the drop-in ui shows this error:

![There was an error processing your request.](https://cloud.githubusercontent.com/assets/2835719/9325770/2f810ba0-4595-11e5-8e25-07cc4036f043.png)

I think it should give some details why it failed to process the request. Now it is unclear that we couldn't perform a transaction with the credit card the user specified, instead of for example an internal server error. It is now also unclear for the user how to proceed and resolve this issue.

Since the UI is full screen when adding a new payment method, there isn't really a good way for us to add such a description ourselves.

**Comment by lilaconlee** [comment]
Hey @markvandertol, thanks for the feedback! Adding additional information to this flow is definitely something we'd like to consider in the future. We'll let you know here if we end up putting it on our roadmap.

**Comment by mloo-sp** [comment]
+1.  
We've been getting complaints from our customers about the unclear error messaging.

**Comment by jamesbondo** [comment]
http://stackoverflow.com/questions/27065660/braintree-client-form-submission-failure
https://developers.braintreepayments.com/reference/general/testing/java#credit-card-numbers

**Comment by EvanHahn** [comment]
We talked this over with our security team and confirmed that showing more descriptive errors can make it easier for merchants to be exposed to various types of attacks (for example, if the criminal has bought a large list of illegally-obtained credit cards). We want to prevent this, of course!

If we can find a more secure way to do this, we will add it to our roadmap. Unfortunately, that means we're closing this issue for now. Sorry I can't give a different answer!
