### ISSUE TITLE
Type `allowDesktop` & `paymentMethodUsage` is not inside venmo.create()

### ISSUE THREAD

**Issue by wangyq1996** [braintree/braintree-web#650]
### General information

- SDK version: 3.88.1
- Environment: Production
- Browser and OS: Browser

### Issue description

I need to set `allowDesktop: true` & `paymentMethodUsage: "multi-use"` to meet out business requirements. However,  I can not found these two types definition in `@types/braintree-web` v 3.75.22. Is there anything I need to pay attentions on? Thx.

**Comment by hollabaq86** [comment]
Sorry @wangyq1996 but we don't own the types library, I suggest you create an issue in their repo.

**Comment by wangyq1996** [comment]
Oh I thought u share the same lib xD. I will go to their repo, thanks.
