### ISSUE TITLE
How to turn off songbird logs

### ISSUE THREAD

**Issue by khrynczenko** [braintree/braintree-web#653]
### General information

- SDK version: 3.88.1
- Environment: Sandbox and Prod
- Browser and OS: Does not seem to be browser/system specific

### Issue description

I can observe multiple logs that seem to be coming from **songbird** like:
```
Base.Message.Init: Init completed slowly
Base.Events: Time boxed event exceeded timeout after [4092]
Base.DF: Device profiling did not complete in [4000]ms
```

According to [this](https://braintree.github.io/braintree-web/current/module-braintree-web_three-d-secure.html#.create) I should be able to do turn off the logs by passing `cardinalSDKConfig: { logging: { level: "off" } }` to the `create` function. So my code looks something similar to this.
```js
        braintreeClient
            .create({
                authorization: braintreeToken,
            })
            .then((clientInstance) => {
                braintreeClientInstance = clientInstance;
                return braintree3DSecureClient.create({
                    version: 2,
                    client: clientInstance,
                    cardinalSDKConfig: {
                        logging: {
                            level: "off"
                        }
                    }
                });
            })
```
But the logs are still there :thinking: Most likely I am missing something.

**Comment by SancSalix** [comment]
I was able to get it turning the logging off with a setup like this. Can you switch to using the authorization parameter instead of the client? If that doesn't work, is the line where you save braintreeClientInstance correct? Should it not have a var in front (for vanilla js)?
```
braintree.threeDSecure.create({
      authorization: clientToken,
      version: '2-inline-iframe',
      cardinalSDKConfig: {
          logging: {
               level: "off"
          }
      }
    })
```

**Comment by hollabaq86** [comment]
Closing this issue since OP hasn't responded.

**Comment by shango420** [comment]
https://github.com/braintree/braintree-web/issues/653#issue-1441693827

**Comment by aderaaij** [comment]
sorry to respond to a closed topic, but i noticed these types aren't in `@types/braintree-web` which makes me wonder if they're up to date or even supported? Thanks for your time
