### ISSUE TITLE
We tried to rollback the libs/dropin but the result is the same.

### ISSUE THREAD

**Issue by hmcmann65** [braintree/braintree-web#656]
We tried to rollback the libs/dropin but the result is the same.

We also tried to provide a callback function and wrap the verifyCard in a Promise and using the resolve() reject() to continue our flow. But also in this case the callback is never called.

```js
return new Promise((resolve, reject) => {
  instance.verifyCard(
    {
      onLookupComplete: function (data, next) {
        console.log("onLookupComplete", data);
        next();
      },
      amount: dsData.amount,
      nonce: dsData.nonce,
      bin: dsData.bin,
      email: dsData.email,
    },
    function (err, payload) {
      console.log("callback", { err, payload });
      if (err) {
        return reject(err);
      }

      return resolve(payload);
    }
  );
})
```

_Originally posted by @hitech95 in https://github.com/braintree/braintree-web/issues/655#issuecomment-1326365358_

**Comment by cgdibble** [comment]
Since this is a continuation of the linked issue, #655, this will be closed as a duplicate. Please keep to the original open issue, thanks.
