### ISSUE TITLE
Make text of the button to remove PayPal configurable

### ISSUE THREAD

**Issue by Rosa** [braintree/braintree-web#66]
Right now the text of the link/button to remove PayPal is hardcoded to `Cancel` in:
```
;t.id="bt-pp-cancel",t.innerHTML="Cancel";
```
This is not very handy when it comes to localising the pages in which that button is shown.

It would be nice to be able to configure it somehow.

**Comment by danielwu426** [comment]
Hi Rosa,

I'm a PM at Braintree focused on our PayPal integration. The request here is a valid one! We likely won't make the text configurable, but will localize it based on the locale passed in during initialization. We've put it on our request backlog and will let you know once we roll this out. 

Cheers,
Dan

**Comment by Rosa** [comment]
Sounds good, thanks so much!

**Comment by danielwu426** [comment]
@Rosa - we made the update to translate "Cancel" when you pass in one of our supported locales. This will be available in the next release of braintree.js We'll keep you posted when that goes out!

**Comment by Rosa** [comment]
That's great! I look forward to the new release, thanks for taking care!

**Comment by danielwu426** [comment]
Hi @Rosa - just an update that our next release is scheduled for next week and will include these changes.

**Comment by Rosa** [comment]
Thanks! :)
