### ISSUE TITLE
Issue with ACH Payments

### ISSUE THREAD

**Issue by robert-asystyou** [braintree/braintree-web#663]
### General information

- SDK version: 3.88.5
- Environment: Sandbox
- Browser and OS: Firefox 107, Arch Linux

### Issue description

I'm trying to accept ACH payments on my site. I've contacted Braintree Support and I have a Merchant Account in our Sandbox with USA Banks enabled. However, whenever I attempt to create an instance of the usBankAccount component, I get an error with the "US_BANK_ACCOUNT_NOT_ENABLED" code.

We have multiple merchant accounts and only one of them has USA Banks enabled. Not sure if that matters.

**Comment by ibooker** [comment]
Hi, 
We'll need more information to troubleshoot this issue, like a sample of your config and code you're using to create the `usBankAccount` component.  Since this is a public forum, you may prefer to provide this to Braintree support instead.

Do you know you've met all the requirements to accept ACH payments? Here's a link to our documentation.

In particular, do you know if the merchant for which you're trying to accept ACH payments is US-based?

**Comment by rawanm900** [comment]
Hhhjj

**Comment by robert-asystyou** [comment]
Here's a snippet of the code that I'm using.

```
braintree.client.create(
{
  authorization: "our_sandbox_api_key",
}, function (clientErr, client) {
   if (clientErr) {
      console.log(clientErr);
      resolve({
          success: false,
          title: "Braintree Error",
          message: "Error connecting to Braintree.",
       });
       return;
     }
     
     braintree.usBankAccount.create(
       { client },
       function (usBankError, usBankInstance: USBankAccount) {
          if (usBankError) {
              // TODO: Handle Error Better.
              console.error(usBankError);
              resolve({
                 success: false,
                 title: "US Bank Error",
                 message: "There was an error with Braintree ACH Processing.",
               });
              return;
          }
          // use useBankInstance to tokenize payment input.
      }
    );
  }
);
```

The error occurs when calling usBankAccount.create. As you can see from the provided screenshot, we have a submerchant account with USA Banks enabled. We were ensured by Braintree that we were ready to accept ACH payments on both our sandbox and production accounts.

![sandbox_merchant_accounts](https://user-images.githubusercontent.com/85708744/209695370-04fe48b5-fa7b-4ddf-ae6c-4e510cbee19f.png)

**Comment by hollabaq86** [comment]
Closing this issue, as this can ultimately only be solved by [Technical Support](https://developer.paypal.com/braintree/help).
