### ISSUE TITLE
Paypal Checkout flow: attributes in received `billingAddress` do not conform to documentation

### ISSUE THREAD

**Issue by fritzgrabo** [braintree/braintree-web#67]
According to the documentation for the client-side integration of the Paypal Checkout flow in https://developers.braintreepayments.com/javascript+ruby/guides/paypal/client-side#options, the billing address received in `onPaymentMethodReceived` should have these attributes:

- city
- countryCode
- line1
- line2
- postalCode
- state

Testing this with a real life Paypal account and a Braintree production (!) environment, it seems like the data-structure of the received billing address is similar to that of the shipping address, which has streetAddress, extendedAddress, etc. attributes:

![onpaymentmethodreceived](https://cloud.githubusercontent.com/assets/592734/9756561/8000bc7c-56db-11e5-8bb5-06ef0de4c2ee.png)

In a sandbox environment though, the data-structure of the received billing address is the same as the one described in the documentation.

Are the docs at err there, or am I missing something?

**Comment by danielwu426** [comment]
Hi,

Thanks for pointing this out. It looks like the PayPal's address keys are being returned in the Sandbox, but should be Braintree's address keys (which are returned in production). We'll do some digging as to why this is the case, and update here when a fix is being pushed.

**Comment by fritzgrabo** [comment]
Awesome - thanks so much for the quick reply, Daniel.

**Comment by danielwu426** [comment]
Fritz - we were unable to repro this issue in Sandbox. Can you provide some additional detail on what integration looks like? Are you using the latest JS? (https://js.braintreegateway.com/v2/braintree.js)

**Comment by fritzgrabo** [comment]
You're right - I can confirm that Sandbox returns the billing address with Braintree's address keys in the latest version 2.12 after upgrading (we were using 2.8 before).

Moreover, it seems like the docs at https://developers.braintreepayments.com/javascript+ruby/guides/paypal/client-side#options have already been updated to reflect this.

Thanks for your support with this, you guys rock! :-)

Closing this issue.
