### ISSUE TITLE
onPaymentMethodReceived not received on Firefox

### ISSUE THREAD

**Issue by Nopik** [braintree/braintree-web#68]
I have integrated my app with Braintree, and it generally works well. My users, however reported that they got stuck sometimes on payment window. I was able to reproduce it on my machine, the issue seem to manifest only on Firefox, but at least 100% of the time. I'm using OS X, my users Windows, so it is not platform dependent. Everything works fine in Chrome. Also, if user goes through payment in Chrome, he is stored into vault and upon subsequent purchase he has his stored payment method ready to use, it works flawlessly even under Firefox.

It is tested on sandbox, with credit card 4242 4242 4242 4242 with expiry 12/16. Also, dropin UI from BT is used.

I was using 2.13.0-beta (due to bug related to single page application initialization stuff which get fixed in that beta), but when I revert to https://js.braintreegateway.com/v2/braintree.js problem persists. 

If you need more info, please let me know.

**Comment by mrak** [comment]
It sounds like you are using Dropin with customer IDs to vault their payment methods.

We seem to be unable to reproduce this with our internal test integrations.

Is it that dropin is rendering as if it were successful, but the `onPaymentMethodReceived` callback is never fired in Firefox?

Are there any console errors?

**Comment by Nopik** [comment]
Yes, I'm using droping+cust ID. UI is rendered correctly, I'm able to enter card details and submit form, then basically nothing happens. No console errors.

**Comment by kyledetella** [comment]
@Nopik would you be able to share some snippets of your code setup? That will help us to better diagnose any issues.

Alternatively, feel free to reach out to support@braintreepayments.com .

**Comment by Nopik** [comment]
So, I'm calling this code (coffeescript):


```
					braintree.setup res.data, "dropin",
						container: "payment-form"
						onPaymentMethodReceived: (info)->

						onReady: (bt)->

						onError: ->
```

with following `res.data`:

```
eyJ2ZXJzaW9uIjoyLCJhdXRob3JpemF0aW9uRmluZ2VycHJpbnQiOiJmZDFkNDNjM2VlNmZlMjU5NGEzZjdhM2Y2YzdjNzlkNDM1Zjk4ZjczMWJhZjAwYzdjNTI2NWZhOWI4ZTc4M2M1fGNyZWF0ZWRfYXQ9MjAxNS0wOS0xNVQxMTozMTowNy41NzI4NzU3MjArMDAwMFx1MDAyNm1lcmNoYW50X2lkPWpmNmdqempidmY0OG0yN25cdTAwMjZwdWJsaWNfa2V5PWh4Nmp3dmhmNHBxeHZnMjgiLCJjb25maWdVcmwiOiJodHRwczovL2FwaS5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tOjQ0My9tZXJjaGFudHMvamY2Z2p6amJ2ZjQ4bTI3bi9jbGllbnRfYXBpL3YxL2NvbmZpZ3VyYXRpb24iLCJjaGFsbGVuZ2VzIjpbXSwiZW52aXJvbm1lbnQiOiJzYW5kYm94IiwiY2xpZW50QXBpVXJsIjoiaHR0cHM6Ly9hcGkuc2FuZGJveC5icmFpbnRyZWVnYXRld2F5LmNvbTo0NDMvbWVyY2hhbnRzL2pmNmdqempidmY0OG0yN24vY2xpZW50X2FwaSIsImFzc2V0c1VybCI6Imh0dHBzOi8vYXNzZXRzLmJyYWludHJlZWdhdGV3YXkuY29tIiwiYXV0aFVybCI6Imh0dHBzOi8vYXV0aC52ZW5tby5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tIiwiYW5hbHl0aWNzIjp7InVybCI6Imh0dHBzOi8vY2xpZW50LWFuYWx5dGljcy5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tIn0sInRocmVlRFNlY3VyZUVuYWJsZWQiOnRydWUsInRocmVlRFNlY3VyZSI6eyJsb29rdXBVcmwiOiJodHRwczovL2FwaS5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tOjQ0My9tZXJjaGFudHMvamY2Z2p6amJ2ZjQ4bTI3bi90aHJlZV9kX3NlY3VyZS9sb29rdXAifSwicGF5cGFsRW5hYmxlZCI6dHJ1ZSwicGF5cGFsIjp7ImRpc3BsYXlOYW1lIjoiVG9LYSIsImNsaWVudElkIjpudWxsLCJwcml2YWN5VXJsIjoiaHR0cDovL2V4YW1wbGUuY29tL3BwIiwidXNlckFncmVlbWVudFVybCI6Imh0dHA6Ly9leGFtcGxlLmNvbS90b3MiLCJiYXNlVXJsIjoiaHR0cHM6Ly9hc3NldHMuYnJhaW50cmVlZ2F0ZXdheS5jb20iLCJhc3NldHNVcmwiOiJodHRwczovL2NoZWNrb3V0LnBheXBhbC5jb20iLCJkaXJlY3RCYXNlVXJsIjpudWxsLCJhbGxvd0h0dHAiOnRydWUsImVudmlyb25tZW50Tm9OZXR3b3JrIjp0cnVlLCJlbnZpcm9ubWVudCI6Im9mZmxpbmUiLCJ1bnZldHRlZE1lcmNoYW50IjpmYWxzZSwiYnJhaW50cmVlQ2xpZW50SWQiOiJtYXN0ZXJjbGllbnQzIiwiYmlsbGluZ0FncmVlbWVudHNFbmFibGVkIjpudWxsLCJtZXJjaGFudEFjY291bnRJZCI6InRva2EiLCJjdXJyZW5jeUlzb0NvZGUiOiJFVVIifSwiY29pbmJhc2VFbmFibGVkIjpmYWxzZSwibWVyY2hhbnRJZCI6ImpmNmdqempidmY0OG0yN24iLCJ2ZW5tbyI6Im9mZiJ9
```

And `onReady` is called, but no `onError` nor `onPaymentMethodReceived`.

**Comment by Nopik** [comment]
Ok, just found another bit. Namely, after form is submitted, I'm hiding dropin (since it starts to display payment info, which makes no sense during transaction processing), and that apparently makes things go south. I.e. if I disabled the dropin hide, it worked.

The form elements is hidden by css (`display: none !important`), not removed from DOM:
![image](https://cloud.githubusercontent.com/assets/554841/9875611/a7bb4baa-5baf-11e5-8e7a-721a9f766366.png)

**Comment by mrak** [comment]
Thanks for the additional information @Nopik.

We wait for transition events to complete before sending over payment information. If the form is hidden, these transition events do not fire in some browsers, leading to your dropped state.

Your use case is valid, but we will not be changing this behavior. We've added your feedback to our consideration list for future SDK version, though.

Although we do not support the hiding of dropin, you could try absolutely positioning dropin off-screen, or seeing if `visibility: hidden` instead of `display: none` does the job.
