### ISSUE TITLE
Dependency on terser is unnecessary

### ISSUE THREAD

**Issue by adam-h** [braintree/braintree-web#680]
https://github.com/braintree/braintree-web/commit/93fb677e1681d2e701cadf080b2983b513798a5d added `terser` as a direct dependency in `package.json`.

As it's not used by this library when published, can it be moved to `devDependencies`?

**Comment by hollabaq86** [comment]
👋 @adam-h thanks for reaching out and spotting this 🙃 we'll fix this up!

For internal tracking, issue 8204

**Comment by hollabaq86** [comment]
@adam-h this is fixed in v[3.92.2](https://github.com/braintree/braintree-web/blob/main/CHANGELOG.md#3922)! Thanks again for the issue.

**Comment by adam-h** [comment]
Thank you! :)
