### ISSUE TITLE
npm versioning

### ISSUE THREAD

**Issue by 719media** [braintree/braintree-web#685]
### General information

- SDK version: 3.95.0

### Issue description

Your beta/alpha versions you are publishing to npm do not follow semver, and therefore show up incorrectly when running commands like `npm outdated`. In my opinion, it would be nice if this pattern was not followed for future to avoid confusion over updates.

For example

```
$ npm outdated
Package        Current  Wanted                  Latest  Location                    Depended by
braintree-web   3.95.0  3.95.0  3.95.0-connect-alpha.5  node_modules/braintree-web  some-project
```

**Comment by hollabaq86** [comment]
👋 @719media thanks for reaching out, and sorry about that incorrect tagging on npm. We're working on updating our release process to ensure we're not incorrectly tagging test versions with the latest tag.

Npm is currently up to date with the latest tagged version being 3.96.0.
