### ISSUE TITLE
Braintree Web and PayPal functionality compilation error suddenly

### ISSUE THREAD

**Issue by Naveed1842** [braintree/braintree-web#693]
### General information

- SDK version:     "@types/braintree-web": "^3.62.2",     "braintree-web": "^3.67.0",
- Environment: Sandbox 
- Browser and OS: Compilation error 

### Issue description

**Problem:**

I am facing compilation errors in my application while working with AWS SDK's CustomerProfiles module and integrating Braintree Web and PayPal functionality. The TypeScript compiler is showing errors related to incompatible types and missing exported members.

**Error Details:**

1. Error message in AWS SDK usage:
   ```typescript
   Error: src/app/views/pages/appointment/book-appointment/book-appointment.component.ts:10:10 - error TS2724: '"aws-sdk/clients/customerprofiles"' has no exported member named 'string0To1000'. Did you mean 'string1To1000'?
   ```
   
2. Error message in Braintree Web and PayPal integration:
   ```typescript
   Error: src/app/views/pages/payment-method/side-panel-add-payment-method/add-payment-method-side.component.ts:90:17 - error TS2322: Type '"vault"' is not assignable to type 'FlowType'.
   ```
   

**Expected Behavior:**

I expect the AWS SDK's CustomerProfiles module to function without errors and the integration of Braintree Web and PayPal to work seamlessly without TypeScript compilation errors.

### Steps to Reproduce:
It just break today yesterday it was working fine. Could you please confirm any change from sever side. I am using these cdn inside our index.html 

		<script src="https://js.braintreegateway.com/web/3.90.0/js/client.min.js"></script>
		<script src="https://js.braintreegateway.com/web/3.90.0/js/paypal-checkout.min.js"></script>

### Additional Information:

- Are you using any specific AWS SDK version or configurations?  No 
- Have you checked for any updates or changes in the libraries that might be causing the issue? No 
- Are there any relevant logs or console outputs? 

### Screenshots or Code Snippets:

![image](https://github.com/braintree/braintree-web/assets/22956528/1c4c9f20-bc79-4ba2-b72f-8e9a00dbb84d)

---
.

**Comment by jplukarski** [comment]
Hello @Naveed1842 ,

Thank you for using the Braintree-web SDK. We do not own the AWS SDK, so you will have to reach out to the owners of that for your issues using their `CustomerProfiles` module.

Additionally, we do not officially support typescript. The typing library you are using (`"@types/braintree-web": "^3.62.2",`) was written by a third-party. You will have to reach out to that entity for any issues.
