### ISSUE TITLE
3.91.0 use paylater throw error paylater is not eligible

### ISSUE THREAD

**Issue by jinrichardJIN** [braintree/braintree-web#696]
### General information

- SDK version: 
- Environment: Sandbox
- Browser and OS 

### Issue description
when i use braintree-web sdk init my paypal with paylater mode
throw error error paylater is not eligible

**Comment by jinrichardJIN** [comment]
![image](https://github.com/braintree/braintree-web/assets/20592013/edaf5023-e2e2-4516-af88-9077e9c1a2a2)
this is js snippets in https://www.paypal.com/sdk/js?components=buttons

**Comment by jplukarski** [comment]
Hey @jinrichardJIN , please see out documentation for [PayPal Pay Later Availability](https://developer.paypal.com/braintree/articles/guides/payment-methods/paypal-pay-later-offers#availability) to ensure you have met all the requirements.

Additionally, you can reach out to [our support team](https://developer.paypal.com/braintree/help) regarding questions on your account and what payment methods you are eligible for.
