### ISSUE TITLE
Drop-In "Card Number" field with Android FireFox 34.0

### ISSUE THREAD

**Issue by CheapData** [braintree/braintree-web#7]
Steeps to reproduce: 
1. Enter “Card Number” value
2. Try to change digits and entered value will be selected

It is not possible to change separate digits. The only option is to delete CC number and retype it.

**Comment by kyledetella** [comment]
@CheapData as mentioned in #8, this has been addressed in `v2.5.3`

**Comment by CheapData** [comment]
The same functionality persists in v2.5.3. I gues it is more likely FireFox for Android native behavier than a bug.
