### ISSUE TITLE
Safari don't show Google Pay button from time to time

### ISSUE THREAD

**Issue by CyrilKrylatov** [braintree/braintree-web#700]
### General information

- SDK version: ^3.97.2
- Environment: Sandbox
- Browser and OS Version: Safari 17.0 (18616.1.27.111.22, 18616) on macOS 13.4 (22F66)

### Issue description

Hello,

I'm encountering an issue with `braintree-web/google-payment` when using Safari. Occasionally, Safari seems to halt the execution of my script without throwing any errors; it simply stops.

You can review my Stimulus component at [this link](https://gist.github.com/CyrilKrylatov/a0c07c5b201fcdb47bb95048cf88f87f)

At [line 41](https://gist.github.com/CyrilKrylatov/a0c07c5b201fcdb47bb95048cf88f87f#file-google-pay_controller-js-L41), there's a `console.log()`. It appears that this is the point where Safari stops processing and doesn't proceed further.

I'm puzzled by this behavior. On refreshing my browser once, the Google Pay button appears. However, upon subsequent refreshes, it sometimes doesn't show up.

Are you aware of any known issues or limitations concerning Safari and the Google Pay button?

Thank you for your assistance. 

Have a great day!

**Comment by jplukarski** [comment]
Hey @CyrilKrylatov , thanks for writing in! I am not able to reproduce this in my own test app, and there are not any limitations with Google Pay and Safari to our knowledge.

I think this question is better suited for our support team, who can help you troubleshoot your integration. You can write in to our support team here -> https://developer.paypal.com/braintree/help

**Comment by CyrilKrylatov** [comment]
Thank you for your answer ; I'll contact them today.

Cheers and have a nice one!
