### ISSUE TITLE
Hosted fields assets 404.

### ISSUE THREAD

**Issue by jexodusmercado** [braintree/braintree-web#705]
### General information

- SDK version: 3.96.0
- Environment: Sandbox
- Browser and OS Firefox 115.0 - Linux

### Issue description

I am experiencing a 404 error with the braintree assets when loading the hosted fields.

Upon investigating, I noticed that I am fetching the html file from **https://assets.braintreegateway.com/web/3.98.0/html/hosted-fields-frame.min.html** which does not yet exist.

I tried to change my braintree-web version however no avail.

Any advice?

**Comment by jexodusmercado** [comment]
Solve. 

My bad. I have my package.json like this 

```
    "braintree-web": "^3.96.0",
```

instead of this

```
    "braintree-web": "3.96.0",
```

**Comment by BenAkroyd** [comment]
We had the same issue, but we were trying to update to SDK version: 3.98.0

**Comment by jasongrishkoff** [comment]
Having the same issue right now with `braintree-web: ^3.98.0`
