### ISSUE TITLE
Upgrading to 3.98.0 hosted fields

### ISSUE THREAD

**Issue by gregh3269** [braintree/braintree-web#706]
### General information

- SDK version: 3.98.0
- Environment:  Sandbox 
- Browser and OS : ff 121.0b9 (64-bit) on Rocky Linux 8

I have tried to upgrade to 3.98.0 from 3.97.4 and I get this 404 error on each of my hosted fields

`https://assets.braintreegateway.com/web/3.98.0/html/hosted-fields-frame.min.html#27f77eec-f2fb-442c-8c3c-d31a411b7db2`

```
Object { name: "BraintreeError", code: "HOSTED_FIELDS_TIMEOUT", message: "Hosted Fields timed out when attempting to set up.", type: "UNKNOWN", details: undefined, stack: "" }
​
code: "HOSTED_FIELDS_TIMEOUT"
​
details: undefined
​message: "Hosted Fields timed out when attempting to set up."
​name: "BraintreeError"
​stack: ""
​type: "UNKNOWN"
​<prototype>: Object { constructor: r(e), stack: "" }
myForm.xxx:325:13
    <anonymous> Ember
    deferred https://js.braintreegateway.com/web/3.98.0/js/hosted-fields.min.js:1
    (Async: setTimeout handler)
    deferred https://js.braintreegateway.com/web/3.98.0/js/hosted-fields.min.js:1
    once https://js.braintreegateway.com/web/3.98.0/js/hosted-fields.min.js:1
    promiseOrCallback https://js.braintreegateway.com/web/3.98.0/js/hosted-fields.min.js:1
    (Async: promise callback)
    promiseOrCallback https://js.braintreegateway.com/web/3.98.0/js/hosted-fields.min.js:1
    a https://js.braintreegateway.com/web/3.98.0/js/hosted-fields.min.js:1
    <anonymous> Ember
    deferred https://js.braintreegateway.com/web/3.98.0/js/client.min.js:1
    (Async: setTimeout handler)
    deferred https://js.braintreegateway.com/web/3.98.0/js/client.min.js:1
    once https://js.braintreegateway.com/web/3.98.0/js/client.min.js:1
    promiseOrCallback https://js.braintreegateway.com/web/3.98.0/js/client.min.js:1
    (Async: promise callback)
    promiseOrCallback https://js.braintreegateway.com/web/3.98.0/js/client.min.js:1
    s https://js.braintreegateway.com/web/3.98.0/js/client.min.js:1
    <anonymous> Ember
    jQuery 13
```

Is there anything we need to do for the upgrade?  If so are there any upgrade instructions?

**Comment by bordeux** [comment]
We are having this same issue. Looks like Braintree team removed important assets from theirs servers
https://assets.braintreegateway.com/web/3.98.0/html/hosted-fields-frame.min.html

We decided to downgrade back to v3.97

**Comment by osahyoun** [comment]
We're getting the same issue but in production (live)

**Comment by yeseniamolinab** [comment]
We are experiencing the same issue with 3.98.0 in Production

**Comment by gguerini** [comment]
Same here. 

### works - 3.97.4
https://assets.braintreegateway.com/web/3.97.4/html/hosted-fields-frame.min.html

### doesn't work - 3.97.4 - 404 status code
https://assets.braintreegateway.com/web/3.98.0/html/hosted-fields-frame.min.html

**Comment by hollabaq86** [comment]
👋 folks, there was an issue with our CDN that we're informed should be resolved. If you continue to encounter 404s when trying to access a hosted asset from the assets.braintreegateway.com URL, please [contact Technical Support](https://developer.paypal.com/braintree/help/).
