### ISSUE TITLE
Support for text-fill-color styling in autofill styles

### ISSUE THREAD

**Issue by jaikiratsingh** [braintree/braintree-web#708]
### General information

- SDK version: 3.97.2
- Environment: Sandbox and Production
- Browser and OS Version 120.0.6099.216 (Official Build) (arm64) on Mac OS 14.2.1

### Issue description

An extension of https://github.com/braintree/braintree-web/issues/559
Can we get support for -webkit-text-fill-color field as well to help style the text color for autofill for webkit browsers ?

**Comment by hollabaq86** [comment]
👋 thanks for reaching out! I've gone ahead and forwarded your request on to our PM to see if it's something we can/should prioritize. I can't guarantee we'll add this or if we do, what the ETA would be on support for this field being released. 

If it's something that's really important to you, you are absolutely welcome to submit a PR adding support.
