### ISSUE TITLE
patch_payment_resource returns generic 422 on second request

### ISSUE THREAD

**Issue by VShredJeffCampbell** [braintree/braintree-web#709]
### General information

- SDK version:  3.100
- Environment: Sandbox (maybe prod too)
- Browser and OS: All

### Issue description

I made a post on the Paypal community that I would like to repost here:

https://www.paypal-community.com/t5/REST-APIs/patch-payment-resource-returns-generic-422-on-second-request/m-p/3132423#M9197

**Comment by jplukarski** [comment]
@VShredJeffCampbell Please [open up a ticket with our Support team](https://developer.paypal.com/braintree/help) for this request. Thanks
