### ISSUE TITLE
Paypal onCancelled not called

### ISSUE THREAD

**Issue by b-hobbs** [braintree/braintree-web#71]
After switching to braintree-web the paypal onCancelled event doesn't seem to be called anymore. I'm using hosted fields.

                    paypal: {
                        container: "paypal-button",
                        onSuccess: function() {
                            console.log('PAYPAL SUCCESS');
                            $('#credit-card-form').hide();
                        },
                        onCancelled: function() {
                            console.log('PAYPAL CANCELLED');
                            $('#credit-card-form').show();
                        }
                    }

**Comment by EvanHahn** [comment]
This is a bug—good catch! We'll look into this and get back to you soon.

**Comment by EvanHahn** [comment]
@b-hobbs We've just deployed `2.14.2` which should fix this issue.

Let us know if you're still experiencing problems!

**Comment by b-hobbs** [comment]
Works now! Thanks.

**Comment by vijaykumar-krishnaswamy** [comment]
I am still having issues with the onCancelled not being called. This is what we are doing. 

including the braintree library as follows:

 <script src="//js.braintreegateway.com/v2/braintree.js"></script>

And we are using paypal custom integration as 


braintree.setup(clientToken, "paypal", {
            container: this.paypalContainerId,
            singleUse: false,
            onPaymentMethodReceived: function (obj) {
                this.setPayPalPaymentInfo(obj);
                this.expandPayPal();
            }.bind(this),
            onUnsupported: function(){
                this.setPayPalPaymentInfo(null);
                this.collapsePayPal();
            }.bind(this),
            onCancelled: function(){
                this.setPayPalPaymentInfo(null);
                this.collapsePayPal();
            }.bind(this)
        });

I can verify that the onPaymentMethodReceived is being called. But the onCancelled method is not called anymore. 

Any help is appreciated. Thanks!.

**Comment by EvanHahn** [comment]
Take a look at #89 if you're still having problems.
