### ISSUE TITLE
Error attempting to convert camel to snake of a null value.

### ISSUE THREAD

**Issue by rrehbein** [braintree/braintree-web#724]
### General information

- SDK version: 3.107.1
- Environment: Sandbox
- Browser and OS: Firefox 130

### Issue description

With Kount enabled, data collector is failing with an error "can't convert null to object".

It appears to be an issue due to `typeof null` is "object" which then follows down the wrong path of lib/camel-case-to-snake-case.js

**Comment by jseaber** [comment]
Confirmed; we've rolled back to 3.106.0 for now.

**Comment by braintreeps** [comment]
Fix in version 3.112.0: https://github.com/braintree/braintree-web/releases/tag/3.112.0
