### ISSUE TITLE
Incompatible Versions - Client vs 3D Secure

### ISSUE THREAD

**Issue by chrisbeldam** [braintree/braintree-web#725]
### General information

- SDK version: Braintree Web (3.107.1), @paypal/react-paypal-js (8.6.0), @google-pay/button-react (3.1.0)
- Environment: Sandbox
- Browser and OS: Chrome 128.0.6613.121 (64-bit) on MacOS 14.6.1

### Issue description

I'm upgrading versions of Braintree-Web (and other payment packages) from 3.84.0 to the latest. However when I toggle between payment methods I'm consistently getting back the following: "Client (version 3.84.0) and 3D Secure (version 3.107.1) components must be from the same SDK version.". However I do not see anything in my code which specifies 3.84.0?

Is this a known bug? The documentation does not make it clear to me what Client is and where I would find this.

<img width="1096" alt="Screenshot 2024-09-13 at 11 33 47" src="https://github.com/user-attachments/assets/79a181c3-098e-44a0-954e-b21b0bce6257">

**Comment by chrisbeldam** [comment]
I have downgraded versions to 3.92.1 and have logged out the braintree version we the application is creating the hostedFields. It is using 3.92.1 yet I am still getting the`incompatible versions error`

<img width="1126" alt="Screenshot 2024-09-13 at 11 51 48" src="https://github.com/user-attachments/assets/19835386-2b66-4a1e-8e45-b0a9a33bad2c">

**Comment by chrisbeldam** [comment]
This was caused due to React-Paypal-JS

**Comment by shahfaizanali** [comment]
@chrisbeldam how did you solve?
