### ISSUE TITLE
`country_code_alpha2` is not properly handled

### ISSUE THREAD

**Issue by Rosa** [braintree/braintree-web#74]
We have noticed a problem with the last JS code when trying to use a `country_code_alpha2` field. In the `normalizeCreditCardFields` function you do the following:

```js
var e, n = {
    billingAddress: t.billingAddress || {}
};
for (e in t)
    if (t.hasOwnProperty(e)) switch (e.replace(/_/, "").toLowerCase()) {
        case "postalcode":
        case "countryname":
        case "countrycodenumeric":
        case "countrycodealpha2":
        case "countrycodealpha3":
        case "region":
        case "extendedaddress":
        case "locality":
        case "firstname":
        case "lastname":
        case "company":
        case "streetaddress":
            n.billingAddress[e] = t[e];
            break;
        default:
            n[e] = t[e]
    }
    return n
```

When `e` is `countrycode_alpha2`, `e.replace(/_/, "").toLowerCase()` results in `countrycode_alpha2` because only the first `_` is replaced, and instead of being part of the `n.billingAddress` object, `country_code_alpha2` ends up being part of the `n` (credit card) object, which makes the tokenize method to fail (and obviously the value wouldn't get properly sent either).

You could perhaps fix this with `e.replace(/_/g, "").toLowerCase()`, so that all occurrences of `_` are replaced.

**Comment by EvanHahn** [comment]
@Rosa Looking into this now!

**Comment by EvanHahn** [comment]
@Rosa This looked like a legitimate issue—thanks for bringing it to our attention! We will have this fixed soon and we'll keep you updated.

**Comment by Rosa** [comment]
That's great! Thanks so much for looking into it :smile:

**Comment by lilaconlee** [comment]
@Rosa This bug has been fixed in our latest release. Thanks for reporting it!

**Comment by Rosa** [comment]
Thanks for fixing it! :)

**Comment by Rosa** [comment]
Just one quick question: do you know when the fix will be available in `https://js.braintreegateway.com/v2/braintree.js`? Thanks!

**Comment by EvanHahn** [comment]
@Rosa That file will likely be updated next week. In the meantime, you can use npm, Bower, or use `https://js.braintreegateway.com/js/braintree-2.14.3.min.js`.

**Comment by Rosa** [comment]
:+1: perfect, thanks!

**Comment by kyledetella** [comment]
@Rosa our latest `braintree.js` hotlink now points to `2.14.4` so you can use `https://js.braintreegateway.com/v2/braintree.js`

**Comment by Rosa** [comment]
Thanks for the heads up! :)
