### ISSUE TITLE
Hosted Fields: cannot use PayPal after gateway error.

### ISSUE THREAD

**Issue by RikdeBoer** [braintree/braintree-web#78]
First the good news: after UX problems with the drop-in, we switched to Hosted Fields. And we were able to create a checkout page with a payment form whereby credit card details do *not* get auto-erased after an error occurs in the gateway backend. Yay!

The shopper is thus given the opportunity to *correct* existing field content (be it order amount, or payment details), rather than having to fill out any fields from scratch. Double Yay!

They then press "Place order" for a second time and a *new* nonce gets generated and the order goes through. And all this without calling teardown(). Triple Yay!

<img width="1060" alt="bthf error" src="https://cloud.githubusercontent.com/assets/4031225/10154810/623cabfe-66af-11e5-95e3-295abd51e149.png">

Now the bad news. If the PayPal button is used after the backend error occurred, then we receive in the callback the same nonce again. As we all know, this will violate backend rules upon submission.   :-(

But it gets worse. In an attempt to alleviate this situation the javascript we wrote detects that the same nonce was passed into the callback. It then uses the teardown() to destroy and re-initialise the setup. Which is what happens.

But guess what? When the form is submitted again using the PayPal button, *after* teardown() and subsequent call to setup(), we still keep receiving the same nonce in the callback!
In the above scenario we do not pass a customerId. Even if we did want to use the Vault and pass a customerID, then the above would still happen for first-time visitors, as their customerID will not be valid/generated until a successful sale() has occurred. Or am I mistaken?

We are using braintree.js v2.14.2 from this git repository.

**Comment by burnto** [comment]
@RikdeBoer thanks. We'll attempt to reproduce this issue tomorrow and will follow up then.

**Comment by RikdeBoer** [comment]
Thank you. For the record. When we *do* pass a valid customerId when generating the clientToken and when invoking sale() in the backend, we get exactly the same behaviour. 
The shopper can only press PayPal once. If the order then goes through, then everybody happy.
But if there is a transaction error of any kind, then pressing PayPal a second time will result in the same nonce, no matter whether teardown()+setup() is called or not.

**Comment by lilaconlee** [comment]
So far, we’ve had some trouble replicating this issue.

From what I understand, this is the flow that trips your integration into a bad state:
	- Enter credit card with bad CVV
	- Submit our form which invokes the callback
	- Post transaction via AJAX, which fails
	- Click PayPal button and complete flow
	- Submit form and a new nonce is generated for PayPal

It sounds like this last step is where things broke down for you. Could you verify that this is the flow we should be testing? Would you be willing to provide some code snippets to give us some further insight into your integration?

**Comment by RikdeBoer** [comment]
@lilaconlee 
Yes that is it, except in our setup that last step produces the previous nonce again.

Yes, happy to provide code snippets. Or even a test site. Give us a few hours.

**Comment by RikdeBoer** [comment]
@lilaconlee @burnto 
I've created a test-site for you to have a look at and sent URL and login credentials to support@braintreepayments.com

**Comment by lilaconlee** [comment]
It looks like the issue lies in your method for checking a new nonce. We also use the hidden input `payment_method_nonce` that you're using, but we update it when the new nonce is generated.  When I changed `hiddenInput.name = hiddenInput.id = 'payment_method_nonce'` to  `hiddenInput.name = hiddenInput.id = 'previous_payment_method_nonce'`, I received a new nonce and my transaction was successful. 

Hope this works for you!

**Comment by RikdeBoer** [comment]
*Sensational* bug-fixing @lilaconlee !
That was it indeed.  We now have a near-perfect workflow. Thank you so much!

May I make a suggestion for the documentation? When one reads it, it's almost like the use of 'payment_method_nonce' is essential for the correct operation of the plug-in, when in reality it is the opposite. The developer may use any name *except* 'payment_method_nonce'.

**Comment by RikdeBoer** [comment]
The final little quibble is this special case: 

1) Shopper presses PayPal and fills out email address and password.
2) Shopper presses "Place order"
3) Payment gets rejected by backend. Could be "insufficient funds" or whatever.
4) Shopper corrects order amount, but does not press "Cancel" on the existing PayPal selection, as it is still the correct account to use, so why enter it again?
5) Shopper presses "Place order" for the second time.
6) Same nonce gets generated. Cannot proceed.

The same scenario *does* work, if a credit card is used twice in succession without any of its details changed by the shopper after a gateway error.

Thanks so much for all your work on Hosted Fields!

**Comment by lilaconlee** [comment]
@RikdeBoer You're right, it looks like a new nonce isn't generated when you follow those steps. I'd recommend using teardown in this case.

**Comment by RikdeBoer** [comment]
Thanks @lilaconlee. Will do that as a workaround. Seems a little strange that the same scenario does work for credit cards.
Thanks again for picking up that we must not use 'payment_method_nonce' for the name of the hidden field.

**Comment by jsanchez034** [comment]
Hi @burnto, is there a long term fix in mind for the stale nonce issue when paying with Paypal and a gateway error happens?  I'm using the teardown then setup workaround but was wondering if a proper fix will coming in future releases.

**Comment by lilaconlee** [comment]
@jsanchez034 This problem should only pertain to v2 of our JS SDK, which we now only support with major bugfixes. We recommend upgrading to [version 3](https://developers.braintreepayments.com/guides/client-sdk/migration/javascript/v3#paypal) where this is not an issue.

**Comment by jsanchez034** [comment]
@lilaconlee, ok thank you!
