### ISSUE TITLE
Vault behaviour: automatically set the last (rather than first) used payment method as the default

### ISSUE THREAD

**Issue by RikdeBoer** [braintree/braintree-web#79]
This feature request applies to both the drop-in and Hosted Fields. It may already be available, I couldn't find it.

From my limited knowledge, it appears that the default payment method shown in the drop-in UI and used by sale() is and always will be the first one created for that customerID.

This means that when a shopper develops a preference to use their second or third payment method, they will always have to hit "Change payment method" on the drop-in. Their selection does not "stick" and carry over to their next visit.  

I feel it would be more natural to most shoppers to automatically set as the new default, the payment method last used by that customerID.

Is there an option for this? If not, can we have one? 

If we can't have one, how would we go about coding this (thinking particularly about Hosted Fields)? How do we change the default payment method via a JS or PHP code snippet?

**Comment by mickeyreiss** [comment]
Hi @RikdeBoer,

Unfortunately, this is a known issue. The default payment method used by `Transaction.sale` is not respected when rendering a customer's vaulted payment methods in Drop in.

See also very similar issues with some suggested workarounds: #5 and #76, as well as the corresponding [iOS](https://github.com/braintree/braintree_ios/issues/146 ) and [Android](https://github.com/braintree/braintree_android/issues/23) manifestations of the problem. (All three platforms rely on the same internal API endpoint to populate Drop-in UI.)

This is great feedback! Thank you for sharing, and we hope to address it soon more fundamentally.

***

In the case of hosted fields on the web, my recommendation would be to drive the payment method selection process from your server just a little bit more:

* You can manage the default payment method using [`makeDefault`](https://developers.braintreepayments.com/javascript+php/reference/request/payment-method/update#options.make_default);
* render the list of payment methods with [`paymentMethods`](https://developers.braintreepayments.com/javascript+php/reference/response/customer#payment_methods);
* pass the references between your client and your server by whatever means makes the most sense in your integration (e.g. payment method token, your own notion of a payment method id, an integer sequence number)

Unfortunately, I do not have a good recommendation for you if you'd like to display Drop-in in your repeat purchase flow. The ordering of payment methods is simply not configurable right now. (For reference, the ordering is based on "most recently used + added"; however `isDefault` is not respected.)

***

I hope this helps. Please let us know if you have any more questions! :smile:

**Comment by RikdeBoer** [comment]
@mickeyreiss Thanks for the pointers. I shall make use of these to try and put something together using Hosted Fields.
