### ISSUE TITLE
Drop-In "Card Number" field with Android 4.1.2 native internet browser

### ISSUE THREAD

**Issue by CheapData** [braintree/braintree-web#8]
Steeps to reproduce: 
1. Enter “Card Number” value (result: 4111 1111 1111 1111)
2. Try to delete some digits and only 4 last digits will be deleted (result: 4111 1111 1111)
3. Goto "MM / YY" and back to “Card Number”, 4 more digits may be deleted

**Comment by kyledetella** [comment]
@CheapData this issue is fixed with the latest release (`v2.5.3`)

**Comment by CheapData** [comment]
Confirmed
