### ISSUE TITLE
Expiration Date input - only numeric keyboard on iOS

### ISSUE THREAD

**Issue by rbsmidt** [braintree/braintree-web#81]
I'm working on a project, where we use Braintree Hosted Fields for our checkout flow. It's a neat service, and we're excited about the freedom it gives us, when designing the checkout flow.

However i just discovered what seems to be a bug:

On mobile (at least iOS 9, haven't had the opportunity to test it on other OS/Devices yet) when expiration date input is in focus, it presents the user with only a numeric keyboard. This means that the user won't be able to enter the required slash between month and year!
As i recall i read somewhere in another issue, that you don't support dropdown for expiration year and month (yet). What is the best way to make the expiration date input work on mobile?

Best regards,
Rasmus

**Comment by lilaconlee** [comment]
@rbsmidt While you don't need the slash to make a successful transaction, we understand that it isn't ideal from a UX perspective. We've definitely got a fix for this issue on our roadmap. One way to avoid this in the meantime is to split the month and year into two separate fields using `expirationMonth` and `expirationYear`.

**Comment by mrak** [comment]
Closing this, as there is a fully-supported workaround (`expirationMonth`/`expirationYear`). 

In the future we may support first-class input formatting or dropdowns, but until then this is a known UX blemish.
