### ISSUE TITLE
doubts about JS tokenizeCard() json attributes

### ISSUE THREAD

**Issue by tavo** [braintree/braintree-web#82]
Hi guys,

We are working on adding the Address Verification System (AVS), and we would like to see the complete schema of the **JS braintree.api.Client - tokenizeCard() json**

on the documentation we found this example: 
```javascript
var client = new braintree.api.Client({clientToken: "CLIENT-TOKEN-FROM-SERVER"});
client.tokenizeCard({
  number: "4111111111111111",
  cardholderName: "John Smith",
  // You can use either expirationDate
  expirationDate: "10/20",
  // or expirationMonth and expirationYear
  expirationMonth: "10",
  expirationYear: "2015",
  // CVV if required
  cvv: "832",
  // Address if AVS is on
  billingAddress: {
    postalCode: "94107"
  }
}, function (err, nonce) {
  // Send nonce to your server
});
```

But we want to know if there are other set of attributes that we could send in order to cover the most validations as possible or if im missing something on the documentation..

Thanks!

**Comment by EvanHahn** [comment]
The `onCancelled` callback is called when the "Cancel" button is clicked _after_ a customer goes through the PayPal login. In other words, it's called when you click this button:

![Screenshot](https://cloud.githubusercontent.com/assets/777712/10498325/b0ce3216-727f-11e5-8d3a-137ee4636105.png)

Does that help?

**Comment by EvanHahn** [comment]
You've got most of them there; the main ones missing are in `billingAddress`. You can find a full list of supported properties [here](https://developers.braintreepayments.com/javascript+node/reference/request/credit-card/create).

Hope that helps!
