### ISSUE TITLE
onCancelled is not called

### ISSUE THREAD

**Issue by Paratron** [braintree/braintree-web#83]
Hey,
I want to catch cases where the customer closes the paypal popup without logging in or authenticating the payment but it appears that the `onCancelled` callback is never called.

This is my setup code:

````
braintree.setup('CLIENT_TOKEN', 'paypal', {
	container: 'paypal-container',
	singleUse: false,
	locale: 'en_US',
	enableShippingAddress: false,
	onPaymentMethodReceived: function (obj) {
		processOrder(obj.nonce);
	},
	onUnsupported: function () {
		console.log('unsupported');
	},
	onCancelled: function () {
		console.log('cancelled');
	}
});
````

When the popup window is closed by clicking on the "X", the `onCancelled` callback is not called, but the dark shade does vanish so I assume that the javascript library is at least somehow notified that the window has been closed.

I tested this in the recent chrome and firefox on win7.

**Comment by EvanHahn** [comment]
The `onCancelled` callback is called when the "Cancel" button is clicked _after_ a customer goes through the PayPal login. In other words, it's called when you click this button:

![Screenshot](https://cloud.githubusercontent.com/assets/777712/10498325/b0ce3216-727f-11e5-8d3a-137ee4636105.png)

Does that help?

**Comment by Paratron** [comment]
Sadly not. How can I catch the case when the user simply closes the popup? Imho, this should also trigger the `onCancelled` callback.

**Comment by EvanHahn** [comment]
We'll take this into consideration; this type of feedback is really helpful for us as we prioritize future work. Until then, sadly, we don't have this feature and it's not on our roadmap.

**Comment by Paratron** [comment]
Well, I'd clearly define that as a bug, not a feature, but well - its your decision. I hope you will at least arrange to get the docs updated that `onCancelled` is only called if the paypal flow is cancelled on a special way (by clicking the cancel button) and not in any case.

It would also be a good practice to not close this ticket but leave it open and tag it as "feature request" so other users can still see it and comment on it and express interest. If the feature gets implemented or is refused, the ticket is closed - at least thats the common practice in other open source projects here on github.

And at last but not least - a workaround I implemented to replace the broken `onCancelled` callback that will fire in any case when the paypal popup has been closed, in case anybode else is affected by this bug and needs to know if a user has cancelled the auth flow:

```javascript
//Make sure to set this to true in your onPaymentMethodReceived callback.
var paypalFinished = false;

var overlayOpen = null;
var paypalWait = setInterval(function () {
	if ($('.bt-overlay').length) {
		overlayOpen = true;
	} else {
		if(overlayOpen === null){
			return;
		}
		clearInterval(paypalWait);
		
		if(!paypalFinished){
			console.log('Popup closed before finished!');
		}
	}
}, 500);

Its not that pretty, relying on an interval - I know, but I don't see another way to solve this right now.

**Comment by EvanHahn** [comment]
We've updated [our docs](https://developers.braintreepayments.com/guides/paypal/client-side/javascript/v2#options) to make things a little clearer—thanks for the feedback.

We're going to keep this ticket closed, but the whole JavaScript team takes a look at all of these issues. We'll keep this in mind.

**Comment by JoniSykes** [comment]
Did anything ever get implemented regarding this?
Docs are still unclear. They imply that I can close the popup and still fire the onCancelled function which is not the case.

**Comment by danielwu426** [comment]
Hi @JoniSykes ,

Looks like we missed that section - we'll update the docs accordingly and update here when done.

**Comment by psergus** [comment]
I am :+1:  to fix this issue.

**Comment by MCProhosting-Matt** [comment]
+1 for calling this when closing the popup

**Comment by Antariano** [comment]
+1 this is needed. @MCProhosting-Matt did not tell me to comment here.

**Comment by crookedneighbor** [comment]
The documentation has been updated to make clear what the `onCancelled` callback refers to. https://developers.braintreepayments.com/guides/paypal/client-side/javascript/v2#options

**Comment by psergus** [comment]
@crookedneighbor we already know what this function does. We just need a new feature to make our customers experience complete and better.

**Comment by Paratron** [comment]
+1 for that comment - its not that we need the documentation to be updated, but its _necessary_ that the underlying application will be notified if the user cancels the paypal payment process in _any_ way so it can react on that.

@crookedneighbor I do not understand why you rather go ahead and update the docs instead of making a small change to the codebase of the library. The library already observes if the popup is being closed because the overlay that darkens the website in the main window will be hidden when the popup is closed. So why not simply call the onCancelled callback when that is being done as well?

**Comment by Antariano** [comment]
if @crookedneighbor would like us to create a new issue specifically about the feature we'd like to see, we can do that. But it's kind of absurd that this isn't a feature already.

**Comment by rturumella** [comment]
That use case does make sense. We'll consider adding the callback in a future release, but we can't give a timeline. It likely will not be soon.

**Comment by Paratron** [comment]
All of you developers spent more time writing comments on this issue as it would take to just fix is.
Well, nevermind - I don't expect a few within the next year - or ever... -.-

**Comment by Antariano** [comment]
> That use case does make sense
Just to clarify: users using the browser's close button on a popup is not a use case that makes sense? Are we on the same page here?

**Comment by Paratron** [comment]
Sure, why would anyone cancel the paypal process by clicking on the browser's close button, here? That would be completely suprising!

![Screenshot](https://dl.dropboxusercontent.com/s/6kk4aqr82v4kzrn/shot_160110_110742.png?dl=0)

**Comment by psergus** [comment]
@Paratron, that's what differentiates development from UI-UX by thinking that something will not happen. It will and it happens, and you need to close the loop guys rather than building wrong assumptions.

**Comment by EvanHahn** [comment]
We can't change `onCancelled` because we have to preserve backwards-compatibility, but we're introducing a new callback called `onAuthorizationDismissed`. Here's how it might be used in a Custom integration:

```js
// This code doesn't work yet (but will work soon!)
braintree.setup('your token', 'custom', {
  id: 'my-custom-form',
  paypal: {
    onAuthorizationDismissed: function () {
      console.log('The user closed the PayPal flow without completing it!');
    }
    // ...
  },
  // ...
});
```

_This is not released yet_, but we'll update this thread as soon as it's out. It should be soon. We'll make sure to update the documentation after this is released.

Thank you for bringing this up and engaging in the subject! This feedback really helps us improve our product.

**Comment by MCProhosting-Matt** [comment]
Thank you! Really appreciate this.

**Comment by kyledetella** [comment]
To follow up on what @EvanHahn posted last week, we have released the `onAuthorizationDismissed` callback. Docs are still forthcoming, but you can use this as of version [`2.19.0`](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#2190).

The implementation code presented above is accurate. We hope this helps and we appreciate your patience. If you run into issued with `onAuthorizationDismissed`, please open a new issue.

**Comment by fullbl** [comment]
How can we know which version is hosted at https://js.braintreegateway.com/v2/braintree.js ?

**Comment by EvanHahn** [comment]
@fullbl Once you've included the `braintree.js` file into your page, you can open the JavaScript console and type:

```js
braintree.VERSION
```

This will print the current version of the library.

The file you mentioned is at version 2.15.4. We'll be improving the documentation around this in the coming weeks.

**Comment by fullbl** [comment]
Thanks a lot!

**Comment by hemanthprabhu22** [comment]
@EvanHahn 
How to upgrade to 1.19.0 version.

**Comment by crookedneighbor** [comment]
@hemanthprabhu22 Please [contact our support team](https://developers.braintreepayments.com/forms/contact) for questions about your integration.
