### ISSUE TITLE
When capturing onPaymentMethodReceived form is not submitted

### ISSUE THREAD

**Issue by alculquicondor** [braintree/braintree-web#84]
If I capture the event, then the form is not submitted. I have tried returning `true`, but no results.
What am I missing?

```js
onPaymentMethodReceived: function (result) {
        if (result.details.lastTwo) {
            $('#id_card_ending').val(result.details.lastTwo);
        }
}
```

```html
<form class="the-form" action="" method="POST" autocomplete="off">
```

**Comment by EvanHahn** [comment]
`onPaymentMethodReceived` prevents automatic form submission—you'll have to do it yourself. Something like this should work:

```js
onPaymentMethodReceived: function (result) {
        if (result.details.lastTwo) {
            $('#id_card_ending').val(result.details.lastTwo);
        }
        $('.the-form').submit();
}
```

Does that help?

**Comment by alculquicondor** [comment]
Actually, I also had to get the nonce and use native `submit` (not jquery's) because it was ignoring a
redirection. The fact that catching the event prevents the form submission should be in the documentation.
Thank you

**Comment by EvanHahn** [comment]
Glad we could steer you in the right direction. We're in the process of updating our docs with an `onPaymentMethodReceived` form submission example, which should be on our live docs in a few days. Thanks for the suggestion!

**Comment by kyledetella** [comment]
@alculquicondor we have updated our documentation to describe the fact that the `onPaymentMethodReceived` callback prevents form submission. Take a look [here](https://developers.braintreepayments.com/guides/client-sdk/javascript/v2#bypass-submit-handlers).

**Comment by tofutim** [comment]
Hi, I am finding that $('#myForm').submit does not work, though myForm.submit (native) works. But I need the jquery one because I would like the results to be in a bootstrap modal without reloading the page. Is this possible?
