### ISSUE TITLE
How to launch paypal payment flow with headless option

### ISSUE THREAD

**Issue by steverandy** [braintree/braintree-web#86]
> When set to true, you opt out of using the PayPal button we render and can use your own UI to launch the PayPal payment flow. By default this is set to false. See this section to see how to instantiate the PayPal flow with this option.

I can't find further explanations about headless mode for paypal on the braintree doc site.
How do you use this feature?

**Comment by schneiderik** [comment]
Hi @steverandy,

This is documentation for an upcoming feature that accidentally slipped into the docs site prematurely. It should be out soon. We'll drop another reply here when its officially released.

**Comment by danielwu426** [comment]
@steverandy -  Our Custom PP button work is now live at these JS urls:

https://js.braintreegateway.com/js/braintree-2.15.1.js
https://js.braintreegateway.com/js/braintree-2.15.1.min.js

I have a small gist [here](https://gist.github.com/danielwu426/70eac6b34ab7491610f0) that provides sample code. We'll keep this updated until we update our docs.

Let us know how the integration goes!

**Comment by messageagency** [comment]
Is the headless option supposed to work with the dropin setup?
Docs do not specify.

**Comment by crookedneighbor** [comment]
@messageagency It does not because in the Drop-In UI setup, the PayPal button is within the Drop-In iframe. I'll pass your feedback onto our Docs team.
