### ISSUE TITLE
Custom Paypal integration not consistent

### ISSUE THREAD

**Issue by Paratron** [braintree/braintree-web#87]
The process of integrating the paypal auth process into a web application is completely different than accepting credit card payments.

To accept credit card payments through a custom UI, you have this flow:

````javascript
var client = new braintree.api.Client({clientToken: "CLIENT-TOKEN-FROM-SERVER"});

client.tokenizeCard({
  number: "4111111111111111",
  expirationDate: "10/20"
}, function (err, nonce) {
  // Send nonce to your server
});
````

To accept paypal payments, its like this:

````javascript
braintree.setup("CLIENT-TOKEN-FROM-SERVER", "paypal", {
  container: "paypal-container",
  onPaymentMethodReceived: function (obj) {
    doSomethingWithTheNonce(obj.nonce);
  }
});
````

You need a DOM object to contain the paypal button and which also receives a hidden form element with the returned nonce - very unfriendly solution for a custom app integration.
I figured out later that there seems to be a headless mode, but there is no information about how to start the auth process without having the paypal button in place.

A much more consistent and nicer method would be to follow the example of the credit card payment and implement it somehow like this:

````javascript
var client = new braintree.api.Client({clientToken: "CLIENT-TOKEN-FROM-SERVER"});

client.authenticatePaypalAccount({
	onPaymentMethodReceived: function (err, nonce) {
 	 // Send nonce to your server
	},
	onCancelled: function(){
		//React to closed auth flow
	}
});
````

**Comment by danielwu426** [comment]
Hi @Paratron,

Regarding the documentation of "headless" mode, see [this issue](https://github.com/braintree/braintree-web/issues/86#issuecomment-149293852) for more information. We'll be supporting this in our next release - we'll drop a reply here with some additional information once it's out.

**Comment by danielwu426** [comment]
@Paratron -  Our Custom PP button work is now live at these JS urls:

https://js.braintreegateway.com/js/braintree-2.15.1.js
https://js.braintreegateway.com/js/braintree-2.15.1.min.js

I have a small gist [here](https://gist.github.com/danielwu426/70eac6b34ab7491610f0) that provides sample code. We'll keep this updated until we update our docs.

Let us know how the integration goes!
