### ISSUE TITLE
CreditCard verification methods missing/broken

### ISSUE THREAD

**Issue by Paratron** [braintree/braintree-web#88]
When processing credit card payments, the `tokenizeCard` method _always_ returns a nonce, no matter what data is passed to it. If you send a malformed cc-number, no number at all, or invalid expiration dates - the braintree server always returns a nonce.

Only at the point where you try to process a payment with the received nonce, you will get an error from braintree.

There really needs to be a `validateCardNumber` method in the SDK that can pre-check the entered CC-data before sending it somewhere (for example using the Luhn algorithm) - or maybe even the braintree server itself returning an error when you call the `tokenizeCard` method and try to tokenize malformed cc-data.

It would be great if there would be live-errors for:

* Malformed card numbers (too short, too long, checksum error, card-type not supported)
* Invalid expiration date
* Missing/malformed CVC

To give users some live feedback before trying to finish the whole process with invalid cc information.

**Comment by kyledetella** [comment]
@Paratron the `tokenizeCard` method provided by our raw api client is designed in such a way to allow developers the ability to use any validation mechanism they so choose. In our products such as [Drop-in](https://developers.braintreepayments.com/javascript+node/guides/drop-in) and [Hosted Fields](https://developers.braintreepayments.com/javascript+node/guides/hosted-fields/overview) this validation is handled for you. If you would like to handle your own validation and card type detection, we have a couple libraries to help you do that:

https://github.com/braintree/card-validator
https://github.com/braintree/credit-card-type

Also, these blog posts may be of some interest as well:

https://www.braintreepayments.com/blog/building-an-open-source-payments-toolkit-for-the-web/
https://www.braintreepayments.com/blog/your-checkout-our-iframes/

**Comment by Paratron** [comment]
Thats a nice information, thank you. Sadly, your documentation lacks this information completely. There is no notice about `tokenizeCard` not doing any verification (I would have assumed that it does at least refuse nonsense input) in the docs and also no links about that there are other libraries for validations available.

**Comment by kyledetella** [comment]
@Paratron we have made some updates to our documentation to clear up these points and that should be released soon. Thanks for your feedback, it was very helpful!
