### ISSUE TITLE
Braintree custom form with PayPal button always creates a payment method

### ISSUE THREAD

**Issue by fireflystorm** [braintree/braintree-web#91]
I have a custom form to allow my existing customers to maintain their default payment method.
I have also added the PayPal button:
  braintree.setup( "SOME_TOKEN",  "custom",
            {
                id: "SOME_FORM_ID",
                paypal: {
                    container: "paypal-button",
                    displayName: "SOME_NAME",
                    paymentMethodNonceInputField: "payment_method_nonce_paypal",
                });

What I observe is that if the user clicks the PayPal button and signs up to the PayPal aggreement a new payment method is created and added to his profile in Braintree even if the form is never submitted. That's even if he then clicks cancel or decides not to proceed saving. 

Why is that happening? I dont want to end up with a bunch of payment methods created when the customer doesnt actually want to use them.

**Comment by danielwu426** [comment]
Hi @fireflystorm,

This is expected behavior if you are including a `customerID` when generating a `clientToken`. If you don't want this to occur you can generate the `clientToken` without the `customerID`, and then vault the payment method server-side when you are ready.

Hope this helps,
Dan

**Comment by fireflystorm** [comment]
If I pass no customerID then my customers can not see their current payment method in order to change it...
