### ISSUE TITLE
Braintree custom form with PayPal no way to distinguish what payment_method_nonce refers to

### ISSUE THREAD

**Issue by fireflystorm** [braintree/braintree-web#92]
I have a custom payment form with credit card details portion and PayPal button next to it.
My customer can enter either her credit card details or use the PayPal button to accept an authorsation agreement.

The issue I have is that I'd like to provide visual feedback and choice to the customer as to which payment method they have selected if they proceed further. Problem is that I don't know and can't control what payment_method_nonce refers to. For example if the customer fills in both the credit card section and accepts PayPal then braintree-web sends payment_method_nonce for PayPal. 

I need to be able to select what the payment_method_nonce sent back to the server is for. For example I'd prefer Credit Card payments rather than PayPal. I'd also want to allow the user to pick which one of the two methods they'd be charged with.

**Comment by kyledetella** [comment]
@fireflystorm you can leverage the `onPaymentMethodReceived` callback which will provide a `details` object in the payload from which you can determine the type of payment method. See [the docs here](https://developers.braintreepayments.com/guides/client-sdk/javascript/v2#global-setup).

```js
braintree.setup(TOKEN, 'custom', {
  id: 'form-id',
  paypal: {...},
  onPaymentMethodReceived: function (payload) {
    // console.log(payload.type) => 'CreditCard' or 'PayPalAccount'
  }
});
```

I hope this helps. Let us know if you run into any further issues!

**Comment by fireflystorm** [comment]
@kyledetella however even with the callback I still end up witht he PayPal payment_method_nonce and can not get payment_method_nonce for the credit card form.
Ie there is no way to have credit card form details and paypal button together in a custom form and be able to get nonce for one or the other back to the server. The PayPal nonce always overrides the credit card one.

**Comment by kyledetella** [comment]
@fireflystorm the `custom` integration will generate a PayPal nonce if the user has authenticated with PayPal, otherwise it will generate a nonce for a Credit Card (validation is up to you unless you use [Hosted Fields](https://developers.braintreepayments.com/guides/hosted-fields/setup-and-integration/javascript/v2)). If the user has authenticated with PayPal, the only way our integration will attempt to tokenize the credit card inputs is if the user clicks `Cancel` in the generated PayPal UI.

This is the intended behavior, although admittedly confusing.

It is possible though that I am missing something. If you could you provide an example of your `braintree.setup` code, I can help get to the bottom of your issue.

**Comment by fireflystorm** [comment]
I think you summed it up correctly.

The problem with this is that even using custom forms developers do not have enough control to give user usable UI experience to manage their credit cards.
Ie I need to show a big red message saying "oh if you want to use your card but entered PayPal click Cancel otherwise it won't work which is not a great thing to show them". 

In addition I then need to think how I hack my way into removing the PayPal account from their payment method list which is yet another major inconvenience.

Would there be any chance for Braintree to look into improving PayPal with custom forms integration?

**Comment by kyledetella** [comment]
@fireflystorm `braintree.js` uses the PayPal nonce _unless_ the user explicitly clicks `Cancel` in the PayPal UI, which conveys intention to use a different payment method.

There are a couple things you could do to offer different behavior.

**1. Manually check whether card input was provided**

When using a `custom` integration, you have access to the credit card input fields. Upon form submission, you could check/validate those fields to determine if they contain card data. You can then check to see if the current nonce type is `PayPalAccount`. If you have determined that the user has both supplied a credit card and authenticated with PayPal, you would can present a message to the user prompting them to click cancel in the PayPal UI.

```js
function userHasEnteredCreditCardData() {
  return true; // or false, this validation is up to you
}

braintree.setup(TOKEN, 'custom', {
  id: 'my-form',
  paypal: {...},
  onPaymentMethodReceived: function (payload) {
    if (payload.type === 'PayPalAccount' && userHasEnteredCreditCardData()) {
      promptUserToCancelPayPal();
    } else {
      // Send nonce to server via AJAX or force submit
    }
  }
});
```

We offer a [credit card validator](https://github.com/braintree/card-validator) library to help with this.

**2. Ask the  user to explicitly identify which payment method they want to use**

Depending on your UI, it may make sense to offer the user an explicit choice between PayPal and Credit Cards (e.g. using radio buttons or a select list). In this case you could leverage the [teardown](https://developers.braintreepayments.com/guides/client-sdk/javascript/v2#teardown) functionality provided by `braintree.js` and only stand up the appropriate integration based on the outcome of this prompt.

```js
var currentIntegration = null;

function setupBraintree(type) {
  var config;
  
  return function () {
    if (type === 'PayPal') {
      config = {
	    paypal: { container: 'paypal-container' }
	  };
	} else {
	  config = {
	    id: 'my-form'
	  };
	}
	
	config.onReady = function (integration) {
	  currentIntegration = integration;
	}
	
    braintree.setup(TOKEN, 'custom', config);
  }
}

function handleUserPaymentMethodChoice(type) {
  var setupCall = setupBraintree(type);
  
  if (currentIntegration) {
    currentIntegration.teardown(setupCall);
  } else {
    setupCall();
  }
}
```
