### ISSUE TITLE
Braintree-data merchant ID requirement

### ISSUE THREAD

**Issue by fix-fix** [braintree/braintree-web#95]
There is a merchant ID requirement in [documentation about usage of BraintreeData.setup](https://developers.braintreepayments.com/guides/advanced-fraud-tools/client-side/javascript/v2)

However, the `setup` function from the [current braintree-data.js](http://0bin.net/paste/t+8VbnBa85rwKsel#Qn6ATsNeiyFRKy2nRWjlLS1EOhrIgwq2KRxIyaki7fx) is just this:

```js
BraintreeData.setup = function(merchantPublicId, formId, env) {
  this._setupCollector(env);
  this._setupForm(formId);
  BraintreeData.FraudNet.initialize();
}
```
i.e. `merchantPublicId` is not being used at all.

**Comment by kyledetella** [comment]
@fix-fix you are correct that `merchantPublicId` is not actually used in the code. At some point the code was changed in such a way to no longer require it, however we did not feel comfortable bumping to a new major version by breaking the API interface so the decision was made to leave it as is. We are currently in the process of making changes to our `BraintreeData` library and this issue will be addressed as part of that.

Thanks for catching that!
