### ISSUE TITLE
Invalid target origin 'null' in a call to 'postMessage'

### ISSUE THREAD

**Issue by alexstrutly** [braintree/braintree-web#96]
I am using hosted fields to implement purchase form. However, when I click submit button, it throws : "Uncaught SyntaxError: Failed to execute 'postMessage' on 'Window': Invalid target origin 'null' in a call to 'postMessage'". I can see the nounce is returned with "threeDSecureInfo" set to null. I was using an dummy credit card number and cvv code in the transaction. Just want to clarify if it is something suppose to happen because the dummy credit card? It would be good if I can use not minified code to debug. Thanks a lot

**Comment by kyledetella** [comment]
@alexstrutly the `"threeDSecureInfo": null` you see in the response object is likely a red herring here and shouldn't interfere with any of the mechanics of `postMessage`.

Would you be able to provide a snippet of your integration (HTML and JS)? That will help us to better debug this scenario.

**Comment by kyledetella** [comment]
I am closing this. If it reoccurs, feel free to open it again.

**Comment by beuhug** [comment]
I had the same error.

Workaround :
It occurred to me when I opened the html without local server. It doesn't occur if it go through a server.
