### ISSUE TITLE
Hosted fields doesn't load customers' data

### ISSUE THREAD

**Issue by denis-bondarenko** [braintree/braintree-web#97]
I create a Client token with the following c# code:
```
token = _gateway.ClientToken.generate(new ClientTokenRequest { CustomerId = customerId, MerchantAccountId = MerchantAccountId });
```
Drop-in form is filled with customer data if a card is assigned to the customer. But hosted fields form is empty

How do i initialize hosted fields form with previously saved customer data?

**Comment by kyledetella** [comment]
@denis-bondarenko unfortunately Hosted Fields does not work this way. They are intended to provide SAQ-A compliant entry of sensitive credit card data when creating new payment methods. If you would like to present vaulted card data to a customer in your UI without Drop-in you have to fetch that data server-side and then present it on the client in a manner of your choosing.

Here is the documentation to can find the Payment Methods associated with a customer: https://developers.braintreepayments.com/reference/response/customer/dotnet#payment_methods
