### ISSUE TITLE
Add paymentMethodNonceInputField selector option to braintree.setup

### ISSUE THREAD

**Issue by tompipe** [braintree/braintree-web#99]
By default, braintree.js inserts the following field 

    <input type="hidden" name="payment_method_nonce" />

Please add an option to allow an ID, DOM element, or jQuery object representing a pre-existing input field to be specified in the configuration passed into braintree.setup,

When set, braintree.js will write the nonce into this field instead of inserting a new hidden field. (similar to the paymentMethodNonceInputField option on the paypal object)

Adding this will allow custom validation to be easily configured for the field, i.e preventing submission when empty etc and negates the need for adding logic using the onPaymentMethodReceived function

**Comment by EvanHahn** [comment]
Because you can already do this with `onPaymentMethodReceived`, we don't plan to add this. We'd like to keep the code as simple as possible going forward.

You can accomplish what you want using `onPaymentMethodReceived`:

```js
var paymentForm = document.querySelector('form');
var nonceField = document.querySelector('#my-braintree-nonce-input');

braintree.setup('your-token', 'dropin', {
  onPaymentMethodReceived: function (payload) {
    // Set the <input>'s value with the nonce.
    nonceField.value = payload.nonce;

    // You can write myFormIsValid() to validate your form.
    if (myFormIsValid()) {
      paymentForm.submit();
    }
  }
});
```

You can also write the nonce to your form on your own with something like this:

```js
var paymentForm = document.querySelector('form');
var nonceField;

braintree.setup('your-token', 'dropin', {
  onPaymentMethodReceived: function (payload) {
    // Create the <input> if it doesn't already exist.
    if (!nonceField) {
      nonceField = document.createElement('input');
      nonceField.name = 'payment_method_nonce';
      nonceField.type = 'hidden';
      paymentForm.appendChild(nonceField);
    }

    // Set its value.
    nonceField.value = nonce;

    // You can write myFormIsValid() to validate your form.
    if (myFormIsValid()) {
      paymentForm.submit();
    }
  }
});
```

Hope that helps!
